"""Private historical replay from existing JSON, never PPTX/DB/HTTP or training.

CLI inputs locate private files; this source contains no resume or local-user
paths. Labels are copied verbatim from a completed historical manifest and its
separate frozen cases file, not generated by a model. These old simulated
requests and relevance labels are neither blind nor credential certification.
"""
import argparse
from datetime import datetime, timezone
import hashlib
import json
import os
from pathlib import Path


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load(path):
    return json.loads(path.read_text(encoding="utf-8"))


def save_private(path, value):
    repo = Path(__file__).resolve().parent.parent
    if path.resolve().is_relative_to(repo) or path.exists():
        raise ValueError("A new private output outside the source repository is required")
    path.parent.mkdir(parents=True, mode=0o700, exist_ok=True)
    with path.open("x", encoding="utf-8") as stream:
        path.chmod(0o600)
        json.dump(value, stream, ensure_ascii=False, indent=2)
        stream.write("\n")


def prepare(args):
    manifest, resumes, cases = load(args.manifest), load(args.resumes), load(args.cases)
    assert manifest["completed"] is True and manifest["private"] is True
    assert manifest["production_touched"] is False
    assert cases == [row["case"] for row in manifest["results"]], "Historical labels differ"
    assert len(cases) == len(manifest["demands"]) and cases
    by_id = {row["id"]: row for row in resumes}
    assert len(by_id) == len(resumes) == len(manifest["teachers"])
    documents, provenance = [], []
    for teacher in manifest["teachers"]:
        source = by_id[teacher["fixture_id"]]
        assert source["sha256"] == teacher["source_sha256"]
        assert source["bytes"] == teacher["source_bytes"]
        assert teacher["upload"]["parse_status"] == teacher["profile"]["parse_status"] == "ready"
        assert teacher["profile"]["page_count"] == len(source["slides"])
        # Preserve the existing paragraph order, with blank page boundaries.
        # This is not represented as the server parser's unavailable full text.
        text = "\n\n".join("\n".join(slide["paragraphs"]) for slide in source["slides"])
        assert text.strip()
        documents.append(dict(id=source["id"], text=text))
        provenance.append(dict(fixture_id=source["id"], source_sha256=source["sha256"],
            reconstructed_text_sha256=hashlib.sha256(text.encode()).hexdigest(),
            pages=len(source["slides"]), characters=len(text)))
    documents.sort(key=lambda row: row["id"])
    ids = {row["id"] for row in documents}
    assert len(ids) == len(documents)
    assert len({case["id"] for case in cases}) == len(cases)
    for case in cases:
        assert set(case["relevant"]) <= ids and set(case["backup"]) <= ids
        assert not set(case["relevant"]) & set(case["backup"])
    bundle = dict(schema_version="private-historical-resume-replay-v1",
        created_at=datetime.now(timezone.utc).isoformat(), private=True,
        source_hashes={"manifest": sha(args.manifest), "resumes_json": sha(args.resumes), "frozen_cases": sha(args.cases)},
        documents=documents, frozen_cases=cases, document_provenance=provenance,
        labels_reused_verbatim=True, model_invoked=False, production_touched=False,
        original_files_reopened=False, database_opened=False,
        caveats=["Previously exposed historical regression, not a blind test.",
            "Real resume content, but historical simulated requests, not real customer orders.",
            "Frozen relevance and backup labels do not certify teaching experience or eligibility.",
            "Reconstructed from existing paragraph JSON; not a byte-exact replay of the server's extracted_text.",
            "No demographic, geographical or commercial labels are inferred; online training mode isolates content."])
    save_private(args.output, bundle)
    print(json.dumps(dict(prepared=True, teachers=len(documents), cases=len(cases),
        labels_reused_verbatim=True, model_invoked=False, bundle_sha256=sha(args.output))))


def evaluate(args):
    # Deliberately imported only on the separately invoked evaluate subcommand.
    from evaluate_posttrain_pilot import EvaluationEncoder
    from evaluate_posttrain_v2 import replay
    class_root=Path(args.classpath.split(os.pathsep)[0]).resolve()
    assert (class_root/"com/training/PosttrainingV2Probe.class").is_file()
    classes={str(f.relative_to(class_root)):sha(f) for f in (class_root/"com/training").glob("*.class")}
    worker_hash=sha(Path(__file__).with_name("worker.py"))
    bundle = load(args.bundle)
    assert bundle["schema_version"] == "private-historical-resume-replay-v1"
    assert bundle["private"] and bundle["labels_reused_verbatim"]
    training = load(args.artifact_training_dir / "training-report.json") if args.artifact_training_dir else {}
    if training:
        assert training["completed"] and training["trained"] and not training["deployed"]
        assert sha(args.artifact_training_dir / "checkpoint/model.safetensors") == training["checkpoint_sha256"]
    encoder = EvaluationEncoder(args.model_dir, args.precision, training)
    cases = [dict(id=row["id"], query=row["query"], documents=bundle["documents"]) for row in bundle["frozen_cases"]]
    prepared = replay(cases, args.java, args.classpath, encoder.actual_model, encoder.actual_revision, args.precision, "prepare")
    assert [row["id"] for row in prepared] == [row["id"] for row in cases]
    pending, diagnostics = [], []
    for case, ready, label in zip(cases, prepared, bundle["frozen_cases"]):
        encoder.cache.execute("DELETE FROM vectors"); encoder.cache.commit()
        row = dict(id=case["id"], frozen_relevant=label["relevant"], frozen_backup=label["backup"], worker_error=None)
        try:
            response = encoder.compare(dict(query=ready["focused_query"], documents=ready["prepared_documents"]))
            ranked = sorted((r for r in response["results"] if r["similarity"] is not None), key=lambda r: (-r["similarity"], r["id"]))
            row.update(worker_ranked_ids=[r["id"] for r in ranked],
                worker_relevant_retained_ids=[r["id"] for r in ranked if r["id"] in label["relevant"]],
                worker_evidence_summary=[dict(id=r["id"], similarity=r["similarity"], evidence_complete=r["evidence_complete"],
                    scoped_evidence_complete=r.get("scoped_evidence_complete",False),scoring_scope=r.get("scoring_scope"),
                    reasons=r["evidence_review_reasons"]) for r in response["results"]])
            pending.append(dict(case, semantic_response=response))
        except (ValueError, TimeoutError) as error:
            row.update(worker_error=f"{type(error).__name__}: {error}", worker_ranked_ids=[], worker_relevant_retained_ids=[])
            pending.append(dict(case, semantic_error="historical_replay_inference_failed"))
        diagnostics.append(row)
    outputs = replay(pending, args.java, args.classpath, encoder.actual_model, encoder.actual_revision, args.precision, "evaluate")
    assert [r["id"] for r in outputs]==[r["id"] for r in diagnostics]
    for row, output in zip(diagnostics, outputs):
        assert row["id"] == output["id"]
        if not row["worker_error"]:
            assert output["semantic_state"]["status"] == "ready"
        selected = [r["teacher_id"] for r in output["selected"]]
        known = set(row["frozen_relevant"]) | set(row["frozen_backup"])
        row.update(selected_ids=selected, admitted_ids=output["admitted_ids"],
            selected_relevant_ids=[i for i in selected if i in row["frozen_relevant"]],
            selected_backup_ids=[i for i in selected if i in row["frozen_backup"]],
            admitted_outside_frozen_relevant_and_backup=[i for i in output["admitted_ids"] if i not in known],
            review_fixture_ids=[r["teacher_id"] for r in output["review"]],
            review_semantic_only_ids=[r["teacher_id"] for r in output["review"] if r.get("semantic_review_only") is True],
            review_ranking_inputs=[dict(teacher_id=r["teacher_id"], content_rank=r.get("content_rank"),
                semantic=dict(similarity=r.get("semantic",{}).get("similarity"))) for r in output["review"]],
            review_checks=[dict(id=r["teacher_id"],checks=[dict(criterion=c.get("criterion"),status=c.get("status"))
                for c in r.get("requirement_coverage",[])]) for r in output["review"]],
            semantic_state=output["semantic_state"])
    positive = [r for r in diagnostics if r["frozen_relevant"]]
    summary = dict(cases=len(diagnostics), positive_cases=len(positive), teachers=len(bundle["documents"]),
        worker_errors=sum(bool(r["worker_error"]) for r in diagnostics),
        worker_top1_relevant=sum(bool(r["worker_ranked_ids"]) and r["worker_ranked_ids"][0] in r["frozen_relevant"] for r in positive),
        worker_any_relevant_retained=sum(bool(r["worker_relevant_retained_ids"]) for r in positive),
        pipeline_any_relevant_selected=sum(bool(r["selected_relevant_ids"]) for r in positive),
        pipeline_any_relevant_admitted=sum(bool(set(r["admitted_ids"]) & set(r["frozen_relevant"])) for r in positive),
        pipeline_any_outside_labels=sum(bool(r["admitted_outside_frozen_relevant_and_backup"]) for r in diagnostics))
    report = dict(private=True, completed=True, model=encoder.actual_model, revision=encoder.actual_revision,
        precision=args.precision, bundle_sha256=sha(args.bundle), model_sha256=encoder.version,
        worker_sha256=worker_hash, evaluator_sha256=sha(Path(__file__)),executed_java_classes_sha256=classes,
        labels_reused_verbatim=True, blind_test=False, real_business_accuracy=False, production_touched=False,
        trained_on_real_resumes=False, caveats=bundle["caveats"], summary=summary, results=diagnostics,
        report_contains_resume_text=False)
    assert all(sha(class_root/n)==s for n,s in classes.items())
    assert sha(Path(__file__).with_name("worker.py"))==worker_hash
    save_private(args.output, report)
    print(json.dumps(dict(completed=True, model=encoder.actual_model, summary=summary, private=True), ensure_ascii=False))


def main():
    parser = argparse.ArgumentParser()
    commands = parser.add_subparsers(dest="command", required=True)
    prep = commands.add_parser("prepare")
    for option in ("manifest", "resumes", "cases", "output"):
        prep.add_argument("--" + option, type=Path, required=True)
    run = commands.add_parser("evaluate")
    for option in ("bundle", "model-dir", "output"):
        run.add_argument("--" + option, type=Path, required=True)
    run.add_argument("--artifact-training-dir", type=Path)
    run.add_argument("--precision", choices=("int8", "fp32"), default="int8")
    run.add_argument("--java", required=True); run.add_argument("--classpath", required=True)
    args = parser.parse_args()
    (prepare if args.command == "prepare" else evaluate)(args)


if __name__ == "__main__":
    main()
