package com.training;

import java.nio.file.*;
import java.time.*;
import java.util.*;
import java.util.function.Supplier;

/** Isolated request-snapshot tests and local micro-measurements; no production writes. */
public final class CityPlanningIndexTest {
    static final LocalDate TODAY=LocalDate.of(2026,9,8);
    static int checks;
    static Map<String,Object> m(Object x){return (Map<String,Object>)x;}
    static List<Object> l(Object x){return (List<Object>)x;}
    static Map<String,Object> copy(Map<?,?> x){return m(Json.parse(Json.write(x)));}
    static void ok(boolean x,String name){checks++;if(!x)throw new AssertionError(name);}
    static void immutable(Runnable edit,String name){try{edit.run();throw new AssertionError("mutable "+name);}catch(UnsupportedOperationException expected){checks++;}}
    record Query(String fp,String fc,String tp,String tc){}
    static Map<String,Object> query(CityPlanningReference.Index index,Query q){return index.lookup(q.fp,q.fc,q.tp,q.tc);}
    static Map<String,Object> query(Map<?,?> library,Query q,LocalDate day){return CityPlanningReference.lookup(library,q.fp,q.fc,q.tp,q.tc,day);}
    static boolean reference(Map<?,?> r){return "planning_reference".equals(r.get("status"));}
    static void pending(CityPlanningReference.Index index,Query q,String reason){Map<?,?> result=query(index,q);ok("planning_pending".equals(result.get("status"))&&reason.equals(result.get("reason")),reason+" "+result);}
    static List<Query> queries(Map<?,?> library){List<Query> result=new ArrayList<>();for(Map<?,?> event:CityPlanningReference.heads(library).values()){Map<?,?> s=CityPlanningReference.map(event.get("snapshot")),from=CityPlanningReference.map(s.get("from")),to=CityPlanningReference.map(s.get("to"));for(boolean f:List.of(true,false)){Map<?,?> a=f?from:to,b=f?to:from;result.add(new Query(a.get("province").toString(),a.get("city").toString(),b.get("province").toString(),b.get("city").toString()));}}return result;}
    static void appendRevocation(Map<String,Object> library){Map<String,Object> chain=m(l(library.get("references")).get(0)),first=m(l(chain.get("revisions")).get(0)),snapshot=copy(m(first.get("snapshot")));snapshot.put("version",2);snapshot.put("status","revoked");Map<String,Object> event=new LinkedHashMap<>();event.put("snapshot",snapshot);event.put("previous_hash",first.get("event_sha256"));event.put("change_reason","Isolated test: source reference withdrawn before next request");event.put("event_sha256",CityPlanningReference.eventHash(event));l(chain.get("revisions")).add(event);library.put("library_revision",2);}
    static void writePair(Path file,Map<?,?> data)throws Exception{Files.writeString(file,Json.write(data)+"\n",StandardOpenOption.TRUNCATE_EXISTING);Files.writeString(Path.of(file+".integrity.json"),Json.write(CityPlanningReference.anchor(data))+"\n",StandardOpenOption.TRUNCATE_EXISTING);}
    static Map<String,Object> baselineBench(Path file,List<Query> queries,int n,boolean repeatLoad){long start=System.nanoTime();var observed=CityPlanningReference.observe(()->{Map<?,?> library=repeatLoad?Map.of():CityPlanningReference.load(file);int passed=0;for(int i=0;i<n;i++){if(repeatLoad)library=CityPlanningReference.load(file);if(reference(query(library,queries.get(i%queries.size()),TODAY)))passed++;}return passed;});long elapsed=System.nanoTime()-start;ok(observed.value()==n,"baseline benchmark outputs");return Map.of("mode",repeatLoad?"baseline_load_per_lookup":"baseline_one_load_many_lookup","lookups",n,"elapsed_ns",elapsed,"measured_call_counts",observed.metrics());}
    static Map<String,Object> indexBench(Path file,List<Query> queries,int n){long begin=System.nanoTime();var index=CityPlanningReference.index(file,TODAY);long built=System.nanoTime();var observed=CityPlanningReference.observe(()->{int passed=0;for(int i=0;i<n;i++)if(reference(query(index,queries.get(i%queries.size()))))passed++;return passed;});long end=System.nanoTime();ok(observed.value()==n,"indexed benchmark outputs");ok(observed.metrics().values().stream().allMatch(v->v==0),"indexed lookups perform zero recorded I/O/parse/validate");return Map.of("mode","request_index","lookups",n,"build_ns",built-begin,"lookup_ns",end-built,"total_ns",end-begin,"build_call_counts",index.buildMetrics(),"lookup_call_counts",observed.metrics());}
    public static void main(String[] args)throws Exception{
        if(args.length!=2)throw new IllegalArgumentException("Usage: CityPlanningIndexTest prepared-six-pair-file NEW-output-directory");Path original=Path.of(args[0]),dir=Path.of(args[1]);Files.createDirectory(dir);
        String originalBytes=Files.readString(original),originalAnchor=Files.readString(Path.of(original+".integrity.json"));Map<String,Object> data=m(Json.parse(originalBytes));List<Query> queries=queries(data);Query shsu=queries.get(0),xiangyi=new Query("湖北","襄阳","湖北","宜昌"),whcs=new Query("湖北","武汉","湖南","长沙");
        String old=System.getProperty(CityPlanningReference.PROPERTY);try{System.setProperty(CityPlanningReference.PROPERTY,"");var empty=CityPlanningReference.index(TODAY);ok(empty.directionCount()==0&&empty.buildMetrics().values().stream().allMatch(v->v==0),"default index empty with no I/O");pending(empty,shsu,"planning_library_not_configured");System.setProperty(CityPlanningReference.PROPERTY,original.toString());ok(CityPlanningReference.index(TODAY).directionCount()==12,"configured API");}finally{if(old==null)System.clearProperty(CityPlanningReference.PROPERTY);else System.setProperty(CityPlanningReference.PROPERTY,old);}
        var index=CityPlanningReference.index(original,TODAY);ok(TODAY.equals(index.asOf())&&index.directionCount()==12,"snapshot date and direction count");Map<?,?> baseline=CityPlanningReference.load(original);
        for(Query q:queries)ok(CityPlanningReference.same(query(index,q),query(baseline,q,TODAY)),"fieldwise parity "+q);
        ok(index.buildMetrics().get("content_file_reads")==2,"file and anchor once each");ok(index.buildMetrics().get("file_json_parses")==2,"two file JSON parses");ok(index.buildMetrics().get("source_document_parses")==14,"14 original documents each parsed once");ok(index.buildMetrics().get("full_library_validations")==1,"one complete validation");ok(index.buildMetrics().get("direction_fact_validations")==12,"12 factual directions validated once");
        var repeated=CityPlanningReference.observe(()->{for(int i=0;i<100;i++)query(index,queries.get(i%12));return null;});ok(repeated.metrics().values().stream().allMatch(v->v==0),"100 lookups no reads/parses/validation");
        Map<String,Object> result=query(index,shsu),before=copy(result);immutable(()->result.put("status","other"),"top-level output");immutable(()->m(result.get("outbound")).put("precision","fake"),"direction output");immutable(()->m(m(result.get("outbound")).get("from")).put("city","fake"),"nested city");immutable(()->m(m(result.get("outbound")).get("readiness")).put("A","fake"),"readiness");immutable(()->l(m(result.get("outbound")).get("read_disagreement_fields")).add("fake"),"nested list");immutable(()->m(m(m(result.get("outbound")).get("reader_background")).get("A")).put("actor_type","human"),"nested reader");immutable(()->index.buildMetrics().put("content_file_reads",999L),"metrics");ok(CityPlanningReference.same(before,query(index,shsu)),"failed edits cannot poison snapshot");
        pending(index,new Query("湖北","武汉","上海","上海"),"city_pair_unobserved");pending(index,new Query("湖北","不存在","上海","上海"),"city_pending");
        var next=CityPlanningReference.index(original,TODAY);ok(next.buildMetrics().equals(index.buildMetrics()),"new request revalidates unchanged files; no cross-request parsed cache");
        var stale=CityPlanningReference.index(original,LocalDate.of(2026,9,30));pending(stale,xiangyi,"source_or_review_stale");ok(reference(query(stale,whcs)),"unexpired unrelated pair still available");pending(CityPlanningReference.index(original,LocalDate.of(2026,12,8)),whcs,"source_or_review_stale");ok(CityPlanningReference.same(query(stale,xiangyi),query(baseline,xiangyi,LocalDate.of(2026,9,30))),"expired baseline parity");
        Path changed=dir.resolve("isolated-changes.json"),anchor=Path.of(changed+".integrity.json");CityPlanningReference.prepare(data,changed,TODAY);var oldRequest=CityPlanningReference.index(changed,TODAY);ok(reference(query(oldRequest,shsu)),"isolated initial file active");String saved=Files.readString(changed),savedAnchor=Files.readString(anchor);
        Path moved=dir.resolve("temporarily-moved.json");Files.move(changed,moved);pending(CityPlanningReference.index(changed,TODAY),shsu,"planning_file_or_anchor_missing");Files.move(moved,changed);
        Path movedAnchor=dir.resolve("temporarily-moved.integrity.json");Files.move(anchor,movedAnchor);pending(CityPlanningReference.index(changed,TODAY),shsu,"planning_file_or_anchor_missing");Files.move(movedAnchor,anchor);
        Files.writeString(changed,"broken",StandardOpenOption.TRUNCATE_EXISTING);ok(!reference(query(CityPlanningReference.index(changed,TODAY),shsu)),"broken JSON next request unavailable");Files.writeString(changed,saved,StandardOpenOption.TRUNCATE_EXISTING);
        Map<String,Object> wrong=copy(data);wrong.put("library_revision",2);Files.writeString(changed,Json.write(wrong),StandardOpenOption.TRUNCATE_EXISTING);pending(CityPlanningReference.index(changed,TODAY),shsu,"planning_anchor_mismatch");Files.writeString(changed,saved,StandardOpenOption.TRUNCATE_EXISTING);
        Files.writeString(anchor,"{}",StandardOpenOption.TRUNCATE_EXISTING);pending(CityPlanningReference.index(changed,TODAY),shsu,"planning_anchor_mismatch");Files.writeString(anchor,savedAnchor,StandardOpenOption.TRUNCATE_EXISTING);
        ok(reference(query(CityPlanningReference.index(changed,TODAY),shsu)),"restored unchanged baseline works");
        Map<String,Object> revoked=copy(data);appendRevocation(revoked);writePair(changed,revoked);var newer=CityPlanningReference.index(changed,TODAY);pending(newer,shsu,"reference_revoked");ok(reference(query(newer,whcs)),"withdrawn pair does not mutate unrelated pair");ok(CityPlanningReference.same(query(newer,shsu),query(CityPlanningReference.load(changed),shsu,TODAY)),"revoked baseline parity");
        // An in-flight request is an immutable snapshot at its start; callers must obtain
        // a NEW index for the next request, never keep one in an application/session cache.
        ok(reference(query(oldRequest,shsu)),"in-flight snapshot remains internally consistent");Files.writeString(changed,saved,StandardOpenOption.TRUNCATE_EXISTING);Files.writeString(anchor,savedAnchor,StandardOpenOption.TRUNCATE_EXISTING);pending(CityPlanningReference.index(changed,TODAY),shsu,"library_rollback");
        Files.move(changed,dir.resolve("rolled-back-file.quarantined.json"));pending(CityPlanningReference.index(changed,TODAY),shsu,"planning_file_or_anchor_missing");
        // Warm the local JVM paths, then retain actual call-site counts alongside timings.
        for(int i=0;i<2;i++)CityPlanningReference.index(original,TODAY);for(int i=0;i<12;i++)query(baseline,queries.get(i),TODAY);
        List<Object> measurements=new ArrayList<>();for(int n:List.of(24,100)){measurements.add(baselineBench(original,queries,n,true));measurements.add(baselineBench(original,queries,n,false));measurements.add(indexBench(original,queries,n));}
        ok(originalBytes.equals(Files.readString(original))&&originalAnchor.equals(Files.readString(Path.of(original+".integrity.json"))),"original prepared data and anchor untouched");
        Map<String,Object> receipt=new LinkedHashMap<>();receipt.put("checks_passed",checks);receipt.put("source_pairs",6);receipt.put("source_directions",12);receipt.put("build_metrics",index.buildMetrics());receipt.put("measurements",measurements);receipt.put("date",TODAY.toString());receipt.put("environment",System.getProperty("java.runtime.version")+" / "+System.getProperty("os.name")+" "+System.getProperty("os.arch"));receipt.put("measurement_scope","Local one-process diagnostic, not production telemetry or an SLA; counts are instrumented content reads/JSON parses/validator calls, not filesystem stat calls or all OS activity.");receipt.put("production_changed",false);receipt.put("original_prepared_unchanged",true);Files.writeString(dir.resolve("index-validation.json"),Json.write(receipt)+"\n",StandardOpenOption.CREATE_NEW);System.out.println(Json.write(receipt));
    }
}
