package com.training;

import java.nio.file.*;
import java.time.LocalDate;
import java.util.*;

/** Offline opt-in integration. Real pinned public references, synthetic teacher rows
 * and scores only. No API/model/UI, old fixture writes or production configuration. */
public final class ContextSharedPlanningIntegrationTest {
    static final LocalDate DAY=LocalDate.of(2026,9,8);static int checks,oldPlanning,oldStrict,oldSelectionParity;
    static void check(boolean b,String why){checks++;if(!b)throw new AssertionError(why);}
    @SuppressWarnings("unchecked") static Map<String,Object> m(Object x){return (Map<String,Object>)x;}
    @SuppressWarnings("unchecked") static List<Object> l(Object x){return (List<Object>)x;}
    static Map<String,Object> obj(Object... kv){Map<String,Object> r=new LinkedHashMap<>();for(int i=0;i<kv.length;i+=2)r.put((String)kv[i],kv[i+1]);return r;}
    static Map<String,Object> copy(Object x){return m(Json.parse(Json.write(x)));}
    static String sha(Path p)throws Exception{return CityPlanningReference.rawHash(Files.readString(p));}
    static void same(Object a,Object b,String why){check(CityPlanningReference.same(a,b),why);}
    static DispatchPreference pref(String province,String city){return DispatchPreference.from(Map.of("training_province",province,"training_city",city,"training_mode","线下"),null);}
    static Map<String,Object> missing(){return obj("status","rail_reference_pending","eligibility","unknown","missing_directions",List.of("Synthetic strict proof missing; do not manufacture rail exclusion"));}
    static Map<String,Object> candidate(long id,String bp,String bc,int score,String level,boolean local,Map<String,Object> route,Map<String,Object> planning){
        Map<String,Object> fit=obj("base_province",bp,"base_city",bc,"residence_recognized",RegionDirectory.known(bp,bc),"local_priority",local,"route_reference",route);
        if(planning!=null)fit.put("planning_reference",planning);
        return obj("teacher_id",id,"base_province",bp,"base_city",bc,"model_score",score,"ranking_score",999-id,"teacher_level",level,"dispatch_fit",fit);
    }
    static Map<String,Object> context(long id,String province,String city,int score,String level){return candidate(id,province,city,score,level,false,missing(),CityPlanningReference.pending("city_pair_unobserved"));}
    static Map<String,Object> fit(Map<String,Object> c){return m(c.get("dispatch_fit"));}
    static List<Long> ids(Map<String,Object> result){return l(result.get("selected")).stream().map(x->((Number)m(x).get("teacher_id")).longValue()).toList();}
    static Map<String,Object> run(List<Map<String,Object>> rows,DispatchPreference p,int target,ContextSharedPlanningAdapter.Catalog catalog,LocalDate date,int maximum){
        String previous=System.getProperty("dispatch.nearby.max.minutes");try{System.setProperty("dispatch.nearby.max.minutes",Integer.toString(maximum));return NearbySelection.select(rows,p,target,catalog,date);}finally{if(previous==null)System.clearProperty("dispatch.nearby.max.minutes");else System.setProperty("dispatch.nearby.max.minutes",previous);}
    }
    static void noContext(Map<String,Object> c,String why){check(!fit(c).containsKey("context_planning_reference")&&!fit(c).containsKey("context_planning_display")&&!ContextSharedPlanningAdapter.POLICY.equals(fit(c).get("planning_policy")),why);}
    static ContextSharedPlanningAdapter.Catalog load(Path file,ContextSharedPlanningAdapter.Pins pins,LocalDate day)throws Exception{return ContextSharedPlanningAdapter.open(file,sha(file),sha(Path.of(file+".integrity.json")),pins,day,ContextSharedPlanningAdapter.OptIn.CONTEXT_SHARED_PREBID_V1);}
    static Map<String,Object> strictBundle(Path file){String oldFile=System.getProperty("dispatch.public.city.references.file"),oldDir=System.getProperty("dispatch.public.city.references.dir");try{System.setProperty("dispatch.public.city.references.file",file.toString());System.setProperty("dispatch.public.city.references.dir","");return m(CityTravelReference.publicBundle("北京","北京"));}finally{if(oldFile==null)System.clearProperty("dispatch.public.city.references.file");else System.setProperty("dispatch.public.city.references.file",oldFile);if(oldDir==null)System.clearProperty("dispatch.public.city.references.dir");else System.setProperty("dispatch.public.city.references.dir",oldDir);}}
    static void parity(Map<String,Object> candidate,DispatchPreference p,ContextSharedPlanningAdapter.Catalog catalog){
        Map<String,Object> old=NearbySelection.select(List.of(copy(candidate)),p,3),nil=NearbySelection.select(List.of(copy(candidate)),p,3,null,DAY),opt=NearbySelection.select(List.of(copy(candidate)),p,3,catalog,DAY);
        same(old,nil,"old/null overload full output parity");same(old,opt,"old unrelated reference unchanged with explicit context");oldSelectionParity++;
    }
    public static void main(String[] args)throws Exception{
        check(args.length==2,"workspace and new output path");Path base=Path.of(args[0]).toAbsolutePath().normalize(),out=Files.createDirectory(Path.of(args[1]).toAbsolutePath().normalize());
        Path source=base.resolve(".codex-tmp/yanxu-context-shared-sources.DoNWLx/source-fixtures.private.json"),review=source.resolveSibling("ROOT_SOURCE_REVIEW.md"),file=base.resolve(".codex-tmp/yanxu-context-shared-adapter.hqpB43/actual-final/two-context-candidates.private.json");
        check("42182000e933db761e9ba0e3405e62433368516d8c69c2d95d6a11b093d0546c".equals(sha(file))&&"aa2b383b8d4ba37ef5cf8691a617774a5eedea6c2b653c8d2b61e178b6901b67".equals(sha(Path.of(file+".integrity.json"))),"previous candidate and anchor exactly pinned");
        var pins=new ContextSharedPlanningAdapter.Pins(source,ContextSharedPlanningAdapterTest.SOURCE_SHA,review,ContextSharedPlanningAdapterTest.REVIEW_SHA);var catalog=load(file,pins,DAY);check(catalog.valid()&&catalog.sharedCount()==2,"two approved real candidates load");
        Path baselineFile=base.resolve(".codex-tmp/yanxu-planning19-shared1.uShL9f/actual-collection-result.json");Map<String,Object> baseline=m(Json.parse(Files.readString(baselineFile)));Map<Path,String> retained=new LinkedHashMap<>();retained.put(source,sha(source));retained.put(review,sha(review));retained.put(file,sha(file));retained.put(Path.of(file+".integrity.json"),sha(Path.of(file+".integrity.json")));retained.put(baselineFile,sha(baselineFile));
        check("73e217decbd8a1f34ef483f2338ad1dd896325994729b771929251339393f47a".equals(sha(baselineFile)),"accepted39 baseline pinned");
        for(var pin:m(baseline.get("input_pins")).entrySet()){Path p=Path.of(pin.getKey());check(pin.getValue().equals(sha(p)),"prior24 input pin");retained.put(p,pin.getValue().toString());}
        Path collection=Path.of(baseline.get("collection_file").toString());for(String path:List.of(collection.toString(),collection+".integrity.json",baseline.get("sidecar_file").toString(),baseline.get("sidecar_file")+".integrity.json"))retained.put(Path.of(path),sha(Path.of(path)));
        var oldIndex=CityPlanningReference.collectionIndex(collection,DAY);check(oldIndex.directionCount()==38&&oldIndex.sharedPairCount()==1,"old39 planning layer remains38 directions plus1 shared");
        var oldShown=CityPlanningReference.collectionIndex(collection,DAY,CityPlanningPresentation.load(Path.of(baseline.get("sidecar_file").toString()),CityPlanningPresentation.VERSION_V2));
        Map<String,Object> tangshan=null,tianjin=null;List<Object> oldQueries=new ArrayList<>(),strictQueries=new ArrayList<>();
        for(Object raw:l(baseline.get("planning_outputs"))){Map<String,Object> row=m(raw),a=m(row.get("from")),b=m(row.get("to"));Map<String,Object> actual=oldIndex.lookup(a.get("province").toString(),a.get("city").toString(),b.get("province").toString(),b.get("city").toString());same(actual,row.get("without_presentation"),"old planning complete default output");oldPlanning++;
            same(oldShown.lookup(a.get("province").toString(),a.get("city").toString(),b.get("province").toString(),b.get("city").toString()),row.get("reference"),"old39 complete optional presentation output");
            if(Boolean.TRUE.equals(row.get("shared")))check(actual==oldIndex.lookup(b.get("province").toString(),b.get("city").toString(),a.get("province").toString(),a.get("city").toString()),"old shared remains one object");
            parity(candidate(1000+oldPlanning,a.get("province").toString(),a.get("city").toString(),80,"讲师",false,missing(),actual),pref(b.get("province").toString(),b.get("city").toString()),catalog);
            if("唐山".equals(a.get("city"))&&"北京".equals(b.get("city")))tangshan=actual;oldQueries.add(obj("from",a,"to",b,"unchanged",true));
        }
        Path strictFile=base.resolve(".codex-tmp/yanxu-jinan-natural-clock.njabjQz8/prepared-v2/public-city-nineteen-merged.private.json");Map<String,Object> strict=strictBundle(strictFile);check(!strict.containsKey("load_status"),"protected strict19 load");
        for(Map<?,?> event:CityTravelReference.heads(strict).values()){Map<?,?> s=CityPlanningReference.map(event.get("snapshot"));String fp=s.get("from_province").toString(),fc=s.get("from_city").toString(),tp=s.get("to_province").toString(),tc=s.get("to_city").toString();for(boolean back:List.of(false,true)){
            String ap=back?tp:fp,ac=back?tc:fc,bp=back?fp:tp,bc=back?fc:tc;Map<String,Object> actual=CityTravelReference.lookup(strict,ap,ac,bp,bc,DAY);strictQueries.add(obj("layer","strict","from",ac,"to",bc,"result",actual));oldStrict++;
            parity(candidate(2000+oldStrict,ap,ac,80,"讲师",false,actual,null),pref(bp,bc),catalog);if("天津".equals(ac)&&"北京".equals(bc))tianjin=actual;
        }}
        same(strictQueries,baseline.get("strict_outputs"),"all strict38 complete outputs unchanged");check(oldPlanning==39&&oldStrict==38&&oldSelectionParity==77,"all original39 city-pair references covered without adding new pair");check(tangshan!=null&&tianjin!=null,"real old planning and strict references available for same-destination mixed pool");
        DispatchPreference beijing=pref("北京","北京");List<Map<String,Object>> pool=new ArrayList<>();for(int i=1;i<=3;i++)pool.add(candidate(i,"北京","北京",59+i,"讲师",true,obj("status","same_city"),null));
        pool.add(context(4,"河北","承德",90,"特聘讲师"));pool.add(context(5,"河北","承德",90,"高级讲师"));pool.add(context(6,"河北","承德",90,"讲师"));
        pool.add(candidate(7,"天津","天津",95,"讲师",false,copy(tianjin),null));pool.add(candidate(8,"河北","唐山",80,"特聘讲师",false,missing(),copy(tangshan)));
        List<String> strictBefore=pool.stream().map(c->Json.write(fit(c).get("route_reference"))).toList();Map<String,Object> mixed=run(pool,beijing,3,catalog,DAY,240);
        check(((Number)mixed.get("pool_size")).intValue()==8,"all local, strict, old planning and context teachers enter one pool");check(ids(mixed).equals(List.of(7L,4L,5L,6L)),"whole pool model score then level; cutoff score ties all kept");check(((Number)mixed.get("ties_included")).intValue()==1&&((Number)mixed.get("context_planning_pool_size")).intValue()==3,"context counts teachers, not direction observations");
        for(int i=0;i<pool.size();i++)check(strictBefore.get(i).equals(Json.write(fit(pool.get(i)).get("route_reference"))),"mixed selection never edits strict source/exclusion");
        Map<String,Object> shown=fit(pool.get(3)),reference=m(shown.get("context_planning_reference")),display=m(shown.get("context_planning_display"));
        check(reference==fit(pool.get(4)).get("context_planning_reference")&&reference==fit(pool.get(5)).get("context_planning_reference"),"multiple teachers share one fact object");
        Map<String,Object> decision=catalog.select("河北","承德","北京","北京",240);check(decision.get("reference")==reference,"decision reuses deeply immutable Catalog reference");
        try{decision.put("planning_pool_eligible",false);throw new AssertionError("mutable decision");}catch(UnsupportedOperationException expected){check(true,"decision wrapper immutable");}
        try{m(reference.get("shared_observation")).put("reference_minutes",1);throw new AssertionError("mutable observation");}catch(UnsupportedOperationException expected){check(true,"decision nested reference immutable");}
        check(!reference.containsKey("outbound")&&!reference.containsKey("inbound")&&((Number)reference.get("independent_direction_observations")).intValue()==0,"no45/45 observation fabrication");
        check("reported_fastest".equals(m(reference.get("shared_observation")).get("qualifier"))&&"2026-01-24".equals(reference.get("source_published_on"))&&reference.containsKey("source_url")&&reference.containsKey("attributed_source"),"single source precision attribution and dates present");
        check(display.get("label").toString().contains("报道最快45分钟")&&display.get("endpoint_label").toString().contains("未指定车站")&&display.get("notice").toString().contains("实际出行待核")&&!Json.write(display).contains("明确单程"),"short honest display metadata");
        check(shown.get("priority_score")==null&&Boolean.FALSE.equals(shown.get("time_score_applicable")),"context never adds a transport ability score");
        Map<String,Object> shenfu=context(20,"辽宁","抚顺",90,"讲师");Map<String,Object> sfResult=run(List.of(shenfu),pref("辽宁","沈阳"),3,catalog,DAY,21);check(ids(sfResult).equals(List.of(20L)),"real reverse沈抚 enters same planning pool");Map<String,Object> sfRef=m(fit(shenfu).get("context_planning_reference"));
        check("approximate".equals(m(sfRef.get("shared_observation")).get("precision"))&&"20分钟左右".equals(m(sfRef.get("shared_observation")).get("original_duration_text"))&&"2025-10-31".equals(sfRef.get("source_published_on"))&&"辽宁日报；受访通勤者叙述".equals(sfRef.get("attributed_source")),"approximation and original source date retained");
        check(ids(run(List.of(context(21,"辽宁","抚顺",90,"讲师")),pref("辽宁","沈阳"),3,catalog,DAY,20)).isEmpty(),"approx20 must be strictly below configured limit");
        for(int max:List.of(20,21,45,46,240)){Map<String,Object> c=context(30,"河北","承德",80,"讲师");check(!ids(run(List.of(c),beijing,3,catalog,DAY,max)).isEmpty()==(max>45),"actual45 strict cutoff "+max);}
        check(!CityPlanningSelection.includeContextPlanning(fit(context(31,"河北","承德",80,"讲师")),beijing,241,catalog,DAY),"explicit context241 rejected");
        Map<String,Object> capped=run(List.of(context(32,"河北","承德",80,"讲师")),beijing,3,catalog,DAY,241);check(((Number)capped.get("maximum_nearby_minutes")).intValue()==240,"existing global maximum clamp unchanged");
        Map<String,Object> reused=context(40,"河北","承德",80,"讲师");run(List.of(reused),beijing,3,catalog,DAY,240);check(fit(reused).containsKey("context_planning_display"),"initial opt-in label exists");
        check(ids(NearbySelection.select(List.of(reused),beijing,3)).isEmpty(),"old entry cannot reuse previous opt-in success");noContext(reused,"opt-out clears context fields");
        run(List.of(reused),beijing,3,catalog,DAY,240);check(ids(run(List.of(reused),pref("上海","上海"),3,catalog,DAY,240)).isEmpty(),"destination switch cannot reuse proof");noContext(reused,"destination switch clears display");
        run(List.of(reused),beijing,3,catalog,DAY,240);check(ids(run(List.of(reused),beijing,3,catalog,DAY.plusDays(1),240)).isEmpty(),"cross-day Catalog rejected");noContext(reused,"cross-day clears display");
        for(LocalDate expired:List.of(LocalDate.of(2026,11,1),LocalDate.of(2026,12,8))){var at=load(file,pins,expired);Map<String,Object> c=expired.getMonthValue()==11?context(50,"辽宁","抚顺",80,"讲师"):context(50,"河北","承德",80,"讲师");DispatchPreference p=expired.getMonthValue()==11?pref("辽宁","沈阳"):beijing;Map<String,Object> result=run(List.of(c),p,3,at,expired,240);check(ids(result).isEmpty()&&l(result.get("air_candidates")).isEmpty(),"expired reference not planning or air");noContext(c,"expired source has no positive display");}
        var nov=load(file,pins,LocalDate.of(2026,11,1));check(ids(run(List.of(context(51,"河北","承德",80,"讲师")),beijing,3,nov,LocalDate.of(2026,11,1),240)).size()==1,"沈抚 source expiry does not expire京承");
        for(String reason:List.of("reference_hash_mismatch","cross_library_revocation_or_integrity_failure","source_or_review_stale")){Map<String,Object> c=context(60,"河北","承德",80,"讲师");fit(c).put("planning_reference",CityPlanningReference.pending(reason));check(ids(run(List.of(c),beijing,3,catalog,DAY,240)).isEmpty(),"old planning hard failure not overridden "+reason);noContext(c,"hard failure no context display");}
        for(String flag:List.of("departure_uncertain","local_priority")){Map<String,Object> c=context(61,"河北","承德",80,"讲师");fit(c).put(flag,true);check(!CityPlanningSelection.includeContextPlanning(fit(c),beijing,240,catalog,DAY),"context location guard "+flag);}
        Map<String,Object> broken=context(62,"河北","承德",80,"讲师");m(fit(broken).get("route_reference")).put("load_status","broken");check(ids(run(List.of(broken),beijing,3,catalog,DAY,240)).isEmpty(),"strict load failure not overridden");
        Map<String,Object> forged=context(63,"河北","承德",80,"讲师");fit(forged).put("context_planning_reference",reference);fit(forged).put("planning_policy",ContextSharedPlanningAdapter.POLICY);fit(forged).put("planning_included",true);check(ids(run(List.of(forged),beijing,3,null,DAY,240)).isEmpty(),"supplied success Map cannot replace Catalog");noContext(forged,"forged fields cleared");
        Map<String,Object> wrongBase=context(64,"河北","承德",80,"讲师");wrongBase.put("base_province","四川");wrongBase.put("base_city","眉山");check(ids(run(List.of(wrongBase),beijing,3,catalog,DAY,240)).isEmpty(),"fit cannot substitute a different teacher city");noContext(wrongBase,"mismatched teacher city no context display");
        var invalidCatalog=ContextSharedPlanningAdapter.open(file,"0".repeat(64),sha(Path.of(file+".integrity.json")),pins,DAY,ContextSharedPlanningAdapter.OptIn.CONTEXT_SHARED_PREBID_V1);Map<String,Object> invalid=context(65,"河北","承德",80,"讲师");Map<String,Object> invalidResult=run(List.of(invalid),beijing,3,invalidCatalog,DAY,240);check(ids(invalidResult).isEmpty()&&l(invalidResult.get("air_candidates")).isEmpty(),"hash-invalid Catalog cannot admit or fabricate air");noContext(invalid,"invalid Catalog no positive display");
        Map<String,Object> unscored=context(70,"河北","承德",80,"讲师");unscored.remove("model_score");Map<String,Object> pendingScores=run(List.of(context(71,"河北","承德",80,"讲师"),unscored),beijing,3,catalog,DAY,240);check(l(pendingScores.get("scoring_pending")).size()==1&&ids(pendingScores).equals(List.of(71L)),"existing model-pending rule retained");
        Map<String,Object> unknown=context(80,"四川","眉山",99,"特聘讲师"),air=candidate(81,"四川","成都",80,"讲师",false,obj("status","air_time_reference","eligibility","air","outbound_reference_minutes",100,"return_reference_minutes",100),null);String airBefore=Json.write(fit(air).get("route_reference"));Map<String,Object> independentAir=run(List.of(unknown,air),beijing,3,catalog,DAY,240);check(ids(independentAir).equals(List.of(81L))&&l(independentAir.get("travel_pending")).size()==1&&airBefore.equals(Json.write(fit(air).get("route_reference"))),"only independently supplied air remains eligible; unknown gains no proof");
        Path revokedFile=file.resolveSibling("FAULT-revocation-control.private.json");var withdrawn=load(revokedFile,pins,DAY);check(withdrawn.valid(),"prior standalone synthetic revocation fixture loads");Map<String,Object> revoked=context(90,"河北","承德",80,"讲师"),revokedResult=run(List.of(revoked),beijing,3,withdrawn,DAY,240);check(ids(revokedResult).isEmpty()&&l(revokedResult.get("air_candidates")).isEmpty(),"revocation blocks existing-pool inclusion and air");noContext(revoked,"revocation no positive display");check(ids(run(List.of(context(91,"辽宁","抚顺",80,"讲师")),pref("辽宁","沈阳"),3,withdrawn,DAY,240)).equals(List.of(91L)),"revocation does not suppress unrelated shared pair");
        for(var pin:retained.entrySet())check(pin.getValue().equals(sha(pin.getKey())),"original inputs and anchors unchanged after all tests");
        Map<String,Object> result=obj("status","PASS_opt_in_context_same_pool_not_production","checks",checks,"old_planning_full_outputs_compared",oldPlanning,"old_presentation_full_outputs_compared",oldPlanning,"old_strict_full_outputs_compared",oldStrict,"old_selection_full_parity_cases",oldSelectionParity,"old_aggregate_city_pairs",39,"context_real_shared_candidates",2,"context_independent_direction_observations",0,"collection_added_pairs",0,"retained_input_pins_checked",retained.size(),"mixed_pool",mixed,"shenfu_reverse_selection",sfResult,"model_called",false,"network_called",false,"production_configuration_changed",false,"old_queries",oldQueries,"old_strict_outputs",strictQueries);
        Files.writeString(out.resolve("result.json"),Json.write(result)+"\n",StandardOpenOption.CREATE_NEW);System.out.println("Context planning integration: "+checks+" checks PASS; old39 unchanged, 2 opt-in shared candidates in the existing pool.");
    }
}
