package com.training;

import java.nio.file.*;
import java.time.*;
import java.util.*;
import java.util.function.Consumer;

/** Synthetic protected-envelope integration; fixture identities are not actual source readers. */
public final class CuratedPlanningIntegrationTest {
    static int checks,sequence;static Path root;static final LocalDate TODAY=LocalDate.of(2026,9,8);
    @SuppressWarnings("unchecked") static Map<String,Object> m(Object x){return (Map<String,Object>)x;}
    @SuppressWarnings("unchecked") static List<Object> l(Object x){return (List<Object>)x;}
    static Map<String,Object> obj(Object...kv){return CuratedCityDurationTest.m(kv);}
    static Map<String,Object> copy(Object x){return m(Json.parse(Json.write(x)));}
    static void ok(boolean b,String name){checks++;if(!b)throw new AssertionError(name);}
    static void eq(Object a,Object b,String name){ok(CityPlanningReference.same(a,b),name+": "+a+" != "+b);}
    static Map<String,Object> doc(Map<String,Object> data,String id){return m(Json.parse((String)m(m(data.get("documents")).get(id)).get("raw_json")));}
    static void putDoc(Map<String,Object> data,String id,Map<?,?> value){String raw=Json.write(value);m(data.get("documents")).put(id,obj("raw_json",raw,"raw_sha256",CityPlanningReference.rawHash(raw)));}
    static void editDoc(Map<String,Object> data,String id,Consumer<Map<String,Object>> edit){Map<String,Object> value=doc(data,id);edit.accept(value);putDoc(data,id,value);}
    static Map<String,Object> policy(){return obj("use_basis","independently_curated_public_facts","license_claimed",false,"minimal_fact_review","no_explicit_minimal_fact_prohibition_observed","article_republication_allowed",false,"checked_on",TODAY.toString(),"scope_note","Synthetic fixture only, not a rights grant","external_restrictions",obj("minimal_fact_extraction_prohibited",false,"minimal_fact_reuse_prohibited",false,"source_research_only",false,"automation_prohibited",false,"access_restricted",false,"direct_article_republication_restricted",false),"checks",List.of(obj("url","https://example.invalid/policy","record_locator","synthetic-only","observation","synthetic policy envelope")));}
    static void rehash(Map<String,Object> data){for(Object rr:l(data.get("references"))){String previous="";for(Object ee:l(m(rr).get("revisions"))){Map<String,Object> e=m(ee);e.put("previous_hash",previous);e.put("event_sha256",CityPlanningReference.eventHash(e));previous=(String)e.get("event_sha256");}}}
    static Map<String,Object> bundle(CuratedCityDuration.Direction out,CuratedCityDuration.Direction back){
        Map<String,Object> data=obj("version",CityPlanningReference.SCHEMA,"library_revision",1,"use_basis","independently_curated_public_facts","license_claimed",false,"local_planning_import_allowed",true,"article_republication_allowed",false,"strict_runtime_admission",false,"purpose","prebid_city_planning_only","policy",obj("buffer_minutes",30,"buffer_basis","planning_assumption_not_source_error_bound"),"documents",new LinkedHashMap<>(),"synthetic_only",true);
        List<Object> sourceRows=new ArrayList<>(),events=new ArrayList<>(),reviews=new ArrayList<>(),factsA=new ArrayList<>(),factsB=new ArrayList<>();
        for(var d:List.of(out,back)){String id=(String)d.source().get("source_id");putDoc(data,id,d.source());sourceRows.add(obj("source_id",id,"url",d.source().get("url"),"file_sha256",m(m(data.get("documents")).get(id)).get("raw_sha256")));
            events.add(obj("source_id",id,"url",d.source().get("url"),"result","original_read","record_locator","SYNTHETIC fixture, no real source reading claimed","recorded_at",null));reviews.add(obj("source_id",id,"reuse_state","no_explicit_prohibition_observed","rationale","Synthetic test envelope"));
            Map<String,Object> a=copy(d.readA()),b=copy(d.readB());a.put("source_id",id);b.put("source_id",id);factsA.add(a);factsB.add(b);}
        putDoc(data,"packet",obj("created_on",TODAY.toString(),"sources",sourceRows));String packetSha=(String)m(m(data.get("documents")).get("packet")).get("raw_sha256");
        for(String role:List.of("A","B"))putDoc(data,role,obj("reviewer",obj("role",role,"actor_type","assistant","agent_id","synthetic-agent-"+role,"run_id","synthetic-run-"+role,"background_context_prior_research",true,"prior_A_result_access",false,"fresh_blind_claimed",false),"source_packet_sha256",packetSha,"read_events",events,"source_reviews",reviews,"facts",role.equals("A")?factsA:factsB,"synthetic_only",true));
        Map<String,Object> outward=obj("from_registry_id",out.from().get("id"),"to_registry_id",out.to().get("id"),"packet_document","packet","source_document",out.source().get("source_id"),"review_a","A","review_b","B","source_policy",policy());
        Map<String,Object> inward=obj("from_registry_id",back.from().get("id"),"to_registry_id",back.to().get("id"),"packet_document","packet","source_document",back.source().get("source_id"),"review_a","A","review_b","B","source_policy",policy());
        Map<String,Object> snapshot=obj("reference_id","curated-fixture","version",1,"from",out.from(),"to",out.to(),"status","active","reviewed_on",TODAY.toString(),"outbound",outward,"inbound",inward);
        data.put("references",new ArrayList<>(List.of(obj("reference_id","curated-fixture","revisions",new ArrayList<>(List.of(obj("snapshot",snapshot,"previous_hash","","change_reason","Synthetic integration fixture, not a curated source claim")))))));rehash(data);return data;
    }
    static CuratedCityDuration.Direction scalar(boolean back,String kind,String token,int n){return CuratedCityDurationTest.fixture(back,CuratedCityDurationTest.scalar(kind,token,n));}
    static Map<String,Object> simple(){return bundle(scalar(false,"reported_minutes","90分钟",90),scalar(true,"reported_minutes","100分钟",100));}
    static Map<String,Object> snapshot(Map<String,Object> data){return m(m(l(m(l(data.get("references")).get(0)).get("revisions")).get(0)).get("snapshot"));}
    static void rejected(Map<String,Object> data,String reason){try{CityPlanningReference.anchor(data);throw new AssertionError("accepted invalid envelope: "+reason);}catch(IllegalArgumentException e){ok(e.getMessage().contains(reason),"specific rejection "+reason+": "+e.getMessage());}}
    static Map<String,Object> prepare(Map<String,Object> data,LocalDate today)throws Exception {Path file=root.resolve("library-"+(++sequence)+".json");CityPlanningReference.prepare(data,file,today);Map<String,Object> loaded=m(CityPlanningReference.load(file));ok(!loaded.containsKey("load_status"),"actual load "+loaded);eq(loaded,data,"load content");return loaded;}
    static Map<String,Object> lookup(Map<?,?> data,LocalDate day){return CityPlanningReference.lookup(data,"江苏","南京","上海","上海",day);}
    static Map<String,Object> ready(Map<String,Object> data)throws Exception {Map<String,Object> result=lookup(prepare(data,TODAY),TODAY);eq(result.get("status"),"planning_reference","protected lookup accepts curated values");eq(result.get("verification_method"),CuratedCityDuration.METHOD,"method visible");eq(result.get("protected_envelope_validated"),true,"outer envelope marker");eq(result.get("semantic_annotations_are_language_proof"),false,"not NLP proof");for(String f:List.of("time_score_applicable","transport_verified","air_fallback_trigger","rail_exclusion_complete"))eq(result.get(f),false,"no stronger capability "+f);for(String leg:List.of("outbound","inbound")){Map<String,Object> value=m(result.get(leg));ok(!value.containsKey("reference_value_minutes_internal")&&!value.containsKey("policy_adjusted_minutes_internal"),"internal scalar removed");Map<String,Object> typed=m(value.get("source_duration"));for(String field:List.of("token","service_id","departure_clock","arrival_clock"))ok(!typed.containsKey(field),"private source role not copied into caller output");}return result;}
    static Map<String,Object> revoked(Map<String,Object> input){Map<String,Object> data=copy(input);data.put("library_revision",2);Map<String,Object> chain=m(l(data.get("references")).get(0)),e=m(l(chain.get("revisions")).get(0)),s=copy(e.get("snapshot"));s.put("version",2);s.put("status","revoked");l(chain.get("revisions")).add(obj("snapshot",s,"previous_hash",e.get("event_sha256"),"change_reason","Synthetic revocation after expiry"));rehash(data);return data;}
    public static void main(String[] args)throws Exception {
        root=args.length==0?Files.createTempDirectory("curated-planning-integration-"):Files.createDirectory(Path.of(args[0]));
        Map<String,Object> initial=simple(),result=ready(initial);eq(result.get("planning_band_id"),"planning_1_2h","unbuffered return controls range");
        var back=scalar(true,"reported_minutes","100分钟",100);
        ready(bundle(scalar(false,"nominal_hour","1小时",1),back));
        Map<String,Object> approx=ready(bundle(scalar(false,"approximate","约90分钟",90),back));eq(m(m(approx.get("outbound")).get("source_duration")).get("kind"),"approximate","not exact");
        for(boolean inclusive:List.of(false,true)){Map<String,Object> bound=ready(bundle(CuratedCityDurationTest.fixture(false,CuratedCityDurationTest.upper(inclusive?"不超过90分钟":"不到90分钟",90,inclusive)),back));eq(m(m(bound.get("outbound")).get("source_duration")).get("upper_inclusive"),inclusive,"bound openness retained");}
        Map<String,Object> range=ready(bundle(CuratedCityDurationTest.fixture(false,CuratedCityDurationTest.range("大于60分钟至不足90分钟",60,90,false,false)),back));eq(m(m(range.get("outbound")).get("source_duration")).get("lower_inclusive"),false,"range lower retained");
        var clockOut=CuratedCityDurationTest.fixture(false,CuratedCityDurationTest.clocks("23：00","01∶00",1,120));
        var clockBack=CuratedCityDurationTest.fixture(true,CuratedCityDurationTest.clocks("09:00","11:00",0,120),"上海虹桥站","南京东站");
        Map<String,Object> different=ready(bundle(clockOut,clockBack));eq(different.get("endpoint_difference"),true,"different urban stations accepted with notice");eq(different.get("endpoint_specificity_mixed"),false,"both urban station");eq(m(l(different.get("endpoint_notices")).get(0)).get("transfer_time_estimated"),false,"no invented transfer");
        Map<String,Object> mixed=ready(bundle(clockOut,back));eq(mixed.get("endpoint_specificity_mixed"),true,"city/station mixture notice");
        rejected(bundle(CuratedCityDurationTest.both(clockBack,f->CuratedCityDurationTest.dur(f).put("calculated_minutes",121)),clockOut),"clock_duration_mismatch");
        for(String scope:List.of("county","unknown","unknown_connection"))rejected(bundle(CuratedCityDurationTest.both(clockOut,f->m(CuratedCityDurationTest.c(f).get("endpoint_scope")).put("from",scope)),clockBack),"county_or_unknown_endpoint_scope");
        rejected(bundle(CuratedCityDurationTest.both(scalar(false,"reported_minutes","90分钟",90),f->CuratedCityDurationTest.c(f).put("verification_method","unknown_v2")),back),"verification_method_mismatch");
        rejected(bundle(CuratedCityDurationTest.change(scalar(false,"reported_minutes","90分钟",90),f->CuratedCityDurationTest.c(f).remove("verification_method"),f->{}),back),"verification_method_mismatch");
        rejected(bundle(CuratedCityDurationTest.change(scalar(false,"reported_minutes","90分钟",90),f->CuratedCityDurationTest.dur(f).put("value",91),f->{}),back),"core_read_disagreement");
        rejected(bundle(CuratedCityDurationTest.both(scalar(false,"reported_minutes","90分钟",90),f->CuratedCityDurationTest.sp(f,"duration").put("text","91分钟")),back),"span_mismatch");
        for(int n:List.of(209,210,227,239,240,241)){Map<String,Object> data=bundle(scalar(false,"reported_minutes","60分钟",60),scalar(true,"approximate","约"+n+"分钟",n));Map<String,Object> q=lookup(prepare(data,TODAY),TODAY);eq(q.get("status"),n<240?"planning_reference":"planning_pending","each unbuffered directional reference strictly below240");if(n>=240)ok(!q.containsKey("planning_band_id"),"boundary cannot carry available band");}
        Map<String,Object> limit=ready(bundle(CuratedCityDurationTest.fixture(false,CuratedCityDurationTest.upper("不到90分钟",90,false)),scalar(true,"reported_minutes","60分钟",60)));
        DispatchPreference pref=DispatchPreference.from(Map.of("training_province","上海","training_city","上海","training_mode","线下"),null);
        for(int maximum:List.of(60,89,90,120,121,180,239,240)){Map<String,Object> fit=obj("local_priority",false,"planning_reference",limit,"route_reference",obj("status","rail_reference_pending","eligibility","unknown","missing_directions",List.of("synthetic missing strict proof")));eq(CityPlanningSelection.include(fit,pref,maximum),maximum>=90,"custom cutoff uses original typed exclusive upper edge");}
        Map<String,Object> last=ready(bundle(scalar(false,"reported_minutes","227分钟",227),scalar(true,"reported_minutes","227分钟",227)));
        for(int maximum:List.of(180,210,227,228,239,240))eq(CityPlanningSelection.underConfiguredLimit(last,maximum),maximum>227,"227-minute reference uses user cutoff without hidden 30 minutes: "+maximum);
        Map<String,Object> open=ready(bundle(CuratedCityDurationTest.fixture(false,CuratedCityDurationTest.upper("不到240分钟",240,false)),back));
        eq(CityPlanningSelection.underConfiguredLimit(open,240),true,"exclusive240 bound allows planning");eq(CityPlanningSelection.underConfiguredLimit(open,239),false,"exclusive240 does not establish a smaller user limit");
        Map<String,Object> exactOpen=ready(bundle(CuratedCityDurationTest.fixture(false,CuratedCityDurationTest.upper("不到227分钟",227,false)),back));
        eq(CityPlanningSelection.underConfiguredLimit(exactOpen,227),true,"exclusive bound equals user maximum");
        Map<String,Object> malformed=copy(last);malformed.put("planning_band_id","planning_0_1h");malformed.put("selection_reference",null);
        ok(!CityPlanningSelection.underConfiguredLimit(malformed,240),"malformed new snapshot never falls back to a permissive old band");
        Map<String,Object> bad=copy(initial);m(m(bad.get("documents")).get("A")).put("raw_sha256","0".repeat(64));rejected(bad,"document_hash_mismatch");
        bad=copy(initial);editDoc(bad,"A",v->v.put("source_packet_sha256","0".repeat(64)));rejected(bad,"reader_packet_mismatch");
        bad=copy(initial);editDoc(bad,"B",v->m(v.get("reviewer")).put("agent_id","synthetic-agent-A"));rejected(bad,"second_independent_reader_missing");
        bad=copy(initial);editDoc(bad,"B",v->m(v.get("reviewer")).put("run_id","synthetic-run-A"));rejected(bad,"second_independent_reader_missing");
        bad=copy(initial);editDoc(bad,"B",v->v.put("read_events",List.of()));rejected(bad,"original_read_event_missing");
        bad=copy(initial);editDoc(bad,"B",v->m(l(v.get("read_events")).get(0)).put("recorded_at","2026-09-09T00:00:00Z"));rejected(bad,"review_date_not_bound_to_read_events");
        bad=copy(initial);m(m(snapshot(bad).get("outbound")).get("source_policy")).put("license_claimed",true);rehash(bad);rejected(bad,"source_license_claim_not_allowed");
        bad=copy(initial);m(m(m(snapshot(bad).get("outbound")).get("source_policy")).get("external_restrictions")).put("minimal_fact_reuse_prohibited",true);rehash(bad);rejected(bad,"source_restriction_minimal_fact_reuse_prohibited");
        rejected(bundle(CuratedCityDurationTest.source(scalar(false,"reported_minutes","90分钟",90),s->s.put("minimal_fact_reuse_prohibited",true)),back),"original_source_restriction");
        Map<String,Object> informed=copy(initial);editDoc(informed,"B",v->{Map<String,Object> actor=m(v.get("reviewer"));actor.put("prior_A_result_access",true);actor.put("review_mode","informed_original_source_crosscheck");actor.put("fresh_blind_claimed",false);});Map<String,Object> cross=ready(informed);eq(m(cross.get("outbound")).get("informed_source_crosscheck"),true,"informed crosscheck explicitly reported");eq(m(m(m(cross.get("outbound")).get("reader_background")).get("B")).get("prior_A_result_access"),true,"informed original flag never rewritten");
        for(String variant:List.of("missing_mode","fresh_claim","fresh_context","same_agent","no_original_events","A_informed")){Map<String,Object> v=copy(informed);switch(variant){case "missing_mode"->editDoc(v,"B",x->m(x.get("reviewer")).remove("review_mode"));case "fresh_claim"->editDoc(v,"B",x->m(x.get("reviewer")).put("fresh_blind_claimed",true));case "fresh_context"->editDoc(v,"B",x->m(x.get("reviewer")).put("blind_fresh_context",true));case "same_agent"->editDoc(v,"B",x->m(x.get("reviewer")).put("agent_id","synthetic-agent-A"));case "no_original_events"->editDoc(v,"B",x->x.put("read_events",List.of()));case "A_informed"->editDoc(v,"A",x->{m(x.get("reviewer")).put("review_mode","informed_original_source_crosscheck");m(x.get("reviewer")).put("prior_A_result_access",true);});}rejected(v,variant.equals("same_agent")?"second_independent_reader_missing":variant.equals("no_original_events")?"original_read_event_missing":"reader_informed_mode_invalid");}
        Map<String,Object> old=prepare(initial,TODAY.plusDays(91));eq(lookup(old,TODAY.plusDays(91)).get("reason"),"source_or_review_stale","expired facts still load, only lookup is pending");
        Map<String,Object> withdrawn=revoked(initial);CityPlanningReference.continuation(CityPlanningReference.anchor(initial),withdrawn);Map<String,Object> retained=prepare(withdrawn,TODAY.plusDays(91));eq(lookup(retained,TODAY.plusDays(91)).get("reason"),"reference_revoked","expired history can be legitimately revoked");eq(m(l(m(l(retained.get("references")).get(0)).get("revisions")).get(0)),m(l(m(l(initial.get("references")).get(0)).get("revisions")).get(0)),"historical event untouched");
        var ended=CuratedCityDurationTest.both(scalar(false,"reported_minutes","90分钟",90),f->{CuratedCityDurationTest.c(f).put("effective_on","2026-08-01");CuratedCityDurationTest.c(f).put("effective_until","2026-08-31");});Map<String,Object> endData=prepare(bundle(ended,back),TODAY);eq(lookup(endData,TODAY).get("reason"),"source_period_ended","ended period retained structurally");
        var future=CuratedCityDurationTest.both(scalar(false,"reported_minutes","90分钟",90),f->CuratedCityDurationTest.c(f).put("effective_on","2026-09-09"));eq(lookup(prepare(bundle(future,back),TODAY),TODAY).get("reason"),"not_yet_effective","future effectiveness cannot admit");
        Path broken=root.resolve("anchor-tamper.json");CityPlanningReference.prepare(initial,broken,TODAY);Files.writeString(Path.of(broken+".integrity.json"),"{}",StandardOpenOption.TRUNCATE_EXISTING);eq(CityPlanningReference.load(broken).get("load_reason"),"planning_anchor_mismatch","external anchor still enforced");
        Path rollback=root.resolve("rollback.json");CityPlanningReference.prepare(initial,rollback,TODAY);CityPlanningReference.load(rollback);Files.writeString(rollback,Json.write(withdrawn),StandardOpenOption.TRUNCATE_EXISTING);Files.writeString(Path.of(rollback+".integrity.json"),Json.write(CityPlanningReference.anchor(withdrawn)),StandardOpenOption.TRUNCATE_EXISTING);CityPlanningReference.load(rollback);Files.writeString(rollback,Json.write(initial),StandardOpenOption.TRUNCATE_EXISTING);Files.writeString(Path.of(rollback+".integrity.json"),Json.write(CityPlanningReference.anchor(initial)),StandardOpenOption.TRUNCATE_EXISTING);eq(CityPlanningReference.load(rollback).get("load_reason"),"library_rollback","remembered version prevents rollback");
        Path indexed=root.resolve("indexed.json");CityPlanningReference.prepare(informed,indexed,TODAY);var index=CityPlanningReference.index(indexed,TODAY);eq(index.directionCount(),2,"request index has both directions");eq(index.lookup("江苏","南京","上海","上海"),lookup(informed,TODAY),"index and direct parity");try{m(index.lookup("江苏","南京","上海","上海").get("outbound")).put("precision","exact");throw new AssertionError("mutable index");}catch(UnsupportedOperationException expected){checks++;}
        Files.writeString(root.resolve("receipt.json"),Json.write(obj("checks",checks,"synthetic_only",true,"model_run",false,"production_changed",false,"actual_prepare_load",true,"informed_fixture",cross,"different_stations_fixture",different,"expired_history_retained",true))+"\n",StandardOpenOption.CREATE_NEW);
        System.out.println("Curated protected planning integration: "+checks+" assertions passed; synthetic only; "+root);
    }
}
