package com.training;

import java.util.*;

/** New synthetic stress cases authored independently of the fixed 72-case suite.
 * Not business-approved labels or blind production validation. No real resumes,
 * HTTP, model, database, or writes. Both admission and review cases are included;
 * rejecting everything cannot pass. Expectations are never generated by rules.
 */
public final class EvidenceAdversarialTest {
    record Case(String id, String purpose, String query, String text, boolean expectedAdmission) {}

    static Map<String,Object> assess(Case test) {
        Map<String,Object> candidate=new LinkedHashMap<>();
        candidate.put("professional_score",80.0);
        candidate.put("_rule_relevant",true);
        candidate.put("gaps",new ArrayList<String>());
        // Deliberately high similarity: it must not override unsupported facts.
        candidate.put("semantic",Map.of("similarity",.99,"evidence_complete",true));
        new RequirementCoverage(test.query()).assess(candidate,test.text(),true);
        return candidate;
    }

    static List<Case> cases() {
        String history="培训主题：领导力；必须有本人实际授课记录";
        return List.of(
            new Case("A01","Explicit personal teaching years can qualify",
                "培训主题：领导力；至少4年对应授课经历",
                "本人实际主讲领导力，累计四年授课经历。",true),
            new Case("A02","Digit-by-digit Chinese calendar date is not five years of experience",
                "培训主题：领导力；至少5年对应授课经历",
                "本人于二〇二五年实际主讲领导力，首次开课记录已归档。",false),
            new Case("A03","Chinese decimal requirement cannot disappear",
                "培训主题：领导力；至少三点五小时",
                "本人实际主讲领导力，实际授课3小时。",false),
            new Case("A04","Chinese decimal evidence cannot become its trailing integer",
                "培训主题：领导力；至少5小时",
                "本人实际主讲领导力，实际授课三点五小时。",false),
            new Case("A05","Spaced teaching-year range does not prove its upper endpoint",
                "培训主题：领导力；至少6年对应授课经历",
                "本人实际主讲领导力4 至 6年。",false),
            new Case("A06","Spaced hour range is not exact four-hour instruction",
                "培训主题：领导力；至少4小时",
                "本人实际主讲领导力，课程时长1 ～ 4小时。",false),
            new Case("A07","Approximate Chinese duration is not a guaranteed lower bound",
                "培训主题：领导力；至少4小时",
                "本人实际主讲领导力，课程时长四小时左右。",false),
            new Case("A08","Exact minutes may meet an hour threshold",
                "培训主题：领导力；至少2小时",
                "本人实际主讲领导力，实际授课120分钟。",true),
            new Case("A09","Unimplemented day unit must not erase an insufficient duration",
                "培训主题：领导力；至少2天",
                "本人实际主讲领导力，教学持续1天，实际授课6小时。",false),
            new Case("A10","Unimplemented seconds unit must not erase an insufficient duration",
                "培训主题：领导力；至少900秒",
                "本人实际主讲领导力，实际授课5分钟。",false),
            new Case("A11","Written fraction is not the trailing one hour",
                "培训主题：领导力；至少1小时",
                "本人实际主讲领导力，实际授课四分之一小时。",false),
            new Case("A12","Opening and closing ceremonies cannot inflate actual instruction",
                "培训主题：领导力；至少2小时",
                "本人实际主讲领导力，活动总长2小时，其中40分钟为开幕和闭幕，教学仅80分钟。",false),
            new Case("A13","A duration on an unknown second topic cannot be transferred",
                "培训主题：领导力；至少3小时",
                "本人实际主讲领导力30分钟，另主讲焊接识图180分钟。",false),
            new Case("A14","A duration on another physical line still belongs to its own topic",
                "培训主题：领导力；至少3小时",
                "本人实际主讲领导力30分钟。\n本人实际主讲焊接识图，授课180分钟。",false),
            new Case("A15","A separate second course must not erase supported requested-course duration",
                "培训主题：领导力；至少3小时",
                "本人实际主讲领导力，实际授课180分钟。\n本人实际主讲战略管理30分钟。",true),
            new Case("A16","Later disclaimer of authorship applies across a physical line",
                history,
                "本人实际主讲领导力课程。\n上行内容为团队宣传样例，不代表本人授课。",false),
            new Case("A17","Dated external-teacher course is not the resume owner's teaching",
                history,
                "2025年领导力课由外部讲师王工主讲，本人负责设备调试。",false),
            new Case("A18","A genuine teacher may have another person organize materials",
                history,
                "2025年本人主讲领导力课程。资料由项目助理整理。",true),
            new Case("A19","Team section heading governs its following dated claim",
                history,
                "团队案例\n2025年累计主讲领导力10场。\n个人职责\n本人负责资料审核。",false),
            new Case("A20","A team subtotal cannot satisfy personal session count",
                "培训主题：领导力；至少6场对应授课经历",
                "本人在2025年主讲领导力，授课统计为6场，其中4场由其他老师完成。",false),
            new Case("A21","Explicit completed personal count may qualify",
                "培训主题：领导力；至少6场对应授课经历",
                "本人实际主讲领导力，已完成个人授课6场，每场记录均已归档。",true),
            new Case("A22","Unverified recorded-video exclusion cannot silently pass",
                history+"；不包括仅有录播课程的经历",
                "本人实际主讲领导力录播课程，录制文件已交付。",false),
            new Case("A23","Unrecognized mandatory delivery language must not be ignored",
                "培训主题：领导力；必须使用法语授课",
                "本人实际主讲中文领导力课程。",false),
            new Case("A24","Unrecognized mandatory audience must not be ignored",
                "培训主题：领导力；必须面向生产班组长",
                "本人实际主讲面向企业董事长的领导力课程。",false),
            new Case("A25","Standalone demographic metadata does not block an eligible teacher",
                history,
                "性别：女。年龄：58。\n本人实际主讲领导力课程。",true),
            new Case("A26","Counterfactual demographic metadata has the same result",
                history,
                "性别：男。年龄：24。\n本人实际主讲领导力课程。",true),
            new Case("A27","A named other teacher plus personal attendance is not own teaching",
                history,
                "2025年陈老师主讲领导力课程，我旁听并负责资料编写。",false),
            new Case("A28","Two affirmative course records can jointly cover two content topics",
                "培训主题：领导力；战略管理",
                "主讲领导力课程。\n主讲战略管理课程。",true),
            new Case("A29","A course catalogue alone is not actual teaching history",
                history,
                "主讲课程：领导力，课程计划面向企业管理者。",false),
            new Case("A30","Explicit supported language condition still admits",
                "培训主题：领导力；必须英文授课",
                "本人实际主讲英文领导力课程。",true)
        );
    }

    public static void main(String[] args) {
        List<Map<String,Object>> results=new ArrayList<>();
        int passed=0,positiveCases=0,positivePassed=0,negativePassed=0;
        for(Case test:cases()) {
            if(test.expectedAdmission()) positiveCases++;
            Map<String,Object> result=new LinkedHashMap<>();
            result.put("id",test.id());result.put("purpose",test.purpose());
            result.put("expected_admission",test.expectedAdmission());
            try {
                Map<String,Object> actual=assess(test);
                boolean admitted=Boolean.TRUE.equals(actual.get("_admitted"));
                boolean ok=admitted==test.expectedAdmission();
                result.put("actual_admission",admitted);result.put("passed",ok);
                result.put("coverage",actual.get("requirement_coverage"));
                if(ok) { passed++; if(test.expectedAdmission()) positivePassed++; else negativePassed++; }
            } catch(Exception error) {
                result.put("passed",false);result.put("error",error.getClass().getSimpleName()+": "+error.getMessage());
            }
            results.add(result);
        }
        Map<String,Object> report=new LinkedHashMap<>();
        report.put("notice","New author-labelled synthetic stress cases, not blind business validation. No model inference, external data, real resumes or deployment.");
        report.put("cases",results.size());report.put("passed",passed);
        report.put("positive_cases",positiveCases);report.put("positive_passed",positivePassed);
        report.put("review_expected_cases",results.size()-positiveCases);report.put("review_expected_passed",negativePassed);
        report.put("results",results);
        System.out.println(Json.write(report));
        if(passed!=results.size()) throw new AssertionError("Evidence adversarial: "+passed+"/"+results.size()+" passed; expectations unchanged");
    }
}
