package com.training;

import java.io.*;
import java.lang.reflect.*;
import java.nio.file.*;
import java.sql.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicLong;
import java.util.function.LongSupplier;

/** Script-only adversarial fixture. Synthetic accounts, owned H2, fake time and memory sender only. */
public final class FirstBindTest {
    static final String PASSWORD="synthetic-first-bind-r26-only";
    static final long START=1_850_000_000_000L,MINUTE=60_000L;
    static final List<String> EMAIL_TABLES=List.of("s01_account_email_heads","s01_account_email_revisions","s01_account_email_requests","s01_account_email_maintenance_heads","s01_account_email_maintenance_revisions","s01_account_email_maintenance_requests","s01_account_email_first_bind","s01_account_email_first_bind_events","s01_account_email_first_bind_receipts");
    static final List<String> PROTECTED_TABLES=List.of("users","organization_account_import_state","organization_account_import_batches","organization_account_import_people","synthetic_permissions","synthetic_outbox");
    static int checks;static String hash;static final List<String> secrets=new ArrayList<>();
    @FunctionalInterface interface Work{void run()throws Exception;}
    static void check(boolean condition,String label){checks++;if(!condition)throw new AssertionError(label);}
    static void denied(Work action,String label)throws Exception{try{action.run();throw new AssertionError("Expected denial: "+label);}catch(Api.ApiException failure){check(Set.of(400,401,403,409,429,503).contains(failure.code),label+" stable denial");String msg=Objects.toString(failure.getMessage(),"");check(!msg.contains(PASSWORD)&&!msg.contains("@example.invalid")&&!msg.contains("pbkdf2$"),label+" safe error");for(String secret:secrets)check(!msg.contains(secret),label+" no proof leak");}}
    static void rejected(int status,Work action,String label)throws Exception{try{action.run();throw new AssertionError("Expected rejection: "+label);}catch(Api.ApiException failure){check(failure.code==status,label+" status expected "+status+", actual "+failure.code);}}
    static String username(long uid){return "synthetic-first-"+uid;}
    static String email(long uid){return "synthetic-first-"+uid+"@example.invalid";}
    static Auth.Credential credential(long uid)throws Exception{Auth.Credential proof=Auth.checkedCredential(username(uid),PASSWORD);check(proof!=null,"password proof for synthetic user "+uid);return proof;}
    @SuppressWarnings("unchecked") static Map<Object,Object> sessions()throws Exception{Field f=Auth.class.getDeclaredField("SESSIONS");f.setAccessible(true);return (Map<Object,Object>)f.get(null);}
    static Map<String,String> rows(List<String> tables)throws Exception{Map<String,String> result=new TreeMap<>();for(String table:tables){List<String> values=new ArrayList<>();for(var row:Db.query("SELECT * FROM "+table))values.add(Json.write(new TreeMap<>(row)));Collections.sort(values);result.put(table,values.toString());}return result;}
    static long count(String table)throws Exception{return Db.count(table);}
    static void noSession(String label)throws Exception{check(sessions().isEmpty(),label+" cannot issue session");}
    static final class Clock implements LongSupplier{final AtomicLong time=new AtomicLong(START);public long getAsLong(){return time.get();}void advance(long ms){time.addAndGet(ms);}}
    static class Mail implements NotificationChannelsLoginVerification.MailSender {
        final List<Map<String,Object>> values=new ArrayList<>();volatile boolean fail;volatile CountDownLatch entered,release;int first,ordinary;
        public void send(String email,String code)throws Exception{ordinary++;accept(email,code,false,0);}
        public void sendFirst(String email,String code,long seconds)throws Exception{first++;accept(email,code,true,seconds);}
        synchronized String code(){return (String)values.get(values.size()-1).get("code");}
        void accept(String email,String code,boolean first,long seconds)throws Exception{check(!Thread.holdsLock(Api.MUTATION_LOCK),"delivery occurs outside shared mutation lock");check(Db.get().getAutoCommit(),"delivery occurs outside SQL transaction");check(email.endsWith("@example.invalid")&&code.matches("[0-9]{6}"),"fake sender only receives synthetic domain and six digit code");if(first)check(seconds>0&&seconds<=600,"first mail exposes bounded remaining proof lifetime");synchronized(this){values.add(Map.of("email",email,"code",code,"first",first,"seconds",seconds));}if(entered!=null)entered.countDown();if(release!=null&&!release.await(10,TimeUnit.SECONDS))throw new IOException("synthetic timeout");if(fail)throw new IOException("synthetic transport failure");}
    }
    static NotificationChannelsLoginVerification service(Clock clock,Mail mail){return new NotificationChannelsLoginVerification(clock,mail);}
    static NotificationChannelsLoginVerification.Enrollment enroll(NotificationChannelsLoginVerification service,long uid)throws Exception{var value=service.enroll(credential(uid));check(value!=null&&value.enrollmentId().matches("[a-f0-9]{64}"),"approved ready account gets random proof");secrets.add(value.enrollmentId());return value;}
    static NotificationChannelsLoginVerification.Challenge send(NotificationChannelsLoginVerification service,long uid,NotificationChannelsLoginVerification.Enrollment enrollment)throws Exception{return send(service,enrollment,email(uid),"127.0.0.1");}
    static NotificationChannelsLoginVerification.Challenge send(NotificationChannelsLoginVerification service,NotificationChannelsLoginVerification.Enrollment enrollment,String address,String remote)throws Exception{var value=service.beginFirst(enrollment.enrollmentId(),address,remote);check(value.challengeId().matches("[a-f0-9]{64}")&&"***@***".equals(value.maskedEmail()),"first challenge gives only opaque identifier and generic mask");check(value.expiresAt()<=enrollment.expiresAt(),"challenge never exceeds enrollment absolute expiry");secrets.add(value.challengeId());return value;}
    static String finish(NotificationChannelsLoginVerification service,NotificationChannelsLoginVerification.Challenge challenge,String code)throws Exception{synchronized(Api.MUTATION_LOCK){var verified=service.verifyFirst(challenge.challengeId(),code);noSession("committed engine result before final Auth handoff");String token=Auth.issueVerified(verified.credential(),verified.snapshot());check(Auth.get(token)!=null,"only committed binding can issue valid session");secrets.add(token);return token;}}

    static void admissionAndGate()throws Exception{
        Clock clock=new Clock();Mail mail=new Mail();var service=service(clock,mail);Map<String,String> before=rows(EMAIL_TABLES);
        check(Auth.checkedCredential(username(181),PASSWORD)==null,"disabled account cannot prove password");check(Auth.checkedCredential(username(100),"incorrect-synthetic")==null,"wrong password is rejected");check(service.enroll(credential(180))==null,"unapproved empty-email account never receives enrollment");
        var proof=credential(100);var enrollment=enroll(service,100);check(enrollment.expiresAt()==START+10*MINUTE,"absolute enrollment lifetime is ten minutes");noSession("password proof");check(mail.values.isEmpty(),"password proof itself sends no email");check(rows(EMAIL_TABLES).equals(before),"password proof never writes email or gate");
        System.setProperty("login.email.mode","legacy");try{check(Auth.login(username(100),PASSWORD)==null,"legacy login cannot bypass READY gate");denied(()->service.beginFirst(enrollment.enrollmentId(),email(100),"127.0.0.1"),"mode switch cannot send first challenge");}finally{System.setProperty("login.email.mode","required");}
        check(Auth.credentialCurrent(proof),"gate preserves account password proof");denied(()->service.beginFirst("f".repeat(64),email(100),"127.0.0.1"),"forged enrollment");denied(()->service.beginFirst(enrollment.enrollmentId(),"bad-address","127.0.0.1"),"malformed email");denied(()->service.beginFirst(enrollment.enrollmentId(),email(100),"spoofed source /"),"invalid socket source");noSession("invalid first admission");service.cancelEnrollment(enrollment.enrollmentId());service.cancelEnrollment(enrollment.enrollmentId());denied(()->send(service,100,enrollment),"cancel idempotently destroys proof");
    }
    static void completionAndPurpose()throws Exception{
        for(long uid:List.of(101L,102L,151L)){Clock clock=new Clock();Mail mail=new Mail();var service=service(clock,mail);var enrollment=enroll(service,uid);Map<String,String> before=rows(EMAIL_TABLES);var challenge=send(service,uid,enrollment);String code=mail.code();check(mail.first==1&&mail.ordinary==0,"first bind uses fixed first-purpose transport");check(before.equals(rows(EMAIL_TABLES)),"delivery leaves persisted email empty");noSession("delivered first challenge");
            denied(()->service.verify(challenge.challengeId(),code),"first challenge cannot enter ordinary verification");denied(()->service.resend(challenge.challengeId(),"127.0.0.1"),"ordinary resend cannot consume first purpose");String token=finish(service,challenge,code);var snapshot=NotificationChannelsAccountEmailPreparation.loginSnapshot(uid);check(snapshot.revision()==1&&email(uid).equals(snapshot.email()),"complete writes first real audited email revision");check("COMPLETED".equals(Db.one("SELECT state FROM s01_account_email_first_bind WHERE user_id=?",uid).get("state")),"gate completion persists");check(FirstBindStore.allowsSession(uid),"completed gate allows final Auth path");check(service.enroll(credential(uid))==null,"completed account returns to ordinary flow");Auth.logout(token);denied(()->service.verifyFirst(challenge.challengeId(),code),"consumed first code cannot issue another session");denied(()->send(service,uid,enrollment),"completed enrollment cannot send again");
            rejected(429,()->service.begin(credential(uid),"127.0.0.1"),"normal login shares first-binding account cooldown");clock.advance(MINUTE);var normal=service.begin(credential(uid),"127.0.0.1");String normalCode=mail.code();denied(()->service.verifyFirst(normal.challengeId(),normalCode),"ordinary code cannot invoke first write callback");var checked=service.verify(normal.challengeId(),normalCode);check(checked.snapshot().equals(snapshot),"ordinary login remains compatible after binding");check(mail.ordinary==1,"postbind ordinary login uses normal purpose");}
    }
    static void replacementsAndFailureBudget()throws Exception{
        Clock clock=new Clock();Mail mail=new Mail();var service=service(clock,mail);var old=enroll(service,103);var first=send(service,103,old);String firstCode=mail.code();var fresh=enroll(service,103);denied(()->send(service,103,old),"new password proof replaces previous proof");denied(()->service.verifyFirst(first.challengeId(),firstCode),"new password proof cancels old challenge");clock.advance(MINUTE);var a=send(service,103,fresh);String aCode=mail.code();clock.advance(MINUTE);var b=send(service,fresh,"different-103@example.invalid","127.0.0.1");String bCode=mail.code();clock.advance(MINUTE);var again=send(service,103,fresh);denied(()->service.verifyFirst(a.challengeId(),aCode),"A-B-A address cannot revive original A challenge");denied(()->service.verifyFirst(b.challengeId(),bCode),"changed destination invalidates previous challenge");service.cancelEnrollment(fresh.enrollmentId());
        Clock otherClock=new Clock();Mail otherMail=new Mail();var other=service(otherClock,otherMail);var enrollment=enroll(other,104);var challenge=send(other,104,enrollment);String correct=otherMail.code(),wrong=correct.equals("000000")?"000001":"000000";for(int i=0;i<4;i++)rejected(400,()->other.verifyFirst(challenge.challengeId(),wrong),"incorrect attempt counted");otherClock.advance(MINUTE);var replacement=other.resendFirst(challenge.challengeId(),"127.0.0.1");check(replacement.expiresAt()<=enrollment.expiresAt(),"resend preserves original proof expiry");String finalWrong=otherMail.code().equals("000000")?"000001":"000000";rejected(401,()->other.verifyFirst(replacement.challengeId(),finalWrong),"fifth cumulative wrong code consumes replacement");denied(()->other.verifyFirst(replacement.challengeId(),otherMail.code()),"correct code cannot repair exhausted attempts");noSession("failed attempts");
    }
    static void sendFailureAndCancellation()throws Exception{
        Clock clock=new Clock();Mail mail=new Mail();var service=service(clock,mail);var enrollment=enroll(service,105);mail.fail=true;denied(()->send(service,105,enrollment),"SMTP failure fails closed");mail.fail=false;clock.advance(MINUTE);denied(()->send(service,105,enrollment),"SMTP failure consumes enrollment rather than reviving it");check(Db.one("SELECT * FROM s01_account_email_maintenance_heads WHERE user_id=105")==null,"SMTP failure writes no email");
        for(long uid:List.of(106L,107L,108L)){Clock heldClock=new Clock();Mail held=new Mail();held.entered=new CountDownLatch(1);held.release=new CountDownLatch(1);var engine=service(heldClock,held);var pending=enroll(engine,uid);ExecutorService pool=Executors.newSingleThreadExecutor();Future<Object> send=pool.submit(()->{try{return engine.beginFirst(pending.enrollmentId(),email(uid),"127.0.0.1");}catch(Api.ApiException expected){return expected.code;}});try{check(held.entered.await(5,TimeUnit.SECONDS),"synthetic sender enters outside lock");synchronized(Api.MUTATION_LOCK){if(uid==106)engine.cancelEnrollment(pending.enrollmentId());else if(uid==107)Auth.revokeUserSessions(uid);else Db.exec("UPDATE users SET status=0 WHERE id=?",uid);}held.release.countDown();check(send.get(10,TimeUnit.SECONDS) instanceof Integer,"cancel, generation change or disable during delivery prevents ready challenge");noSession("late delivery");}finally{held.release.countDown();pool.shutdownNow();check(pool.awaitTermination(5,TimeUnit.SECONDS),"sender worker terminates");if(uid==108)Db.exec("UPDATE users SET status=1 WHERE id=?",uid);}}
    }
    static void absoluteExpiryAndRollbackClock()throws Exception{
        Clock clock=new Clock();Mail mail=new Mail();var service=service(clock,mail);var enrollment=enroll(service,109);var challenge=send(service,109,enrollment);clock.advance(9*MINUTE+30_000);var resend=service.resendFirst(challenge.challengeId(),"127.0.0.1");check(resend.expiresAt()==enrollment.expiresAt(),"late resend cannot extend ten-minute enrollment");check(resend.resendAfter()<=resend.expiresAt(),"late resend DTO never exceeds absolute expiry");clock.advance(30_000);denied(()->service.verifyFirst(resend.challengeId(),mail.code()),"exact absolute deadline rejects correct code");clock.advance(-5*MINUTE);denied(()->service.verifyFirst(resend.challengeId(),mail.code()),"backward clock cannot revive expired proof");
    }
    static void uniquenessAndConcurrency()throws Exception{
        Clock clock=new Clock();Mail mail=new Mail();var service=service(clock,mail);var one=enroll(service,110);var c1=send(service,one,"shared-target@example.invalid","127.0.0.1");String code1=mail.code();clock.advance(MINUTE);var two=enroll(service,111);var c2=send(service,two,"SHARED-TARGET@example.invalid","127.0.0.2");String code2=mail.code();check(mail.values.size()==2,"occupied candidate receives same sending behavior before proof");ExecutorService pool=Executors.newFixedThreadPool(2);CountDownLatch start=new CountDownLatch(1);List<Future<Object>> work=new ArrayList<>();try{work.add(pool.submit(()->verifyAtBarrier(service,c1,code1,start)));work.add(pool.submit(()->verifyAtBarrier(service,c2,code2,start)));start.countDown();int won=0,lost=0;for(var future:work){Object result=future.get(10,TimeUnit.SECONDS);if(result instanceof NotificationChannelsLoginVerification.Verified)won++;else lost++;}check(won==1&&lost==1,"two accounts competing for normalized email have exactly one commit");check(((Number)Db.one("SELECT COUNT(*) AS n FROM s01_account_email_maintenance_heads WHERE email_key='shared-target@example.invalid'").get("n")).longValue()==1,"global normalized ownership has one email head");noSession("engine concurrent commit");}finally{pool.shutdownNow();check(pool.awaitTermination(5,TimeUnit.SECONDS),"duplicate race workers terminate");}
        Clock dupClock=new Clock();Mail dupMail=new Mail();var duplicate=service(dupClock,dupMail);var enrollment=enroll(duplicate,112);var challenge=send(duplicate,112,enrollment);String code=dupMail.code();ExecutorService single=Executors.newFixedThreadPool(2);CountDownLatch barrier=new CountDownLatch(1);try{var a=single.submit(()->verifyAtBarrier(duplicate,challenge,code,barrier));var b=single.submit(()->verifyAtBarrier(duplicate,challenge,code,barrier));barrier.countDown();Object av=a.get(10,TimeUnit.SECONDS),bv=b.get(10,TimeUnit.SECONDS);check((av instanceof NotificationChannelsLoginVerification.Verified)^(bv instanceof NotificationChannelsLoginVerification.Verified),"same challenge concurrent verify has exactly one winner");check(((Number)Db.one("SELECT COUNT(*) AS n FROM s01_account_email_maintenance_revisions WHERE user_id=112").get("n")).intValue()==1,"same code writes one revision");}finally{single.shutdownNow();check(single.awaitTermination(5,TimeUnit.SECONDS),"single-code race workers terminate");}
    }
    static Object verifyAtBarrier(NotificationChannelsLoginVerification service,NotificationChannelsLoginVerification.Challenge challenge,String code,CountDownLatch start)throws Exception{start.await();try{return service.verifyFirst(challenge.challengeId(),code);}catch(Api.ApiException failure){return failure.code;}}
    static void sharedRecipientQuota()throws Exception{
        Clock clock=new Clock();Mail mail=new Mail();var service=service(clock,mail);String target="recipient-quota@example.invalid";int sent=0;boolean limited=false;for(long uid=130;uid<160;uid++){var enrollment=enroll(service,uid);try{send(service,enrollment,target,"127.0.1."+(uid-129));sent++;}catch(Api.ApiException failure){check(failure.code==429,"cross-account same-recipient quota is rate limit");limited=true;break;}service.cancelEnrollment(enrollment.enrollmentId());clock.advance(MINUTE);}check(limited&&sent>0&&sent<30,"normalized recipient quota bounds independent accounts before global/socket caps");var remaining=enroll(service,160);rejected(429,()->send(service,remaining,target.toUpperCase(Locale.ROOT),"127.0.2.1"),"uppercase destination cannot escape recipient quota");noSession("recipient abuse");
    }
    static void transactionFailures()throws Exception{
        for(boolean afterCommit:List.of(false,true)){long uid=afterCommit?114:113;Clock clock=new Clock();Mail mail=new Mail();var service=service(clock,mail);var enrollment=enroll(service,uid);var challenge=send(service,uid,enrollment);String code=mail.code();Map<String,String> before=rows(EMAIL_TABLES);Connection actual=Db.get();Field connection=Db.class.getDeclaredField("conn");connection.setAccessible(true);boolean[] injected={false},committed={false};Connection proxy=(Connection)Proxy.newProxyInstance(FirstBindTest.class.getClassLoader(),new Class<?>[]{Connection.class},(p,m,a)->{try{if(!afterCommit&&m.getName().equals("prepareStatement")&&a!=null&&a.length>0&&a[0] instanceof String sql&&sql.matches("(?is)^\\s*UPDATE\\s+s01_account_email_first_bind.*")){injected[0]=true;throw new SQLException("synthetic gate completion failure");}if(afterCommit&&m.getName().equals("commit")){Object result=m.invoke(actual,a);committed[0]=true;return result;}if(afterCommit&&committed[0]&&m.getName().equals("setAutoCommit")&&Boolean.TRUE.equals(a[0])&&!injected[0]){injected[0]=true;m.invoke(actual,a);throw new SQLException("synthetic committed but restoration uncertain");}return m.invoke(actual,a);}catch(InvocationTargetException target){throw target.getCause();}});connection.set(null,proxy);try{denied(()->service.verifyFirst(challenge.challengeId(),code),afterCommit?"postcommit uncertainty":"SQL rollback");}finally{connection.set(null,actual);if(!actual.getAutoCommit())actual.setAutoCommit(true);}check(injected[0],"expected transaction fault was reached");noSession("transaction failure");denied(()->service.verifyFirst(challenge.challengeId(),code),"failed transaction code never resurrects");if(afterCommit){check("COMPLETED".equals(Db.one("SELECT state FROM s01_account_email_first_bind WHERE user_id=?",uid).get("state")),"committed ambiguity keeps durable completion");check(NotificationChannelsAccountEmailPreparation.loginSnapshot(uid).revision()==1,"postcommit ambiguity keeps audited email");clock.advance(MINUTE);check(service.begin(credential(uid),"127.0.0.1")!=null,"fresh original password can recover through normal email login");}else check(before.equals(rows(EMAIL_TABLES)),"email heads, revisions, requests and gate roll back atomically");}
    }
    static void schemaFailClosed()throws Exception{
        for(String table:List.of("s01_account_email_first_bind","s01_account_email_first_bind_receipts","s01_account_email_first_bind_events")){
            var proof=credential(182);var snapshot=NotificationChannelsAccountEmailPreparation.loginSnapshot(182);String token=Auth.issueVerified(proof,snapshot);check(Auth.get(token)!=null,"uninvolved registered account has ordinary verified session before schema fault");
            Db.exec("ALTER TABLE "+table+" RENAME TO synthetic_missing_gate");try{check(Auth.get(token)==null,"missing gate schema invalidates existing ordinary session");denied(()->Auth.issueVerified(proof,snapshot),"missing gate schema cannot issue ordinary session");denied(()->FirstBindStore.allowsSession(180),"missing gate schema is not interpreted as absent old-account gate");denied(()->FirstBindStore.ready(credential(115)),"missing gate schema cannot admit READY");System.setProperty("login.email.mode","legacy");try{denied(()->Auth.login(username(182),PASSWORD),"legacy rejects missing gate schema");}finally{System.setProperty("login.email.mode","required");}}finally{Db.exec("ALTER TABLE synthetic_missing_gate RENAME TO "+table);}
            check(FirstBindStore.allowsSession(182),"restored gate schema leaves uninvolved account usable");check(FirstBindStore.ready(credential(115))!=null,"restored schema preserves genuine READY");noSession("missing schema failures");
        }
    }
    static void sourceAndAuthorizationAba()throws Exception{
        Clock clock=new Clock();Mail mail=new Mail();var engine=service(clock,mail);var enrollment=enroll(engine,152);var challenge=send(engine,152,enrollment);String code=mail.code();var source=Db.one("SELECT source_reference FROM organization_account_import_people WHERE account_id=152");Db.exec("UPDATE organization_account_import_people SET source_reference='SYNTHETIC-TEMPORARY-CHANGED' WHERE account_id=152");try{denied(()->engine.verifyFirst(challenge.challengeId(),code),"source binding change invalidates first proof");}finally{Db.exec("UPDATE organization_account_import_people SET source_reference=? WHERE account_id=152",source.get("source_reference"));}denied(()->engine.verifyFirst(challenge.challengeId(),code),"source A-B-A cannot restore old proof");
        var old=enroll(engine,116);var oldChallenge=send(engine,116,old);String oldCode=mail.code();long original=((Number)Db.one("SELECT epoch FROM s01_account_email_first_bind WHERE user_id=116").get("epoch")).longValue();FirstBindPreparation.revoke(username(1),PASSWORD,receiptFor(List.of(116L)));check(!FirstBindStore.allowsSession(116),"REVOKED gate refuses ordinary access");System.setProperty("login.email.mode","legacy");try{check(Auth.login(username(116),PASSWORD)==null,"REVOKED gate refuses accidental legacy login");}finally{System.setProperty("login.email.mode","required");}prepareReady(List.of(116L));check(((Number)Db.one("SELECT epoch FROM s01_account_email_first_bind WHERE user_id=116").get("epoch")).longValue()==original+2,"revoke then reauthorize increments gate epoch twice");denied(()->engine.verifyFirst(oldChallenge.challengeId(),oldCode),"READY-REVOKED-READY cannot restore old code");noSession("gate reauthorization");
    }
    static void normalAndFirstShareRecipientQuota()throws Exception{
        Clock clock=new Clock();Mail mail=new Mail();var engine=service(clock,mail);var normal=engine.begin(credential(182),"127.0.5.1");String normalCode=mail.code();var enrollment=enroll(engine,117);rejected(429,()->send(engine,enrollment,email(182).toUpperCase(Locale.ROOT),"127.0.5.2"),"normal and first purposes share normalized recipient cooldown");clock.advance(MINUTE);var challenge=send(engine,enrollment,email(182),"127.0.5.2");String firstCode=mail.code();denied(()->engine.verifyFirst(challenge.challengeId(),firstCode),"already-registered recipient rejects only after mailbox proof");check(engine.verify(normal.challengeId(),normalCode).credential().uid()==182,"other account's legitimate ordinary challenge remains its own");noSession("cross-purpose recipient quota");
    }
    static Auth.Session admin()throws Exception{String previous=System.getProperty("login.email.mode");System.setProperty("login.email.mode","legacy");try{String token=Auth.login(username(1),PASSWORD);return Auth.get(token);}finally{System.setProperty("login.email.mode",previous);}}
    static void markReady(long uid)throws Exception{prepareReady(List.of(uid));}
    static FirstBindPreparation.Receipt receiptFor(List<Long> users)throws Exception{System.setProperty("s01.first-bind.offline","true");List<FirstBindPreparation.Account> accounts=new ArrayList<>();synchronized(Api.MUTATION_LOCK){for(long uid:users){var identity=NotificationChannelsAccountEmailMaintenance.firstBindIdentity(uid);var row=Db.one("SELECT username,name,role,status,password FROM users WHERE id=?",uid);var gate=Db.one("SELECT epoch FROM s01_account_email_first_bind WHERE user_id=?",uid);accounts.add(new FirstBindPreparation.Account(uid,(String)row.get("username"),(String)row.get("name"),(String)row.get("role"),((Number)row.get("status")).intValue(),FirstBindPreparation.passwordFingerprint((String)row.get("password")),identity.kind(),identity.binding(),gate==null?0:((Number)gate.get("epoch")).longValue(),null));}}return new FirstBindPreparation.Receipt(UUID.randomUUID().toString(),"SYNTHETIC-R26-FIRST-BIND-TEST",FirstBindPreparation.manifestDigest(accounts),accounts);}
    static void prepareReady(List<Long> users)throws Exception{FirstBindPreparation.prepare(username(1),PASSWORD,receiptFor(users));}
    static void setup(boolean full)throws Exception{
        System.setProperty("login.email.mode","legacy");if(!full)Db.exec("CREATE TABLE users(id BIGINT PRIMARY KEY,username VARCHAR(64) UNIQUE,password VARCHAR(128),name VARCHAR(64),role VARCHAR(16),status INT)");hash=Auth.hash(PASSWORD);if(full)Db.exec("UPDATE users SET username=?,password=?,name='Synthetic first admin',role='admin',status=1 WHERE id=1",username(1),hash);else Db.exec("INSERT INTO users VALUES(1,?,?,?,'admin',1)",username(1),hash,"Synthetic first admin");for(long uid=100;uid<=185;uid++)Db.exec("INSERT INTO users(id,username,password,name,role,status) VALUES(?,?,?,?,'viewer',?)",uid,username(uid),hash,"Synthetic first user "+uid,uid==181?0:1);Db.exec("UPDATE users SET role='admin' WHERE id=101");OrganizationAccountImport.init();NotificationChannelsAccountEmailPreparation.init();TrustedDevices.init();FirstBindStore.init();
        for(long uid:List.of(101L,151L,152L)){String batch="SYNTHETIC-FIRST-BIND";Db.exec("INSERT INTO organization_account_import_people(person_code,source_namespace,source_reference,account_id,batch_key,source_fingerprint,payload,disposition,created_by) VALUES(?,?,?,?,?,?,?,?,1)","SYNTHETIC-FIRST-P"+uid,"b".repeat(64),"SYNTHETIC-FIRST-REF"+uid,uid,batch,"a".repeat(64),Json.write(Map.of("synthetic",true,"accountId",uid,"readyForExecution",0,"supplemental",uid!=101)),"CREATE_PENDING");}Db.exec("INSERT INTO organization_account_import_batches(batch_key,source_fingerprint,decision_digest,receipt,created_by) VALUES(?,?,?,?,1)","SYNTHETIC-FIRST-BIND","a".repeat(64),"c".repeat(64),Json.write(Map.of("synthetic",true,"revision",1,"accountsActivated",false,"permissionsPublished",false)));Db.exec("UPDATE organization_account_import_state SET revision=1 WHERE singleton=1");
        Auth.Session admin=admin();NotificationChannelsAccountEmailMaintenance.save(admin,Map.of("user_id",182L,"expected_revision",0L,"request_id",UUID.randomUUID().toString(),"email",email(182),"confirmed_username",username(182),"purpose","LOGIN_VERIFICATION"));sessions().clear();System.setProperty("login.email.mode","required");List<Long> approved=new ArrayList<>();for(long uid=100;uid<180;uid++)approved.add(uid);prepareReady(approved);for(String table:List.of("synthetic_permissions","synthetic_outbox")){Db.exec("CREATE TABLE "+table+"(id INT PRIMARY KEY,payload VARCHAR(64))");Db.exec("INSERT INTO "+table+" VALUES(1,'unchanged synthetic sentinel')");}
    }
    static Path configure(String[] args,boolean reopen)throws Exception{if(args.length!=(reopen?2:1))throw new IllegalArgumentException("Owned synthetic data directory required");Path path=Path.of(args[reopen?1:0]);if(!path.isAbsolute()||Files.isSymbolicLink(path))throw new IllegalArgumentException("Absolute nonsymlink directory required");Path data=path.toRealPath(),root=data.getParent();if(!data.getFileName().toString().equals("data")||!root.getFileName().toString().startsWith("yanxu-first-bind-r26.")||!Files.isRegularFile(root.resolve(".first-bind-test-root")))throw new IllegalArgumentException("Owned test marker required");String configured=System.getProperty("data.dir");if(configured==null||!Path.of(configured).toRealPath().equals(data))throw new IllegalArgumentException("JVM data.dir must already match owned data");if(!"disabled".equals(System.getenv("YANXU_LOGIN_MAIL_TRANSPORT")))throw new IllegalArgumentException("Real mail transport must be disabled");for(String key:System.getenv().keySet())if(key.startsWith("YANXU_LOGIN_SMTP_"))throw new IllegalArgumentException("SMTP settings prohibited");if(reopen){if(!Files.isRegularFile(data.resolve("training.mv.db")))throw new IllegalArgumentException("Existing owned fixture required");}else try(var files=Files.list(data)){if(files.findAny().isPresent())throw new IllegalArgumentException("Empty new fixture required");}System.setProperty("data.dir",data.toString());return data;}
    static void prepareRestart(Path data)throws Exception{Clock clock=new Clock();Mail mail=new Mail();var service=service(clock,mail);var enrollment=enroll(service,170);var challenge=send(service,170,enrollment);Properties p=new Properties();p.setProperty("enrollment",enrollment.enrollmentId());p.setProperty("challenge",challenge.challengeId());p.setProperty("code",mail.code());try(var out=Files.newOutputStream(data.getParent().resolve("synthetic-restart.properties"))){p.store(out,"Synthetic memory proof should die at restart");}}
    static void restart(Path data)throws Exception{System.setProperty("login.email.mode","required");FirstBindStore.init();Clock clock=new Clock();Mail mail=new Mail();var service=service(clock,mail);Properties p=new Properties();try(var in=Files.newInputStream(data.getParent().resolve("synthetic-restart.properties"))){p.load(in);}var before=rows(EMAIL_TABLES);denied(()->service.beginFirst(p.getProperty("enrollment"),email(170),"127.0.0.1"),"cold process rejects old enrollment");denied(()->service.verifyFirst(p.getProperty("challenge"),p.getProperty("code")),"cold process rejects old correct code");check(before.equals(rows(EMAIL_TABLES)),"replayed cold proof is write-free");check(FirstBindStore.allowsSession(101),"completed gate remains durable across cold JVM");check(!FirstBindStore.allowsSession(170),"pending gate remains protected across cold JVM");check(NotificationChannelsAccountEmailPreparation.loginSnapshot(101).revision()==1,"audited imported completion survives cold JVM");check(service.begin(credential(101),"127.0.0.1")!=null,"cold completed account recovers via ordinary login proof");noSession("cold replay and new email challenge");}
    public static void main(String[] args)throws Exception{boolean reopen=args.length>0&&args[0].equals("--reopen");Path data=configure(args,reopen);boolean opened=false;try{check(Db.get().getMetaData().getURL().startsWith("jdbc:h2:"+data.resolve("training")),"validated isolated H2 location");opened=true;if(reopen)restart(data);else{setup(false);var before=rows(PROTECTED_TABLES);admissionAndGate();completionAndPurpose();replacementsAndFailureBudget();sendFailureAndCancellation();absoluteExpiryAndRollbackClock();uniquenessAndConcurrency();sharedRecipientQuota();normalAndFirstShareRecipientQuota();transactionFailures();schemaFailClosed();sourceAndAuthorizationAba();check(before.equals(rows(PROTECTED_TABLES)),"all first-binding flows preserve users, import identities, permissions and outbox");prepareRestart(data);}System.out.println("R26 first bind "+(reopen?"cold JVM":"core")+": "+checks+" checks passed; synthetic H2, memory mail, no network or private data.");}finally{if(opened)Db.exec("SHUTDOWN");}}
}
