'use strict';
// Actual pageUsers, original modal/API and relationship module with synthetic DOM/transport only.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const base=fs.readFileSync(path.join(__dirname,'IntegrationAccountBindingsUI.test.cjs'),'utf8');const support=vm.runInNewContext(base.slice(0,base.indexOf('(async () => {')).replace('pages.replace(', 'pages.replaceAll(')+'\n({harness,NodeStub});',{require,__dirname,console,structuredClone,AbortController,setImmediate});
const moduleSource=fs.readFileSync(path.join(__dirname,'../web/modules/identity/account-relationships.js'),'utf8');
const deferred=()=>{let resolve;const promise=new Promise(yes=>resolve=yes);return{promise,resolve};},tick=()=>new Promise(yes=>setImmediate(yes));let checks=0;const check=(v,l)=>{assert.ok(v,l);checks++;},equal=(v,x,l)=>{assert.deepEqual(JSON.parse(JSON.stringify(v)),x,l);checks++;};
const candidate=(code,id,name='同名候选')=>({person_code:code,account_id:id,username:'synthetic-'+id,name,role_codes:['SYN-ROLE'],eligible:true});
const get=()=>({configuration_version:'SYN-1',subject:{account_id:12,username:'synthetic-12',name:'合成原账号',account_enabled:true,binding_enabled:true,person_code:'SOURCE-12',organization_code:'ORG-001',person_enabled:true,role_codes:['SYN-SOURCE']},current:{leader:candidate('LEAD-A',21),bp:candidate('BP-A',23,'合成 BP')},leader_required:true,bp_required:false,leader_options:[candidate('LEAD-A',21),candidate('LEAD-B',22),candidate('BOTH',24)],bp_options:[candidate('BP-A',23,'合成 BP'),candidate('BOTH',24),candidate('LEAD-B',22)],combined_person_codes:['BOTH'],warnings:[]});
function harness({role='admin',initial=get(),override,moduleFail=false,moduleGate,sessionInvalidated=false}={}){
 let remote=structuredClone(initial),review=null,sequence=0,controller,host;
 const h=support.harness({fetchOverride:(url,opts,normal,respond)=>{const fallback=()=>{if(!url.startsWith('/api/organization/account-relationships/'))return normal(url,opts);if(opts.method==='GET')return respond(remote);const body=JSON.parse(opts.body);if(url.endsWith('/preview')){const selected=key=>body[key+'_person_code']===null?null:remote[key+'_options'].find(r=>r.person_code===body[key+'_person_code']);const after={leader:selected('leader'),bp:selected('bp')};const changed=['leader','bp'].some(k=>(after[k]?.person_code??null)!==(remote.current[k]?.person_code??null));review={configuration_version:remote.configuration_version,subject:remote.subject,before:remote.current,after,changed,review_token:(++sequence).toString(16).padStart(64,'0'),expires_at:new Date(Date.now()+300000).toISOString(),warnings:[],workflow_impact:{historical_assignments_changed:false,pending_tasks_reassigned:false,combined_workflows_may_pause:changed}};return respond(review);}if(url.endsWith('/confirm')){const saved=review.changed;if(saved){remote={...remote,current:review.after,configuration_version:'SYN-'+(++sequence)};}return respond({saved,unchanged:!saved,configuration_version:remote.configuration_version,account_id:12,person_code:'SOURCE-12',leader_person_code:review.after.leader?.person_code??null,bp_person_code:review.after.bp?.person_code??null,sessionInvalidated});}throw Error('Unexpected path');};return override?override(url,opts,fallback,respond,{get:()=>remote,set:v=>remote=v,review:()=>review}):fallback();}});
 h.sandbox.state.user.role=role;vm.runInContext('{'+moduleSource.replace('export function createAccountRelationships','function createAccountRelationships')+';globalThis.relationshipsModule=createAccountRelationships;}',h.sandbox);
 const load=h.sandbox.loadIdentityModule;h.sandbox.loadIdentityModule=async url=>{if(!url.includes('/account-relationships.js?'))return load(url);h.imports.push(url);if(moduleGate)await moduleGate.promise;if(moduleFail)throw Error('Synthetic unavailable');return{createAccountRelationships(context){host=context;controller=h.sandbox.relationshipsModule(context);return controller;}};};
 h.open=()=>h.modules[0].host.actions.find(a=>a.l==='维护负责人/BP').onClick(h.users.find(r=>r.id===12));h.node=k=>h.modal()?.querySelector('[data-relationships-'+k+']');h.change=async(k,v)=>{h.node(k).value=v;h.node(k).onchange();await tick();};h.click=k=>h.node(k).onclick();h.reads=()=>h.calls.filter(r=>r.url.startsWith('/api/organization/account-relationships/')&&r.opts.method==='GET');h.writes=tail=>h.calls.filter(r=>r.url.endsWith('/'+tail)&&r.url.includes('/organization/account-relationships/'));h.remote=()=>remote;h.controller=()=>controller;h.host=()=>host;return h;
}
(async()=>{
 const h=harness();await h.mount();equal(h.reads().length,0,'List does not inspect every target');check(h.actions(12).some(a=>a.textContent==='维护负责人/BP'),'Explicit admin row entry');await h.open();const mask=h.modal();equal(h.reads()[0].url,'/api/organization/account-relationships/12','GET target uses exact path without query');equal(h.node('leader').value,'LEAD-A','Current leader retained instead of first/default guess');equal(h.node('bp').value,'BP-A','Current BP retained');check(h.node('subject').textContent.includes('合成原账号')&&h.node('subject').textContent.includes('账号 ID 12'),'Explicit server subject');check(h.node('leader').textContent.includes('账号 ID 21')&&h.node('leader').textContent.includes('账号 ID 22'),'Same-name candidates retain separate account IDs');check(h.modal().textContent.includes('不会转派待办'),'Historic assignment limitation shown');equal(h.writes('preview').length,0,'Opening never creates preview');await h.change('leader','LEAD-B');equal(h.writes('preview').length,0,'Selection does not automatically POST');await h.click('preview');equal(JSON.parse(h.writes('preview')[0].opts.body),{expected_version:'SYN-1',leader_person_code:'LEAD-B',bp_person_code:'BP-A'},'Preview has exactly server version and two explicit selections');check(h.node('review').textContent.includes('改前')&&h.node('review').textContent.includes('账号 ID 21')&&h.node('review').textContent.includes('账号 ID 22'),'Preview exposes both precise identities');check(h.node('review').textContent.includes('兼任')&&!h.node('review').textContent.includes('000000000000'),'Token never enters DOM');equal(h.writes('confirm').length,0,'Preview is separate from confirm');await h.change('bp','');check(h.node('confirm').disabled&&!h.node('review').textContent,'Any value change discards review authorization');await h.click('preview');equal(JSON.parse(h.writes('preview').at(-1).opts.body).bp_person_code,null,'Allowed empty maps to null');await h.click('confirm');equal(Object.keys(JSON.parse(h.writes('confirm')[0].opts.body)),['review_token'],'Confirm body contains only original review token');check(h.modal()===mask&&h.node('notice').textContent.includes('已保存'),'Known save refreshes same modal');equal(h.remote().current.leader.person_code,'LEAD-B','Saved relation re-read');equal(h.node('bp').value,'','Saved null remains explicit empty');equal(h.invalidations,0,'No session removal without explicit flag');check(h.calls.filter(r=>r.url==='/api/organization/config').length===2,'Known save refreshes original binding configuration snapshot');
 await h.click('preview');check(h.node('review').textContent.includes('不会重复保存'),'No-change preview is supported');await h.click('confirm');check(h.node('notice').textContent.includes('未变化'),'No-op confirms without claiming a changed write');await h.change('leader','LEAD-A');h.sandbox.closeModal();check(h.modal()&&h.node('guard').textContent.includes('尚未确认'),'Dirty close uses page-local guard');await h.click('stay');equal(h.node('leader').value,'LEAD-A','Stay retains selected draft');h.sandbox.closeModal();await h.click('discard');check(!h.modal(),'Explicit discard closes owned modal');
 const stale=get();stale.current.leader={...candidate('RETIRED',29),eligible:false};const old=harness({initial:stale});await old.mount();await old.open();equal(old.node('leader').value,'RETIRED','Unavailable existing relation not auto-replaced');check(old.node('current').textContent.includes('当前不可选'),'Unavailable old relation remains visible');await old.click('preview');equal(old.writes('preview').length,0,'Cannot submit unavailable old selection without deliberate replacement');old.controller().destroy();
 const disabled=get();disabled.subject.account_enabled=disabled.subject.binding_enabled=disabled.subject.person_enabled=false;const disabledSource=harness({initial:disabled});await disabledSource.mount();await disabledSource.open();check(!disabledSource.node('leader').disabled&&disabledSource.node('subject').textContent.includes('账号停用'),'Source enable flags are displayed without inventing editing restrictions');disabledSource.controller().destroy();
 const combo=harness();await combo.mount();await combo.open();await combo.change('leader','LEAD-B');await combo.change('bp','LEAD-B');await combo.click('preview');equal(combo.writes('preview').length,0,'Same person without explicit combined evidence rejected');await combo.change('leader','BOTH');await combo.change('bp','BOTH');await combo.click('preview');check(!combo.node('confirm').disabled,'Explicit combined candidate can be reviewed');combo.controller().destroy();
 const missing=get();missing.current.leader=null;const none=harness({initial:missing});await none.mount();await none.open();equal(none.node('leader').value,'','Required null never defaults to first option');await none.click('preview');equal(none.writes('preview').length,0,'Missing required relation stays local invalid');none.controller().destroy();
 for(const role of ['viewer','manager']){const denied=harness({role});await denied.mount();check(!denied.actions(12).some(a=>a.textContent==='维护负责人/BP'),role+' has no relationship editor entry');equal(denied.reads().length,0,role+' has no relationship read');denied.sandbox.beginRouteEpoch();}
 for(const status of [401,403,409,503]){const bad=harness({override:(url,opts,normal,respond)=>url.includes('/organization/account-relationships/')?respond(null,status):normal()});await bad.mount();await bad.open();if([401,403].includes(status))check(!bad.modal(),status+' initial read removes private modal');else check(bad.node('leader').disabled&&bad.node('preview').disabled&&!bad.node('subject').textContent,status+' cannot edit unpublished/unbound or bad configuration');bad.sandbox.beginRouteEpoch();}
 const mutations=[v=>v.subject.account_id=99,v=>v.subject.binding_enabled=null,v=>v.leader_required=null,v=>v.current.leader=undefined,v=>v.leader_options[0].eligible=false,v=>v.leader_options.push(v.leader_options[0]),v=>v.leader_options[1].account_id=21,v=>v.current.leader.account_id=99,v=>v.combined_person_codes.push('MISSING'),v=>v.warnings=null];for(const change of mutations){const value=get();change(value);const bad=harness({initial:value});await bad.mount();await bad.open();check(bad.node('leader').disabled&&!bad.node('subject').textContent,'Invalid editor DTO clears data and stays disabled');bad.controller().destroy();}
 const evil='<img src=x onerror=alert(1)>',evilValue=get();evilValue.subject.name=evil;evilValue.leader_options[1].name=evil;evilValue.warnings=[evil];const escaped=harness({initial:evilValue});await escaped.mount();await escaped.open();await escaped.change('leader','LEAD-B');await escaped.click('preview');check(!escaped.modal().querySelector('img,script')&&escaped.node('review').textContent.includes(evil),'Names, warnings and preview values are escaped');escaped.controller().destroy();
 for(const mutation of [v=>v.configuration_version='WRONG',v=>v.after.leader.account_id=999,v=>v.review_token='bad',v=>v.expires_at='bad',v=>v.changed=false,v=>v.workflow_impact.pending_tasks_reassigned=true]){const x=harness({override:async(url,opts,normal,respond)=>{if(!url.endsWith('/preview'))return normal();const response=await normal(),envelope=JSON.parse(await response.text());mutation(envelope.data);return respond(envelope.data);}});await x.mount();await x.open();await x.change('leader','LEAD-B');await x.click('preview');check(x.node('confirm').disabled&&!x.node('review').textContent,'Malformed/mismatched preview cannot grant confirmation');x.controller().destroy();}
 for(const status of [400,401,403,409,503]){const x=harness({override:(url,opts,normal,respond)=>url.endsWith('/preview')?respond(null,status):normal()});await x.mount();await x.open();await x.change('leader','LEAD-B');await x.click('preview');if([401,403].includes(status))check(!x.modal(),status+' preview clears private modal');else check(x.node('confirm').disabled&&!x.node('review').textContent,status+' preview cannot reuse former token');x.sandbox.beginRouteEpoch();}
 const expires=harness({override:async(url,opts,normal,respond)=>{if(!url.endsWith('/preview'))return normal();const value=JSON.parse(await(await normal()).text()).data;value.expires_at='2000-01-01T00:00:00Z';return respond(value);}});await expires.mount();await expires.open();await expires.click('preview');check(expires.node('confirm').disabled,'Expired preview never enables confirmation');expires.controller().destroy();
 const verifyGate=deferred();let confirms=0;const double=harness({override:(url,opts,normal)=>url.endsWith('/confirm')?(confirms++,verifyGate.promise.then(normal)):normal()});await double.mount();await double.open();await double.change('leader','LEAD-B');await double.click('preview');const confirmation=double.click('confirm');await tick();await double.click('confirm');equal(confirms,1,'Duplicate confirm clicks cannot issue a second request');check(double.node('leader').disabled&&double.sandbox.closeModal()===false,'Confirm locks draft and modal navigation');verifyGate.resolve();await confirmation;double.controller().destroy();
 let lost=true;const unknown=harness({override:(url,opts,normal)=>url.endsWith('/confirm')&&lost?Promise.reject(Error('Synthetic connection loss')):normal()});await unknown.mount();await unknown.open();await unknown.change('leader','LEAD-B');await unknown.click('preview');await unknown.click('confirm');check(unknown.node('notice').textContent.includes('尚未核实')&&unknown.node('leader').disabled&&unknown.node('preview').disabled&&unknown.node('confirm').disabled,'Unknown confirmation blocks further writes until deliberate query');lost=false;await unknown.click('confirm');equal(unknown.writes('confirm').length,1,'Unknown confirmation is never resubmitted even by handler invocation');await unknown.click('read');await unknown.click('discard');await tick();check(unknown.node('leader').value==='LEAD-A'&&unknown.node('confirm').disabled,'Explicit refresh reads current relation and discards consumed/unknown review');unknown.controller().destroy();
 for(const status of [401,403,409]){const x=harness({override:(url,opts,normal,respond)=>url.endsWith('/confirm')?respond(null,status):normal()});await x.mount();await x.open();await x.change('leader','LEAD-B');await x.click('preview');await x.click('confirm');if([401,403].includes(status))check(!x.modal(),status+' confirm removes private modal');else check(x.node('confirm').disabled&&x.node('leader').disabled&&!x.node('review').textContent,'Consumed/stale review requires an explicit fresh read');x.sandbox.beginRouteEpoch();}
 const savedGate=deferred(),slowSaved=harness();await slowSaved.mount();await slowSaved.open();const originalSaved=slowSaved.host().onSaved;slowSaved.host().onSaved=async()=>{await savedGate.promise;await originalSaved();};await slowSaved.change('leader','LEAD-B');await slowSaved.click('preview');const saving=slowSaved.click('confirm');await tick();check(slowSaved.node('read').disabled&&slowSaved.node('leader').disabled&&slowSaved.node('preview').disabled,'Slow parent refresh keeps the post-save editor busy');await slowSaved.click('read');await slowSaved.click('preview');equal(slowSaved.reads().length,1,'Attempted new read during onSaved cannot race old continuation');equal(slowSaved.writes('preview').length,1,'Attempted second preview during onSaved is blocked');savedGate.resolve();await saving;equal(slowSaved.node('leader').value,'LEAD-B','Only confirmed relationship is reread after parent refresh');await slowSaved.change('leader','LEAD-A');await slowSaved.click('preview');check(!slowSaved.node('confirm').disabled&&slowSaved.node('review').textContent.includes('账号 ID 21'),'A later real editing round is retained after prior save settles');slowSaved.controller().destroy();
 let breakList=false;const listFail=harness({override:(url,opts,normal,respond)=>breakList&&url==='/api/organization/config'?respond(null,503):normal()});await listFail.mount();await listFail.open();await listFail.change('leader','LEAD-B');await listFail.click('preview');breakList=true;await listFail.click('confirm');check(listFail.node('notice').textContent.includes('已保存，账号列表刷新失败')&&listFail.node('confirm').disabled,'List refresh failure never turns a committed save into another confirmation');equal(listFail.writes('confirm').length,1,'Committed save is not resent after list refresh failure');listFail.controller().destroy();
 const committedLost=harness({override:async(url,opts,normal)=>{const response=await normal();if(url.endsWith('/confirm'))throw Error('Synthetic committed response lost');return response;}});await committedLost.mount();await committedLost.open();await committedLost.change('leader','LEAD-B');await committedLost.click('preview');await committedLost.click('confirm');await committedLost.click('read');await committedLost.click('discard');await tick();equal(committedLost.node('leader').value,'LEAD-B','Unknown saved result resolves only through fresh current relationship GET');equal(committedLost.calls.filter(r=>r.url==='/api/organization/config').length,2,'Unknown then version-changing read refreshes original binding snapshot');equal(committedLost.writes('confirm').length,1,'Unknown committed result is never confirmed twice');committedLost.controller().destroy();
 const invalidated=harness({sessionInvalidated:true});await invalidated.mount();await invalidated.open();await invalidated.change('leader','LEAD-B');await invalidated.click('preview');await invalidated.click('confirm');equal(invalidated.invalidations,1,'Only validated explicit sessionInvalidated returns host to original login');check(!invalidated.modal(),'Saved and invalidated session retains no relation data');
 for(const phase of ['read','preview','confirm']){const gate=deferred(),x=harness({override:(url,opts,normal)=>url.includes('/organization/account-relationships/')&&(phase==='read'?opts.method==='GET':url.endsWith('/'+phase))?gate.promise.then(normal):normal()});await x.mount();let pending;if(phase==='read')pending=x.open();else{await x.open();await x.change('leader','LEAD-B');if(phase==='confirm')await x.click('preview');pending=x.click(phase);}await tick();x.sandbox.state.user={uid:99,role:'admin'};gate.resolve();await pending;check(!x.modal()&&x.invalidations===0,'Late '+phase+' cannot render or invalidate a newer identity');}
 const routeGate=deferred(),route=harness({override:(url,opts,normal)=>url.endsWith('/preview')?routeGate.promise.then(normal):normal()});await route.mount();await route.open();await route.change('leader','LEAD-B');const rp=route.click('preview');await tick();route.sandbox.beginRouteEpoch();routeGate.resolve();await rp;check(!route.modal(),'Route abort clears pending preview');
 const owned=harness();await owned.mount();await owned.open();owned.controller().destroy();owned.sandbox.openModal('其他窗口','<p>保留</p>');const other=owned.modal();owned.controller().destroy();check(owned.modal()===other,'Destroy cannot close someone else’s modal');owned.sandbox.closeModal();
 const nullMask=harness();await nullMask.mount();await nullMask.open();nullMask.click('close');nullMask.host().openModal=()=>null;await nullMask.controller().open(12);equal(nullMask.reads().length,1,'Refused original modal never starts a request');
 const fail=harness({moduleFail:true});await fail.mount();await fail.open();check(!fail.modal()&&fail.actions(12).some(a=>a.textContent==='编辑'),'Module failure retains original account editor');
 console.log(JSON.stringify({ok:true,suite:'original account relationships preview confirmation',checks,network:false,browser:false,database:false}));
})().catch(error=>{console.error(error);process.exitCode=1;});
