'use strict';
// Real server-pinned teacher roster intake through Main/Auth and prior M01 account receipt. Synthetic only.
const fs=require('node:fs'),path=require('node:path'),net=require('node:net'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{spawn,execFile}=require('node:child_process'),{promisify}=require('node:util'),run=promisify(execFile),args={};
for(let i=2;i<process.argv.length;i+=2){assert.ok(['--java','--classes'].includes(process.argv[i])&&process.argv[i+1],'Use --java PATH --classes DIRECTORY or CLASSES_DIR');args[process.argv[i]]=process.argv[i+1];}
const java=args['--java']||'java',repo=path.resolve(__dirname,'..'),classes=fs.realpathSync(args['--classes']||process.env.CLASSES_DIR||'');assert.ok(classes!==repo&&!classes.startsWith(repo+path.sep),'Use isolated classes outside repository');
assert.ok(fs.existsSync(path.join(classes,'com/training/IntegrationTeacherRosterHttpFixture.class'))&&fs.existsSync(path.join(classes,'com/training/OrganizationAccountImportSourceTest.class')),'Compile new fixture and existing synthetic source fixture');
const own=fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'yanxu-teacher-roster-http-')),data=path.join(own,'data');fs.mkdirSync(data);
const password=crypto.randomBytes(24).toString('hex'),tokens={},failures=[],servicePids=[],readEvidence=[],base='/teacher-roster',accountBase='/organization/account-import';
const env={...process.env,YANXU_SEMANTIC_PORT:'',YANXU_SEMANTIC_TOKEN:''};let pins,child,port,checks=0,phase='setup',fatal=null,viewer,admin2;
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function check(ok,label){checks++;if(!ok)failures.push(phase+': '+label);}
function same(a,b,label){let ok=true;try{assert.deepEqual(a,b);}catch{ok=false;}check(ok,label);}
function options(resume=false){return ['-Dbind.address=127.0.0.1','-Dbootstrap.demo=false','-Dbootstrap.admin.password='+password,'-Dintegration.teacher.roster.root='+own,'-Dintegration.teacher.roster.resume='+resume,'-Ddata.dir='+data,'-Dsemantic.port=','-Dsemantic.token=',...(pins?['-Daccount.import.manifest='+pins.manifest,'-Daccount.import.manifest.sha256='+pins.sha256]:['-Daccount.import.manifest=','-Daccount.import.manifest.sha256=']),'-cp',classes+path.delimiter+path.join(repo,'lib','*')];}
async function fixture(operation){const r=await run(java,[...options(true),'com.training.IntegrationTeacherRosterHttpFixture',operation],{cwd:repo,env,timeout:20000,maxBuffer:65536});return JSON.parse(r.stdout.trim());}
function privateResponse(r,label){check(!r.text.includes(own)&&!r.text.includes('/sources/')&&!r.text.includes('000SYN')&&!r.text.includes('source_staff_id'),label+' reveals no source path or HR identifier');check(r.headers.get('cache-control')==='no-store',label+' is not cacheable');}
async function request(route,body,actor='admin',overrides={}){
 const headers={...(tokens[actor]?{'X-Token':tokens[actor]}:{})};if(body!==undefined)headers['Content-Type']=overrides.contentType||'application/json';
 const r=await fetch(`http://127.0.0.1:${port}/api${route}`,{method:overrides.method||(body===undefined?'GET':'POST'),headers,body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(10000)});
 const text=await r.text();let envelope=null;if(text){try{envelope=JSON.parse(text);}catch{throw new Error(route+': non-JSON HTTP '+r.status);}}
 const result={status:r.status,text,envelope,headers:r.headers};if(route.startsWith(base)||route.startsWith(accountBase))privateResponse(result,'Import HTTP');return result;
}
async function api(route,body,actor='admin'){const r=await request(route,body,actor);assert.equal(r.status,200,phase+': '+route+': '+r.status+': '+r.envelope?.msg);assert.equal(r.envelope?.code,0,route);return r.envelope.data;}
async function denied(route,body,actor,status,label,overrides={}){const r=await request(route,body,actor,overrides);check((Array.isArray(status)?status.includes(r.status):r.status===status)&&(overrides.method==='HEAD'?r.text==='':r.envelope?.code===r.status),label+' (HTTP '+r.status+': '+r.envelope?.msg+')');check(!r.envelope?.data?.branchCoverage&&!r.envelope?.data?.rows&&!r.headers.has('content-disposition'),'Rejected response exposes no partial intake data');check(!r.text.includes('SYNTHETIC PRIVATE'),'Rejected response reveals no candidate name');return r;}
async function login(actor){tokens[actor]=(await api('/login',{username:actor==='admin'?'admin':'synthetic-roster-'+actor,password},'anonymous')).token;}
async function boot(resume=false){for(const key of Object.keys(tokens))delete tokens[key];const listener=net.createServer();await new Promise((resolve,reject)=>{listener.once('error',reject);listener.listen(0,'127.0.0.1',resolve);});port=listener.address().port;await new Promise(resolve=>listener.close(resolve));child=spawn(java,[...options(resume),'com.training.IntegrationTeacherRosterHttpFixture',String(port)],{cwd:repo,env,stdio:'ignore'});if(child.pid)servicePids.push(child.pid);let error;child.once('error',e=>{error=e;});for(let i=0;i<150;i++){if(error)throw error;assert.equal(child.exitCode,null,'Synthetic pinned import Main exited');try{await login('admin');return;}catch{}await pause(100);}throw new Error('Synthetic Main startup timeout');}
async function stop(){const running=child;child=null;if(!running||running.exitCode!==null||running.signalCode!==null)return;await new Promise(resolve=>{const timer=setTimeout(()=>{if(running.exitCode===null&&running.signalCode===null)running.kill('SIGKILL');},2000);running.once('exit',()=>{clearTimeout(timer);resolve();});running.kill('SIGTERM');});}
async function control(operation){const nonce=crypto.randomUUID(),tmp=path.join(own,'control-request.next');fs.writeFileSync(tmp,JSON.stringify({nonce,operation}),{mode:0o600});fs.renameSync(tmp,path.join(own,'control-request.json'));for(let i=0;i<200;i++){try{const ack=JSON.parse(fs.readFileSync(path.join(own,'control-result.json'),'utf8'));if(ack.nonce===nonce&&ack.ok)return ack.data;}catch{}await pause(20);}throw new Error('Synthetic control timeout: '+operation);}
async function readOnly(label,operation){phase=label;const before=await control('snapshot');await operation();const after=await control('snapshot');same(Object.keys(after),Object.keys(before),'Read keeps schema unchanged');for(const name of Object.keys(before))same(after[name],before[name],'Read leaves full '+name+' contents unchanged');readEvidence.push({phase:label,tables:Object.keys(before).length,before:crypto.createHash('sha256').update(JSON.stringify(before)).digest('hex'),after:crypto.createHash('sha256').update(JSON.stringify(after)).digest('hex')});}
const preview=()=>api(base+'/preview'),rosterCommand=view=>({batchKey:view.batchKey,sourceFingerprint:view.sourceFingerprint,reviewToken:view.reviewToken});
const expectedSummary={teachers:6,excludedLeads:1,historicalExcluded:2},levels=['讲师','高级讲师','特级讲师'];
function checkPreview(view,accountReceipt,teacherReceipt=null,{initial=true}={}){
 same(Object.keys(view).sort(),['batchKey','imported','reviewToken','rows','sourceFingerprint','summary'],'Preview has only the documented source preparation contract');
 check(view.batchKey==='synthetic-import'&&typeof view.sourceFingerprint==='string'&&view.sourceFingerprint.length===64,'Teacher preview uses the fixed verified batch/source');check(view.imported===Boolean(teacherReceipt),'Imported state reflects only durable teacher intake');same(view.summary,expectedSummary,'Only six active teacher rows are included; lead-only and history rows excluded');same(view.rows.map(r=>r.reference),[3,4,5,6,7,8].map(n=>'teacher-row-'+n),'Teacher candidates retain exact source references and order');
 const accounts=new Map(accountReceipt.rows.map(r=>[r.reference,r.accountId])),teachers=new Map((teacherReceipt?.rows||[]).map(r=>[r.reference,r.teacherId]));
 for(const row of view.rows){const n=Number(row.reference.slice(12));same(Object.keys(row).sort(),['accountId','job','name','organization','reference','status','teacherId','teacherLevel'],'Preview includes only teacher preparation fields');check(row.accountId===accounts.get(row.reference)&&row.teacherId===(teachers.get(row.reference)??null),'Exact source reference links account and teacher IDs');
  if(initial){check(row.teacherLevel===levels[(n-3)%3]&&row.job===(n===7?null:'SYNTHETIC JOB '+n),'Grade and optional job are exact verified source facts');check(row.status===(teacherReceipt?'待完善':'待接收'),'New teacher status never claims a complete ready-to-use profile');}
 }
 check(view.rows[0].name===view.rows[1].name&&view.rows[0].organization!==view.rows[1].organization&&view.rows[0].accountId!==view.rows[1].accountId,'Same-name people in distinct organizations stay separate exact-reference identities');
 check(teacherReceipt?view.reviewToken===null:typeof view.reviewToken==='string'&&view.reviewToken.length>20,'Only a new intake preview issues an explicit review token');
}
function checkReceipt(receipt,accountReceipt){same(Object.keys(receipt).sort(),['batchKey','imported','replayed','rows','sourceFingerprint','summary'],'Receipt exposes no unrelated account or authorization fields');check(receipt.imported===true&&receipt.batchKey==='synthetic-import'&&typeof receipt.replayed==='boolean','Receipt is durable and explicitly distinguishes replay');same(receipt.summary,expectedSummary,'Receipt retains source inclusion/exclusion counts');same(receipt.rows.map(r=>r.reference),[3,4,5,6,7,8].map(n=>'teacher-row-'+n),'Receipt includes only exact eligible teacher references');check(new Set(receipt.rows.map(r=>r.teacherId)).size===6,'Every distinct teacher reference creates a distinct teacher record');for(const row of receipt.rows){same(Object.keys(row).sort(),['accountId','reference','teacherId'],'Receipt exposes only stable source/account/teacher associations');check(Number.isSafeInteger(row.teacherId)&&row.teacherId>0&&row.accountId===accountReceipt.rows.find(a=>a.reference===row.reference)?.accountId,'Teacher receipt preserves the already-received account ID');}}
async function runChecks(){
 pins=await fixture('prepare');await boot();
 viewer=await api('/users',{username:'synthetic-roster-viewer',name:'SYNTHETIC EXISTING VIEWER',role:'viewer',status:1,password});admin2=await api('/users',{username:'synthetic-roster-admin2',name:'SYNTHETIC SECOND ADMIN',role:'admin',status:1,password});await api('/users',{username:'synthetic-roster-manager',name:'SYNTHETIC MANAGER',role:'manager',status:1,password});for(const actor of ['viewer','admin2','manager'])await login(actor);
 await readOnly('actual login and prerequisite account receipt',async()=>{
  await denied(base+'/preview',undefined,'admin',409,'Teacher intake requires complete prior account receipt');
  for(const actor of ['anonymous','viewer','manager']){const status=actor==='anonymous'?401:403;await denied(base+'/preview',undefined,actor,status,'Only real administrator can preview teacher intake');await denied(base+'/import?unknown=1',{},actor,status,'Authentication precedes query/body validation');}
 });
 phase='original M01 account intake';const accountPreview=await api(accountBase+'/preview'),account=await api(accountBase+'/accounts/'+viewer);
 const accountReceipt=await api(accountBase+'/commit',{expectedRevision:accountPreview.revision,sourceFingerprint:accountPreview.sourceFingerprint,reviewToken:accountPreview.reviewToken,decisions:accountPreview.rows.map(r=>({reference:r.reference,action:r.reference==='teacher-row-4'?'LINK_EXISTING':'CREATE_PENDING',accountId:r.reference==='teacher-row-4'?viewer:null,accountProof:r.reference==='teacher-row-4'?account.proof:null,reviewed:true}))});
 check(accountReceipt.rows.length===7,'Original account intake also preserves the excluded lead-only account');const protectedBaseline=await control('snapshot');let expectedEpochs=await control('device-epochs');let initial,body;
 async function verifyAccountEpoch(label){const next=new Map(expectedEpochs.map(row=>[row.user_id,row.epoch]));next.set(viewer,(next.get(viewer)||0)+1);expectedEpochs=[...next].sort((a,b)=>a[0]-b[0]).map(([user_id,epoch])=>({user_id,epoch}));same(await control('device-epochs'),expectedEpochs,label+' increments only the changed account epoch exactly once');}
 await readOnly('complete teacher preview has no writes',async()=>{initial=await preview();checkPreview(initial,accountReceipt);body=rosterCommand(initial);check((await api('/teachers')).length===0,'Preview does not materialize any teacher record');checkPreview(await preview(),accountReceipt);});
 await readOnly('minimal import protocol and token ownership',async()=>{
  for(const field of ['rows','teacherId','name','teacherLevel','status','email','password','sourcePath','fee_rate'])await denied(base+'/import',{...body,[field]:'SYNTHETIC CLIENT VALUE'},'admin',400,'Client cannot inject '+field);
  await denied(base+'/preview?batchKey=client',undefined,'admin',400,'Preview cannot override fixed server batch');await denied(base+'/import?sourceFingerprint=client',body,'admin',400,'Import accepts no query source claims');await denied(base+'/preview',{},'admin',405,'Preview is GET only');await denied(base+'/import',undefined,'admin',405,'Import is POST only');
  await denied(base+'/import',body,'admin2',409,'Another administrator cannot reuse a live review token');
  tokens.oldAdmin=tokens.admin;await login('admin');await denied(base+'/import',body,'admin',409,'New session of same administrator cannot use old live token');tokens.admin=tokens.oldAdmin;delete tokens.oldAdmin;
  await denied(base+'/import',{...body,reviewToken:null},'admin',409,'First import cannot skip review');
 });
 await control('expire-reviews');await readOnly('actual review expiry',async()=>{await denied(base+'/import',body,'admin',409,'Expired review cannot perform a new import');initial=await preview();body=rosterCommand(initial);});
 phase='account snapshot changed before import';await api('/users',{id:viewer,username:'synthetic-roster-viewer',name:'SYNTHETIC CHANGED VIEWER',role:'viewer',status:1});await verifyAccountEpoch('Changing the viewer name');await readOnly('all users state is part of first-write review',async()=>{await denied(base+'/import',body,'admin',409,'Account change since preview invalidates teacher review even without mapping changes');});await api('/users',{id:viewer,username:'synthetic-roster-viewer',name:'SYNTHETIC EXISTING VIEWER',role:'viewer',status:1});await verifyAccountEpoch('Restoring the viewer name');const verifiedEpochTable=(await control('snapshot')).S01_TRUSTED_DEVICE_EPOCHS;initial=await preview();body=rosterCommand(initial);
 phase='teacher snapshot changed before import';const ordinary=await api('/teachers',{name:'SYNTHETIC EXISTING TEACHER',status:'待完善',teacher_level:'讲师'});
 await readOnly('nonempty legacy roster is never joined by name',async()=>{await denied(base+'/preview',undefined,'admin',409,'Existing teachers without this receipt block first intake');await denied(base+'/import',body,'admin',409,'Changed teacher snapshot invalidates reviewed command');});await api('/teachers/delete',{id:ordinary});
 await control('capture-account');await control('fault-account-receipt');await readOnly('inconsistent M01 account receipt fails closed',async()=>{await denied(base+'/preview',undefined,'admin',409,'Teacher references require intact prior account evidence');await denied(base+'/import',body,'admin',409,'Import rechecks account receipt association');});await control('restore-account');
 const candidates=path.join(own,'sources','candidates.json'),originalSource=fs.readFileSync(candidates);fs.appendFileSync(candidates,'\n');
 await readOnly('fixed source changed after preparation',async()=>{await denied(base+'/preview',undefined,'admin',409,'Changed source pin prevents roster preview');await denied(base+'/import',body,'admin',409,'Changed source pin prevents roster import');});fs.writeFileSync(candidates,originalSource);
 await readOnly('restored source requires explicit current review',async()=>{initial=await preview();checkPreview(initial,accountReceipt);body=rosterCommand(initial);});
 await control('rollback-on');await readOnly('mid-batch SQL failure rolls back entire new roster',async()=>{await denied(base+'/import',body,'admin',409,'Synthetic failure after earlier teacher inserts is contained');check((await api('/teachers')).length===0,'Failed transaction leaves no partial teachers');});await control('rollback-off');
 const beforeImport=await control('snapshot');phase='transactional roster intake';initial=await preview();body=rosterCommand(initial);const pair=await Promise.all([request(base+'/import',body),request(base+'/import',body)]);same(pair.map(r=>r.status),[200,200],'Concurrent identical explicit retry completes without duplicates');const receipt=pair[0].envelope.data;checkReceipt(receipt,accountReceipt);same(pair[1].envelope.data.rows,receipt.rows,'Concurrent retry returns the same stable teacher IDs');same(pair.map(r=>r.envelope.data.replayed).sort(),[false,true],'One first commit and one replay are distinguished');
 const teacherRows=await api('/teachers');check(teacherRows.length===6,'Exactly six active-source teacher records exist');
 for(const mapping of receipt.rows){const stored=teacherRows.find(t=>t.id===mapping.teacherId),source=initial.rows.find(r=>r.reference===mapping.reference);check(stored.name===source.name&&stored.org===source.organization&&stored.title===source.job&&stored.teacher_level===source.teacherLevel&&stored.status==='待完善','Original teachers table holds exact source name/org/job/grade and pending profile status');for(const field of ['gender','field','phone','email','fee_rate','intro','in_date','out_date','base_province','base_city'])same(stored[field],null,'Unprovided '+field+' stays unknown, never invented');}
 check(teacherRows.filter(t=>t.name==='SYNTHETIC PRIVATE 4').length===2,'Same-name source people create separate teachers without automatic merge');
 await readOnly('received preview retries and original deletion guard',async()=>{
  checkPreview(await preview(),accountReceipt,receipt);const replay=await api(base+'/import',body);checkReceipt(replay,accountReceipt);check(replay.replayed===true,'Exact retry is marked replay');same(replay.rows,receipt.rows,'Retry keeps original IDs');
  const fromImportedPreview=await preview();const nullReplay=await api(base+'/import',rosterCommand(fromImportedPreview));check(nullReplay.replayed===true,'Imported preview null token permits only verified no-write replay');same(nullReplay.rows,receipt.rows,'Null-token replay retains receipt');
  for(const mapping of receipt.rows)await denied('/teachers/delete',{id:mapping.teacherId},'admin',409,'Original delete retains teacher roster intake references');
  check((await api('/organization/config')).configuration===null,'Teacher intake does not publish M01 authorization');
 });
 await control('fault-account-receipt');await readOnly('durable teacher replay still rechecks M01 intake evidence',async()=>{await denied(base+'/preview',undefined,'admin',409,'Existing teacher receipt cannot conceal broken account linkage');await denied(base+'/import',body,'admin',409,'Already-imported shortcut revalidates M01 receipt');});await control('restore-account');
 await control('capture-roster');await control('fault-roster-receipt');await readOnly('teacher receipt mapping corruption fails closed',async()=>{await denied(base+'/preview',undefined,'admin',409,'Teacher ID mapping in durable receipt must remain verifiable');await denied(base+'/import',{...body,reviewToken:null},'admin',409,'Null-token replay cannot repair or skip corrupt teacher mapping');});await control('restore-roster');
 phase='later legitimate original teacher editing';const selected=teacherRows.find(t=>t.id===receipt.rows[0].teacherId);await api('/teachers',{id:selected.id,name:'SYNTHETIC EDITED TEACHER',org:'SYNTHETIC EDITED ORG',title:'SYNTHETIC EDITED JOB',teacher_level:'特级讲师',base_province:'浙江',base_city:'杭州',email:'edited@example.test',fee_rate:123.45});const edited=(await api('/teachers')).find(t=>t.id===selected.id);
 check(edited.name==='SYNTHETIC EDITED TEACHER'&&edited.teacher_level==='特级讲师'&&edited.base_city==='杭州'&&edited.fee_rate===123.45,'Original teacher maintenance remains possible after intake');
 await readOnly('receipt remains immutable without overwriting later teacher facts',async()=>{checkPreview(await preview(),accountReceipt,receipt,{initial:false});same((await api(base+'/import',body)).rows,receipt.rows,'Edited teacher does not break identity receipt');same((await api('/teachers')).find(t=>t.id===selected.id),edited,'Replay never overwrites legitimate current teacher data');await denied('/teachers/delete',{id:selected.id},'admin',409,'Deletion guard survives legitimate teacher edits');});
 await control('revoke-admin');await readOnly('revoked administrator session',async()=>{await denied(base+'/preview',undefined,'admin',401,'Preview rechecks live session');await denied(base+'/import',body,'admin',401,'No-write replay also rechecks session');});await login('admin');
 same(await control('device-epochs'),expectedEpochs,'Teacher roster operations preserve the precisely verified account epochs');
 const beforeRestart=await control('snapshot');const allowed=new Set(['TEACHERS','TEACHER_ROSTER_IMPORT_BATCHES','TEACHER_ROSTER_IMPORT_PEOPLE']);let unchanged=0;
 for(const name of Object.keys(protectedBaseline))if(!allowed.has(name)){same(beforeRestart[name],name==='S01_TRUSTED_DEVICE_EPOCHS'?verifiedEpochTable:protectedBaseline[name],'Teacher intake preserves protected '+name+' at its verified baseline');unchanged++;}
 check(beforeRestart.TEACHER_ROSTER_IMPORT_BATCHES?.count===1&&beforeRestart.TEACHER_ROSTER_IMPORT_PEOPLE?.count===6,'Only one complete durable teacher receipt and six reference mappings exist');
 await stop();same(await fixture('inspect'),beforeRestart,'Offline inspector matches complete database');await boot(true);await login('admin2');
 await readOnly('cold restart permits checked no-write replay',async()=>{checkPreview(await preview(),accountReceipt,receipt,{initial:false});const oldToken=await api(base+'/import',body);check(oldToken.replayed===true,'Cold restart replays intact receipt despite old process review token');same(oldToken.rows,receipt.rows,'Cold restart retains teacher/account/reference mapping');const withoutToken=await api(base+'/import',{...body,reviewToken:null},'admin2');check(withoutToken.replayed===true,'Another current admin can verify durable null-token replay');same(withoutToken.rows,receipt.rows,'No-write replay never duplicates teachers');same((await api('/teachers')).find(t=>t.id===selected.id),edited,'Cold replay preserves later editable teacher fields');});const final=await control('snapshot');same(final,beforeRestart,'Restart, previews and durable retries change no row');
 fs.writeFileSync(path.join(own,'database-invariants.json'),JSON.stringify({before_import:beforeImport,before_restart:beforeRestart,final,read_phases:readEvidence},null,2),{mode:0o600});fs.writeFileSync(path.join(own,'synthetic-teacher-receipt.json'),JSON.stringify({summary:receipt.summary,rows:receipt.rows},null,2),{mode:0o600});return {read_only_phases:readEvidence.length,tables_per_read_phase:Object.keys(final).length,protected_tables_unchanged:unchanged,received_teachers:6,excluded_leads:1,historical_excluded:2};
}
let evidence;runChecks().then(value=>{evidence=value;}).catch(error=>{fatal=String(error.message||error).replaceAll(password,'[redacted]');process.exitCode=1;}).finally(async()=>{await stop();const stopped=servicePids.every(pid=>{try{process.kill(pid,0);return false;}catch(e){return e.code==='ESRCH';}});check(stopped,'All isolated teacher-roster Main processes stopped');const summary={suite:'teacher-roster-http',checks,failures,...(fatal?{error:fatal}:{}),...(evidence||{}),server_processes_stopped:stopped,production_touched:false,notifications_sent:false,artifacts:own};fs.writeFileSync(path.join(own,'result.json'),JSON.stringify(summary,null,2),{mode:0o600});console.log(JSON.stringify(summary));if(failures.length||fatal)process.exitCode=1;});
