'use strict';
// Private mount-only candidate. Existing DOM/API harness; no shared file mutation, browser or DB.
const fs = require('node:fs'), path = require('node:path'), vm = require('node:vm'), assert = require('node:assert/strict');
const appRoot = path.resolve(__dirname, '..');
const originalRead = fs.readFileSync.bind(fs), source = originalRead(path.join(appRoot, 'web/app.js'), 'utf8');
if(process.argv[2] === '--legacy') { require(path.join(appRoot,'scripts',process.argv[3] || 'IntegrationSummariesUI.test.cjs')); }
else {
const legacy = originalRead(path.join(appRoot,'scripts/IntegrationSummariesUI.test.cjs'),'utf8');
const lib = vm.runInNewContext(legacy.slice(0, legacy.indexOf('\n(async () => {'))+'\n({harness,view,content,sources,revision,tick,deferred,deliverySources});', { require, __dirname:path.join(appRoot,'scripts'), console, structuredClone, AbortController, DOMException, URL, URLSearchParams, Buffer, setImmediate });
let checks=0;const check=(v,m)=>{assert.ok(v,m);checks++}, equal=(a,b,m)=>{assert.deepEqual(JSON.parse(JSON.stringify(a)),b,m);checks++};
const formal=(status='DRAFT', role=null, edit=true)=>{
 const dto=lib.view(1,lib.content(),edit);dto.draft_only=false;dto.photo_policy='TEXT_PLACEHOLDERS_ONLY';
 const cap={edit,refresh_sources:edit,submit:status==='DRAFT'&&edit,review:role!==null,review_role:role,export:status==='APPROVED'};
 dto.capabilities={read:true,...cap};dto.workflow={project_id:5,revision:1,workflow_version:status==='DRAFT'?0:2,status,submitted_revision:status==='DRAFT'?null:1,submitter_code:status==='DRAFT'?null:'AUTHOR',branch_reviewer_code:'BRANCH-ACTOR',bp_reviewer_code:'BP-ACTOR',review_order:'BRANCH_THEN_BP',policy_version:'SYNTH-V1',policy_configured:true,decisions:[],capabilities:cap,photo_policy:'TEXT_PLACEHOLDERS_ONLY',synthetic:false};return dto;
};
const setup=options=>{const h=lib.harness(options); h.downloads=[];h.revoked=[];h.sandbox.Blob=Blob;h.sandbox.Uint8Array=Uint8Array;h.sandbox.URL={createObjectURL:()=> 'blob:synthetic',revokeObjectURL:u=>h.revoked.push(u)};const create=h.document.createElement;h.document.createElement=tag=>{const el=create(tag);if(tag==='a')el.click=()=>h.downloads.push({filename:el.download,href:el.href});return el};return h;};
const flowResponse=(dto,respond)=>respond({...dto.workflow,replayed:false,result_workflow_version:dto.workflow.workflow_version});
const word=(overrides={})=>{const bytes=Buffer.from([80,75,3,4,0,1,2,3]);return new Response(bytes,{status:200,headers:{'Content-Type':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','Content-Disposition':'attachment; filename="training-summary-5-v1.docx"','Cache-Control':'no-store',...overrides}})};
(async()=>{
 const h=setup({initial:formal(),fetchOverride:(url,opts,normal,respond,remote)=>{if(url.endsWith('/submit')){const next=formal('SUBMITTED',null,false);next.workflow.workflow_version=1;remote.set(next);return flowResponse(next,respond)}return normal()}});await h.mount();await h.open();
 check(h.button('submit')&&!h.button('submit').disabled,'formal DTO accepted on original summary editor');check(!h.modal().textContent.includes('尚不能提交')&&!h.modal().textContent.includes('待接入'),'obsolete formal wording removed');
 await h.edit('issues','未保存正文');check(h.button('submit').disabled,'dirty body disables submit');await h.emit(h.button('submit'),'click');equal(h.requests('submit').length,0,'programmatic dirty click cannot submit');await h.edit('issues',lib.content().issues);await h.click('submit');
 const sent=JSON.parse(h.requests('submit')[0].opts.body);equal(Object.keys(sent).sort(),['expected_version','expected_workflow_version','project_id','request_id'],'formal submit only exact version/request fields');equal([sent.expected_version,sent.expected_workflow_version],[1,0],'separate body and workflow versions');check(h.modal().textContent.includes('复核中')&&!h.button('save')&&!h.button('submit'),'submitted server capability freezes editor');check(h.reads().length>=3,'successful operation re-reads full current detail');
 const legacyHost=setup();await legacyHost.mount();await legacyHost.open();check(!legacyHost.button('submit')&&!legacyHost.button('export'),'legacy draft response stays draft-only');
 for(const mutate of [d=>delete d.workflow,d=>d.workflow.project_id=9,d=>d.workflow.revision=2,d=>d.workflow.synthetic=true,d=>d.capabilities.review=true,d=>d.workflow.capabilities.extra=true,d=>d.photo_policy='FAKE_PHOTO',d=>d.current.status='APPROVED']){const d=formal();mutate(d);const bad=setup({initial:d});await bad.mount();check(!bad.panel().querySelector('[data-summary-open]'),'malformed or mismatched formal DTO fails closed');}
 for(const role of ['BRANCH','BP']) {
  const review=setup({initial:formal('SUBMITTED',role,false),fetchOverride:(url,opts,normal,respond,remote)=>{if(url.endsWith('/review')){const next=formal('RETURNED',null,true);next.workflow.workflow_version=3;remote.set(next);return flowResponse(next,respond)}return normal()}});await review.mount();await review.open();
  check(review.button('approve')&&review.button('review-return')&&!review.button('save'),'review-only server role gets review controls');await review.click('review-return');equal(review.requests('review').length,0,'return requires note');const note=review.modal().querySelector('[data-summary-review-note]');note.value='<script>需要补充</script>';await review.emit(note,'input');await review.click('review-return');const body=JSON.parse(review.requests('review')[0].opts.body);equal([body.review_role,body.decision,body.note],[role,'RETURN','<script>需要补充</script>'],'uses server review role and explicit return note');check(review.button('save')&&!review.button('submit'),'returned body must save new revision before submit');
 }
 let once=true;const unknown=setup({initial:formal(),fetchOverride:(url,opts,normal,respond,remote)=>{if(url.endsWith('/submit')){if(once){once=false;throw Error('connection lost')}const next=formal('SUBMITTED',null,false);remote.set(next);return flowResponse(next,respond)}return normal()}});await unknown.mount();await unknown.open();await unknown.click('submit');check(unknown.button('submit').disabled&&!unknown.button('retry').disabled,'unknown result blocks new operation');await unknown.click('retry');equal(unknown.requests('submit')[0].opts.body,unknown.requests('submit')[1].opts.body,'retry preserves complete body and same request identity');
 const conflict=setup({initial:formal('SUBMITTED','BP',false),fetchOverride:(url,opts,normal,respond,remote)=>{if(url.endsWith('/review')){remote.set(formal('RETURNED',null,true));return respond(null,409)}return normal()}});await conflict.mount();await conflict.open();const note=conflict.modal().querySelector('[data-summary-review-note]');note.value='版本冲突时保留意见';await conflict.emit(note,'input');await conflict.click('approve');check(conflict.modal().querySelector('#summary-conflict').textContent.includes('服务器'),'409 reloads versions into explicit reconciliation');check(conflict.modal().querySelector('[data-summary-review-note]').value==='版本冲突时保留意见','409 preserves review note');check(conflict.requests('review').length===1,'409 never automatically reposts');
 for(const status of [401,403]){const denied=setup({initial:formal(),fetchOverride:(url,opts,normal,respond)=>url.endsWith('/submit')?respond(null,status):normal()});await denied.mount();await denied.open();await denied.click('submit');check(!denied.modal(),status+' clears summary modal and local text');}
 const feedback=lib.deliverySources();feedback.feedback={format:'M07-REVIEWED-SOURCE-1',status:'AVAILABLE',reason:'',source_version:'SECRET_HASH',value:{results:[{summary:{responseRowCount:3,questions:[{label:'评分<一>',averageText:'8.50',validCount:2,blankCount:1,invalidCount:0}]},review:{reviewed_at:'2026-09-23T01:00:00Z'}},{summary:{responseRowCount:4,questions:[{label:'评分二',averageText:null,validCount:0,blankCount:3,invalidCount:1}]},review:{reviewed_at:'2026-09-23T01:01:00Z'}}]}};
 for(const visibility of [undefined,'DELIVERY_HIDDEN','FEEDBACK_HIDDEN','DELIVERY_AND_FEEDBACK_HIDDEN']){const dto=formal();dto.sources={...feedback,visibility};dto.current.sources=dto.sources;const f=setup({initial:dto});await f.mount();await f.open();const text=f.modal().querySelector('#summary-sources').textContent;check(f.modal().querySelector('[data-summary-feedback]').textContent.includes('8.50')===![ 'FEEDBACK_HIDDEN','DELIVERY_AND_FEEDBACK_HIDDEN'].includes(visibility),'feedback visibility is independent');check(text.includes('1.33')===!['DELIVERY_HIDDEN','DELIVERY_AND_FEEDBACK_HIDDEN'].includes(visibility),'delivery visibility is independent');check(!text.includes('SECRET_HASH'),'source fingerprints never displayed');if(!visibility){check(text.includes('评价汇总 1')&&text.includes('评价汇总 2')&&text.includes('待补齐'),'separate reviewed summaries and unknown mean shown');check(!f.modal().querySelector('script'),'feedback labels escaped');}}
 const history=setup({initial:formal(),fetchOverride:(url,opts,normal,respond)=>{if(url.includes('/workflow-history?')){const offset=Number(new URL(url,'http://local').searchParams.get('offset'));return respond({project_id:5,workflow_version:21,offset,limit:20,total:21,read_only:true,items:[{workflow_version:21-offset,revision:1,action:'RETURN',actor_code:'SYNTH',created_at:'2026-09-23T01:00:00Z',review_role:'BP',note:'<img src=x>明确退回原因'}]})}return normal()}});await history.mount();await history.open();await history.click('flow-history');check(history.modal().querySelector('#summary-flow-history').textContent.includes('明确退回原因')&&!history.modal().querySelector('#summary-flow-history').querySelector('img'),'workflow history shows escaped return notes');await history.click('flow-next');check(history.calls.some(c=>c.url.includes('workflow-history?')&&c.url.includes('offset=20')),'workflow history bounded server pagination');
 for(const writer of [false,true]){const exp=setup({initial:formal('APPROVED',null,false),writer,fetchOverride:(url,opts,normal)=>url.endsWith('/export')?word():normal()});await exp.mount();await exp.open();if(!writer){check(!exp.button('export'),'non-admin does not see Word even inconsistent capability');continue}await exp.click('export');equal(exp.downloads,[{filename:'training-summary-5-v1.docx',href:'blob:synthetic'}],'admin downloads strictly named DOCX');equal(Object.keys(JSON.parse(exp.requests('export')[0].opts.body)).sort(),['expected_version','expected_workflow_version','project_id','request_id'],'Word uses both versions and request identity');exp.leave();check(exp.revoked.includes('blob:synthetic'),'route cleanup revokes document URL');}
 for(const headers of [{'Content-Type':'application/json'},{'Content-Disposition':'attachment; filename="wrong.docx"'},{'Cache-Control':'public'},{'Content-Length':'20000000'}]){const exp=setup({initial:formal('APPROVED',null,false),writer:true,fetchOverride:(url,opts,normal)=>url.endsWith('/export')?word(headers):normal()});await exp.mount();await exp.open();await exp.click('export');check(exp.downloads.length===0&&exp.button('retry')&&!exp.button('retry').disabled,'invalid Word headers never download; exact-request recovery retained');}
 for(const status of [401,403,409]){const exp=setup({initial:formal('APPROVED',null,false),writer:true,fetchOverride:(url,opts,normal)=>url.endsWith('/export')?new Response('{}',{status,headers:{'Content-Type':'application/json'}}):normal()});await exp.mount();await exp.open();await exp.click('export');check(exp.downloads.length===0,'error JSON is never downloaded');if(status!==409)check(!exp.modal(),'download auth rejection clears sensitive editor');else check(exp.button('keep-local'),'download conflict requires fresh reconciliation');}
 const late=lib.deferred();const isolated=setup({initial:formal('APPROVED',null,false),writer:true,fetchOverride:(url,opts,normal)=>url.endsWith('/export')?late.promise:normal()});await isolated.mount();await isolated.open();const action=isolated.click('export');await lib.tick();isolated.leave();late.resolve(word());await action;check(isolated.downloads.length===0&&!isolated.modal(),'route change suppresses late file response');
 const identityWait=lib.deferred();const isolatedIdentity=setup({initial:formal('APPROVED',null,false),writer:true,fetchOverride:(url,opts,normal)=>url.endsWith('/export')?identityWait.promise:normal()});await isolatedIdentity.mount();await isolatedIdentity.open();const identityAction=isolatedIdentity.click('export');await lib.tick();isolatedIdentity.sandbox.state.user={uid:99,role:'admin'};identityWait.resolve(word());await identityAction;check(isolatedIdentity.downloads.length===0&&!isolatedIdentity.modal(),'identity change suppresses late file response');
 const dirtyExport=setup({initial:formal('APPROVED',null,true),writer:true});await dirtyExport.mount();await dirtyExport.open();await dirtyExport.edit('issues','更新但未保存');check(dirtyExport.button('export').disabled,'dirty approved body cannot export prior approved version as current');

 const noPolicy=formal();noPolicy.workflow.policy_configured=false;noPolicy.workflow.capabilities.submit=false;noPolicy.capabilities.submit=false;const policy=setup({initial:noPolicy});await policy.mount();await policy.open();check(!policy.button('submit')&&policy.modal().textContent.includes('尚未配置'),'unconfigured policy keeps draft only');
 const blank=formal();blank.version=blank.revision=blank.latest_version=0;blank.current=null;blank.workflow.revision=0;blank.workflow.capabilities.submit=blank.capabilities.submit=false;blank.workflow.capabilities.refresh_sources=blank.capabilities.refresh_sources=false;const zero=setup({initial:blank});await zero.mount();await zero.open();check(zero.button('save')&&!zero.button('submit'),'new formal zero revision editable but not submittable');
 const save=setup({initial:formal('RETURNED',null,true),fetchOverride:(url,opts,normal,respond,remote)=>{if(url.endsWith('/save')){const next=formal();next.version=next.revision=next.latest_version=next.workflow.revision=2;next.current=lib.revision(2,JSON.parse(opts.body).content);next.workflow.workflow_version=3;remote.set(next);return respond(next)}return normal()}});await save.mount();await save.open();await save.edit('achievements','修改退回正文');await save.click('save');check(save.button('submit')&&!save.button('submit').disabled&&save.field('achievements').value==='修改退回正文','returned save creates new draft and enables server-authorized resubmit');equal(Object.keys(JSON.parse(save.requests('save')[0].opts.body)).sort(),['content','expected_version','project_id','request_id'],'original body saving protocol unchanged');
 const approved=setup({initial:formal('SUBMITTED','BP',false),fetchOverride:(url,opts,normal,respond,remote)=>{if(url.endsWith('/review')){const next=formal('APPROVED',null,true);next.workflow.workflow_version=3;next.workflow.decisions=[{review_role:'BRANCH',actor_code:'B',reviewed_at:'2026-09-23T01:00:00Z',workflow_version:2},{review_role:'BP',actor_code:'P',reviewed_at:'2026-09-23T02:00:00Z',workflow_version:3}];remote.set(next);return flowResponse(next,respond)}return normal()}});await approved.mount();await approved.open();await approved.click('approve');check(approved.modal().textContent.includes('已通过两方复核')&&approved.modal().textContent.includes('BP已通过'),'successful two-party approval displays server decisions');equal(JSON.parse(approved.requests('review')[0].opts.body).decision,'APPROVE','approval is explicit server decision');
 const badMagic=setup({initial:formal('APPROVED',null,false),writer:true,fetchOverride:(url,opts,normal)=>{if(!url.endsWith('/export'))return normal();const r=word();return new Response('this is not a zip',{headers:r.headers})}});await badMagic.mount();await badMagic.open();await badMagic.click('export');check(badMagic.downloads.length===0,'non-ZIP body never becomes DOCX');
 const lateFlow=lib.deferred();const flowIsolation=setup({initial:formal(),fetchOverride:(url,opts,normal,respond)=>url.endsWith('/submit')?lateFlow.promise:normal()});await flowIsolation.mount();await flowIsolation.open();const flowPromise=flowIsolation.click('submit');await lib.tick();flowIsolation.leave();lateFlow.resolve(new Response(JSON.stringify({code:0,data:{...formal('SUBMITTED',null,false).workflow,replayed:false,result_workflow_version:2}})));await flowPromise;check(!flowIsolation.modal()&&flowIsolation.content.textContent==='后续页面','late submit response cannot revive prior route');
 const failedIdentity=lib.deferred();const identityFailure=setup({initial:formal(),fetchOverride:(url,opts,normal)=>url.endsWith('/submit')?failedIdentity.promise:normal()});await identityFailure.mount();await identityFailure.open();const failPromise=identityFailure.click('submit');await lib.tick();identityFailure.sandbox.state.user={uid:91,role:'viewer'};failedIdentity.resolve(new Response(JSON.stringify({code:403,msg:'拒绝'}),{status:403}));await failPromise;check(!identityFailure.modal(),'identity change during rejected request also clears old content');
 console.log(JSON.stringify({suite:'private-original-summary-formal-ui',checks,status:'passed'}));
})().catch(e=>{console.error(e);process.exitCode=1});
}
