'use strict';
// Actual pageUsers/modal/table/API and inspection component. Only DOM and HTTP are synthetic.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync(path.join(__dirname,'IntegrationAccountBindingsUI.test.cjs'),'utf8');
const supportText=source.slice(0,source.indexOf('(async () => {')).replace('pages.replace(', 'pages.replaceAll(');
const support=vm.runInNewContext(supportText+'\n({harness,NodeStub});',{require,__dirname,console,structuredClone,AbortController,setImmediate});
const component=fs.readFileSync(path.join(__dirname,'../web/modules/identity/account-permissions.js'),'utf8');
const tick=()=>new Promise(yes=>setImmediate(yes)),deferred=()=>{let resolve;const promise=new Promise(yes=>resolve=yes);return{promise,resolve};};
let checks=0;const check=(value,label)=>{assert.ok(value,label);checks++;},equal=(actual,expected,label)=>{assert.deepEqual(JSON.parse(JSON.stringify(actual)),expected,label);checks++;};
const whitelist=[['demand.read','VIEW'],['demand.write','HANDLE'],['approval.review','HANDLE'],['demand.accept','HANDLE'],['bid.result','HANDLE'],['catalog.read','VIEW'],['catalog.manage','HANDLE'],['delivery.read','VIEW'],['delivery.write','HANDLE'],['delivery.verify','HANDLE'],['reports.read','VIEW'],['reports.export','EXPORT'],['survey.preview','HANDLE'],['summary.read','VIEW'],['summary.edit','HANDLE']];
function view(account_id=12,selected_organization=null){return{read_only:true,organization_gate_only:true,configuration_status:'CONFIGURED',configuration_version:'SYNTHETIC-1',subject:{account_id,username:'synthetic-'+account_id,name:'合成账号 '+account_id,account_enabled:true,binding_status:'BOUND_ENABLED',person_code:'SYN-P'+account_id,organization_code:'ORG-001',person_enabled:true,home_organization_enabled:true,role_codes:['SYN-ROLE']},organizations:[{organization_code:'ORG-001',enabled:true},{organization_code:'ORG-002',enabled:true},{organization_code:'ORG-OFF',enabled:false}],selected_organization,decisions:selected_organization?whitelist.map(([resource,action])=>({resource,action,label:'合成许可说明',allowed:selected_organization==='ORG-001',status:selected_organization==='ORG-001'?'ALLOWED':'DENIED',reason:selected_organization==='ORG-001'?'机构范围已核实':'本机构范围未许可',matched_rule_ids:selected_organization==='ORG-001'?['RULE-SYN']:[]})):[]};}
const notConfigured=id=>({...view(id),configuration_status:'NOT_CONFIGURED',configuration_version:null,subject:{...view(id).subject,binding_status:'CONFIG_NOT_PUBLISHED',person_code:null,organization_code:null,person_enabled:null,home_organization_enabled:null,role_codes:[]},organizations:[],selected_organization:null,decisions:[]});
function harness({role='admin',transform=value=>value,override,moduleGate,moduleFail=false,bindingsFail=false}={}){
 let controller,host;
 const h=support.harness({fetchOverride:(url,opts,normal,respond)=>{const fallback=()=>{if(url.startsWith('/api/organization/account-access?')){const params=new URL('http://synthetic'+url).searchParams;return respond(transform(view(Number(params.get('account_id')),params.get('organization_code'))));}return normal(url,opts);};return override?override(url,opts,fallback,respond):fallback();}});
 h.sandbox.state.user.role=role;
 vm.runInContext('{'+component.replace('export function createAccountPermissions','function createAccountPermissions')+';globalThis.permissionsModule=createAccountPermissions;}',h.sandbox);
 const loader=h.sandbox.loadIdentityModule;h.sandbox.loadIdentityModule=async url=>{if(!url.includes('/account-permissions.js?')){if(bindingsFail)throw Error('SYNTHETIC optional binding failure');return loader(url);}h.imports.push(url);if(moduleGate)await moduleGate.promise;if(moduleFail)throw Error('SYNTHETIC inspection unavailable');return{createAccountPermissions(context){host=context;controller=h.sandbox.permissionsModule(context);return controller;}};};
 h.open=async(id=12)=>{if(h.modules[0])return h.modules[0].host.actions.find(a=>a.l==='查看业务权限').onClick(h.users.find(u=>u.id===id));h.clickAction(id,'查看业务权限');await tick();};h.node=key=>h.modal()?.querySelector('[data-permissions-'+key+']');h.choose=async value=>{h.node('organization').value=value;await h.node('organization').onchange();await tick();};h.refresh=()=>h.node('read').onclick();h.close=()=>h.node('close').onclick();h.reads=()=>h.calls.filter(call=>call.url.startsWith('/api/organization/account-access?'));h.controller=()=>controller;h.host=()=>host;return h;
}
(async()=>{
 const h=harness();await h.mount();equal(h.reads().length,0,'User table does not query every account');check(h.actions(12).some(a=>a.textContent==='查看业务权限')&&h.actions(13).some(a=>a.textContent==='查看业务权限'),'All admin user rows including disabled accounts expose inspection');await h.open();const mask=h.modal();equal(h.reads()[0].url,'/api/organization/account-access?account_id=12','Initial request has only target account ID');equal(h.node('organization').value,'','No automatic default organization');equal(h.node('results').textContent,'','No invented decisions before explicit selection');check(h.node('subject').textContent.includes('合成账号 12')&&h.node('subject').textContent.includes('synthetic-12')&&h.node('subject').textContent.includes('账号 ID 12'),'Server subject identity is explicit');check(h.modal().textContent.includes('具体事项还须符合流程条件'),'Organization gate limitation is concise');check(!h.modal().querySelector('#modal-ok'),'Read-only modal has no save control');await h.choose('ORG-001');equal(h.reads().at(-1).url,'/api/organization/account-access?account_id=12&organization_code=ORG-001','Exact selected organization sent');check(h.modal()===mask&&h.node('results').textContent.includes('范围允许'),'Selection updates same original modal');equal(h.node('results').querySelectorAll('tr[data-row-id]').length,15,'Exactly all 15 allowed operations rendered');check(!h.node('results').textContent.includes('RULE-SYN'),'Internal matched rules are not disclosed in UI');check(h.node('results').querySelector('[data-label="原因"]'),'Original renderTable provides mobile card labels');await h.choose('ORG-002');check(h.node('results').textContent.includes('范围不允许')&&!h.node('results').textContent.includes('范围允许'),'Changing organization removes former permissions');equal(h.posts().length,0,'Inspection only performs GET');h.close();check(!h.modal(),'Explicit close returns to unchanged user table');check(h.actions(12).some(a=>a.textContent==='编辑')&&h.actions(12).some(a=>a.textContent==='绑定人员'),'Original editor and binding actions retained');
 const nc=harness({transform:value=>notConfigured(value.subject.account_id)});await nc.mount();await nc.open();check(nc.node('notice').textContent.includes('组织权限尚未发布')&&nc.node('organization').disabled&&!nc.node('results').textContent,'Account inspection works before configuration is published');equal(nc.reads().length,1,'No guessed organization or permission request');nc.close();
 for(const role of ['viewer','manager']){const denied=harness({role});await denied.mount();check(!denied.actions(12).some(a=>a.textContent==='查看业务权限'),role+' has no inspection action');equal(denied.reads().length,0,role+' makes no inspection read');denied.sandbox.beginRouteEpoch();}
 const disabled=harness({transform:value=>({...value,subject:{...value.subject,account_enabled:false},decisions:value.decisions.map(row=>({...row,allowed:false,status:'ACCOUNT_DISABLED',reason:'账号已停用'}))})});await disabled.mount();await disabled.open(13);await disabled.choose('ORG-001');check(disabled.node('subject').textContent.includes('账号停用')&&!disabled.node('results').textContent.includes('范围允许'),'Disabled account never looks permitted');disabled.close();
 for(const binding_status of ['UNBOUND','BOUND_DISABLED']){const x=harness({transform:value=>({...value,subject:binding_status==='UNBOUND'?{...value.subject,binding_status,person_code:null,organization_code:null,person_enabled:null,home_organization_enabled:null,role_codes:[]}:{...value.subject,binding_status},decisions:value.decisions.map(r=>({...r,allowed:false,status:'NOT_CONFIGURED',reason:'业务身份未配置'}))})});await x.mount();await x.open();await x.choose('ORG-001');check(!x.node('results').textContent.includes('范围允许'),'Binding '+binding_status+' does not infer account-role permissions');x.close();}
 const evil='<img src=x onerror=alert(1)>',markup=harness({transform:value=>({...value,subject:{...value.subject,name:evil},decisions:value.decisions.map(row=>({...row,label:evil,reason:evil}))})});await markup.mount();await markup.open();await markup.choose('ORG-001');check(!markup.modal().querySelector('img,script')&&markup.node('results').textContent.includes(evil),'Subject, label and reason markup cannot execute');check(markup.node('subject').textContent.includes(evil),'Untrusted name stays literal');markup.close();
 const invalids=[v=>v.read_only=false,v=>v.organization_gate_only=false,v=>v.subject.account_id=99,v=>v.configuration_status='UNKNOWN',v=>v.configuration_version=null,v=>v.subject.account_enabled='true',v=>v.subject.binding_status='ADMIN',v=>v.organizations.push(v.organizations[0]),v=>v.selected_organization='ORG-002',v=>v.decisions.pop(),v=>v.decisions.push(v.decisions[0]),v=>v.decisions[0].resource='money.pay',v=>v.decisions[0].action='EXPORT',v=>v.decisions[0].allowed='true',v=>v.decisions[0].status='DENIED',v=>v.decisions[0].status='UNKNOWN',v=>v.decisions[0].reason=null,v=>v.decisions[0].matched_rule_ids=null,v=>v.subject.person_enabled=false,v=>v.subject.home_organization_enabled=false,v=>v.subject.account_enabled=false,v=>v.organizations[0].enabled=false];
 for(const mutate of invalids){const bad=harness({transform:value=>{if(value.selected_organization)mutate(value);return value;}});await bad.mount();await bad.open();await bad.choose('ORG-001');check(!bad.node('results').textContent&&!bad.node('subject').textContent&&bad.node('organization').disabled,'Malformed/contradictory DTO clears all old permissions');check(bad.node('notice').textContent.includes('无法核实'),'Malformed DTO has safe retry message');equal(bad.posts().length,0,'Bad data never publishes configuration');bad.close();}
 for(const status of [400,401,403,404,503]){let reject=false;const x=harness({override:(url,opts,normal,respond)=>reject&&url.startsWith('/api/organization/account-access?')?respond(null,status):normal()});await x.mount();await x.open();await x.choose('ORG-001');reject=true;await x.refresh();if([401,403].includes(status))check(!x.modal(),status+' clears owned private modal');else check(!x.node('subject').textContent&&!x.node('results').textContent&&x.node('organization').disabled,status+' clears stale account/configuration results');x.sandbox.beginRouteEpoch();}
 let configVersion='SYNTHETIC-1';const changed=harness({transform:value=>({...value,configuration_version:configVersion})});await changed.mount();await changed.open();await changed.choose('ORG-001');configVersion='SYNTHETIC-2';await changed.refresh();check(changed.node('notice').textContent.includes('已更新'),'Configuration version change is shown as current read without mixed rows');changed.close();
 const gate=deferred();let queued=false;const racing=harness({override:(url,opts,normal,respond)=>queued&&url.endsWith('organization_code=ORG-001')?gate.promise.then(()=>respond(view(12,'ORG-001'))):normal()});await racing.mount();await racing.open();queued=true;const slow=racing.choose('ORG-001');await tick();check(!racing.node('results').textContent,'Beginning new organization query immediately clears old conclusions');await racing.choose('ORG-002');gate.resolve();await slow;check(racing.node('organization').value==='ORG-002'&&!racing.node('results').textContent.includes('范围允许'),'Late first organization cannot overwrite later result');check(racing.reads().find(r=>r.url.endsWith('ORG-001')).opts.signal.aborted,'Changing organization aborts previous request');racing.close();
 for(const mode of ['close','route','identity']){const wait=deferred(),x=harness({override:(url,opts,normal,respond)=>url.includes('organization_code=')?wait.promise.then(()=>respond(view(12,'ORG-001'))):normal()});await x.mount();await x.open();const read=x.choose('ORG-001');await tick();const prior=x.modal();if(mode==='close')x.close();if(mode==='route')x.sandbox.beginRouteEpoch();if(mode==='identity')x.sandbox.state.user={uid:98,role:'admin'};wait.resolve();await read;check(!x.modal()&&!prior.querySelector('[data-permissions-results]').textContent,mode+' rejects and clears late response');}
 const ownership=harness();await ownership.mount();await ownership.open();ownership.close();ownership.sandbox.openModal('他人窗口','<p>保留</p>');const other=ownership.modal();ownership.controller().destroy();check(ownership.modal()===other,'Destroy only closes its own actual mask');ownership.sandbox.closeModal();
 const noMask=harness();await noMask.mount();await noMask.open();noMask.close();noMask.host().openModal=()=>null;await noMask.controller().open(12);equal(noMask.reads().length,1,'Modal guard returning null never binds or requests under another owner');
 const blocked=harness({moduleFail:true});await blocked.mount();await blocked.open();check(!blocked.modal()&&blocked.actions(12).some(a=>a.textContent==='编辑')&&blocked.reads().length===0,'Dynamic module failure preserves original account maintenance');
 const importGate=deferred(),lateModule=harness({moduleGate:importGate});await lateModule.mount();const opening=lateModule.open();await tick();lateModule.sandbox.beginRouteEpoch();importGate.resolve();await opening;check(!lateModule.modal()&&!lateModule.reads().length,'Late dynamic import cannot open under a new route');
 const fallback=harness({bindingsFail:true});await fallback.mount();await fallback.open();check(fallback.node('subject').textContent.includes('synthetic-12'),'Inspection still works when optional bindings adapter fails');fallback.close();equal(fallback.posts().length,0,'Fallback inspection remains read only');
 console.log(JSON.stringify({ok:true,suite:'original account organization permissions inspection',checks,network:false,browser:false,database:false}));
})().catch(error=>{console.error(error);process.exitCode=1;});
