'use strict';
// Real teacher page + new roster module + original modal/table/API, synthetic DOM and HTTP only.
const fs = require('node:fs'), path = require('node:path'), vm = require('node:vm'), assert = require('node:assert/strict');
const base = fs.readFileSync(path.join(__dirname, 'IntegrationDeliveryCatalogUI.test.cjs'), 'utf8');
const support = vm.runInNewContext(base.slice(0, base.indexOf('\n(async () => {')) + '\n({ harness });', { require, __dirname, console, structuredClone, AbortController, DOMException, URL, URLSearchParams, Buffer, setImmediate });
const source = fs.readFileSync(path.join(__dirname, '../web/modules/course-catalog/roster-import.js'), 'utf8');
const tick = () => new Promise(yes => setImmediate(yes));
const deferred = () => { let resolve; const promise = new Promise(yes => { resolve = yes; }); return { promise, resolve }; };
let checks = 0;
const check = (value, label) => { assert.ok(value, label); checks++; };
const equal = (value, expected, label) => { assert.deepEqual(JSON.parse(JSON.stringify(value)), expected, label); checks++; };
function fixture(count = 3) { return { batchKey: 'SYNTHETIC-TEACHERS', sourceFingerprint: 'a'.repeat(64), reviewToken: 'b'.repeat(64), imported: false, rows: Array.from({ length: count }, (_, i) => ({ reference: 'teacher-' + i, name: i < 2 ? 'SYNTHETIC 同名' : 'SYNTHETIC ' + i, organization: 'SYNTHETIC 机构 ' + i, job: i ? 'SYNTHETIC 岗位 ' + i : null, teacherLevel: ['讲师', '高级讲师', '特级讲师'][i % 3], accountId: 201 + i, teacherId: null, status: '待接收' })), summary: { teachers: count, excludedLeads: 3, historicalExcluded: 9 } }; }
function receipt(preview) { return { batchKey: preview.batchKey, sourceFingerprint: preview.sourceFingerprint, imported: true, replayed: false, rows: preview.rows.map((row, i) => ({ reference: row.reference, accountId: row.accountId, teacherId: 501 + i })), summary: structuredClone(preview.summary) }; }
function imported(preview) { const r = receipt(preview); return { ...structuredClone(preview), imported: true, reviewToken: null, rows: preview.rows.map((row, index) => ({ ...row, teacherId: r.rows[index].teacherId, status: '待完善' })) }; }
function harness({ role = 'admin', preview = fixture(), override, moduleFailure = false, moduleWait } = {}) {
  let current = structuredClone(preview), teachers = current.imported ? current.rows.map(row => ({ id: row.teacherId, name: row.name, org: row.organization, status: row.status, base_city: null, base_province: null, teacher_level: row.teacherLevel })) : [], cacheInvalidations = 0;
  const h = support.harness({ page: 'teachers', writer: role !== 'viewer', fetchOverride: (url, opts, normal, respond) => {
    const fallback = () => {
      if (url.startsWith('/api/teachers')) return respond(teachers);
      if (url === '/api/teacher-roster/preview') return respond(current);
      if (url === '/api/teacher-roster/import') { const r = receipt(current); current = imported(current); teachers = current.rows.map(row => ({ id: row.teacherId, name: row.name, org: row.organization, title: row.job, teacher_level: row.teacherLevel, status: '待完善', base_city: null, base_province: null })); return respond(r); }
      return normal(url, opts);
    };
    return override ? override(url, opts, fallback, respond) : fallback();
  } });
  h.sandbox.state.user.role = role; h.sandbox.invalidateTeacherRecommendations = () => { cacheInvalidations++; };
  vm.runInContext('{ ' + source.replace('export function openTeacherRosterImport', 'function openTeacherRosterImport') + '; globalThis.actualRoster = openTeacherRosterImport; }', h.sandbox);
  h.sandbox.loadHostModule = async url => { h.imports.push(url); if (moduleWait) await moduleWait.promise; if (moduleFailure) throw Error('SYNTHETIC MODULE FAILED'); return { openTeacherRosterImport: h.sandbox.actualRoster }; };
  h.open = () => h.content.querySelector('#teacher-roster-import').onclick(); h.node = key => h.modal()?.querySelector('[data-roster-' + key + ']'); h.clickRoster = key => h.node(key).onclick();
  h.reads = () => h.calls.filter(call => call.url === '/api/teacher-roster/preview'); h.writes = () => h.calls.filter(call => call.url === '/api/teacher-roster/import'); h.cacheInvalidations = () => cacheInvalidations;
  return h;
}
(async () => {
  const h = harness({ preview: fixture(181) }); await h.mount(); check(h.content.querySelector('#teacher-roster-import') && h.content.querySelector('#teacher-add-manual') && h.content.querySelector('#teacher-course-catalog'), 'Original library adds a localized administrator entry without replacing existing actions'); equal(h.reads().length, 0, 'No private roster read before explicit entry');
  await h.open(); check(h.imports[0].includes('/course-catalog/roster-import.js?v='), 'Roster dynamically loaded and versioned'); equal(h.modal().querySelector('#modal-title').textContent, '接收教师名单', 'Original modal hosts roster preview');
  check(h.node('summary').textContent.includes('181 位教师') && h.node('summary').textContent.includes('3 位额外牵头人') && h.node('summary').textContent.includes('9 位历史人员'), 'Full source counts are explicit and independent of pagination');
  equal(h.node('table').querySelector('tbody').querySelectorAll('tr').length, 20, 'Large verified roster uses local pagination'); check(h.node('notice').textContent.includes('常驻地区和逐课授课资格需另行核对'), 'No inferred residence or certification');
  await h.clickRoster('next'); check(h.node('count').textContent.includes('21–40'), 'Next page preserves full batch'); h.node('search').value = '同名'; h.node('search').oninput({ target: h.node('search') }); equal(h.node('table').querySelector('tbody').querySelectorAll('tr').length, 2, 'Same-name people remain separate by explicit reference/account');
  check(h.node('receive').textContent.includes('181'), 'Filtered subset never changes reception batch count'); const mask = h.modal(); await h.clickRoster('receive'); equal(h.writes().length, 1, 'One explicit reception POST'); equal(Object.keys(JSON.parse(h.writes()[0].opts.body)).sort(), ['batchKey', 'reviewToken', 'sourceFingerprint'], 'Only server-issued preview proof sent'); equal(h.reads().length, 2, 'Success explicitly rereads current persisted preview');
  check(h.modal() === mask && h.node('notice').textContent.includes('本批已接收') && h.node('receive').disabled && h.node('receive').style.display === 'none', 'Successful reception retains result modal and cannot submit again');
  check(h.node('table').textContent.includes('名单等级') && h.node('table').textContent.includes('待完善'), 'Source facts are labeled as roster data with current status');
  check(h.content.querySelector('#tbl').textContent.includes('SYNTHETIC 同名') && h.content.querySelector('[data-teacher-total]').textContent === '181人' && h.content.querySelector('[data-teacher-in-library]').textContent === '0人', 'Original teacher list and counters update locally without activating teachers'); equal(h.renders, 0, 'No whole-page rebuild loses import result'); equal(h.cacheInvalidations(), 1, 'Verified receipt invalidates recommendation cache once');
  await h.clickRoster('refresh'); equal(h.writes().length, 1, 'Repeated GET never recreates teachers'); check(!h.node('table').textContent.includes('a'.repeat(64)), 'Private proofs are not displayed'); await h.clickRoster('close'); check(!h.modal(), 'Original modal closes cleanly');
  const binding = h.bindings.at(-1); check(binding.actions.some(action => action.l === '编辑') && binding.actions.some(action => action.l === '完善并入库'), 'Original editing and later completion actions remain');
  for (const role of ['manager', 'viewer']) { const denied = harness({ role }); await denied.mount(); check(!denied.content.querySelector('#teacher-roster-import'), role + ': no import entry'); equal(denied.reads().length, 0, role + ': no private roster request'); }
  const staleFilter = deferred(); let filterReads = 0; const filtered = harness({ override: (url, opts, normal, respond) => url.startsWith('/api/teachers?') && ++filterReads === 1 ? staleFilter.promise.then(respond) : normal() }); await filtered.mount(); filtered.content.querySelector('#flt-kw').value = 'SYNTHETIC'; const filtering = filtered.content.querySelector('#flt-btn').onclick(); await tick(); await filtered.open(); await filtered.clickRoster('receive'); staleFilter.resolve([{ id: 999, name: 'SYNTHETIC STALE FILTER', status: '在库' }]); await filtering; check(!filtered.content.querySelector('#tbl').textContent.includes('STALE FILTER') && filtered.content.querySelector('[data-teacher-total]').textContent === '3人', 'Obsolete library filter cannot overwrite locally refreshed imported rows');
  const malicious = fixture(); malicious.rows[0].name = '<img src=x onerror=alert(1)>'; malicious.rows[0].job = '<script>alert(1)</script>'; const safe = harness({ preview: malicious }); await safe.mount(); await safe.open(); check(!safe.node('table').querySelector('img,script') && safe.node('table').textContent.includes('<img'), 'Names and source jobs remain inert escaped text');
  for (const mutate of [p => { p.rows[1].reference = p.rows[0].reference; }, p => { p.rows[1].accountId = p.rows[0].accountId; }, p => { p.rows[0].teacherLevel = '猜测等级'; }, p => { p.rows[0].teacherId = 7; }, p => { p.summary.teachers++; }, p => { p.summary.excludedLeads = -1; }, p => { p.reviewToken = null; }, p => { p.sourceFingerprint = 'NOT_A_HASH'; }, p => { p.rows[0].status = '在库'; }]) { const p = fixture(); mutate(p); const bad = harness({ preview: p }); await bad.mount(); await bad.open(); check(bad.node('receive').disabled && !bad.node('table').textContent && bad.node('notice').textContent.includes('无法核实'), 'Malformed full preview never permits reception'); }
  for (const mutate of [r => { r.rows[0].accountId++; }, r => { r.rows[0].reference = 'WRONG'; }, r => { r.rows[1].teacherId = r.rows[0].teacherId; }, r => { r.summary.teachers++; }, r => { r.batchKey = 'OTHER'; }]) {
    let after = false; const bad = harness({ override: (url, opts, normal, respond) => { if (url.endsWith('/teacher-roster/import')) { after = true; const r = receipt(fixture()); mutate(r); return respond(r); } if (after && url.endsWith('/teacher-roster/preview')) return respond(null, 503); return normal(); } }); await bad.mount(); await bad.open(); await bad.clickRoster('receive'); check(bad.node('receive').disabled && !bad.node('notice').textContent.includes('本批已接收') && bad.cacheInvalidations() === 0, 'Invalid receipt cannot claim success or update host');
  }
  for (const status of [401, 403, 409, 503]) { const failed = harness({ override: (url, opts, normal, respond) => url.endsWith('/teacher-roster/import') ? respond(null, status) : normal() }); await failed.mount(); await failed.open(); await failed.clickRoster('receive'); check(!failed.modal() || failed.node('receive').disabled && !failed.node('table').textContent, status + ': clears sensitive roster and obsolete token'); equal(failed.writes().length, 1, status + ': no automatic resubmit'); }
  let committed = false; const failedRefresh = harness({ override: async (url, opts, normal, respond) => { if (committed && url.endsWith('/teacher-roster/preview')) return respond(null, 503); const result = await normal(); if (url.endsWith('/teacher-roster/import')) committed = true; return result; } }); await failedRefresh.mount(); await failedRefresh.open(); await failedRefresh.clickRoster('receive'); check(failedRefresh.node('notice').textContent.includes('已接收，当前名单刷新失败') && failedRefresh.node('receive').disabled, 'Known successful receipt remains successful when followup GET fails'); equal(failedRefresh.cacheInvalidations(), 1, 'Known write invalidates host cache even when current preview fails');
  let failList = false; const listFailure = harness({ override: async (url, opts, normal, respond) => { if (failList && url.startsWith('/api/teachers')) return respond(null, 503); const result = await normal(); if (url.endsWith('/teacher-roster/import')) failList = true; return result; } }); await listFailure.mount(); await listFailure.open(); await listFailure.clickRoster('receive'); check(listFailure.node('notice').textContent.includes('已接收，师资列表刷新失败'), 'List-refresh failure is visible in modal instead of hidden by a toast');
  const gate = deferred(), double = harness({ override: (url, opts, normal, respond) => url.endsWith('/teacher-roster/import') ? gate.promise.then(respond) : normal() }); await double.mount(); await double.open(); const saving = double.clickRoster('receive'); await tick(); await double.clickRoster('receive'); equal(double.writes().length, 1, 'In-flight submit lock rejects repeated clicks'); await double.clickRoster('close'); gate.resolve(receipt(fixture())); await saving; check(!double.modal() && double.cacheInvalidations() === 0, 'Closed modal ignores delayed write result and host refresh'); check(double.writes()[0].opts.signal.aborted, 'Closing aborts pending submission transport');
  const readGate = deferred(), late = harness({ override: (url, opts, normal, respond) => url.endsWith('/teacher-roster/preview') ? readGate.promise.then(respond) : normal() }); await late.mount(); const opening = late.open(); await tick(); late.leave(); readGate.resolve(fixture()); await opening; check(!late.modal() && late.reads()[0].opts.signal.aborted, 'Route cleanup blocks delayed preview');
  const newer = deferred(), older = deferred(); let readCount = 0; const ordering = harness({ override: (url, opts, normal, respond) => url.endsWith('/teacher-roster/preview') ? (++readCount === 1 ? older : newer).promise.then(respond) : normal() }); await ordering.mount(); const firstRead = ordering.open(); await tick(); const secondRead = ordering.clickRoster('refresh'); const newData = fixture(); newData.rows[0].name = 'SYNTHETIC NEWEST'; newer.resolve(newData); await secondRead; older.resolve(fixture()); await firstRead; check(ordering.node('table').textContent.includes('SYNTHETIC NEWEST') && ordering.reads()[0].opts.signal.aborted, 'Out-of-order older refresh cannot replace newest preview');
  const identityGate = deferred(), identity = harness({ override: (url, opts, normal, respond) => url.endsWith('/teacher-roster/preview') ? identityGate.promise.then(respond) : normal() }); await identity.mount(); const privateRead = identity.open(); await tick(); identity.sandbox.state.user = { uid: 99, role: 'admin' }; identityGate.resolve(fixture()); await privateRead; check(!identity.modal(), 'Replacing administrator identity clears delayed private preview');
  const recovered = harness({ override: async (url, opts, normal) => { const result = await normal(); if (url.endsWith('/teacher-roster/import')) throw Error('SYNTHETIC lost response'); return result; } }); await recovered.mount(); await recovered.open(); await recovered.clickRoster('receive'); check(recovered.node('notice').textContent.includes('本批已接收') && recovered.writes().length === 1 && recovered.reads().length === 2, 'Unknown POST outcome is recovered only by a verified real-read path');
  const moduleGate = deferred(), tab = harness({ moduleWait: moduleGate }); await tab.mount(); const loading = tab.open(); tab.sandbox.state.teacherTab = 'resumes'; moduleGate.resolve(); await loading; equal(tab.reads().length, 0, 'Delayed module cannot mount in another teacher tab');
  const missing = harness({ moduleFailure: true }); await missing.mount(); await missing.open(); check(missing.toasts.some(item => item.message.includes('原师资档案仍可维护')) && missing.content.querySelector('#teacher-add-manual'), 'Lazy module failure preserves original teacher maintenance');
  const owned = harness(); await owned.mount(); const guarded = owned.sandbox.openModal('原未保存总结', '<p>原内容</p>', { noFoot: true }); guarded._beforeClose = () => false; await owned.open(); check(owned.modal() === guarded && owned.reads().length === 0, 'Rejected modal replacement never binds or reads into another modal'); guarded._beforeClose = null; owned.sandbox.closeModal(); await owned.open(); owned.sandbox.openModal('后继窗口', '<p>后继</p>', { noFoot: true }); const successor = owned.modal(); owned.leave(); check(owned.modal() === successor, 'Route disposal does not close a successor modal');
  console.log(JSON.stringify({ ok: true, suite: 'original teacher roster reception', checks, transport: 'synthetic', browser: false, database: false }));
})().catch(error => { console.error(error); process.exitCode = 1; });
