import { tmpdir as testTmpdir } from 'node:os';
import { chromium } from 'playwright';
import { writeFile, readFile, mkdir, mkdtemp, realpath, access } from 'node:fs/promises';
import { createServer } from 'node:net';
import { spawn } from 'node:child_process';
import { dirname, resolve, join, delimiter, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes } from 'node:crypto';
import assert from 'node:assert/strict';
// Original SPA, real Main and cookie sessions; isolated synthetic H2 only.
const app=resolve(dirname(fileURLToPath(import.meta.url)),'..'), args={};
for(let i=2;i<process.argv.length;i+=2){assert.ok(['--java','--classes'].includes(process.argv[i])&&process.argv[i+1]);args[process.argv[i]]=process.argv[i+1];}
assert.ok(args['--java']&&args['--classes']);const classes=await realpath(args['--classes']);assert.ok(classes!==app&&!classes.startsWith(app+sep));
for(const name of ['Main','IntegrationCertificationMaintenanceHttpFixture'])await access(join(classes,'com/training/'+name+'.class'));
const own=await mkdtemp(join(testTmpdir(), 'yanxu-certification-maintenance-http-browser-')),password=randomBytes(24).toString('hex'),classpath=classes+delimiter+join(app,'lib','*');
let browser,child,base,fixture,log='',error=null,checks=0;const screenshots=[],browserErrors=[],outsideRequests=[],unexpectedFailures=[],expectedFailures=[],tokens={};
const pause=ms=>new Promise(yes=>setTimeout(yes,ms));const check=(yes,label)=>{assert.ok(yes,label);checks++;};const equal=(a,b,label)=>{assert.deepEqual(a,b,label);checks++;};
async function api(path,body,actor='manager'){const response=await fetch(base+'/api'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(tokens[actor]?{'X-Token':tokens[actor]}:{})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(10000)});const value=await response.json();assert.equal(response.status,200,path+': '+value.msg);assert.equal(value.code,0,path+': '+value.msg);return value.data;}
async function boot(width){const data=join(own,'data-'+width);await mkdir(data);for(const key of Object.keys(tokens))delete tokens[key];const listener=createServer();await new Promise(yes=>listener.listen(0,'127.0.0.1',yes));const port=listener.address().port;await new Promise(yes=>listener.close(yes));base='http://127.0.0.1:'+port;
child=spawn(args['--java'],['-Dbind.address=127.0.0.1','-Dbootstrap.demo=false','-Dbootstrap.admin.password='+password,'-Ddata.dir='+data,'-Dintegration.certification.maintenance.root='+own,'-Dsemantic.port=','-Dsemantic.token=','-cp',classpath,'com.training.IntegrationCertificationMaintenanceHttpFixture',String(port)],{cwd:app,env:{...process.env,YANXU_SEMANTIC_PORT:'',YANXU_SEMANTIC_TOKEN:''},stdio:['ignore','pipe','pipe']});child.stdout.on('data',b=>log=(log+b).slice(-24000));child.stderr.on('data',b=>log=(log+b).slice(-24000));let failure;child.once('error',e=>failure=e);
for(let i=0;i<180;i++){if(failure)throw failure;assert.equal(child.exitCode,null);try{tokens.manager=(await api('/login',{username:'synthetic-cert-manager',password},'anonymous')).token;fixture=JSON.parse(await readFile(join(own,'fixture.json'),'utf8'));return;}catch{}await pause(100);}throw Error('Synthetic Main not ready');}
async function stop(){if(!child||child.exitCode!==null||child.signalCode!==null)return;await new Promise(yes=>{const timer=setTimeout(()=>child.kill('SIGKILL'),2500);child.once('exit',()=>{clearTimeout(timer);yes();});child.kill('SIGTERM');});}
async function contextFor(width,actor){const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce',deviceScaleFactor:1});await context.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin===base){if(url.pathname==='/api/visitor-context')return route.abort();return route.continue();}if(url.protocol==='data:')return route.continue();outsideRequests.push(url.origin);return route.abort();});const response=await context.request.post(base+'/api/login',{data:{username:'synthetic-cert-'+actor,password}});equal(response.status(),200,width+' '+actor+' actual cookie login');equal((await response.json()).code,0,'Session valid');const page=await context.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>browserErrors.push(String(e)));page.on('dialog',async d=>{browserErrors.push('native dialog '+d.type());await d.dismiss();});page.on('response',r=>{const path=new URL(r.url()).pathname;if(path.startsWith('/api/')&&r.status()>=400)([401,409].includes(r.status())?expectedFailures:unexpectedFailures).push({width,path,status:r.status()});});return{context,page};}
async function open(page,scope){await page.goto(base+'/#/teachers');await page.locator('#teacher-course-catalog').click();await page.locator('[data-k="scope_id"]').selectOption(String(scope));await page.locator('[data-catalog-action="editor:certifications"]').click();}
const field=(page,key,row)=>page.locator('[data-certification-field="'+key+'"]'+(row===undefined?'':'[data-row="'+row+'"]'));
const action=(page,key)=>page.locator('[data-certification-action="'+key+'"]');
const notice=page=>page.locator('[data-certification-notice]');
async function editMeta(page,version){await field(page,'catalog_version').fill(version);await field(page,'change_comment').fill('SYNTHETIC 逐课认证状态、来源和有效期核对');}
async function ready(page){await field(page,'catalog_version').waitFor();await page.waitForFunction(()=>!document.querySelector('[data-certification-field="catalog_version"]')?.disabled);}
async function saved(page){await page.waitForFunction(()=>document.querySelector('[data-certification-notice]')?.textContent.includes('已保存，认证资料已刷新'));}
async function noOverflow(page,label){const size=await page.evaluate(()=>({width:innerWidth,page:document.documentElement.scrollWidth,surfaces:[...document.querySelectorAll('.modal,[data-certification-maintenance], [data-certification-maintenance] .table-wrap')].filter(n=>n.clientWidth).map(n=>[n.clientWidth,n.scrollWidth])}));check(size.page<=size.width+1&&size.surfaces.every(([a,b])=>b<=a+1),label+': '+JSON.stringify(size));}
async function shot(page,name){const path=join(own,name+'.png');await page.screenshot({path,fullPage:false,animations:'disabled'});screenshots.push(path);}
async function query(page,course){const form=page.locator('[data-catalog-form="query"]');await form.locator('[data-k="course_code"]').fill(course);await form.locator('[data-k="as_of"]').fill('2026-09-23');await form.getByRole('button',{name:'查询资格',exact:true}).click();await page.getByText('本次课程资格符合 · 1 条',{exact:true}).waitFor();return page.getByText('本次课程资格符合 · 1 条',{exact:true}).locator('..').textContent();}
async function verify(width){
 const {context,page}=await contextFor(width,'manager'),calls=[];page.on('request',r=>{if(r.url().includes('/api/course-catalog/'))calls.push(r);});
 try{
  await page.goto(base+'/#/teachers');await page.locator('#teacher-course-catalog').click();await page.locator('[data-k="scope_id"]').selectOption(String(fixture.retained_scope));await page.locator('[data-course-maintenance]').waitFor();equal(calls.filter(r=>r.url().endsWith('/certification-management')).length,0,'Default course editor defers certification read');check((await query(page,'SYN-001')).includes('SYN-T1'),'Original qualified teacher before certification change');await page.locator('[data-catalog-action="editor:certifications"]').click();await ready(page);equal(await page.locator('[data-course-maintenance]').count(),0,'Only certification editor mounted');check(await field(page,'teacher_code',0).isDisabled()&&await field(page,'course_code',0).isDisabled(),'Existing pair locked');check(await action(page,'preview').isDisabled(),'No-op disabled');const original=await api('/course-catalog/scopes/'+fixture.retained_scope);
  await field(page,'status',0).selectOption('revoked');await editMeta(page,'cert-ui-'+width);await action(page,'add').click();equal(await field(page,'status',2).inputValue(),'unknown','New pair starts unknown');equal(await field(page,'valid_from',2).inputValue(),'','No default valid-from');equal(await field(page,'valid_to',2).inputValue(),'','No default valid-to');
  await page.locator('[data-certification-pick="teacher_code:2"]').click();await page.locator('[data-certification-choice="1"]').click();equal(await field(page,'teacher_code',2).inputValue(),'SYN-T2','Exact teacher selected from trusted current list');await page.locator('[data-certification-pick="course_code:2"]').click();check((await page.locator('[data-certification-maintenance]').textContent()).includes('停用'),'Picker exposes inactive course explicitly');await page.locator('[data-certification-choice="0"]').click();equal(await field(page,'course_code',2).inputValue(),'SYN-001','Exact current course selected');await field(page,'status',2).selectOption('certified');await field(page,'source_ref',2).fill('SYNTHETIC EVIDENCE 新认定依据');await field(page,'valid_from',2).fill('2026-01-01');equal(calls.filter(r=>r.url().endsWith('/certifications-preview')).length,0,'Typing/selecting sends no batch');
  await page.locator('[data-certification-maintenance]').evaluate(n=>n.scrollIntoView({block:'start'}));await noOverflow(page,'editor '+width);await shot(page,'certification-editor-'+width);await action(page,'preview').click();await page.waitForFunction(()=>document.querySelector('[data-certification-notice]')?.textContent.includes('尚未生效'));check((await page.locator('[data-certification-maintenance]').textContent()).includes('有效期边界未完整提供'),'Explicit missing-end-date warning preserved');const pre=calls.find(r=>r.url().endsWith('/certifications-preview')).postDataJSON();equal(Object.keys(pre).sort(),['catalog_version','certifications','change_comment','expected_version'],'No client course/teacher/binding replacement');equal(pre.certifications[2].valid_to,'','Empty date stays exact empty');equal(calls.filter(r=>r.url().endsWith('/confirm')).length,0,'Separate confirm required');await action(page,'confirm').evaluate(n=>n.scrollIntoView({block:'start'}));await noOverflow(page,'preview '+width);await shot(page,'certification-preview-'+width);
  const mask=await page.locator('#modal-mask').elementHandle();await action(page,'confirm').click();await saved(page);check(await mask.evaluate(n=>n===document.querySelector('#modal-mask')),'Save keeps original modal');const after=await api('/course-catalog/scopes/'+fixture.retained_scope);equal(after.version,2,'Single version committed');equal(after.catalog.courses,original.catalog.courses,'Courses retained exactly');equal(after.catalog.teachers,original.catalog.teachers,'Teachers retained exactly');equal(after.bindings,original.bindings,'Bindings retained exactly');equal(after.catalog.certifications.map(r=>r.status),['revoked','unknown','certified'],'Revocation and new certification persisted');const qualified=await query(page,'SYN-001');check(qualified.includes('SYN-T2')&&!qualified.includes('SYN-T1'),'Original UI qualification uses updated certification, not stale result');equal(calls.filter(r=>r.url().endsWith('/certification-management')).length,2,'Current certification management reread');
  await field(page,'source_ref',0).fill('SYNTHETIC UNSAVED');await page.locator('[data-catalog-action="editor:courses"]').click();await action(page,'stay').click();equal(await field(page,'source_ref',0).inputValue(),'SYNTHETIC UNSAVED','Dirty switch stay retains input');await page.locator('[data-catalog-action="editor:courses"]').click();await action(page,'discard').click();await page.locator('[data-course-maintenance]').waitFor();equal(await page.locator('[data-certification-maintenance]').count(),0,'Explicit discard leaves only course editor');await page.locator('[data-catalog-action="editor:certifications"]').click();await ready(page);
  if(width===1280){
   await field(page,'status',0).selectOption('not_certified');await editMeta(page,'cert-lost-response');await action(page,'preview').click();await page.waitForFunction(()=>document.querySelector('[data-certification-action="confirm"]')?.disabled===false);await page.route('**/api/course-catalog/scopes/'+fixture.retained_scope+'/confirm',async route=>{const response=await route.fetch();equal(response.status(),200,'Lost-response test committed actual server transaction');await route.abort('failed');});await action(page,'confirm').click();await page.waitForFunction(()=>document.querySelector('[data-certification-notice]')?.textContent.includes('尚未确认'));check(await action(page,'preview').isDisabled()&&!await page.locator('[data-catalog-form="query"]').count(),'Unknown outcome freezes batch and removes stale qualification');await page.unroute('**/api/course-catalog/scopes/'+fixture.retained_scope+'/confirm');const prior=calls.filter(r=>r.url().endsWith('/confirm')).at(-1).postDataJSON();await action(page,'confirm').click();await saved(page);equal(calls.filter(r=>r.url().endsWith('/confirm')).at(-1).postDataJSON(),prior,'Explicit retry uses same immutable batch');equal((await api('/course-catalog/scopes/'+fixture.retained_scope)).version,3,'Replay never increments twice');
   await field(page,'source_ref',0).fill('SYNTHETIC REFRESH FAILURE');await editMeta(page,'cert-refresh-failure');await action(page,'preview').click();await page.waitForFunction(()=>document.querySelector('[data-certification-action="confirm"]')?.disabled===false);await page.route('**/api/course-catalog/scopes/'+fixture.retained_scope+'/certification-management',route=>route.abort('failed'));await action(page,'confirm').click();await page.waitForFunction(()=>document.querySelector('[data-certification-notice]')?.textContent.includes('已保存，当前列表刷新失败'));check(await action(page,'confirm').isDisabled(),'Refresh failure does not reopen committed confirmation');await page.unroute('**/api/course-catalog/scopes/'+fixture.retained_scope+'/certification-management');await action(page,'refresh').click();await ready(page);equal(await field(page,'source_ref',0).inputValue(),'SYNTHETIC REFRESH FAILURE','Explicit refresh recovers persisted data');
   await field(page,'source_ref',0).fill('SYNTHETIC STALE');await editMeta(page,'cert-stale');await action(page,'preview').click();await page.waitForFunction(()=>document.querySelector('[data-certification-action="confirm"]')?.disabled===false);tokens.colleague=(await api('/login',{username:'synthetic-cert-colleague',password},'anonymous')).token;const current=await api('/course-catalog/scopes/'+fixture.retained_scope+'/certification-management',undefined,'colleague');current.certifications[0].source_ref='SYNTHETIC colleague won';const p=await api('/course-catalog/scopes/'+fixture.retained_scope+'/certifications-preview',{expected_version:current.version,catalog_version:'cert-concurrent',certifications:current.certifications,change_comment:'SYNTHETIC concurrent source correction'},'colleague');await api('/course-catalog/scopes/'+fixture.retained_scope+'/confirm',{batch_id:p.batch_id,expected_version:current.version,confirm:true},'colleague');await action(page,'confirm').click();await page.waitForFunction(()=>document.querySelector('[data-certification-notice]')?.textContent.includes('目录版本或师资依据已变化'));equal(await page.locator('[data-certification-field]').count(),0,'CAS requires explicit new read');await action(page,'refresh').click();await ready(page);equal(await field(page,'source_ref',0).inputValue(),'SYNTHETIC colleague won','Concurrent winner retained');
   await page.locator('[data-catalog-action="editor:courses"]').click();await page.locator('[data-course-maintenance]').waitFor();let release,intercepted=false;const gate=new Promise(yes=>release=yes);await page.route('**/api/course-catalog/scopes/'+fixture.retained_scope+'/certification-management',async route=>{const response=await route.fetch();intercepted=true;await gate;try{await route.fulfill({response});}catch{}});await page.locator('[data-catalog-action="editor:certifications"]').click();for(let i=0;!intercepted&&i<100;i++)await pause(20);check(intercepted,'Late read is an actual authorized server GET');await page.locator('[data-catalog-action="editor:courses"]').click();await action(page,'discard').click();await page.locator('[data-course-maintenance]').waitFor();release();await pause(80);equal(await page.locator('[data-certification-maintenance]').count(),0,'Late certification cannot replace newly selected editor');await page.unroute('**/api/course-catalog/scopes/'+fixture.retained_scope+'/certification-management');
  }
 }finally{await context.close();}
 const write=await contextFor(width,'maintainer'),requests=[];write.page.on('request',r=>{if(r.url().includes('/api/course-catalog/'))requests.push(r);});try{
  await open(write.page,fixture.retained_scope);await ready(write.page);await field(write.page,'source_ref',0).fill('SYNTHETIC MANAGE ONLY');await editMeta(write.page,'cert-manage-only-'+width);await action(write.page,'preview').click();await write.page.waitForFunction(()=>document.querySelector('[data-certification-action="confirm"]')?.disabled===false);await action(write.page,'confirm').click();await saved(write.page);equal(requests.filter(r=>/^\/api\/course-catalog\/scopes\/\d+$/.test(new URL(r.url()).pathname)||r.url().endsWith('/qualify')).length,0,'Manage-only has no read/qualify request');
  for(const id of [fixture.empty_scope,fixture.empty_courses_scope,fixture.removed_teachers_scope]){await write.page.locator('[data-k="scope_id"]').selectOption(String(id));await write.page.locator('[data-catalog-action="editor:certifications"]').click();await ready(write.page);check(await action(write.page,'add').isDisabled(),'No invented pair for missing current teachers/courses '+id);}
  await write.page.locator('[data-k="scope_id"]').selectOption(String(fixture.partial_teachers_scope));await write.page.locator('[data-catalog-action="editor:certifications"]').click();await ready(write.page);await action(write.page,'add').click();await write.page.locator('[data-certification-pick]').first().click();const picker=write.page.locator('[data-certification-choice]');equal(await picker.count(),1,'Removed historical teacher code is not offered as current');await action(write.page,'picker-close').click();await write.page.locator('#modal-x').click();await action(write.page,'discard').click();
  await open(write.page,fixture.retained_scope);await ready(write.page);equal((await write.context.request.post(base+'/api/logout',{data:{}})).status(),200,'Real session logout');await action(write.page,'refresh').click();await write.page.waitForFunction(()=>!document.querySelector('#modal-mask'));equal(await write.page.locator('[data-certification-maintenance]').count(),0,'Expired session clears certification data');
 }finally{await write.context.close();}
 const reader=await contextFor(width,'reader'),reads=[];reader.page.on('request',r=>reads.push(r.url()));try{await reader.page.goto(base+'/#/teachers');await reader.page.locator('#teacher-course-catalog').click();await reader.page.locator('[data-k="scope_id"]').selectOption(String(fixture.retained_scope));await reader.page.locator('[data-catalog-form="query"]').waitFor();equal(await reader.page.locator('[data-catalog-action="editor:certifications"]').count(),0,'Read-only keeps original read UI');equal(reads.filter(u=>u.includes('certification-management')||u.includes('certifications-preview')).length,0,'Read-only never requests certification management');}finally{await reader.context.close();}
}
try{browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || undefined,headless:true});for(const width of [1280,390,320]){await boot(width);await verify(width);await stop();}equal(browserErrors,[],'No browser errors/native dialogs');equal(outsideRequests,[],'No outside requests');equal(unexpectedFailures,[],'No unexpected API failure');}catch(e){error=e;}finally{await browser?.close();await stop();await writeFile(join(own,'server.log'),log.replaceAll(password,'[synthetic password redacted]'),{mode:0o600});const result={ok:!error,checks,classes,temporaryDirectory:own,screenshots,browserErrors,outsideRequests,unexpectedFailures,expectedFailures,temporaryServiceStopped:!child||child.exitCode!==null||child.signalCode!==null,...(error?{error:error.stack||String(error)}:{})};await writeFile(join(own,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));}if(error)process.exitCode=1;
