import { tmpdir as testTmpdir } from 'node:os';
import { chromium } from 'playwright';
import { mkdir,mkdtemp,realpath,access,writeFile,readFile,rename } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { createServer } from 'node:net';
import { randomBytes,randomUUID,createHash } from 'node:crypto';
import { dirname,resolve,join,delimiter,sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
// Real original SPA, Main/API and cookie login. Only isolated synthetic fixture data; no business response mocks.
const app=resolve(dirname(fileURLToPath(import.meta.url)),'..'),args={};
for(let i=2;i<process.argv.length;i+=2){assert.ok(['--java','--classes'].includes(process.argv[i])&&process.argv[i+1]);args[process.argv[i]]=process.argv[i+1];}
assert.ok(args['--java']&&args['--classes']);const classes=await realpath(args['--classes']);assert.ok(classes!==app&&!classes.startsWith(app+sep));
for(const name of ['Main','IntegrationAccountPermissionsHttpFixture'])await access(join(classes,'com/training/'+name+'.class'));
const own=await mkdtemp(join(testTmpdir(), 'yanxu-account-permissions-http-browser-')),password=randomBytes(24).toString('hex'),classpath=classes+delimiter+join(app,'lib','*');
const inspectedFiles=['web/app.js','web/modules/identity/account-permissions.js','scripts/IntegrationAccountPermissionsBrowser.mjs'];
const sourceHashes=async()=>Object.fromEntries(await Promise.all(inspectedFiles.map(async file=>[file,createHash('sha256').update(await readFile(join(app,file))).digest('hex')])));
const testedSourceSha256=await sourceHashes();
let browser,child,base,fixture,error=null,log='',checks=0;const screenshots=[],browserErrors=[],outsideRequests=[],failures=[],contexts=new Set();
const pause=ms=>new Promise(yes=>setTimeout(yes,ms)),check=(value,label)=>{assert.ok(value,label);checks++;},equal=(value,expected,label)=>{assert.deepEqual(value,expected,label);checks++;};
async function control(operation){const nonce=randomUUID();await writeFile(join(own,'control-request.next'),JSON.stringify({nonce,operation}));await rename(join(own,'control-request.next'),join(own,'control-request.json'));for(let i=0;i<150;i++){try{const r=JSON.parse(await readFile(join(own,'control-result.json'),'utf8'));if(r.nonce===nonce){assert.equal(r.ok,true);return r.data;}}catch{}await pause(20);}throw Error('Synthetic control timeout');}
async function boot(label,empty=false){await writeFile(join(own,'control-request.json'),'{}');const data=join(own,'data-'+label);await mkdir(data);const listener=createServer();await new Promise(yes=>listener.listen(0,'127.0.0.1',yes));const port=listener.address().port;await new Promise(yes=>listener.close(yes));base='http://127.0.0.1:'+port;
 child=spawn(args['--java'],['-Dbind.address=127.0.0.1','-Dbootstrap.demo=false','-Dlogin.email.mode=legacy','-Dbootstrap.admin.password='+password,'-Ddata.dir='+data,'-Dintegration.account.permissions.root='+own,'-Dintegration.account.permissions.empty='+empty,'-Dsemantic.port=','-Dsemantic.token=','-cp',classpath,'com.training.IntegrationAccountPermissionsHttpFixture',String(port)],{cwd:app,env:{...process.env,YANXU_SEMANTIC_PORT:'',YANXU_SEMANTIC_TOKEN:''},stdio:['ignore','pipe','pipe']});child.stdout.on('data',b=>log=(log+b).slice(-24000));child.stderr.on('data',b=>log=(log+b).slice(-24000));let startupError;child.once('error',e=>startupError=e);
 for(let i=0;i<180;i++){if(startupError)throw startupError;assert.equal(child.exitCode,null,'Synthetic Main alive');try{const r=await fetch(base+'/',{signal:AbortSignal.timeout(1000)});if(r.ok){fixture=JSON.parse(await readFile(join(own,'fixture.json'),'utf8'));return;}}catch{}await pause(100);}throw Error('Synthetic Main startup timeout');}
async function stop(){if(!child||child.exitCode!==null||child.signalCode!==null)return;await new Promise(yes=>{const timer=setTimeout(()=>child.kill('SIGKILL'),2500);child.once('exit',()=>{clearTimeout(timer);yes();});child.kill('SIGTERM');});}
async function contextFor(width,actor='admin'){const context=await browser.newContext({viewport:{width,height:1000},deviceScaleFactor:1,reducedMotion:'reduce'});contexts.add(context);await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin===base||u.protocol==='data:'){if(u.pathname==='/api/visitor-context')return route.abort();return route.continue();}outsideRequests.push(u.origin);return route.abort();});const response=await context.request.post(base+'/api/login',{data:{username:actor==='admin'?'admin':'synthetic-access-'+actor,password}});equal(response.status(),200,'Actual cookie login '+actor);equal((await response.json()).code,0,'Cookie login envelope');const page=await context.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>browserErrors.push(String(e)));page.on('dialog',async d=>{browserErrors.push('Native '+d.type());await d.dismiss();});page.on('response',r=>{const path=new URL(r.url()).pathname;if(path.startsWith('/api/')&&r.status()>=400)failures.push({width,path,status:r.status()});});return{context,page};}
async function closeContext(context){await context.close();contexts.delete(context);}
async function rowAction(page,id,label){const row=page.locator('#tbl [data-row-id="'+id+'"]'),button=row.getByRole('button',{name:label,exact:true});if(await button.isVisible())await button.click();else{await row.locator('summary').click();await page.getByRole('button',{name:label,exact:true}).click();}}
const part=(page,key)=>page.locator('[data-permissions-'+key+']');
async function open(page,key){await rowAction(page,fixture.accounts[key],'查看业务权限');await page.waitForFunction(()=>document.querySelector('[data-permissions-read]')?.disabled===false);}
async function select(page,organization){await part(page,'organization').selectOption(organization);await page.waitForFunction(()=>document.querySelector('[data-permissions-read]')?.disabled===false);}
async function result(page,label){return part(page,'results').evaluate((root,label)=>[...root.querySelectorAll('tbody tr')].find(row=>row.querySelector('td')?.textContent===label)?.querySelectorAll('td')[1]?.textContent,label);}
async function noOverflow(page,label){const d=await page.evaluate(()=>({width:innerWidth,page:document.documentElement.scrollWidth,surfaces:[...document.querySelectorAll('.modal,[data-permissions-results], [data-permissions-results] .table-wrap, #modal-mask .toolbar')].filter(n=>n.clientWidth).map(n=>[n.clientWidth,n.scrollWidth])}));check(d.page<=d.width+1&&d.surfaces.every(([a,b])=>b<=a+1),label+': '+JSON.stringify(d));}
async function shot(page,name){const path=join(own,name+'.png');await page.screenshot({path,fullPage:false,animations:'disabled'});screenshots.push(path);}
async function mainCase(width){const {context,page}=await contextFor(width),requests=[],writes=[];page.on('request',r=>{const u=new URL(r.url());if(u.pathname==='/api/organization/account-access')requests.push(r);if(u.pathname.startsWith('/api/organization/')&&r.method()!=='GET'&&r.method()!=='HEAD')writes.push(u.pathname);});try{
 await page.goto(base+'/#/users');await page.locator('#tbl tbody tr').first().waitFor();equal(requests.length,0,'No row-by-row inspection requests');const before=await control('snapshot');await open(page,'teacher');equal(await page.locator('#modal-title').textContent(),'查看业务权限','Original read-only modal');check((await part(page,'subject').textContent()).includes('SYNTHETIC ACCESS teacher'),'Explicit server subject');equal(await part(page,'organization').inputValue(),'','User must select organization');equal(await part(page,'results').textContent(),'','No guessed initial permissions');equal(await page.locator('#modal-ok').count(),0,'No save action');await select(page,'001');equal(await part(page,'results').locator('tbody tr').count(),15,'All 15 inspected operations');equal(await result(page,'查看授课'),'范围允许','Bound teacher has only real delivery read');equal(await result(page,'维护课程目录'),'尚未配置','Viewer account role does not invent catalog management');check(!(await part(page,'results').textContent()).includes('TEACHER_READ'),'Matched rule identifiers hidden');await part(page,'close').click();
 await open(page,'combined');await select(page,'001');equal(await result(page,'维护课程目录'),'范围允许','Leader range applies to 001');equal(await result(page,'核对授课'),'范围不允许','BP range not broadened to 001');equal(await result(page,'审批审核'),'范围允许','Assigned role range permits approval gate');await noOverflow(page,'combined '+width);await shot(page,'account-permissions-'+width);await select(page,'002');equal(await result(page,'维护课程目录'),'范围不允许','Leader range not broadened to 002');equal(await result(page,'核对授课'),'范围允许','BP range applies to 002');await part(page,'close').click();
 await open(page,'denied');await select(page,'001');equal(await result(page,'查看课程目录'),'范围允许','Explicit read remains');equal(await result(page,'维护课程目录'),'范围不允许','Explicit deny takes precedence');check((await part(page,'results').textContent()).includes('显式禁止'),'Deny reason shown');await part(page,'close').click();
 await open(page,'disabled');await select(page,'001');check((await part(page,'subject').textContent()).includes('账号停用'),'Disabled account distinct');equal(await part(page,'results').locator('tbody tr').filter({hasText:'账号已停用'}).count(),15,'Disabled account has no actionable-looking permission');await part(page,'close').click();
 for(const key of ['unbound','binding-off','person-off','org-off']){await open(page,key);await select(page,'001');check(!(await part(page,'results').textContent()).includes('范围允许'),key+' never inherits account-level role');await part(page,'close').click();}
 await rowAction(page,fixture.accounts.teacher,'编辑');equal(await page.locator('#modal-title').textContent(),'编辑用户','Original edit preserved');await page.locator('#modal-x').click();await page.locator('#add-btn').click();equal(await page.locator('#modal-title').textContent(),'新增用户','Original add preserved');await page.locator('#modal-x').click();equal(await control('snapshot'),before,'All persisted tables unchanged by inspection');equal(writes,[],'No organization mutation request');check(requests.every(r=>r.method()==='GET'),'All inspection reads use GET');
 if(width===1280){
  await open(page,'combined');let release,held=false;const gate=new Promise(yes=>release=yes);const url='**/api/organization/account-access?account_id='+fixture.accounts.combined+'&organization_code=001';await page.route(url,async route=>{const actual=await route.fetch();equal(actual.status(),200,'Delayed inspection is actual Main response');held=true;await gate;try{await route.fulfill({response:actual});}catch{}});await part(page,'organization').selectOption('001');for(let i=0;!held&&i<100;i++)await pause(20);check(held,'Old institution read held');equal(await part(page,'results').textContent(),'','New read clears old decisions immediately');await select(page,'002');release();await pause(80);equal(await result(page,'维护课程目录'),'范围不允许','Late 001 cannot replace 002 decisions');equal(await part(page,'organization').inputValue(),'002','Selected institution remains latest');await page.unroute(url);await part(page,'close').click();
  let closeRelease,closeHeld=false;const closeGate=new Promise(yes=>closeRelease=yes),targetUrl='**/api/organization/account-access?account_id='+fixture.accounts.teacher;await page.route(targetUrl,async route=>{const actual=await route.fetch();closeHeld=true;await closeGate;try{await route.fulfill({response:actual});}catch{}});await rowAction(page,fixture.accounts.teacher,'查看业务权限');for(let i=0;!closeHeld&&i<100;i++)await pause(20);check(closeHeld,'Real initial target read held');await part(page,'close').click();await page.evaluate(()=>{location.hash='#/dashboard';});await page.locator('#priority-list').waitFor();closeRelease();await pause(80);equal(await part(page,'subject').count(),0,'Close and route change do not reopen late subject');await page.unroute(targetUrl);await page.goto(base+'/#/users');await page.locator('#tbl tbody tr').first().waitFor();
  await open(page,'teacher');await select(page,'001');await control('corrupt-configuration');await part(page,'read').click();await page.waitForFunction(()=>document.querySelector('[data-permissions-read]')?.disabled===false);check(!(await part(page,'results').textContent())&&!(await part(page,'subject').textContent())&&await part(page,'organization').isDisabled(),'Bad configuration clears prior private conclusions');await control('restore-configuration');await part(page,'read').click();await page.waitForFunction(()=>document.querySelector('[data-permissions-organization]')?.disabled===false);await select(page,'001');equal(await result(page,'查看授课'),'范围允许','Explicit retry re-reads restored configuration');await control('downgrade-admin');await part(page,'read').click();await part(page,'subject').waitFor({state:'detached'});equal(await page.locator('[data-permissions-results]').count(),0,'Administrator role loss clears modal');await control('restore-admin');
 }
 }finally{await closeContext(context);}
 if(width===1280){for(const actor of ['manager','viewer']){const next=await contextFor(width,actor);try{const calls=[];next.page.on('request',r=>{if(r.url().includes('/organization/account-access'))calls.push(r.url());});await next.page.goto(base+'/#/users');await next.page.locator('#priority-list').waitFor();equal(await next.page.getByRole('button',{name:'查看业务权限',exact:true}).count(),0,actor+' cannot access inspection entry');equal(calls,[],actor+' never sends inspection reads');}finally{await closeContext(next.context);}}}
}
async function emptyCase(){const {context,page}=await contextFor(1280);try{await page.goto(base+'/#/users');await page.locator('#tbl tbody tr').first().waitFor();const before=await control('snapshot');await open(page,'teacher');check((await part(page,'notice').textContent()).includes('组织权限尚未发布'),'Unpublished configuration remains queryable');check(await part(page,'organization').isDisabled()&&!(await part(page,'results').textContent()),'No invented organization or permissions before publication');await noOverflow(page,'unpublished');await shot(page,'account-permissions-unpublished-1280');equal(await control('snapshot'),before,'Unpublished inspection writes nothing');}finally{await closeContext(context);}}
try{browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || undefined,headless:true});for(const width of [1280,390,320]){await boot(width);await mainCase(width);await stop();}await boot('empty',true);await emptyCase();await stop();equal(browserErrors,[],'No browser errors/native dialogs');equal(outsideRequests,[],'No external requests');equal(await sourceHashes(),testedSourceSha256,'Tested sources remained unchanged throughout browser run');}catch(e){error=e;}finally{for(const context of contexts)await context.close().catch(()=>{});await browser?.close();await stop();await writeFile(join(own,'server.log'),log.replaceAll(password,'[synthetic password redacted]'),{mode:0o600});const result={ok:!error,checks,classes,temporaryDirectory:own,testedSourceSha256,screenshots,browserErrors,outsideRequests,authenticationOrConfigurationResponses:failures,browserClosed:true,temporaryServiceStopped:!child||child.exitCode!==null||child.signalCode!==null,...(error?{error:error.stack||String(error)}:{})};await writeFile(join(own,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));}if(error)process.exitCode=1;
