'use strict';
// Initial M01 configuration through real pinned import, Main, Auth and transactional Store publication.
const fs=require('node:fs'),path=require('node:path'),net=require('node:net'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {spawn,execFile}=require('node:child_process'),run=require('node:util').promisify(execFile),args={};
for(let i=2;i<process.argv.length;i+=2){assert.ok(['--java','--classes','--fixture-classes'].includes(process.argv[i])&&process.argv[i+1],'Use --java PATH --classes DIRECTORY or CLASSES_DIR');args[process.argv[i]]=process.argv[i+1];}
const java=args['--java']||'java',repo=path.resolve(__dirname,'..'),classes=fs.realpathSync(args['--classes']||process.env.CLASSES_DIR||''),fixtureClasses=args['--fixture-classes']?fs.realpathSync(args['--fixture-classes']):classes;
for(const value of [classes,fixtureClasses])assert.ok(value!==repo&&!value.startsWith(repo+path.sep),'Use independent classes outside repository');assert.ok(fs.existsSync(path.join(fixtureClasses,'com/training/IntegrationAccountProvisioningHttpFixture.class')),'Compile synthetic fixture first');
const base='/organization/account-provisioning',password=crypto.randomBytes(24).toString('hex'),failures=[],pids=[],readEvidence=[],tokens={},roots=[],env={...process.env,JAVA_TOOL_OPTIONS:'',JDK_JAVA_OPTIONS:'',_JAVA_OPTIONS:'',YANXU_SEMANTIC_PORT:'',YANXU_SEMANTIC_TOKEN:''};
let own,data,pins,child,port,checks=0,phase='setup',fatal=null,evidence,empty=true,linkAdmin=true;const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms)),digest=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
function freshRoot(){own=fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'yanxu-account-provisioning-http-'));data=path.join(own,'data');fs.mkdirSync(data);roots.push(own);pins=null;for(const key of Object.keys(tokens))delete tokens[key];}
function check(ok,label){checks++;if(!ok)failures.push(phase+': '+label);}
function same(a,b,label){let ok=true;try{assert.deepEqual(a,b);}catch{ok=false;}check(ok,label);}
function options(resume=false){return ['-Dbind.address=127.0.0.1','-Dbootstrap.demo=false','-Dbootstrap.admin.password='+password,'-Dlogin.email.mode=legacy','-Dintegration.account.provisioning.root='+own,'-Dintegration.account.provisioning.resume='+resume,'-Dintegration.account.provisioning.empty='+empty,'-Dintegration.account.provisioning.linkAdmin='+linkAdmin,'-Ddata.dir='+data,'-Dsemantic.port=','-Dsemantic.token=',...(pins?['-Daccount.import.manifest='+pins.manifest,'-Daccount.import.manifest.sha256='+pins.sha256]:['-Daccount.import.manifest=','-Daccount.import.manifest.sha256=']),'-cp',fixtureClasses+path.delimiter+classes+path.delimiter+path.join(repo,'lib','*')];}
async function fixture(operation){return JSON.parse((await run(java,[...options(true),'com.training.IntegrationAccountProvisioningHttpFixture',operation],{cwd:repo,env,timeout:20000,maxBuffer:65536})).stdout.trim());}
async function request(route,body,actor='admin',opts={}){
 const headers={...(tokens[actor]?{'X-Token':tokens[actor]}:{}),...(body!==undefined?{'Content-Type':opts.contentType||'application/json'}:{})};const r=await fetch(`http://127.0.0.1:${port}/api${route}`,{method:opts.method||(body===undefined?'GET':'POST'),headers,body:body===undefined?undefined:opts.raw?body:JSON.stringify(body),signal:AbortSignal.timeout(15000)}),text=await r.text();let envelope=null;if(text){try{envelope=JSON.parse(text);}catch{throw new Error('Non-JSON HTTP '+r.status+' at '+route);}}
 if(route.startsWith(base)){check(r.headers.get('cache-control')==='no-store','Provisioning responses and errors are no-store');check(!text.includes(password)&&!text.includes('pbkdf2$')&&!text.includes(own)&&!text.includes('/sources/')&&!text.includes('000SYN')&&!text.includes('imp_p_')&&!text.includes('jdbc:'),'No credential, hidden person code, staff number or private source path is returned');check(!envelope?.data?.token&&!r.headers.get('set-cookie')?.match(/^yx_session=[^;]/),'Preparation never signs an account session');}
 return {status:r.status,text,envelope,headers:r.headers};
}
async function api(route,body,actor='admin',opts={}){const r=await request(route,body,actor,opts);assert.equal(r.status,200,phase+': '+route+' HTTP '+r.status+' '+r.envelope?.msg);assert.equal(r.envelope?.code,0,route);return r.envelope.data;}
async function denied(route,body,status,label,actor='admin',opts={}){const r=await request(route,body,actor,opts);check(r.status===status,label+' (HTTP '+r.status+')');if(opts.method==='HEAD')same(r.text,'','HEAD error has no body');else check(r.envelope?.code===status&&!r.envelope?.data,'Failure returns no partial people, review or configuration');check(!r.text.includes('SYNTHETIC PRIVATE'),'Failure does not disclose a candidate name');return r;}
async function login(actor='admin',key=actor){tokens[key]=(await api('/login',{username:actor==='admin'?'admin':'synthetic-provisioning-'+actor,password},null)).token;}
async function boot(resume=false){const listener=net.createServer();await new Promise((resolve,reject)=>{listener.once('error',reject);listener.listen(0,'127.0.0.1',resolve);});port=listener.address().port;await new Promise(resolve=>listener.close(resolve));child=spawn(java,[...options(resume),'com.training.IntegrationAccountProvisioningHttpFixture',String(port)],{cwd:repo,env,stdio:'ignore'});if(child.pid)pids.push(child.pid);let error;child.once('error',value=>{error=value;});for(let i=0;i<200;i++){if(error)throw error;assert.equal(child.exitCode,null,'Synthetic Main exited');try{await login();return;}catch{}await pause(100);}throw new Error('Synthetic Main startup timeout');}
async function stop(){const running=child;child=null;if(!running||running.exitCode!==null||running.signalCode!==null)return;await new Promise(resolve=>{const timer=setTimeout(()=>{if(running.exitCode===null&&running.signalCode===null)running.kill('SIGKILL');},2000);running.once('exit',()=>{clearTimeout(timer);resolve();});running.kill('SIGTERM');});}
async function control(operation){const nonce=crypto.randomUUID(),tmp=path.join(own,'control-request.next');fs.writeFileSync(tmp,JSON.stringify({nonce,operation}),{mode:0o600});fs.renameSync(tmp,path.join(own,'control-request.json'));for(let i=0;i<250;i++){try{const r=JSON.parse(fs.readFileSync(path.join(own,'control-result.json'),'utf8'));if(r.nonce===nonce&&r.ok)return r.data;}catch{}await pause(20);}throw new Error('Synthetic control timeout: '+operation);}
async function readOnly(label,operation){phase=label;const before=await control('snapshot');await operation();const after=await control('snapshot');same(after,before,'Every PUBLIC table remains unchanged');readEvidence.push({phase:label,root:path.basename(own),tables:Object.keys(before).length,before:digest(before),after:digest(after)});}
const preview=(actor='admin')=>api(base+'/preview',{},actor),confirmation=value=>({batch_key:value.batch_key,review_token:value.review_token}),protectedTables=value=>Object.fromEntries(Object.entries(value).filter(([name])=>name!=='ORGANIZATION_ACCESS_CONFIG'));
function epochTable(rows){return {count:rows.length,sha256:digest(rows.map(row=>JSON.stringify({epoch:row.epoch,user_id:row.user_id})).sort())};}
async function initialPublicationOnly(before,after,people){
 const expected=people.map(person=>({user_id:person.account_id,epoch:1})).sort((a,b)=>a.user_id-b.user_id);
 check(expected.length===7&&new Set(expected.map(row=>row.user_id)).size===7&&expected.every(row=>Number.isSafeInteger(row.user_id)&&row.user_id>0),'Initial publication affects exactly seven distinct received account IDs');
 same(before.S01_TRUSTED_DEVICE_EPOCHS,epochTable([]),'Fresh initial publication starts with no device epoch rows');
 same(await control('device-epochs'),expected,'Initial publication creates epoch one exactly for every new disabled binding and no unrelated account');
 same(protectedTables(after),{...protectedTables(before),S01_TRUSTED_DEVICE_EPOCHS:epochTable(expected)},'Publication changes only configuration history and the exactly expected device epoch rows');
}
function statusSchema(value,present,version=null){same(Object.keys(value).sort(),['account_count','bindings_enabled','can_prepare','configuration_present','configuration_version'],'Base status has exact publication fields');same(value,{configuration_present:present,configuration_version:version,account_count:present?7:0,bindings_enabled:0,can_prepare:!present},'Base status reports durable configuration independently of a browser review');}
function previewSchema(value,receipt,accountsEnabled){
 same(Object.keys(value).sort(),['accounts_activated','batch_key','can_operate','combined_assignments','diff','expires_at','grants','intake_revision','issues','office_codes_status','organizations','people','permissions_published','policy_version','proposed_version','requires_account_activation','review_token','source_fingerprint','summary','validation','warnings'],'Exact safe generation preview DTO');
 check(value.permissions_published===false&&value.accounts_activated===false&&value.can_operate===false&&value.requires_account_activation===true,'Prepared policy never claims accounts or authority are already active');check(value.office_codes_status==='UNKNOWN'&&value.policy_version==='M01-INITIAL-PROVISIONING-v1'&&value.batch_key==='synthetic-import','Only approved policy version and server-pinned batch are used');check(/^[a-f0-9]{64}$/.test(value.review_token)&&Date.parse(value.expires_at)>Date.now(),'Review is opaque and has finite expiry');same(value.validation,{configuration_valid:true},'Candidate passes complete original M01 configuration validation');
 check(value.people.length===7&&new Set(value.people.map(row=>row.reference)).size===7,'Each received source identity remains separate');const byReceipt=new Map(receipt.rows.map(row=>[row.reference,row]));
 for(const row of value.people){same(Object.keys(row).sort(),['account_enabled','account_id','binding_enabled','bp_reference','leader_reference','name','organization_code','organization_name','person_enabled','reference','role_codes','role_scopes','route_status'],'Person projection excludes private import person IDs and editable configuration');check(row.account_id===byReceipt.get(row.reference)?.accountId&&row.binding_enabled===false&&row.person_enabled===true,'Account comes from verified receipt while binding remains disabled');check(row.role_codes.includes('MEMBER')&&row.role_scopes.length===row.role_codes.length&&row.role_scopes.every(scope=>row.role_codes.includes(scope.role_code)),'Every held duty has an explicit separate scope');if(row.route_status!=='ROUTE_PREPARED')check(row.leader_reference===null&&row.bp_reference===null&&!row.role_codes.includes('SUBMITTER'),'Blocked route does not silently choose a partial/default handler');}
 const ordinary=value.people.find(row=>row.reference==='teacher-row-3'),multi=value.people.filter(row=>['teacher-row-4','teacher-row-5','teacher-row-8'].includes(row.reference));check(ordinary.route_status==='ROUTE_PREPARED'&&ordinary.leader_reference==='lead-row-9'&&ordinary.bp_reference==='teacher-row-7'&&ordinary.role_codes.includes('SUBMITTER'),'Unique verified branch route is prepared for ordinary employee without approving duties');check(!ordinary.role_codes.some(role=>['BRANCH_RESPONSIBLE','BRANCH_LEAD','BP'].includes(role)),'Ordinary teacher never receives implicit approval role');check(multi.every(row=>row.route_status==='MULTIPLE_LEADERS'),'Every identity in multi-leader branch remains blocked individually');check(value.people.find(row=>row.reference==='lead-row-9').route_status==='SELF_REVIEW','Branch leader cannot receive a self-review submit route');check(['teacher-row-6','teacher-row-7'].every(ref=>value.people.find(row=>row.reference===ref).route_status==='HOME_NOT_BRANCH'),'Responsible scopes do not move HR home organization into a branch');
 check(value.organizations.every(org=>/^org_sys_v1_[a-f0-9]{32}$/.test(org.organization_code)&&org.office_code===null&&org.enabled===true),'Organization IDs are technical IDs, office codes remain unknown');for(const org of value.organizations){const sourceName=org.kind==='ROOT'?'SYSTEM_ROOT':org.display_name;check(org.organization_code==='org_sys_v1_'+crypto.createHash('sha256').update(org.kind+'\n'+sourceName).digest('hex').slice(0,32),'Technical organization namespace is reproducible from exact source name');}
 check(value.grants.every(grant=>grant.effect==='ALLOW'&&['approval.review','demand.read','demand.write'].includes(grant.resource)&&['OWN_ORG','RESPONSIBLE_ORGS'].includes(grant.scope)&&grant.role_code!=='MEMBER'),'No training-team, course, delivery, finance or export grant is invented');check(value.combined_assignments.length===1&&value.combined_assignments[0].reference==='teacher-row-6'&&value.combined_assignments[0].evidence_status==='VERIFIED_SOURCE','Explicit same-person branch/BP evidence is preserved separately');
 same([value.summary.account_count,value.summary.accounts_enabled,value.summary.accounts_disabled,value.summary.bindings_enabled],[7,accountsEnabled,7-accountsEnabled,0],'Account enablement counts do not become binding enablement');same([value.summary.route_prepared_count,value.summary.route_blocked_count],[1,6],'Prepared and blocked route counts reflect actual trusted source');same([value.summary.route_blocked_counts.MULTIPLE_LEADERS,value.summary.route_blocked_counts.HOME_NOT_BRANCH,value.summary.route_blocked_counts.SELF_REVIEW],[3,2,1],'Block reasons are counted per actual person');check(value.issues.length===6&&value.diff.bindings_added===7&&value.diff.enabled_bindings_added===0,'Every blocked person has a review issue while every generated binding stays disabled');
}
async function slowPost(actor,route){return new Promise((resolve,reject)=>{const socket=net.createConnection({host:'127.0.0.1',port});let bytes='',done=false;const timer=setTimeout(()=>finish(new Error('Preflight waited for an incomplete body')),2500);function finish(error,value){if(done)return;done=true;clearTimeout(timer);socket.destroy();error?reject(error):resolve(value);}socket.on('error',error=>finish(error));socket.on('data',chunk=>{bytes+=chunk;if(bytes.includes('\r\n\r\n'))finish(null,{status:Number(/^HTTP\/1\.1 (\d+)/.exec(bytes)?.[1]),no_store:/cache-control:\s*no-store/i.test(bytes)});});socket.on('connect',()=>socket.write('POST /api'+route+' HTTP/1.1\r\nHost: 127.0.0.1:'+port+'\r\nConnection: close\r\nContent-Type: application/json\r\nContent-Length: 900000\r\n'+(tokens[actor]?'X-Token: '+tokens[actor]+'\r\n':'')+'\r\n{'));});}
async function runChecks(){
 freshRoot();pins=await fixture('prepare');await boot();for(const actor of ['admin2','manager','viewer'])await login(actor);
 await readOnly('base status and incomplete intake',async()=>{statusSchema(await api(base),false);await denied(base+'/preview',{},409,'Unreceived account source cannot produce initial permissions');const head=await request(base,undefined,'admin',{method:'HEAD'});check(head.status===200&&head.text==='','HEAD verifies durable state without body');});
 await readOnly('administrator preflight precedes methods queries and slow bodies',async()=>{for(const [actor,status] of [[null,401],['manager',403],['viewer',403]]){await denied(base+'?x=1',undefined,status,'Authentication precedes query disclosure',actor);await denied(base+'/unknown',{},status,'Unknown route authenticates first',actor);await denied(base,undefined,status,'HEAD has same administrator boundary',actor,{method:'HEAD'});}await denied(base+'/unknown',{},404,'Unknown authenticated action does not fall through CRUD');await denied(base,{},405,'Status is read-only');await denied(base+'/preview',undefined,405,'Preview requires explicit POST');for(const [actor,status,route] of [[null,401,base+'/preview'],['manager',403,base+'/confirm'],['admin',405,base]]){const waiting=slowPost(actor,route);check(Object.keys(await control('snapshot')).length>0,'Incomplete body holds no shared business lock');const r=await waiting;check(r.status===status&&r.no_store,'Slow incomplete POST rejected before body read');}});
 await readOnly('strict empty preview and review-only confirmation protocol',async()=>{for(const suffix of ['?','?x=1','?x=1&%78=2'])await denied(base+suffix,undefined,400,'No query accepts client source/configuration selection');await denied(base+'/preview',{configuration:{}},400,'Client configuration is never accepted');await denied(base+'/preview',{active:true},400,'Client cannot activate bindings');for(const raw of ['', '[]','{"x":"a","\\u0078":"b"}','\u000b{}','{}\u000c'])await denied(base+'/preview',raw,400,'Strict flat JSON rejects empty/array/duplicate/illegal whitespace','admin',{raw:true});await denied(base+'/preview',Buffer.from([0x7b,0x22,0xff,0x22,0x3a,0x22,0x78,0x22,0x7d]),400,'Invalid UTF-8 rejected','admin',{raw:true});await denied(base+'/preview','{}',415,'JSON content type required','admin',{raw:true,contentType:'text/plain'});await denied(base+'/preview','{"x":"'+'x'.repeat(5000)+'"}',413,'Four-KiB request bound preserved','admin',{raw:true});await denied(base+'/confirm',{batch_key:'synthetic-import',review_token:'a'.repeat(64),configuration:{}},400,'Confirm accepts only opaque server review fields');});
 phase='original real pinned account reception';const original=await api('/organization/account-import/preview'),proof=await api('/organization/account-import/accounts/1');const receipt=await api('/organization/account-import/commit',{expectedRevision:original.revision,sourceFingerprint:original.sourceFingerprint,reviewToken:original.reviewToken,decisions:original.rows.map(row=>({reference:row.reference,action:row.reference==='teacher-row-4'?'LINK_EXISTING':'CREATE_PENDING',accountId:row.reference==='teacher-row-4'?1:null,accountProof:row.reference==='teacher-row-4'?proof.proof:null,reviewed:true}))});check(receipt.rows.length===7&&receipt.accountsActivated===false&&receipt.permissionsPublished===false,'Real intake preserves explicit old account and six disabled new accounts');await control('capture');const baseline=await control('snapshot');let first;
 await readOnly('generation from complete verified receipt is entirely read-only',async()=>{first=await preview();previewSchema(first,receipt,1);statusSchema(await api(base),false);check(first.people.find(row=>row.reference==='teacher-row-4').name==='SYNTHETIC PRIVATE 4','Display name comes from trusted source, not current linked administrator name');same((await api('/organization/config')).configuration,null,'Preview does not publish a configuration');});
 await readOnly('review binding to actor session and batch',async()=>{const p=await preview();await denied(base+'/confirm',confirmation(p),409,'Other administrator cannot consume review','admin2');await login('admin','second-session');await denied(base+'/confirm',confirmation(p),409,'Same account second session cannot confirm old review','second-session');await denied(base+'/confirm',{...confirmation(p),batch_key:'not-the-configured-batch'},409,'Wrong batch cannot select a different importer or consume review');});
 for(const [change,restore] of [['account-change','account-restore'],['receipt-change','receipt-restore'],['decision-digest-change','receipt-restore'],['receipt-replay-change','receipt-restore']]){phase='prepare changed source proof';const p=await preview();await control(change);await readOnly('changed trusted intake '+change,async()=>{await denied(base+'/confirm',confirmation(p),409,'Current receipt and actual accounts must still match preview');});await control(restore);await readOnly('changed intake proof cannot be revived '+change,async()=>{await denied(base+'/confirm',confirmation(p),409,'Restored facts cannot revive a previously rejected review');});}
 phase='source pin alteration';const source=path.join(own,'sources','candidates.json'),sourceBytes=fs.readFileSync(source),sourceReview=await preview();fs.appendFileSync(source,'\n');await readOnly('changed pinned source fails safely',async()=>{await denied(base+'/preview',{},409,'Pinned source cannot be replaced through reviewed batch');await denied(base+'/confirm',confirmation(sourceReview),409,'Confirm checks source independently of prior preview');});fs.writeFileSync(source,sourceBytes);await readOnly('source restoration does not revive failed proof',async()=>{await denied(base+'/confirm',confirmation(sourceReview),409,'Source-invalidated review remains consumed');});
 for(const useOldHost of [false,true]){phase='manifest reset setup';const review=await preview(),bytes=fs.readFileSync(pins.manifest);fs.writeFileSync(pins.manifest,'SYNTHETIC INVALID MANIFEST');await readOnly('pinned host failure drops stale review cache '+useOldHost,async()=>{await denied(useOldHost?'/organization/account-import/preview':base+'/preview',useOldHost?undefined:{},503,'Unverifiable server manifest closes private source host');statusSchema(await api(base),false);});fs.writeFileSync(pins.manifest,bytes);await readOnly('new trusted importer requires fresh provisioning review '+useOldHost,async()=>{await denied(base+'/confirm',confirmation(review),409,'Restored manifest cannot revive reviews in old importer instance');});}
 phase='expiry setup';const expired=await preview();await control('expire-reviews');await readOnly('expired review cannot publish',async()=>{await denied(base+'/confirm',confirmation(expired),409,'Five-minute review is enforced by server');});
 phase='publication rollback setup';const failed=await preview();await control('publish-failure-on');await readOnly('failed publication is atomic and sanitized',async()=>{await denied(base+'/confirm',confirmation(failed),503,'Storage failure returns no SQL/private source details');statusSchema(await api(base),false);same((await api('/me')).uid,1,'Failed transaction does not revoke actor session');});await control('publish-failure-off');await readOnly('failed publication token is permanently consumed',async()=>{await denied(base+'/confirm',confirmation(failed),409,'Same review cannot be reused after a failed publish');});
 phase='revoked administrator setup';const revoked=await preview();await control('revoke-admin');await readOnly('withdrawn session cannot prepare or confirm',async()=>{await denied(base,undefined,401,'Status rechecks live actor');await denied(base+'/confirm',confirmation(revoked),401,'Withdrawn actor cannot publish');});await login();await readOnly('replacement session cannot reuse old review',async()=>{await denied(base+'/confirm',confirmation(revoked),409,'Old session identity remains part of review binding');});
 phase='explicit initial publication';const finalReview=await preview();await denied(base+'/confirm',confirmation(finalReview),409,'Wrong actor does not consume final rightful review','admin2');await denied(base+'/confirm',{...confirmation(finalReview),batch_key:'wrong'},409,'Wrong batch does not consume final rightful review');const before=await control('snapshot');same(before,baseline,'All preparation, rejected writes and restored fixture faults preserve every table since intake');const result=await api(base+'/confirm',confirmation(finalReview)),after=await control('snapshot');
 same(Object.keys(result).sort(),['account_count','accounts_activated','batch_key','bindings_enabled','can_operate','configuration_valid','configuration_version','intake_revision','permissions_published','policy_version','prepared','proposed_version','published','requires_account_activation','route_blocked_count','route_prepared_count','sessionInvalidated','source_fingerprint'],'Published receipt has exact prepared plus host publication fields');check(result.published===true&&result.permissions_published===true&&result.accounts_activated===false&&result.can_operate===false&&result.requires_account_activation===true&&result.bindings_enabled===0,'Publication is explicit but neither accounts nor operations are activated');same(result.configuration_version,finalReview.proposed_version,'Host publishes the exact reviewed server configuration version');check(result.sessionInvalidated===true,'Publishing a new disabled binding for the linked administrator returns success and invalidates its old session');await initialPublicationOnly(before,after,finalReview.people);check(after.ORGANIZATION_ACCESS_CONFIG.count===1,'First publication creates exactly one immutable version');
 await denied('/me',undefined,401,'Success actually revoked old linked administrator session');await login();let durable;
 await readOnly('durable published status and all-disabled effective grants',async()=>{durable=await api(base);statusSchema(durable,true,result.configuration_version);await denied(base+'/confirm',confirmation(finalReview),409,'Consumed publication cannot replay');await denied(base+'/preview',{},409,'Initial generator cannot overwrite an existing configuration');const cfg=(await api('/organization/config')).configuration;check(cfg.accountBindings.length===7&&cfg.accountBindings.every(binding=>binding.enabled===false),'Every stored account binding is disabled including pre-enabled existing user');for(const p of finalReview.people){const view=await api('/organization/account-access?account_id='+p.account_id+'&organization_code='+p.organization_code);check(view.decisions.length===15&&view.decisions.every(d=>!d.allowed),'No generated account can operate before explicit activation');}const imported=await api('/organization/account-import/preview');same(imported.receipt.rows,receipt.rows,'Original full intake receipt remains exactly compatible after publication');});
 await control('corrupt-configuration');await readOnly('base status fails safely for bad stored configuration',async()=>{await denied(base,undefined,503,'Corrupt persisted source is not presented as absent');await denied(base,undefined,503,'HEAD also fails safely','admin',{method:'HEAD'});});await control('restore-configuration');const beforeRestart=await control('snapshot');await stop();same(await fixture('inspect'),beforeRestart,'Offline table digests agree before restart');await boot(true);await readOnly('cold restart confirms published state without replaying generation',async()=>{same(await api(base),durable,'Browser can resolve an unknown prior result from durable status');await denied(base+'/preview',{},409,'Restart cannot reopen initial configuration generation');});const final=await control('snapshot');same(final,beforeRestart,'Cold restart and status query perform no persistent writes');fs.writeFileSync(path.join(own,'database-invariants.json'),JSON.stringify({baseline,before_publish:before,after_publish:after,final,read_phases:readEvidence},null,2),{mode:0o600});fs.writeFileSync(path.join(own,'synthetic-preview.json'),JSON.stringify({...first,review_token:'[redacted]'},null,2),{mode:0o600});await stop();
 // A separate all-pending fixture verifies CAS concurrency without either caller being a revoked imported user.
 freshRoot();empty=false;linkAdmin=false;pins=await fixture('prepare');await boot();const allPendingReceipt=(await api('/organization/account-import/preview')).receipt;let p1,p2;await readOnly('all-pending account generation remains disabled',async()=>{p1=await preview();p2=await preview();previewSchema(p1,allPendingReceipt,0);});const concurrentBefore=await control('snapshot');phase='competing initial confirmations';const responses=await Promise.all([request(base+'/confirm',confirmation(p1)),request(base+'/confirm',confirmation(p2))]);same(responses.map(r=>r.status).sort(),[200,409],'Competing valid reviews publish once and return a conflict to the loser');const concurrentAfter=await control('snapshot');await initialPublicationOnly(concurrentBefore,concurrentAfter,p1.people);check(concurrentAfter.ORGANIZATION_ACCESS_CONFIG.count===1,'Concurrent publication writes only one configuration');const winner=responses.find(r=>r.status===200).envelope.data;check(winner.sessionInvalidated===false,'Unbound administrator is not unnecessarily revoked');await readOnly('all-pending result never activates accounts',async()=>{statusSchema(await api(base),true,winner.configuration_version);check((await api('/users')).filter(user=>String(user.username).startsWith('pending_')).every(user=>user.status===0&&user.role==='viewer'),'All seven synthetic received users remain disabled viewers');});fs.writeFileSync(path.join(own,'concurrent-publication.json'),JSON.stringify({statuses:responses.map(r=>r.status),before:concurrentBefore,after:concurrentAfter},null,2),{mode:0o600});return {read_only_phases:readEvidence.length,tables_per_read_phase:Object.keys(concurrentAfter).length,protected_tables:Object.keys(concurrentAfter).length-1,source_candidates:7,isolated_scenarios:2,all_bindings_disabled:true};
}
runChecks().then(value=>{evidence=value;}).catch(error=>{fatal=String(error.message||error).replaceAll(password,'[redacted]');process.exitCode=1;}).finally(async()=>{await stop();const stopped=pids.every(pid=>{try{process.kill(pid,0);return false;}catch(error){return error.code==='ESRCH';}});check(stopped,'All synthetic provisioning Main processes stopped');const summary={suite:'account-provisioning-http',checks,failures,...(fatal?{error:fatal}:{}),...(evidence||{}),server_processes_stopped:stopped,production_touched:false,notifications_sent:false,artifacts:roots[0],scenario_roots:roots};if(roots[0])fs.writeFileSync(path.join(roots[0],'result.json'),JSON.stringify(summary,null,2),{mode:0o600});console.log(JSON.stringify(summary));if(failures.length||fatal)process.exitCode=1;});
