'use strict';
// Real Main login/email verification. Synthetic pinned intake, private memory sender and temporary H2 only.
const fs=require('node:fs'),path=require('node:path'),net=require('node:net'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {spawn,execFile}=require('node:child_process'),run=require('node:util').promisify(execFile),args={};
for(let i=2;i<process.argv.length;i+=2){assert.ok(['--java','--classes','--fixture-classes'].includes(process.argv[i])&&process.argv[i+1],'Use --java PATH --classes DIRECTORY or CLASSES_DIR');args[process.argv[i]]=process.argv[i+1];}
const java=args['--java']||'java',repo=path.resolve(__dirname,'..'),classes=fs.realpathSync(args['--classes']||process.env.CLASSES_DIR||'');assert.ok(classes!==repo&&!classes.startsWith(repo+path.sep),'Use independent classes outside the repository');const fixtureClasses=args['--fixture-classes']?fs.realpathSync(args['--fixture-classes']):classes;assert.ok(fixtureClasses!==repo&&!fixtureClasses.startsWith(repo+path.sep),'Use independent fixture classes');assert.ok(fs.existsSync(path.join(fixtureClasses,'com/training/IntegrationLoginVerificationHttpFixture.class')),'Compile the synthetic fixture first');
const own=fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'yanxu-login-verification-http-')),data=path.join(own,'data');fs.mkdirSync(data);
const password=crypto.randomBytes(24).toString('hex'),failures=[],servicePids=[],readEvidence=[],env={...process.env,JAVA_TOOL_OPTIONS:'',JDK_JAVA_OPTIONS:'',_JAVA_OPTIONS:'',YANXU_SEMANTIC_PORT:'',YANXU_SEMANTIC_TOKEN:''};let child,port,checks=0,phase='setup',fatal=null,ids,launchMode=null,sender='memory';
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function check(ok,label){checks++;if(!ok)failures.push(phase+': '+label);}
function same(a,b,label){let ok=true;try{assert.deepEqual(a,b);}catch{ok=false;}check(ok,label);}
function options(resume=false){return ['-Dbind.address=127.0.0.1','-Dbootstrap.demo=false','-Dbootstrap.admin.password='+password,'-Dintegration.login.verification.root='+own,'-Dintegration.login.verification.resume='+resume,'-Dintegration.login.verification.sender='+sender,...(launchMode===null?[]:['-Dlogin.email.mode='+launchMode]),'-Ddata.dir='+data,'-Dsemantic.port=','-Dsemantic.token=','-Daccount.import.manifest=','-Daccount.import.manifest.sha256=','-cp',fixtureClasses+path.delimiter+classes+path.delimiter+path.join(repo,'lib','*')];}
async function request(route,body,options={}){
 const headers={...(options.token?{'X-Token':options.token}:{}),...(options.cookie?{Cookie:options.cookie}:{})};if(body!==undefined)headers['Content-Type']=options.contentType||'application/json';
 const r=await fetch(`http://127.0.0.1:${port}/api${route}`,{method:options.method||(body===undefined?'GET':'POST'),headers,body:body===undefined?undefined:options.raw?body:JSON.stringify(body),signal:AbortSignal.timeout(25000)});const text=await r.text();let envelope=null;if(text){try{envelope=JSON.parse(text);}catch{throw new Error('Non-JSON response at '+route+' HTTP '+r.status);}}
 check(!text.includes(password)&&!text.includes('pbkdf2$')&&!text.includes('@example.test')&&!text.includes(own),'HTTP never exposes password/hash/candidate email/private path');if(route.startsWith('/login'))check(r.headers.get('cache-control')==='no-store','Authentication responses are not cacheable');return {status:r.status,text,envelope,headers:r.headers};
}
async function api(route,body,options={}){const r=await request(route,body,options);assert.equal(r.status,200,phase+': '+route+': HTTP '+r.status+': '+r.envelope?.msg);assert.equal(r.envelope?.code,0,route);return r.envelope.data;}
function sessionCookie(response){const value=response.headers.get('set-cookie')||'';return /^yx_session=([^;]+)/.test(value)&&!/Max-Age=0(?:;|$)/i.test(value)?value.split(';')[0]:null;}
function noSession(response,label){check(!response.envelope?.data?.token&&!sessionCookie(response),label+' creates no authentication token or usable cookie');}
async function denied(route,body,status,label,options={}){const r=await request(route,body,options);check(r.status===status&&r.envelope?.code===status,label+' (HTTP '+r.status+')');check(!r.envelope?.data,'Rejected login reveals no candidate/session/challenge details');noSession(r,label);return r;}
async function boot(resume=false){const listener=net.createServer();await new Promise((resolve,reject)=>{listener.once('error',reject);listener.listen(0,'127.0.0.1',resolve);});port=listener.address().port;await new Promise(resolve=>listener.close(resolve));child=spawn(java,[...options(resume),'com.training.IntegrationLoginVerificationHttpFixture',String(port)],{cwd:repo,env,stdio:'ignore'});if(child.pid)servicePids.push(child.pid);let error;child.once('error',e=>{error=e;});for(let i=0;i<180;i++){if(error)throw error;assert.equal(child.exitCode,null,'Synthetic Main exited');try{const r=await fetch(`http://127.0.0.1:${port}/api/me`,{signal:AbortSignal.timeout(1000)});await r.text();if(r.status===401){ids=JSON.parse(fs.readFileSync(path.join(own,'fixture.json'),'utf8'));return;}}catch{}await pause(100);}throw new Error('Synthetic Main startup timeout');}
async function stop(){const running=child;child=null;if(!running||running.exitCode!==null||running.signalCode!==null)return;await new Promise(resolve=>{const timer=setTimeout(()=>{if(running.exitCode===null&&running.signalCode===null)running.kill('SIGKILL');},2000);running.once('exit',()=>{clearTimeout(timer);resolve();});running.kill('SIGTERM');});}
async function control(operation,extra={}){const nonce=crypto.randomUUID(),tmp=path.join(own,'control-request.next');fs.writeFileSync(tmp,JSON.stringify({nonce,operation,...extra}),{mode:0o600});fs.renameSync(tmp,path.join(own,'control-request.json'));for(let i=0;i<250;i++){try{const ack=JSON.parse(fs.readFileSync(path.join(own,'control-result.json'),'utf8'));if(ack.nonce===nonce&&ack.ok)return ack.data;}catch{}await pause(20);}throw new Error('Synthetic control timeout: '+operation);}
const stats=()=>control('stats'),advance=millis=>control('advance',{millis}),freshWindow=()=>advance(3600001),digest=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
async function readOnly(label,operation){phase=label;const before=await control('snapshot');await operation();const after=await control('snapshot');same(after,before,'Full PUBLIC table data remains unchanged');readEvidence.push({phase:label,tables:Object.keys(before).length,before:digest(before),after:digest(after)});}
const loginBody=name=>({username:'synthetic-login-'+name,password}),verifyBody=(challenge,code)=>({challenge_id:challenge.challenge_id,code});
function mailbox(){return JSON.parse(fs.readFileSync(path.join(own,'mailbox.json'),'utf8'));}
function latest(name='worker'){const rows=mailbox().filter(row=>row.email===name+'@example.test');assert.ok(rows.length,'Expected private synthetic mail');const mail=rows.at(-1);assert.match(mail.code,/^[0-9]{6}$/,'Code is six digits');return mail;}
async function begin(name='worker'){const before=await stats(),r=await request('/login',loginBody(name));assert.equal(r.status,200,phase+': expected email challenge, HTTP '+r.status);const c=r.envelope?.data;same(Object.keys(c).sort(),['challenge_id','expires_at','masked_email','resend_after','status'],'Password proof response has only challenge DTO');check(c.status==='EMAIL_REQUIRED'&&/^[a-f0-9]{64}$/.test(c.challenge_id)&&c.masked_email==='***@***','Challenge is opaque and candidate identity is fully masked');check(Number.isFinite(Date.parse(c.expires_at))&&Date.parse(c.expires_at)>before.clock&&Date.parse(c.resend_after)>before.clock,'Challenge reports absolute expiry and cooldown');noSession(r,'Password phase');same((await stats()).sessions,before.sessions,'Correct password alone does not issue any Auth session');return c;}
async function complete(challenge,code=latest().code){const before=await stats(),r=await request('/login/email/verify',verifyBody(challenge,code));assert.equal(r.status,200,phase+': verify HTTP '+r.status);const data=r.envelope.data;same(Object.keys(data).sort(),['token','user'],'Successful verification returns original session DTO only');check(typeof data.token==='string'&&data.token.length>=32&&Boolean(sessionCookie(r)),'Only verification creates a session token and cookie');check((r.headers.get('set-cookie')||'').includes('HttpOnly')&&(r.headers.get('set-cookie')||'').includes('SameSite=Lax'),'Issued session cookie keeps original HttpOnly/SameSite protection');same((await stats()).sessions,before.sessions+1,'Exactly one Auth session is minted');const cookie=sessionCookie(r);same((await api('/me',undefined,{cookie})).uid,data.user.uid,'Real same-origin cookie authorizes the original API');return {token:data.token,cookie,user:data.user};}
async function logout(session){await api('/logout',{}, {cookie:session.cookie});await denied('/me',undefined,401,'Logout invalidates the original session cookie',{cookie:session.cookie});}
async function runChecks(){
 await boot();const baseline=await control('snapshot');
 await readOnly('default legacy login remains compatible',async()=>{const r=await request('/login',loginBody('admin'));check(r.status===200&&typeof r.envelope?.data?.token==='string'&&Boolean(sessionCookie(r)),'Absent mode property retains legacy password login');same((await api('/me',undefined,{cookie:sessionCookie(r)})).uid,ids.accounts['synthetic-login-admin'],'Legacy session represents the actual synthetic administrator');await api('/logout',{}, {cookie:sessionCookie(r)});check((await stats()).sessions===0&&(await stats()).mail_count===0,'Legacy mode does not send a verification email');});
 await control('mode-unknown');await readOnly('unknown mode fails closed',async()=>{await denied('/login',loginBody('worker'),503,'Unknown configured mode cannot fall back to legacy password login');check((await stats()).sessions===0,'Misconfiguration creates no session');});await control('mode-required');
 await readOnly('strict unauthenticated login input protocol',async()=>{
  await denied('/login',undefined,405,'Login requires POST');await denied('/login/email/verify',undefined,405,'Verification requires POST');await denied('/login?x=1&%78=2',loginBody('worker'),400,'No query or encoded repeated override allowed');await denied('/login/email/unknown',{},404,'Unknown login action is not accepted');
  for(const b of [{...loginBody('worker'),email:'injected@example.test'},{...loginBody('worker'),password:123},{username:'synthetic-login-worker'},[]])await denied('/login',b,400,'Client cannot replace candidate/proof or omit required fields');
  for(const raw of ['{"username":"a","username":"b","password":"x"}','{"username":"a","pass\\u0077ord":"x","password":"y"}','\u000b{"username":"a","password":"x"}'])await denied('/login',raw,400,'Strict parser rejects duplicate decoded keys and illegal JSON whitespace',{raw:true});
  await denied('/login',JSON.stringify(loginBody('worker')),415,'Only JSON media is accepted',{raw:true,contentType:'text/plain'});await denied('/login',JSON.stringify({username:'x',password:'x'.repeat(1024*1024)}),413,'Original actual request-size limit remains enforced',{raw:true});
  await denied('/login/email/verify',{challenge_id:'x',code:'123456'},400,'Challenge format is strict');await denied('/login/email/verify',{challenge_id:'a'.repeat(64),code:123456},400,'Code must be text');await denied('/login/email/resend',{challenge_id:'a'.repeat(64),email:'injected@example.test'},400,'Resend cannot override recipient');
 });
 await freshWindow();await readOnly('invalid credentials and missing prepared candidate never issue sessions',async()=>{
  const before=await stats();await denied('/login',{...loginBody('worker'),password:'synthetic-wrong-password'},401,'Wrong password rejected before sender');await denied('/login',{username:'synthetic-not-found',password},401,'Unknown account is not disclosed');for(const name of ['pending','no-password'])await denied('/login',loginBody(name),401,'Only explicitly active password-bearing account can proceed');for(const name of ['missing','cleared'])await denied('/login',loginBody(name),409,'Missing or cleared candidate has no password-only fallback');const after=await stats();check(after.sessions===0&&after.mail_count===before.mail_count,'All rejected first factors leave sender and Auth sessions untouched');
 });
 await freshWindow();await readOnly('password proof then code verify establishes only final cookie session',async()=>{const c=await begin();const mail=latest();check(mail.held_lock===false,'Memory sender ran outside shared business lock');await denied('/me',undefined,401,'Password proof cannot call authenticated APIs');await denied('/login/email/verify',verifyBody(c,mail.code==='000000'?'999999':'000000'),400,'Wrong code rejected without issuing session');const session=await complete(c,mail.code);same(session.user.uid,ids.accounts['synthetic-login-worker'],'Verified identity is the password-proven account');await denied('/login/email/verify',verifyBody(c,mail.code),401,'Verified challenge is consumed exactly once');await logout(session);});
 await freshWindow();await readOnly('parallel verify consumes one challenge exactly once',async()=>{const c=await begin(),code=latest().code;const before=await stats(),responses=await Promise.all([request('/login/email/verify',verifyBody(c,code)),request('/login/email/verify',verifyBody(c,code))]);same(responses.map(r=>r.status).sort(),[200,401],'Concurrent correct codes produce one success and one expired challenge');check(responses.filter(r=>sessionCookie(r)).length===1,'Only winning request receives a usable authentication cookie');same((await stats()).sessions,before.sessions+1,'Parallel verification mints only one session');const success=responses.find(r=>r.status===200);await logout({cookie:sessionCookie(success)});});
 await freshWindow();await readOnly('cancel is idempotent and consumes no authenticated session',async()=>{const c=await begin(),code=latest().code;const before=await stats();same(await api('/login/email/cancel',{challenge_id:c.challenge_id}),null,'Cancel returns only null');same(await api('/login/email/cancel',{challenge_id:c.challenge_id}),null,'Cancel retry is idempotent');same(await api('/login/email/cancel',{challenge_id:'a'.repeat(64)}),null,'Unknown opaque challenge cancellation is harmless');await denied('/login/email/verify',verifyBody(c,code),401,'Canceled challenge cannot verify');same((await stats()).sessions,before.sessions,'Cancel cannot create a session');});
 await freshWindow();await readOnly('resend cooldown replacement and expiry use server time',async()=>{const c=await begin(),oldCode=latest().code;await denied('/login/email/resend',{challenge_id:c.challenge_id},429,'Resend respects current server cooldown');await advance(Date.parse(c.resend_after)-(await stats()).clock+1);const r=await request('/login/email/resend',{challenge_id:c.challenge_id});check(r.status===200&&r.envelope?.data?.status==='EMAIL_REQUIRED','Cooldown elapsed permits another challenge');noSession(r,'Resend');const next=r.envelope.data;check(next.challenge_id!==c.challenge_id,'Resend replaces rather than revives old challenge');await denied('/login/email/verify',verifyBody(c,oldCode),401,'Old challenge becomes unusable after resend');const session=await complete(next,latest().code);await logout(session);});
 await freshWindow();await readOnly('wrong-code budget survives challenge resend',async()=>{let c=await begin(),correct=latest().code,wrong=correct==='000000'?'999999':'000000';for(let i=0;i<3;i++)await denied('/login/email/verify',verifyBody(c,wrong),400,'Incorrect code consumes a bounded attempt');await advance(Date.parse(c.resend_after)-(await stats()).clock+1);c=await api('/login/email/resend',{challenge_id:c.challenge_id});correct=latest().code;wrong=correct==='000000'?'999999':'000000';await denied('/login/email/verify',verifyBody(c,wrong),400,'Fourth wrong attempt remains the same account challenge budget');await denied('/login/email/verify',verifyBody(c,wrong),401,'Fifth wrong attempt consumes challenge even across resend');await denied('/login/email/verify',verifyBody(c,correct),401,'Exhausted challenge rejects even its correct code');check((await stats()).sessions===0,'Wrong-code exhaustion creates no Auth session');});
 await freshWindow();await readOnly('challenge expiry is enforced at verification',async()=>{const c=await begin(),code=latest().code;await advance(Date.parse(c.expires_at)-(await stats()).clock+1);await denied('/login/email/verify',verifyBody(c,code),401,'Correct but expired code cannot sign a session');check((await stats()).sessions===0,'Expired challenge never authenticates');});
 for(const operation of ['worker-disable','worker-password','worker-role','worker-email','worker-clear-email','worker-source','revoke-worker']){
  await freshWindow();phase='candidate or account revision invalidates challenge';const c=await begin(),code=latest().code;await control(operation);
  await readOnly('challenge invalidation after '+operation,async()=>{await denied('/login/email/verify',verifyBody(c,code),401,'Current account/credential/email/import binding must still match');check((await stats()).sessions===0,'Changed identity cannot create a session');});await control('worker-restore');
 }
 await freshWindow();phase='sender hold';await control('sender-hold');const sending=request('/login',loginBody('worker'));let waiting=false;for(let i=0;i<200;i++){try{waiting=JSON.parse(fs.readFileSync(path.join(own,'sender-waiting.json'),'utf8')).waiting;if(waiting)break;}catch{}await pause(20);}check(waiting,'Synthetic sender pauses while real HTTP request is in flight');
 await readOnly('sender does not hold database lock during delivery',async()=>{const s=await stats();check(s.sender_lock_violations===0&&s.sessions===0,'Independent control and whole database read proceed while sender waits');await denied('/me',undefined,401,'Unrelated HTTP handling is not blocked by sender');});await control('worker-email');await control('sender-release');const changedDuringSend=await sending;check(changedDuringSend.status===401,'Email/source is checked again after delivery before returning challenge');noSession(changedDuringSend,'Candidate changed during send');await control('worker-restore');
 await freshWindow();await control('sender-fail');await readOnly('sender failure has no credential-only fallback',async()=>{await denied('/login',loginBody('worker'),503,'Unavailable sender cannot create a challenge or session');check((await stats()).sessions===0,'Delivery failure signs no session');});await control('sender-normal');
 await freshWindow();await readOnly('per-account delivery window remains enforced across cancel',async()=>{const before=await stats();for(let i=0;i<5;i++){const c=await begin();await api('/login/email/cancel',{challenge_id:c.challenge_id});await advance(60001);}await denied('/login',loginBody('worker'),429,'Sixth send in the same hour is throttled even after cancel');check((await stats()).mail_count===before.mail_count+5,'Throttled attempt does not reach sender');});
 await freshWindow();await readOnly('password preflight limits requests before account discovery',async()=>{const before=await stats(),statuses=[];for(let i=0;i<30;i++)statuses.push((await request('/login',{username:'synthetic-never-imported',password:'invalid'})).status);check(statuses.every(s=>s===401),'First bounded window attempts have uniform unauthorized result');await denied('/login',{username:'synthetic-never-imported',password:'invalid'},429,'Password preflight stops attempt31 before hashing/source lookup');check((await stats()).mail_count===before.mail_count&& (await stats()).sessions===0,'Preflight failures neither mail nor sign sessions');});
 await freshWindow();await readOnly('explicit withdrawal invalidates a verified session',async()=>{const c=await begin(),session=await complete(c,latest().code);await control('revoke-worker');await denied('/me',undefined,401,'Explicit account session withdrawal invalidates verified cookie',{cookie:session.cookie});});
 for(const operation of ['worker-email','worker-source']){await freshWindow();phase='verified session binding '+operation;const c=await begin(),session=await complete(c,latest().code);await control(operation);await readOnly('verified session invalidation after '+operation,async()=>{await denied('/me',undefined,401,'Existing verified session rechecks current email/import evidence',{cookie:session.cookie});check((await stats()).sessions===0,'Changed proof also removes its existing session');});await control('worker-restore');}
 await freshWindow();const beforeRestart=await control('snapshot');same(beforeRestart,baseline,'Login verification and restored fixture faults leave all persistent tables equal to setup');phase='cold restart setup';const pending=await begin(),pendingCode=latest().code;await stop();const offline=JSON.parse((await run(java,[...options(true),'com.training.IntegrationLoginVerificationHttpFixture','inspect'],{cwd:repo,env,timeout:20000,maxBuffer:65536})).stdout.trim());same(offline,baseline,'Independent stopped-database inspection confirms zero persistent login writes');launchMode='required';await boot(true);
 await readOnly('cold restart discards pending proof and permits fresh verified login',async()=>{await denied('/login/email/verify',verifyBody(pending,pendingCode),401,'Challenges do not survive a process restart');check((await stats()).sessions===0,'Cold startup restores no authenticated sessions');const c=await begin(),session=await complete(c,latest().code);await logout(session);});
 await stop();sender='none';await boot(true);await readOnly('required deployment without sender fails closed',async()=>{await denied('/login',loginBody('worker'),503,'No installed transport means no email verification fallback');check((await stats()).mail_count===0&&(await stats()).sessions===0,'Required no-sender mode neither sends nor creates a session');});const final=await control('snapshot');same(final,baseline,'All login modes and restart checks preserve original data');fs.writeFileSync(path.join(own,'database-invariants.json'),JSON.stringify({baseline,before_restart:beforeRestart,final,read_phases:readEvidence},null,2),{mode:0o600});return {read_only_phases:readEvidence.length,tables_per_read_phase:Object.keys(final).length,persistent_tables_unchanged:Object.keys(final).length,synthetic_imported_accounts:7,sender_network_calls:0};
}
let evidence;runChecks().then(value=>{evidence=value;}).catch(error=>{fatal=String(error.message||error).replaceAll(password,'[redacted]');process.exitCode=1;}).finally(async()=>{await stop();const stopped=servicePids.every(pid=>{try{process.kill(pid,0);return false;}catch(e){return e.code==='ESRCH';}});check(stopped,'Every isolated login-verification Main process stopped');const summary={suite:'login-verification-http',checks,failures,...(fatal?{error:fatal}:{}),...(evidence||{}),server_processes_stopped:stopped,production_touched:false,notifications_sent:false,artifacts:own};fs.writeFileSync(path.join(own,'result.json'),JSON.stringify(summary,null,2),{mode:0o600});console.log(JSON.stringify(summary));if(failures.length||fatal)process.exitCode=1;});
