'use strict';
// Existing teacher page, modal, forms and tables; synthetic transport only.
const fs = require('node:fs'), path = require('node:path'), vm = require('node:vm'), assert = require('node:assert/strict');
const base = fs.readFileSync(path.join(__dirname, 'IntegrationDeliveryCatalogUI.test.cjs'), 'utf8');
const support = vm.runInNewContext(base.slice(0, base.indexOf('\n(async () => {')) + '\n({ harness, NodeStub, setModules: value => modules=value });', { require, __dirname, console, structuredClone, AbortController, DOMException, URL, URLSearchParams, Buffer, setImmediate });
support.NodeStub.prototype.replaceChildren = function (...nodes) { this.innerHTML = ''; this.append(...nodes); };
const dataKey = key => key.slice(5).replace(/-([a-z])/g, (_, c) => c.toUpperCase());
support.NodeStub.prototype.getAttribute = function(key) { return key.startsWith('data-') && Object.hasOwn(this.dataset, dataKey(key)) ? this.dataset[dataKey(key)] : this.attributes[key] ?? null; };
support.NodeStub.prototype.hasAttribute = function(key) { return this.getAttribute(key) !== null; };
const read = name => fs.readFileSync(path.join(__dirname, '../web/modules/course-catalog', name), 'utf8');
const data = value => 'data:text/javascript;base64,' + Buffer.from(value).toString('base64');
const deferred = () => { let resolve; const promise = new Promise(yes => { resolve = yes; }); return { promise, resolve }; };
const tick = () => new Promise(yes => setImmediate(yes));
let checks = 0;
const check = (yes, label) => { assert.ok(yes, label); checks++; };
const equal = (a,b,label) => { assert.deepEqual(JSON.parse(JSON.stringify(a)),b,label); checks++; };
const empty = () => ({ added: [], updated: [], removed: [] });
function fixture(count=2, version=1) { return { scope_id:1, organization_code:'SYNTHETIC', version, catalog_version:version?'original-v1':null, courses:Array.from({length:count},(_,i)=>({course_code:'SYN-'+i,course_name:'SYNTHETIC 课程 '+i,active:true})), retained_counts:{teachers:version?2:0,certifications:version?2:0,bindings:version?2:0},can_manage:true }; }
function preview(current, body) { const old=new Map(current.courses.map(row=>[row.course_code,row])); return {schema_version:'m04_preview_v1',scope_id:1,organization_code:'SYNTHETIC',current_version:current.version,catalog_version:body.catalog_version,ready:true,issues:[],counts:{courses:body.courses.length,teachers:current.retained_counts.teachers,certifications:current.retained_counts.certifications},data:{schema_version:'m04_catalog_v1',catalog_version:body.catalog_version,courses:body.courses,teachers:[],certifications:[]},batch_id:'10000000-0000-0000-0000-000000000001',confirmation_required:true,changes:{courses:{added:body.courses.filter(r=>!old.has(r.course_code)).map(r=>r.course_code),updated:body.courses.filter(r=>old.has(r.course_code)&&JSON.stringify(old.get(r.course_code))!==JSON.stringify(r)).map(r=>r.course_code),removed:[]},teachers:empty(),certifications:empty(),bindings:empty()}}; }
function harness({current=fixture(),readAccess=true,manage=true,override}={}) {
  let stored=structuredClone(current),pending=null,invalidations=0;
  const h=support.harness({page:'teachers',scopes:[{scope_id:1,organization_code:'SYNTHETIC',can_read:readAccess,can_manage:manage},{scope_id:2,organization_code:'SECOND',can_read:true,can_manage:false}],fetchOverride:(url,opts,normal,respond)=>{
    const fallback=()=>{
      if(url.endsWith('/1/course-management'))return respond(stored);
      if(url.endsWith('/1/courses-preview')) { const body=JSON.parse(opts.body);pending=preview(stored,body);return respond(pending); }
      if(url.endsWith('/1/confirm')) { const body=JSON.parse(opts.body);if(stored.version===current.version) stored={...stored,version:stored.version+1,catalog_version:pending.catalog_version,courses:pending.data.courses};return respond({status:'CONFIRMED',scope_id:1,batch_id:body.batch_id,version:stored.version,current_version:stored.version,changes:pending.changes}); }
      if(url==='/api/course-catalog/scopes/1')return respond({scope_id:1,organization_code:'SYNTHETIC',version:stored.version,status:stored.version?'READY':'NOT_CONFIGURED',catalog:{catalog_version:stored.catalog_version,courses:stored.courses,teachers:[],certifications:[]},bindings:[]});
      if(url==='/api/course-catalog/scopes/2')return respond({scope_id:2,version:0,status:'NOT_CONFIGURED'});
      return normal(url,opts);
    };return override?override(url,opts,fallback,respond):fallback();
  }});
  h.sandbox.invalidateTeacherRecommendations=()=>invalidations++;
  h.open=async()=>{await h.mount();await h.content.querySelector('#teacher-course-catalog').onclick();await h.select(1);};
  h.select=async id=>{const f=h.modal().querySelector('[data-k="scope_id"]');f.value=String(id);await h.emit(f,'change');};
  h.node=selector=>h.modal()?.querySelector(selector);
  h.mButton=action=>h.node('[data-maintenance-action="'+action+'"]');
  h.mClick=async action=>{const button=h.mButton(action);assert.ok(button&&!button.disabled,action+' available');await h.emit(button,'click');};
  h.mEdit=async(field,value,row)=>{const f=h.node('[data-maintenance-field="'+field+'"]'+(row===undefined?'':'[data-row="'+row+'"]'));assert.ok(f&&!f.disabled,'editable '+field);f.value=String(value);await h.emit(f,field==='active'?'change':'input');};
  h.notice=()=>h.node('[data-maintenance-notice]')?.textContent||'';
  h.prepare=async()=>{await h.mEdit('course_name','SYNTHETIC 修改',0);await h.mEdit('catalog_version','new-v2');await h.mEdit('change_comment','SYNTHETIC 修改说明');};
  h.requests=suffix=>h.calls.filter(call=>call.url.endsWith(suffix));h.invalidations=()=>invalidations;return h;
}
(async()=>{
  support.setModules({catalog:await import(data(read('index.js').replace("'/modules/course-catalog/course-maintenance.js?v=20260923certmaintenance2'",JSON.stringify(data(read('course-maintenance.js'))))))});
  const h=harness({current:fixture(25)});await h.open();check(h.node('[data-course-maintenance]')&&h.node('[data-catalog-form="query"]'),'Read/manage retains qualification and adds localized maintenance');check(h.mButton('preview').disabled,'No change cannot preview');check(h.node('[data-maintenance-field="course_code"][data-row="0"]').disabled,'Existing code immutable');equal(h.node('[data-course-maintenance]').querySelectorAll('[data-maintenance-field="course_name"]').length,20,'Editable list paginates 20 rows');await h.prepare();await h.mClick('next');await h.mEdit('course_name','第二页修改',20);await h.mClick('previous');equal(h.node('[data-maintenance-field="course_name"][data-row="0"]').value,'SYNTHETIC 修改','Draft survives page change');equal(h.posts().length,0,'Typing and pagination never create batches');await h.mClick('preview');equal(h.requests('/courses-preview').length,1,'Explicit preview creates one batch');const body=JSON.parse(h.requests('/courses-preview')[0].opts.body);equal(Object.keys(body).sort(),['catalog_version','change_comment','courses','expected_version'],'Only course maintenance keys submitted');equal(body.courses[20].course_name,'第二页修改','Complete cross-page draft submitted');check(h.node('[data-course-maintenance]').textContent.includes('保存前')&&h.node('[data-course-maintenance]').textContent.includes('确认后'),'Business before/after table displayed');equal(h.requests('/confirm').length,0,'Preview does not confirm');await h.mEdit('change_comment','修订说明');check(h.mButton('confirm').disabled,'Any edit invalidates old confirmation');await h.mClick('preview');const mask=h.modal();await h.mClick('confirm');check(h.modal()===mask&&h.notice().includes('已保存'),'Confirmed save retains original modal');equal(h.requests('/course-management').length,2,'Confirmed save rereads management');equal(h.requests('/scopes/1').length,2,'Read-capable save refreshes original directory');equal(h.invalidations(),1,'Confirmed save invalidates recommendation cache once');check(h.mButton('preview').disabled&&h.mButton('confirm').disabled,'Saved form starts clean');
  const write=harness({readAccess:false,current:fixture(0,0)});await write.open();equal(write.requests('/scopes/1').length,0,'Manage-only never reads protected directory');check(!write.node('[data-catalog-form="query"]'),'Manage-only never presents qualification');await write.mClick('add');await write.mEdit('course_code','0001',0);await write.mEdit('course_name','首门课程',0);await write.mEdit('catalog_version','first');await write.mEdit('change_comment','建立首门课程');await write.mClick('preview');await write.mClick('confirm');check(write.notice().includes('已保存'),'Authorized zero version can create first course');equal(write.requests('/scopes/1').length,0,'Manage-only success still does not read directory');
  const readonly=harness({manage:false});await readonly.open();check(!readonly.node('[data-course-maintenance]'),'Read-only cannot manage');equal(readonly.requests('/course-management').length,0,'Read-only sends no management request');
  const emptyCourses=harness({current:fixture(0)});await emptyCourses.open();check(emptyCourses.node('[data-course-maintenance]').textContent.includes('保留 2 位师资'),'Nonzero empty courses preserves retained metadata');
  const guarded=harness();await guarded.open();await guarded.prepare();await guarded.select(2);equal(guarded.requests('/scopes/2').length,0,'Unsaved switch waits for inline decision');await guarded.mClick('stay');equal(guarded.node('[data-maintenance-field="course_name"]').value,'SYNTHETIC 修改','Stay preserves draft');check(guarded.sandbox.closeModal()===false&&guarded.modal(),'Original modal close uses inline guard');await guarded.mClick('discard');check(!guarded.modal(),'Explicit discard closes original modal without native confirm');
  const scope=harness();await scope.open();await scope.prepare();await scope.select(2);await scope.mClick('discard');equal(scope.requests('/scopes/2').length,1,'Explicit discard switches scope');check(!scope.node('[data-course-maintenance]'),'Scope switch clears prior management');
  const attack=harness();await attack.open();await attack.mEdit('course_name','<img src=x onerror=alert(1)>',0);await attack.mEdit('catalog_version','safe');await attack.mEdit('change_comment','安全文字');await attack.mClick('preview');check(!attack.node('[data-course-maintenance]').querySelector('img,script')&&attack.node('[data-course-maintenance]').textContent.includes('<img'),'Course names are inert in before/after');
  const warning=harness({override:(url,opts,normal,respond)=>{if(url.endsWith('/courses-preview')){const p=preview(fixture(),JSON.parse(opts.body));p.issues=[{severity:'warning',message:'保留认证未知'}];return respond(p);}return normal();}});await warning.open();await warning.prepare();await warning.mClick('preview');check(!warning.mButton('confirm').disabled&&warning.node('[data-course-maintenance]').textContent.includes('保留认证未知'),'Server warnings preserve ready preview and remain visible');
  for(const mutate of [p=>p.scope_id=2,p=>p.organization_code='OTHER',p=>p.current_version=99,p=>p.batch_id='not-uuid',p=>p.changes.teachers.added=['private'],p=>p.changes.certifications.updated=['private'],p=>p.changes.bindings.removed=['private'],p=>p.changes.courses.removed=['SYN-0'],p=>p.data.courses[0].course_name='OTHER',p=>p.counts.teachers=0]) {const bad=harness({override:(url,opts,normal,respond)=>{if(url.endsWith('/courses-preview')){const p=preview(fixture(),JSON.parse(opts.body));mutate(p);return respond(p);}return normal();}});await bad.open();await bad.prepare();await bad.mClick('preview');check(bad.mButton('confirm').disabled&&!bad.notice().includes('尚未生效'),'Malformed or noncourse-changing preview cannot confirm');}
  const invalid=harness({override:(url,opts,normal,respond)=>{if(url.endsWith('/courses-preview')){const p=preview(fixture(),JSON.parse(opts.body));return respond({...p,ready:false,data:null,changes:null,batch_id:null,confirmation_required:false,issues:[{message:'课程编码重复'}]});}return normal();}});await invalid.open();await invalid.prepare();await invalid.mClick('preview');check(invalid.mButton('confirm').disabled&&invalid.node('[data-course-maintenance]').textContent.includes('课程编码重复'),'Invalid preview displays issues without a batch');
  for(const status of [401,403,409]){const rejected=harness({override:(url,opts,normal,respond)=>url.endsWith('/courses-preview')?respond(null,status):normal()});await rejected.open();await rejected.prepare();await rejected.mClick('preview');check(!rejected.node('[data-maintenance-field]'),'Authorization/CAS '+status+' clears obsolete values');equal(rejected.requests('/courses-preview').length,1,'No automatic rebase '+status);}
  let attempt=0;const unknown=harness({override:(url,opts,normal)=>url.endsWith('/confirm')&&++attempt===1?Promise.reject(Error('网络连接失败')):normal()});await unknown.open();await unknown.prepare();await unknown.mClick('preview');await unknown.mClick('confirm');check(unknown.notice().includes('尚未确认')&&unknown.mButton('preview').disabled&&!unknown.mButton('confirm').disabled,'Unknown confirmation freezes draft and keeps explicit same-batch retry');await unknown.mClick('confirm');equal(unknown.requests('/confirm').map(r=>JSON.parse(r.opts.body).batch_id),['10000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001'],'Unknown outcome retries exact batch');equal(unknown.requests('/courses-preview').length,1,'Retry never creates another batch');
  let saved=false;const refreshFail=harness({override:async(url,opts,normal,respond)=>{if(saved&&url.endsWith('/course-management'))return respond(null,503);const r=await normal();if(url.endsWith('/confirm'))saved=true;return r;}});await refreshFail.open();await refreshFail.prepare();await refreshFail.mClick('preview');await refreshFail.mClick('confirm');check(refreshFail.notice().includes('已保存，当前列表刷新失败')&&refreshFail.mButton('confirm').disabled,'Known success remains explicit when refresh fails');equal(refreshFail.invalidations(),1,'Known save invalidates host even if refresh fails');
  const gate=deferred(),late=harness({override:(url,opts,normal)=>url.endsWith('/courses-preview')?gate.promise:normal()});await late.open();await late.prepare();const pending=late.mClick('preview');await tick();late.leave();gate.resolve({status:200,text:async()=>JSON.stringify({code:0,data:preview(fixture(),JSON.parse(late.requests('/courses-preview')[0].opts.body))})});await pending;check(!late.modal()&&late.requests('/courses-preview')[0].opts.signal.aborted,'Route cleanup aborts and ignores late batch');
  const d=deferred();const double=harness({override:(url,opts,normal)=>url.endsWith('/courses-preview')?d.promise.then(normal):normal()});await double.open();await double.prepare();const savingPreview=double.mClick('preview');await tick();await double.emit(double.mButton('preview'),'click');equal(double.requests('/courses-preview').length,1,'Double preview click is locked');d.resolve();await savingPreview;
  const identity=harness();await identity.open();await identity.prepare();identity.sandbox.state.user={uid:99,role:'admin'};await identity.emit(identity.mButton('preview'),'click');equal(identity.requests('/courses-preview').length,0,'Changed identity cannot submit old draft');check(!identity.node('[data-course-maintenance]'),'Changed identity clears owned maintenance');
  let committedUnknown=false;const refreshUnknown=harness({override:async(url,opts,normal)=>{const response=await normal();if(url.endsWith('/confirm')){committedUnknown=true;throw Error('网络连接失败');}return response;}});await refreshUnknown.open();await refreshUnknown.prepare();await refreshUnknown.mClick('preview');await refreshUnknown.mClick('confirm');check(committedUnknown&&!refreshUnknown.node('[data-catalog-form="query"]'),'Sending confirmation clears previous read/qualification even if receipt is lost');equal(refreshUnknown.invalidations(),1,'Unknown confirmation immediately invalidates host recommendation cache');await refreshUnknown.mClick('refresh');await refreshUnknown.mClick('discard');check(refreshUnknown.notice().includes('修改课程后')&&!refreshUnknown.node('[data-catalog-form="query"]'),'Explicit unknown-result refresh cannot revive old qualification');equal(refreshUnknown.node('[data-maintenance-field="course_name"]').value,'SYNTHETIC 修改','Unknown-result refresh reads committed course');
  const staleRead=deferred();let readonlyCalls=0;const racing=harness({override:(url,opts,normal,respond)=>url==='/api/course-catalog/scopes/1'&&++readonlyCalls===1?staleRead.promise.then(respond):normal()});const opening=racing.open();for(let i=0;i<20&&!racing.node('[data-maintenance-field="course_name"]');i++)await tick();await racing.prepare();await racing.mClick('preview');await racing.mClick('confirm');check(racing.node('[data-catalog-form="query"]'),'Latest saved read exists before old request returns');staleRead.resolve({scope_id:1,organization_code:'SYNTHETIC',version:1,status:'READY',catalog:{catalog_version:'OLD',courses:[{course_code:'STALE',course_name:'STALE OLD CATALOG',active:true}],teachers:[],certifications:[]},bindings:[]});await opening;check(!racing.modal().textContent.includes('STALE OLD CATALOG')&&racing.modal().textContent.includes('目录版本：2'),'Independent read ticket rejects initial old directory after newer save');check(racing.requests('/scopes/1')[0].opts.signal.aborted,'Confirming aborts original directory transport');
  console.log(JSON.stringify({ok:true,suite:'original course maintenance',checks,transport:'synthetic',browser:false,database:false}));
})().catch(error=>{console.error(error);process.exitCode=1;});
