import { tmpdir as testTmpdir } from 'node:os';
import { chromium } from 'playwright';
import { writeFile, readFile, mkdir, mkdtemp, realpath, access, rename } from 'node:fs/promises';
import { createServer } from 'node:net';
import { spawn } from 'node:child_process';
import { dirname, resolve, join, delimiter, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes, randomUUID } from 'node:crypto';
import assert from 'node:assert/strict';
// Actual original SPA + real Main. Only the isolated fixture's private synthetic mailbox is read.
const app=resolve(dirname(fileURLToPath(import.meta.url)),'..'),args={};
for(let i=2;i<process.argv.length;i+=2){assert.ok(['--java','--classes','--overlay'].includes(process.argv[i])&&process.argv[i+1]);args[process.argv[i]]=process.argv[i+1];}
assert.ok(args['--java']&&args['--classes']);const classes=await realpath(args['--classes']),overlay=args['--overlay']?await realpath(args['--overlay']):null;
for(const dir of [classes,overlay].filter(Boolean))assert.ok(dir!==app&&!dir.startsWith(app+sep));
await access(join(classes,'com/training/Main.class'));await access(join(overlay||classes,'com/training/IntegrationLoginVerificationHttpFixture.class'));
const own=await mkdtemp(join(testTmpdir(), 'yanxu-login-verification-http-browser-')),password=randomBytes(24).toString('hex'),classpath=[overlay,classes,join(app,'lib','*')].filter(Boolean).join(delimiter);
let browser,child,base,fixture,error=null,checks=0,log='';const screenshots=[],browserErrors=[],outsideRequests=[],responses=[],privateConsoleLeaks=[],contexts=new Set();
const pause=ms=>new Promise(yes=>setTimeout(yes,ms));const check=(yes,label)=>{assert.ok(yes,label);checks++;};const equal=(a,b,label)=>{assert.deepEqual(a,b,label);checks++;};
async function control(operation,more={}){const nonce=randomUUID();await writeFile(join(own,'control-request.json.next'),JSON.stringify({nonce,operation,...more}));await rename(join(own,'control-request.json.next'),join(own,'control-request.json'));for(let i=0;i<150;i++){try{const r=JSON.parse(await readFile(join(own,'control-result.json'),'utf8'));if(r.nonce===nonce){assert.equal(r.ok,true,'Synthetic fixture control failed');return r.data;}}catch{}await pause(20);}throw Error('Synthetic fixture control timed out: '+operation);}
async function boot(width){await writeFile(join(own,'control-request.json'),'{}');const data=join(own,'data-'+width);await mkdir(data);const listener=createServer();await new Promise(yes=>listener.listen(0,'127.0.0.1',yes));const port=listener.address().port;await new Promise(yes=>listener.close(yes));base='http://127.0.0.1:'+port;
 child=spawn(args['--java'],['-Dbind.address=127.0.0.1','-Dbootstrap.demo=false','-Dbootstrap.admin.password='+password,'-Ddata.dir='+data,'-Dlogin.email.mode=required','-Dintegration.login.verification.root='+own,'-Dsemantic.port=','-Dsemantic.token=','-cp',classpath,'com.training.IntegrationLoginVerificationHttpFixture',String(port)],{cwd:app,env:{...process.env,YANXU_SEMANTIC_PORT:'',YANXU_SEMANTIC_TOKEN:''},stdio:['ignore','pipe','pipe']});child.stdout.on('data',b=>log=(log+b).slice(-24000));child.stderr.on('data',b=>log=(log+b).slice(-24000));let failure;child.once('error',e=>failure=e);
 for(let i=0;i<200;i++){if(failure)throw failure;if(child.exitCode!==null)throw Error('Synthetic Main exited during startup');try{const r=await fetch(base+'/',{signal:AbortSignal.timeout(1000)});if(r.ok){fixture=JSON.parse(await readFile(join(own,'fixture.json'),'utf8'));return;}}catch{}await pause(100);}throw Error('Synthetic Main not ready');}
async function stop(){if(!child||child.exitCode!==null||child.signalCode!==null)return;await new Promise(yes=>{const timer=setTimeout(()=>child.kill('SIGKILL'),2500);child.once('exit',()=>{clearTimeout(timer);yes();});child.kill('SIGTERM');});}
async function createContext(width){const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce',deviceScaleFactor:1});contexts.add(context);await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin===base){if(u.pathname==='/api/visitor-context')return route.abort();return route.continue();}if(u.protocol==='data:')return route.continue();outsideRequests.push(u.origin);return route.abort();});const page=await context.newPage();page.setDefaultTimeout(12000);await page.clock.install({time:(await control('stats')).clock});page.on('pageerror',e=>browserErrors.push(String(e)));page.on('dialog',async d=>{browserErrors.push('native dialog '+d.type());await d.dismiss();});page.on('console',m=>{if(m.text().includes(password)||m.text().includes('@example.test'))privateConsoleLeaks.push('Sensitive console text');});page.on('response',r=>{const path=new URL(r.url()).pathname;if(path.startsWith('/api/')&&r.status()>=400)responses.push({width,path,status:r.status()});});await page.goto(base+'/');await page.locator('#login-user').waitFor();return{context,page};}
async function noOverflow(page,label){const dims=await page.evaluate(()=>({viewport:innerWidth,page:document.documentElement.scrollWidth,panels:[...document.querySelectorAll('#login-form,.login-card,#login-email-actions')].filter(n=>n.clientWidth).map(n=>[n.clientWidth,n.scrollWidth])}));check(dims.page<=dims.viewport+1&&dims.panels.every(([a,b])=>b<=a+1),label+': '+JSON.stringify(dims));}
async function shot(page,name){await page.locator('#login-form').scrollIntoViewIfNeeded();const path=join(own,name+'.png');await page.screenshot({path,fullPage:false,animations:'disabled'});screenshots.push(path);}
async function advance(page,millis){await control('advance',{millis});await page.clock.fastForward(millis);}
async function freshTime(page){await advance(page,3600001);}
async function start(page,name='worker'){await page.locator('#login-user').fill('synthetic-login-'+name);await page.locator('#login-pwd').fill(password);const waiting=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/login'&&r.request().method()==='POST');await page.locator('#login-btn').click();const response=await waiting;equal(response.status(),200,'Actual password accepted without authentication');const data=(await response.json()).data;check(data.status==='EMAIL_REQUIRED'&&/^[a-f0-9]{64}$/.test(data.challenge_id),'Actual challenge returned');equal(data.masked_email,'***@***','Generic email mask');check(!Object.hasOwn(data,'token')&&!Object.hasOwn(data,'user'),'Challenge carries no authenticated user or token');await page.locator('#login-email-step').waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('#login-btn')?.disabled===false);return data;}
async function codeFor(name='worker'){const box=JSON.parse(await readFile(join(own,'mailbox.json'),'utf8'));const item=box.filter(r=>r.email===name+'@example.test').at(-1);assert.ok(item&&/^\d{6}$/.test(item.code),'Synthetic mailbox has a six digit code');check(item.held_lock===false,'Sender runs outside business lock');return item.code;}
async function verifyCode(page,code,status=200){await page.locator('#login-code').fill(code);const pending=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/login/email/verify');await page.locator('#login-btn').click();const r=await pending;equal(r.status(),status,'Actual verification result');return r;}
async function anonymous(context){equal((await context.request.get(base+'/api/me')).status(),401,'Password challenge does not grant a cookie session');}
async function privacy(page,challenge){const data=await page.evaluate(()=>({stored:[...Object.entries(localStorage),...Object.entries(sessionStorage)],url:location.href,text:document.body.textContent,pwd:document.querySelector('#login-pwd')?.value,code:document.querySelector('#login-code')?.value}));check(!JSON.stringify(data.stored).includes(password)&&!JSON.stringify(data.stored).includes(challenge.challenge_id)&&!JSON.stringify(data.stored).includes('code'),'No password, challenge or code persisted');check(!data.url.includes(challenge.challenge_id)&&!data.url.includes(password),'No secrets in location');check(!data.text.includes(challenge.challenge_id)&&!data.text.includes('@example.test'),'No challenge or unmasked email in DOM');equal(data.pwd,'','Password input cleared');}
async function logout(context,page){equal((await context.request.post(base+'/api/logout',{data:{}})).status(),200,'Explicit test session cleanup');await page.goto(base+'/');await page.locator('#login-user').waitFor();}
async function mainCase(width){const {context,page}=await createContext(width);try{
 check(await page.locator('#pwd-toggle').isVisible()&&await page.locator('#login-pwd').isVisible(),'Original login fields and password toggle');equal(await page.locator('#login-email-step').isVisible(),false,'Verification initially hidden');check(!(await page.locator('#login-form').textContent()).includes('记住设备'),'No remembered-device option');await noOverflow(page,'password '+width);await shot(page,'login-password-'+width);
 let challenge=await start(page);await anonymous(context);await privacy(page,challenge);check(await page.locator('#login-resend').isDisabled(),'Resend starts with server cooldown');check((await page.locator('#login-code-time').textContent()).includes('分'),'Chinese expiry countdown');await noOverflow(page,'verification '+width);await shot(page,'login-verification-'+width);
 const firstCode=await codeFor(),wrong=firstCode==='000000'?'111111':'000000';await verifyCode(page,wrong,400);await page.getByText('验证码不正确或格式有误，请重新填写。',{exact:true}).waitFor();check(await page.locator('#login-email-step').isVisible(),'Wrong code stays in verification panel');equal(await page.locator('#login-code').inputValue(),'','Wrong code cleared');await anonymous(context);
 const stats=await control('stats'),millis=Math.max(1,Date.parse(challenge.resend_after)-stats.clock+1);await advance(page,millis);await page.waitForFunction(()=>document.querySelector('#login-resend')?.disabled===false);const pendingResend=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/login/email/resend');await page.locator('#login-resend').click();const resent=await pendingResend;equal(resent.status(),200,'Actual resend succeeds after absolute cooldown');const next=(await resent.json()).data;check(next.challenge_id!==challenge.challenge_id,'Resend rotates challenge');equal((await context.request.post(base+'/api/login/email/verify',{data:{challenge_id:challenge.challenge_id,code:firstCode}})).status(),401,'Old challenge invalid after resend');challenge=next;await page.waitForFunction(()=>document.querySelector('#login-btn')?.disabled===false);await privacy(page,challenge);
 await verifyCode(page,await codeFor());await page.locator('#login-form').waitFor({state:'detached'});const me=(await (await context.request.get(base+'/api/me')).json()).data;equal(me.username,'synthetic-login-worker','Workspace and cookie belong to verified worker');const stored=await page.evaluate(()=>Object.entries(localStorage));equal(stored,[['yx_last_username','synthetic-login-worker']],'Only original username hint persists after success');
 if(width===1280){
  await logout(context,page);await freshTime(page);const cancelled=await start(page);const old=await codeFor();const cancelledResponse=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/login/email/cancel');await page.locator('#login-back').click();equal((await cancelledResponse).status(),200,'Back cancels actual owned challenge');check(await page.locator('#login-pwd').isVisible()&&await page.locator('#login-email-hint').textContent()==='','Back clears private challenge display');equal((await context.request.post(base+'/api/login/email/verify',{data:{challenge_id:cancelled.challenge_id,code:old}})).status(),401,'Cancelled challenge rejected');await anonymous(context);
  await freshTime(page);await start(page);const lastCode=await codeFor();for(let i=0;i<5;i++){await verifyCode(page,lastCode==='000000'?'111111':'000000',i===4?401:400);if(i<4)await page.waitForFunction(()=>document.querySelector('#login-btn')?.disabled===false);}await page.locator('#login-password-step').waitFor({state:'visible'});check((await page.locator('#login-err').textContent()).includes('已失效'),'Fifth wrong code returns to credentials');equal(await page.locator('#login-code').inputValue(),'','Exhausted attempt clears code');
  await freshTime(page);const expired=await start(page);const expiryCode=await codeFor();await advance(page,Date.parse(expired.expires_at)-(await control('stats')).clock+1);check((await page.locator('#login-code-time').textContent()).includes('可能已过期'),'Expiry is shown without fabricating authentication');await verifyCode(page,expiryCode,401);await page.locator('#login-password-step').waitFor({state:'visible'});
  await freshTime(page);await control('sender-fail');await page.locator('#login-user').fill('synthetic-login-worker');await page.locator('#login-pwd').fill(password);let unavailable=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/login');await page.locator('#login-btn').click();equal((await unavailable).status(),503,'Sender failure returns real 503');await page.getByText('登录服务暂不可用，请稍后重试。',{exact:true}).waitFor();check(await page.locator('#login-password-step').isVisible(),'Unavailable sender keeps credential step');await control('sender-normal');
  await freshTime(page);await start(page);await control('worker-disable');await verifyCode(page,await codeFor(),401);await page.locator('#login-password-step').waitFor({state:'visible'});await control('worker-restore');check((await page.locator('#login-email-hint').textContent())==='','Changed account clears challenge display');
  await freshTime(page);await start(page);const pendingCode=await codeFor();let release,intercepted=false;const gate=new Promise(yes=>release=yes);await page.route('**/api/login/email/verify',async route=>{const actual=await route.fetch();equal(actual.status(),200,'Delayed receipt is a real verification transaction');intercepted=true;await gate;try{await route.fulfill({response:actual});}catch{}});await page.locator('#login-code').fill(pendingCode);await page.locator('#login-btn').click();for(let i=0;!intercepted&&i<100;i++)await pause(20);check(intercepted,'Real verify receipt held');check(await page.locator('#login-back').isDisabled()&&await page.locator('#login-btn').isDisabled(),'Pending verify prevents back/new-login identity race');await page.locator('#login-back').evaluate(n=>n.click());check(await page.locator('#login-email-step').isVisible(),'Disabled back cannot return to new credentials');release();await page.locator('#login-form').waitFor({state:'detached'});await page.unroute('**/api/login/email/verify');equal((await (await context.request.get(base+'/api/me')).json()).data.username,'synthetic-login-worker','Late verified cookie matches original displayed account');
  await logout(context,page);await freshTime(page);await start(page);await advance(page,60001);let releaseResend,resentHeld=false;const resendGate=new Promise(yes=>releaseResend=yes);await page.route('**/api/login/email/resend',async route=>{const actual=await route.fetch();equal(actual.status(),200,'Delayed resend is actual server output');resentHeld=true;await resendGate;try{await route.fulfill({response:actual});}catch{}});await page.locator('#login-resend').click();for(let i=0;!resentHeld&&i<100;i++)await pause(20);check(resentHeld,'Real resend response held');await page.locator('#login-back').click();await page.locator('#login-password-step').waitFor({state:'visible'});await freshTime(page);const second=await start(page,'second');releaseResend();await pause(80);await privacy(page,second);equal(await page.locator('#login-user').inputValue(),'synthetic-login-second','Late resend does not replace second account');await page.unroute('**/api/login/email/resend');await verifyCode(page,await codeFor('second'));await page.locator('#login-form').waitFor({state:'detached'});equal((await (await context.request.get(base+'/api/me')).json()).data.username,'synthetic-login-second','Only second challenge signs in second account');
  await logout(context,page);await control('mode-legacy');await page.locator('#login-user').fill('synthetic-login-worker');await page.locator('#login-pwd').fill(password);const legacyResponse=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/login');await page.locator('#login-btn').click();const legacy=await legacyResponse;equal(legacy.status(),200,'Legacy mode still accepts password');const value=(await legacy.json()).data;check(!!value.token&&value.user.username==='synthetic-login-worker'&&!value.status,'Real legacy response retained');await page.locator('#login-form').waitFor({state:'detached'});await control('mode-required');
 }
 const statsEnd=await control('stats');equal(statsEnd.sender_lock_violations,0,'No sender call under mutation lock');
 }finally{await context.close();contexts.delete(context);}}
try{browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || undefined,headless:true});for(const width of [1280,390,320]){await boot(width);await mainCase(width);await stop();}equal(browserErrors,[],'No browser errors or native dialogs');equal(privateConsoleLeaks,[],'No sensitive console output');equal(outsideRequests,[],'No outside requests');}catch(e){error=e;}finally{for(const context of contexts)await context.close().catch(()=>{});await browser?.close();await stop();await writeFile(join(own,'server.log'),log.replaceAll(password,'[synthetic password redacted]'),{mode:0o600});const result={ok:!error,checks,classes,overlay,temporaryDirectory:own,screenshots,browserErrors,privateConsoleLeaks,outsideRequests,expectedAuthenticationResponses:responses,temporaryServiceStopped:!child||child.exitCode!==null||child.signalCode!==null,browserClosed:true,...(error?{error:error.stack||String(error)}:{})};await writeFile(join(own,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));}if(error)process.exitCode=1;
