'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const base=fs.readFileSync(path.join(__dirname,'IntegrationCourseMaintenanceUI.test.cjs'),'utf8');
const shared=vm.runInNewContext(base.slice(0,base.indexOf('function fixture('))+'\n({support,read,data,deferred,tick});',{require,__dirname,console,structuredClone,AbortController,DOMException,URL,URLSearchParams,Buffer,setImmediate});
const {support,read,data,deferred,tick}=shared;let checks=0;const check=(yes,label)=>{assert.ok(yes,label);checks++;};const equal=(a,b,label)=>{assert.deepEqual(JSON.parse(JSON.stringify(a)),b,label);checks++;};const empty=()=>({added:[],updated:[],removed:[]});
const pair=r=>r.teacher_code+'/'+r.course_code;
function fixture(count=2,version=1){return{scope_id:1,organization_code:'SYNTHETIC',version,catalog_version:version?'original-v1':null,courses:version?[{course_code:'C1',course_name:'SYNTHETIC 具体课程',active:true},{course_code:'C2',course_name:'SYNTHETIC 停用课程',active:false}]:[],teacher_codes:version?Array.from({length:Math.max(count,25)},(_,i)=>'T'+i):[],certifications:Array.from({length:count},(_,i)=>({teacher_code:'T'+i,course_code:'C1',status:'unknown',source_ref:'',valid_from:'',valid_to:''})),retained_counts:{courses:version?2:0,teachers:version?Math.max(count,25):0,bindings:version?Math.max(count,25):0},can_manage:true};}
function preview(current,body){const original=new Map(current.certifications.map(row=>[pair(row),row]));return{schema_version:'m04_preview_v1',scope_id:1,organization_code:'SYNTHETIC',current_version:current.version,catalog_version:body.catalog_version,ready:true,issues:[],counts:{courses:current.courses.length,teachers:current.teacher_codes.length,certifications:body.certifications.length},data:{schema_version:'m04_catalog_v1',catalog_version:body.catalog_version,courses:current.courses,teachers:[],certifications:body.certifications},batch_id:'10000000-0000-0000-0000-000000000001',confirmation_required:true,changes:{courses:empty(),teachers:empty(),bindings:empty(),certifications:{added:body.certifications.filter(row=>!original.has(pair(row))).map(pair),updated:body.certifications.filter(row=>original.has(pair(row))&&JSON.stringify(original.get(pair(row)))!==JSON.stringify(row)).map(pair),removed:[]}}};}
function harness({current=fixture(),readAccess=true,manage=true,override}={}){let stored=structuredClone(current),pending,invalidations=0;const h=support.harness({page:'teachers',scopes:[{scope_id:1,organization_code:'SYNTHETIC',can_read:readAccess,can_manage:manage},{scope_id:2,organization_code:'SECOND',can_read:true,can_manage:false}],fetchOverride:(url,opts,normal,respond)=>{const fallback=()=>{
 if(url.endsWith('/course-management'))return respond({...stored,retained_counts:{teachers:stored.teacher_codes.length,certifications:stored.certifications.length,bindings:stored.retained_counts.bindings}});
 if(url.endsWith('/certification-management'))return respond(stored);
 if(url.endsWith('/courses-preview')){const body=JSON.parse(opts.body);pending=preview(stored,{...body,certifications:stored.certifications});pending.data.courses=body.courses;pending.changes.certifications=empty();pending.changes.courses={added:[],updated:[body.courses[0].course_code],removed:[]};return respond(pending);}
 if(url.endsWith('/certifications-preview')){pending=preview(stored,JSON.parse(opts.body));return respond(pending);}
 if(url.endsWith('/confirm')){if(stored.version===current.version)stored={...stored,version:stored.version+1,catalog_version:pending.catalog_version,certifications:pending.data.certifications,courses:pending.data.courses};return respond({status:'CONFIRMED',scope_id:1,batch_id:pending.batch_id,version:stored.version,current_version:stored.version,changes:pending.changes});}
 if(url==='/api/course-catalog/scopes/1')return respond({scope_id:1,organization_code:'SYNTHETIC',version:stored.version,status:stored.version?'READY':'NOT_CONFIGURED',catalog:{catalog_version:stored.catalog_version,courses:stored.courses,teachers:[],certifications:stored.certifications},bindings:[]});
 if(url==='/api/course-catalog/scopes/2')return respond({scope_id:2,version:0,status:'NOT_CONFIGURED'});return normal(url,opts);};return override?override(url,opts,fallback,respond):fallback();}});
 h.sandbox.invalidateTeacherRecommendations=()=>invalidations++;h.node=q=>h.modal()?.querySelector(q);h.mode=async kind=>h.emit(h.node('[data-catalog-action="editor:'+kind+'"]'),'click');
 h.open=async(cert=true)=>{await h.mount();await h.content.querySelector('#teacher-course-catalog').onclick();const f=h.node('[data-k="scope_id"]');f.value='1';await h.emit(f,'change');if(cert&&manage)await h.mode('certifications');};
 h.button=key=>h.node('[data-certification-action="'+key+'"]');h.clickCert=async key=>{const b=h.button(key);assert.ok(b&&!b.disabled,key);await h.emit(b,'click');};h.editCert=async(key,value,row)=>{const f=h.node('[data-certification-field="'+key+'"]'+(row===undefined?'':'[data-row="'+row+'"]'));assert.ok(f&&!f.disabled,key);f.value=value;await h.emit(f,key==='status'?'change':'input');};
 h.prepare=async()=>{await h.editCert('status','certified',0);await h.editCert('source_ref','SYNTHETIC EVIDENCE',0);await h.editCert('catalog_version','next-v2');await h.editCert('change_comment','SYNTHETIC 认定依据核对');};h.notice=()=>h.node('[data-certification-notice]')?.textContent||'';h.requests=tail=>h.calls.filter(r=>r.url.endsWith(tail));h.invalidations=()=>invalidations;return h;}
(async()=>{
 let index=read('index.js').replace("'/modules/course-catalog/course-maintenance.js?v=20260923certmaintenance2'",JSON.stringify(data(read('course-maintenance.js')))).replace("'/modules/course-catalog/certification-maintenance.js?v=20260923certmaintenance2'",JSON.stringify(data(read('certification-maintenance.js'))));support.setModules({catalog:await import(data(index))});
 const h=harness({current:fixture(25)});await h.open(false);check(h.node('[data-course-maintenance]')&&!h.node('[data-certification-maintenance]'),'Default remains course maintenance');equal(h.requests('/certification-management').length,0,'No certification read before explicit switch');await h.mode('certifications');check(!h.node('[data-course-maintenance]')&&h.node('[data-certification-maintenance]'),'Only one editor mounted');check(h.node('[data-catalog-form="query"]'),'Read-capable qualification remains');check(h.node('[data-certification-field="teacher_code"][data-row="0"]').disabled&&h.node('[data-certification-field="course_code"][data-row="0"]').disabled,'Existing pair immutable');check(h.button('preview').disabled,'No-op disabled');equal(h.node('[data-certification-maintenance]').querySelectorAll('[data-certification-field="status"]').length,20,'20 editable rows at a time');await h.prepare();await h.clickCert('next');await h.editCert('status','revoked',20);await h.clickCert('previous');equal(h.node('[data-certification-field="status"][data-row="0"]').value,'certified','Page changes retain edits');equal(h.posts().length,0,'Input and paging cause no POST');await h.clickCert('preview');equal(Object.keys(JSON.parse(h.requests('/certifications-preview')[0].opts.body)).sort(),['catalog_version','certifications','change_comment','expected_version'],'Only certification fields and CAS submitted');equal(JSON.parse(h.requests('/certifications-preview')[0].opts.body).certifications[20].status,'revoked','Full draft includes next-page edits');check(h.node('[data-certification-maintenance]').textContent.includes('有效起日：未提供'),'Empty dates stay unspecified, not permanent');check(!h.button('confirm').disabled&&h.requests('/confirm').length===0,'Separate explicit confirm required');await h.editCert('change_comment','另补说明');check(h.button('confirm').disabled,'Metadata edit invalidates preview');await h.clickCert('preview');const mask=h.modal();await h.clickCert('confirm');check(h.modal()===mask&&h.notice().includes('已保存'),'Verified save preserves original modal');equal(h.requests('/certification-management').length,2,'After save GETs latest management');equal(h.requests('/scopes/1').length,2,'After save GETs latest original read');equal(h.invalidations(),1,'Confirmation invalidates recommendations once');
 const picker=harness();await picker.open();await picker.clickCert('add');equal(picker.node('[data-certification-field="status"][data-row="2"]').value,'unknown','New state defaults unknown');equal(picker.node('[data-certification-field="valid_from"][data-row="2"]').value,'','No default date');await picker.emit(picker.node('[data-certification-pick="teacher_code:2"]'),'click');equal(picker.node('[data-certification-maintenance]').querySelectorAll('[data-certification-choice]').length,20,'Picker never renders thousands of options');await picker.clickCert('picker-next');equal(picker.node('[data-certification-maintenance]').querySelectorAll('[data-certification-choice]').length,5,'Picker retains remainder');await picker.emit(picker.node('[data-certification-choice="24"]'),'click');equal(picker.node('[data-certification-field="teacher_code"][data-row="2"]').value,'T24','Picker binds exact referenced target row');await picker.emit(picker.node('[data-certification-pick="course_code:2"]'),'click');check(picker.node('[data-certification-maintenance]').textContent.includes('停用'),'Picker labels inactive concrete courses');await picker.emit(picker.node('[data-certification-choice="1"]'),'click');equal(picker.node('[data-certification-field="course_code"][data-row="2"]').value,'C2','Inactive course remains explicit selectable historical certification subject');await picker.emit(picker.node('[data-certification-remove="2"]'),'click');equal(picker.node('[data-certification-maintenance]').querySelectorAll('[data-certification-field="status"]').length,2,'New row removable without removing existing pairs');
 const guarded=harness();await guarded.open();await guarded.prepare();await guarded.mode('courses');check(guarded.node('[data-certification-maintenance]')&&!guarded.node('[data-course-maintenance]'),'Dirty switch requires inline choice');await guarded.clickCert('stay');equal(guarded.node('[data-certification-field="source_ref"]').value,'SYNTHETIC EVIDENCE','Continue preserves draft');await guarded.mode('courses');await guarded.clickCert('discard');await tick();check(guarded.node('[data-course-maintenance]')&&!guarded.node('[data-certification-maintenance]'),'Discard mounts only next editor');
 const readOnly=harness({manage:false});await readOnly.open();check(!readOnly.node('[data-catalog-action="editor:certifications"]'),'Read-only has no management tabs');equal(readOnly.requests('/certification-management').length,0,'Read-only makes no certification management request');
 const manageOnly=harness({readAccess:false});await manageOnly.open();await manageOnly.prepare();await manageOnly.clickCert('preview');await manageOnly.clickCert('confirm');equal(manageOnly.requests('/scopes/1').length,0,'Manage-only never reads protected directory, including save');check(!manageOnly.node('[data-catalog-form="query"]'),'Manage-only has no qualify form');
 for(const f of [fixture(0,0),{...fixture(0),teacher_codes:[],retained_counts:{courses:2,teachers:0,bindings:0}},{...fixture(0),courses:[],retained_counts:{courses:0,teachers:25,bindings:25}}]){const unavailable=harness({current:f});await unavailable.open();check(unavailable.button('add').disabled&&unavailable.notice().includes('没有可配对'),'Missing current teacher/course prevents invented pairing');}
 const malicious=harness();await malicious.open();await malicious.prepare();await malicious.editCert('source_ref','<img src=x onerror=alert(1)>',0);await malicious.clickCert('preview');check(!malicious.node('[data-certification-maintenance]').querySelector('img,script')&&malicious.node('[data-certification-maintenance]').textContent.includes('<img'),'Source evidence renders as inert text');
 for(const mutate of [p=>p.scope_id=9,p=>p.current_version=9,p=>p.batch_id='bad',p=>p.changes.courses.updated=['C1'],p=>p.changes.teachers.removed=['T0'],p=>p.changes.bindings.added=['T1'],p=>p.changes.certifications.removed=['T0/C1'],p=>p.data.certifications[0].source_ref='WRONG',p=>p.data.certifications[0].teacher_code='HISTORICAL',p=>p.counts.teachers=0]){const bad=harness({override:(url,opts,normal,respond)=>{if(url.endsWith('/certifications-preview')){const p=preview(fixture(),JSON.parse(opts.body));mutate(p);return respond(p);}return normal();}});await bad.open();await bad.prepare();await bad.clickCert('preview');check(bad.button('confirm').disabled,'Invalid or noncert change cannot confirm');}
 const invalid=harness({override:(url,opts,normal,respond)=>url.endsWith('/certifications-preview')?respond({...preview(fixture(),JSON.parse(opts.body)),ready:false,data:null,changes:null,batch_id:null,confirmation_required:false,issues:[{message:'认定来源不可为空'}]}):normal()});await invalid.open();await invalid.prepare();await invalid.clickCert('preview');check(invalid.button('confirm').disabled&&invalid.node('[data-certification-maintenance]').textContent.includes('认定来源不可为空'),'Server field issues do not make batches');
 for(const status of [401,403,409]){const denied=harness({override:(url,opts,normal,respond)=>url.endsWith('/certifications-preview')?respond(null,status):normal()});await denied.open();await denied.prepare();await denied.clickCert('preview');check(!denied.node('[data-certification-field]'),'Authorization/CAS '+status+' clears old data');equal(denied.requests('/certifications-preview').length,1,'No automatic retry/rebase '+status);}
 let attempt=0;const unknown=harness({override:async(url,opts,normal)=>{const result=await normal();if(url.endsWith('/confirm')&&++attempt===1)throw Error('lost response');return result;}});await unknown.open();await unknown.prepare();await unknown.clickCert('preview');await unknown.clickCert('confirm');check(unknown.notice().includes('尚未确认')&&!unknown.node('[data-catalog-form="query"]')&&unknown.button('preview').disabled,'Unknown confirm clears original qualification and freezes new batch');await unknown.clickCert('confirm');equal(unknown.requests('/confirm').map(r=>JSON.parse(r.opts.body).batch_id),['10000000-0000-0000-0000-000000000001','10000000-0000-0000-0000-000000000001'],'Unknown confirm retries same batch');equal(unknown.requests('/certifications-preview').length,1,'No replacement batch');
 let saved=false;const failedRead=harness({override:async(url,opts,normal,respond)=>{if(saved&&url.endsWith('/certification-management'))return respond(null,503);const result=await normal();if(url.endsWith('/confirm'))saved=true;return result;}});await failedRead.open();await failedRead.prepare();await failedRead.clickCert('preview');await failedRead.clickCert('confirm');check(failedRead.notice().includes('已保存，当前列表刷新失败')&&failedRead.button('confirm').disabled,'Known success survives failed followup GET');
 const slow=deferred(),stale=harness({override:(url,opts,normal,respond)=>url.endsWith('/certification-management')?slow.promise.then(respond):normal()});await stale.open(false);const opening=stale.mode('certifications');await tick();await stale.mode('courses');await stale.clickCert('discard');await tick();slow.resolve(fixture());await opening;check(stale.node('[data-course-maintenance]')&&!stale.node('[data-certification-maintenance]'),'Late certification read cannot replace selected course editor');check(stale.requests('/certification-management')[0].opts.signal.aborted,'Mode switch aborts old certification request');
 const gate=deferred(),late=harness({override:(url,opts,normal)=>url.endsWith('/certifications-preview')?gate.promise:normal()});await late.open();await late.prepare();const pending=late.clickCert('preview');await tick();await late.emit(late.button('preview'),'click');equal(late.requests('/certifications-preview').length,1,'Duplicate preview click locked');late.leave();gate.resolve({status:200,text:async()=>JSON.stringify({code:0,data:preview(fixture(),JSON.parse(late.requests('/certifications-preview')[0].opts.body))})});await pending;check(!late.modal()&&late.requests('/certifications-preview')[0].opts.signal.aborted,'Route/close prevents stale preview');
 const changedIdentity=harness();await changedIdentity.open();await changedIdentity.prepare();changedIdentity.sandbox.state.user={uid:99,role:'admin'};await changedIdentity.emit(changedIdentity.button('preview'),'click');equal(changedIdentity.requests('/certifications-preview').length,0,'Identity change cannot submit old cert draft');check(!changedIdentity.node('[data-certification-maintenance]'),'Identity change clears certification editor');
 for(const kind of ['courses','certifications']){const delayed=deferred();let reads=0;const f=fixture(25);if(kind==='courses'){f.courses=Array.from({length:25},(_,i)=>({course_code:'C'+(i+1),course_name:'SYNTHETIC '+i,active:true}));f.retained_counts.courses=25;}const lock=harness({current:f,override:(url,opts,normal)=>url==='/api/course-catalog/scopes/1'&&++reads===2?delayed.promise.then(normal):normal()});await lock.open(kind==='certifications');const prefix=kind==='courses'?'maintenance':'certification';const button=key=>lock.node('[data-'+prefix+'-action="'+key+'"]');const edit=async(key,value,row)=>{const field=lock.node('[data-'+prefix+'-field="'+key+'"]'+(row===undefined?'':'[data-row="'+row+'"]'));field.value=value;await lock.emit(field,'input');};await edit(kind==='courses'?'course_name':'source_ref','SYNTHETIC MODIFIED',0);await edit('catalog_version','pagination-v2');await edit('change_comment','SYNTHETIC pagination lock');await lock.emit(button('next'),'click');await lock.emit(button('preview'),'click');check(!button('confirm').disabled,kind+': batch ready for controlled delayed refresh');const confirming=lock.emit(button('confirm'),'click');for(let i=0;i<20&&reads<2;i++)await tick();check(reads===2&&button('previous').disabled,kind+': confirmation followup read locks old pagination');await lock.emit(button('previous'),'click');check(button('previous').disabled,kind+': synthetic click cannot render null current snapshot');delayed.resolve();await confirming;check(lock.node('[data-'+prefix+'-notice]').textContent.includes('已保存'),kind+': delayed save completes after pagination attempt');}
 console.log(JSON.stringify({ok:true,suite:'original certification maintenance',checks,transport:'synthetic',browser:false,database:false}));
})().catch(error=>{console.error(error);process.exitCode=1;});
