'use strict';
// Original renderLogin/disposal + real verification module with synthetic DOM and transport.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const base=fs.readFileSync(path.join(__dirname,'IntegrationDeliveryCatalogUI.test.cjs'),'utf8');
const support=vm.runInNewContext(base.slice(0,base.indexOf('\n(async () => {'))+'\n({harness,NodeStub});',{require,__dirname,console,structuredClone,AbortController,DOMException,URL,URLSearchParams,Buffer,setImmediate});
const app=fs.readFileSync(path.join(__dirname,'../web/app.js'),'utf8'),moduleSource=fs.readFileSync(path.join(__dirname,'../web/modules/notifications/login-verification.js'),'utf8');
const slice=(a,b)=>app.slice(app.indexOf(a),app.indexOf(b,app.indexOf(a)));
const deferred=()=>{let resolve;const promise=new Promise(yes=>resolve=yes);return{promise,resolve};};const tick=()=>new Promise(yes=>setImmediate(yes));let checks=0;
const check=(yes,label)=>{assert.ok(yes,label);checks++;};const equal=(a,b,label)=>{assert.deepEqual(JSON.parse(JSON.stringify(a)),b,label);checks++;};
function harness({legacy=false,override,moduleGate,moduleFailure=false}={}){
 const h=support.harness(),storage=new Map([['token','OLD-UNUSED']]),intervals=new Map(),windowEvents=new Map();h.now=Date.parse('2026-09-23T08:00:00Z');h.requests=[];h.layouts=0;h.disposals=0;h.phases=[];h.nextChallenge=0;
 const root=h.document.createElement('div');root.id='app';h.body.append(root);h.root=root;
 h.field=id=>h.document.querySelector('#'+id);h.storage=storage;h.intervals=intervals;
 h.challenge=()=>({status:'EMAIL_REQUIRED',challenge_id:String(++h.nextChallenge%10).repeat(64),masked_email:'***@***',expires_at:new Date(h.now+600000).toISOString(),resend_after:new Date(h.now+60000).toISOString()});
 h.success=()=>({token:'SYNTHETIC_SESSION_ONLY',user:{uid:97,username:'synthetic-login',name:'SYNTHETIC',role:'viewer'}});
 const response=(data,status=200)=>({ok:status>=200&&status<300,status,text:async()=>JSON.stringify({code:status===200?0:status,data:status===200?data:undefined,msg:'SYNTHETIC generic error'})});h.response=response;
 Object.assign(h.sandbox,{clearCharts:()=>{},navKeyHandler:null,navViewportCleanup:null,globalKeyHandler:null,scrollShadowHandler:null,v7GlowHandler:null,v6PointerHandler:null,loginRotTimer:null,loginRotSwap:null,
 sceneBridge:{setMode:()=>{},setPhase:p=>h.phases.push(p)},brandSymbol:()=>'<span>研序</span>',prefersReducedMotion:()=>true,clearInterval:id=>intervals.delete(id),setInterval:fn=>{const id=Symbol();intervals.set(id,fn);return id;},Date:class extends Date{static now(){return h.now;}},
 localStorage:{getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v),removeItem:k=>storage.delete(k)},restoreRouteFromUrl:()=>false,writeRouteToUrl:()=>{},
 renderLayout:()=>{h.layouts++;h.sandbox.disposeLoginExperience();h.root.innerHTML='<p>工作台</p>';},
 fetch:async(url,opts)=>{h.requests.push({url,opts});const normal=()=>{if(opts.signal?.aborted)throw Object.assign(Error('abort'),{name:'AbortError'});if(url==='/api/login')return response(legacy?h.success():h.challenge());if(url==='/api/login/email/verify')return response(h.success());if(url==='/api/login/email/resend')return response(h.challenge());if(url==='/api/login/email/cancel')return response(null);throw Error('Unexpected auth route');};return override?override(url,opts,normal,response,h):normal();},
 });
 h.document.defaultView=h.sandbox.window;h.sandbox.window.addEventListener=(key,fn)=>windowEvents.set(key,fn);h.sandbox.window.removeEventListener=(key,fn)=>{if(windowEvents.get(key)===fn)windowEvents.delete(key);};h.sandbox.window.YanxuLoginMotion={mount:()=>({setPhase:p=>h.phases.push(p),destroy:()=>h.disposals++})};
 vm.runInContext('{'+moduleSource.replace('export function mountLoginVerification','function mountLoginVerification')+';globalThis.actualLoginModule={mountLoginVerification};}',h.sandbox);
 h.sandbox.loadLoginModule=async()=>{if(moduleGate)await moduleGate.promise;if(moduleFailure)throw Error('SYNTHETIC unavailable');return h.sandbox.actualLoginModule;};
 vm.runInContext(slice('  let loginMotion = null;','  function clearRouteAsync()')+slice('  const V6_JOBS =','  // ============ 主布局 ============').replace("await import('/modules/notifications/login-verification.js?v=20260924firstbind1')","await loadLoginModule()"),h.sandbox);
 h.mount=()=>{h.sandbox.renderLogin();for(const id of ['login-email-step','login-email-actions'])h.field(id).hidden=h.field(id).hasAttribute('hidden');};h.mount();h.set=(key,value)=>h.field(key).value=value;h.submit=()=>h.field('login-form').onsubmit({preventDefault(){}});h.start=async()=>{h.set('login-user','synthetic-login');h.set('login-pwd','SYNTHETIC-PASSWORD');return h.submit();};h.code=async(value='123456')=>{h.set('login-code',value);return h.submit();};h.advance=ms=>{h.now+=ms;for(const fn of [...intervals.values()])fn();};h.back=()=>h.field('login-back').onclick();h.resend=()=>h.field('login-resend').onclick();h.pagehide=()=>windowEvents.get('pagehide')?.();h.calls=tail=>h.requests.filter(r=>r.url.endsWith(tail));h.destroy=()=>h.sandbox.disposeLoginExperience();return h;
}
(async()=>{
 const h=harness();check(h.field('login-email-step').hidden&&h.field('login-user')&&h.field('pwd-toggle'),'Original password panel remains default');equal(h.requests.length,0,'Initial render sends no auth request');check(h.field('login-password-step').getAttribute('style').includes('minmax(0,1fr)'),'Original credential grid can shrink at 320px');await h.start();equal(JSON.parse(h.calls('/api/login')[0].opts.body),{username:'synthetic-login',password:'SYNTHETIC-PASSWORD'},'Exact initial credentials body');check(h.field('login-password-step').hidden&&!h.field('login-email-step').hidden,'Challenge switches same original panel');equal(h.field('login-pwd').value,'','Password clears immediately');check(h.field('login-email-hint').textContent.includes('***@***'),'Only masked email shown');check(h.field('login-resend').disabled&&h.field('login-resend').textContent.includes('60'),'Resend obeys server absolute cooldown');equal(h.layouts,0,'Challenge never enters workspace');equal([...h.storage.entries()],[['token','OLD-UNUSED']],'Challenge writes no token/password/code/ID to storage');check(!h.root.innerHTML.includes('1111111111111111'),'Challenge ID stays out of DOM');await h.code('123');equal(h.calls('/verify').length,0,'Invalid short code rejected before request');h.advance(60001);check(!h.field('login-resend').disabled,'Server cooldown reaching zero enables resend');await h.resend();equal(JSON.parse(h.calls('/resend')[0].opts.body),{challenge_id:'1'.repeat(64)},'Resend only sends old challenge');check(h.field('login-code').value===''&&h.field('login-resend').disabled,'Rotated challenge resets code and cooldown');await h.code();equal(JSON.parse(h.calls('/verify')[0].opts.body),{challenge_id:'2'.repeat(64),code:'123456'},'Verification uses rotated ID and exact string code');equal(h.layouts,1,'Only verified final user enters original workspace');equal([...h.storage.entries()],[['yx_last_username','synthetic-login']],'Only previous username remembered after success');equal(h.intervals.size,0,'Success disposes countdown');
 const rawEmail=harness({override:(url,opts,normal,respond,x)=>url==='/api/login'?respond({...x.challenge(),masked_email:'worker@example.test'}):normal()});await rawEmail.start();check(rawEmail.field('login-email-step').hidden&&!rawEmail.root.textContent.includes('worker@example.test'),'Unmasked email response is rejected without display');rawEmail.destroy();
 const old=harness({legacy:true});await old.start();equal(old.layouts,1,'Legacy token/user response remains compatible');equal(old.calls('/verify').length,0,'Legacy mode has no fabricated verification step');
 for(const [kind,status]of[['verify',400],['verify',429],['resend',429]]){const x=harness({override:(url,opts,normal,respond)=>url.endsWith('/'+kind)?respond(null,status):normal()});await x.start();x.advance(60001);if(kind==='verify')await x.code();else await x.resend();check(!x.field('login-email-step').hidden&&x.layouts===0,kind+' '+status+' stays in current challenge');check(x.field('login-err').textContent.length>0,'Inline auth error shown');equal(x.invalidations,0,'No global invalidation called');x.destroy();}
 for(const [kind,status]of[['verify',401],['verify',503],['resend',401],['resend',503]]){const x=harness({override:(url,opts,normal,respond)=>url.endsWith('/'+kind)?respond(null,status):normal()});await x.start();x.advance(60001);if(kind==='verify')await x.code();else await x.resend();check(x.field('login-email-step').hidden&&!x.field('login-password-step').hidden,kind+' '+status+' returns to credentials');equal(x.field('login-pwd').value,'','No retained password after invalid challenge');equal(x.field('login-code').value,'','No retained code after invalid challenge');equal(x.intervals.size,0,'No retained expiry timer');check(x.calls('/cancel').length===1,'Invalid challenge retired best effort');x.destroy();}
 const back=harness();await back.start();back.set('login-code','123456');await back.back();check(back.field('login-email-step').hidden&&!back.field('login-user').disabled,'Back restores original input');equal(back.calls('/cancel').length,1,'Back cancels one owned challenge');equal(back.field('login-code').value,'','Back clears code');equal(back.intervals.size,0,'Back clears countdown');await back.start();await back.code();equal(back.layouts,1,'Fresh credentials after back can complete');
 const delayed=deferred(),late=harness({override:(url,opts,normal,respond)=>url.endsWith('/verify')?delayed.promise.then(respond):normal()});await late.start();const verifying=late.code();await tick();check(late.field('login-back').disabled,'In-flight verification locks back to prevent cookie identity races');late.back();await late.start();equal(late.calls('/api/login').length,1,'Back handler cannot begin another identity while verification is pending');equal(late.calls('/cancel').length,0,'Pending verification does not cancel through a new login');delayed.resolve(late.success());await verifying;equal(late.layouts,1,'Pending verification enters only its original identity');
 const goneGate=deferred(),gone=harness({override:(url,opts,normal,respond)=>url.endsWith('/verify')?goneGate.promise.then(respond):normal()});await gone.start();const goneVerify=gone.code();await tick();gone.mount();goneGate.resolve(gone.success());await goneVerify;equal(gone.layouts,0,'Disposed form cannot render late verification success');check(gone.calls('/verify')[0].opts.signal.aborted,'Disposal aborts pending verification');
 const noEmail=harness({override:(url,opts,normal,respond)=>url==='/api/login'?respond(null,409):normal()});await noEmail.start();check(noEmail.field('login-email-step').hidden&&noEmail.field('login-err').textContent.includes('个人邮箱尚未准备好'),'Missing candidate gives a safe preparation message');noEmail.destroy();
 const resendGate=deferred(),stale=harness({override:(url,opts,normal,respond)=>url.endsWith('/resend')?resendGate.promise.then(respond):normal()});await stale.start();stale.advance(60001);const sending=stale.resend();await tick();stale.back();await stale.start();const oldId='a'.repeat(64);resendGate.resolve({...stale.challenge(),challenge_id:oldId});await sending;check(!stale.field('login-email-step').hidden&&stale.layouts===0,'Late resend does not replace newer login');check(stale.calls('/cancel').some(r=>JSON.parse(r.opts.body).challenge_id===oldId),'Late returned challenge retired without affecting new one');stale.destroy();
 const lost=harness({override:(url,opts,normal)=>url.endsWith('/verify')?Promise.reject(Error('SYNTHETIC network')):normal()});await lost.start();await lost.code();check(!lost.field('login-email-step').hidden&&lost.field('login-err').textContent.includes('未能确认'),'Unknown verify remains explicit and does not fabricate success');equal(lost.calls('/verify').length,1,'No automatic resubmission');lost.destroy();
 const doubleGate=deferred(),double=harness({override:(url,opts,normal)=>url==='/api/login'?doubleGate.promise.then(normal):normal()});const starting=double.start();await tick();await double.submit();equal(double.calls('/api/login').length,1,'Double credential submit locked');doubleGate.resolve();await starting;double.destroy();
 const oldRead=deferred(),replaced=harness({override:(url,opts,normal,respond)=>url==='/api/login'?oldRead.promise.then(respond):normal()});const login=replaced.start();await tick();const oldForm=replaced.field('login-form');replaced.mount();oldRead.resolve(replaced.challenge());await login;check(replaced.field('login-form')!==oldForm&&replaced.field('login-email-step').hidden,'Replaced panel ignores old password result');check(replaced.calls('/api/login')[0].opts.signal.aborted,'Replacing login aborts old password request');equal(replaced.calls('/cancel').length,1,'Returned obsolete challenge cancelled');
 const lazy=deferred(),loading=harness({moduleGate:lazy});const load=loading.start();await tick();const oldPassword=loading.field('login-pwd');loading.mount();lazy.resolve();await load;equal(loading.requests.length,0,'Late module cannot start request for replaced form');equal(oldPassword.value,'','Disposal clears password even before module finishes loading');
 const failure=harness({moduleFailure:true});await failure.start();check(!failure.field('login-btn').disabled&&failure.field('login-err').textContent.includes('无法加载'),'Module failure keeps original login retryable');equal(failure.field('login-pwd').value,'','Module failure clears password');
 for(const mutate of [r=>r.challenge_id='invalid',r=>r.expires_at='invalid',r=>r.resend_after='2099-01-01T00:00:00Z',r=>r.user={uid:1},r=>r.token='wrong']){const malformed=harness({override:(url,opts,normal,respond,x)=>{if(url==='/api/login'){const value=x.challenge();mutate(value);return respond(value);}return normal();}});await malformed.start();check(malformed.field('login-email-step').hidden&&malformed.layouts===0,'Malformed challenge never authenticates or displays verification');malformed.destroy();}
 const expired=harness();await expired.start();expired.advance(600001);check(expired.field('login-code-time').textContent.includes('可能已过期')&&!expired.field('login-code').disabled,'Local expiry informs user; server remains authority');expired.destroy();
 const bfcache=harness();await bfcache.start();bfcache.pagehide();check(bfcache.field('login-email-step').hidden&&bfcache.field('login-code').value===''&&bfcache.intervals.size===0,'Pagehide removes private challenge and timer');await bfcache.start();check(!bfcache.field('login-email-step').hidden,'Cached original page can mount a fresh verifier');bfcache.destroy();
 check(!moduleSource.includes('localStorage')&&!moduleSource.includes('console.')&&!moduleSource.includes('location.'),'Module never persists or logs secrets');check(!app.slice(app.indexOf('  function renderLogin()'),app.indexOf('  // ============ 主布局')).includes('记住设备'),'No remembered-device option');
 console.log(JSON.stringify({ok:true,suite:'original login email verification',checks,network:false,browser:false,database:false}));
})().catch(error=>{console.error(error);process.exitCode=1;});
