'use strict';
// Real Main/Auth/M01 relationship editor; synthetic file-backed H2 and loopback only.
const fs=require('node:fs'),path=require('node:path'),net=require('node:net'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {spawn,execFile}=require('node:child_process'),run=require('node:util').promisify(execFile),args={};
for(let i=2;i<process.argv.length;i+=2){assert.ok(['--java','--classes','--fixture-classes'].includes(process.argv[i])&&process.argv[i+1],'Use --java PATH --classes DIRECTORY or CLASSES_DIR');args[process.argv[i]]=process.argv[i+1];}
const java=args['--java']||'java',repo=path.resolve(__dirname,'..'),classes=fs.realpathSync(args['--classes']||process.env.CLASSES_DIR||''),fixtureClasses=args['--fixture-classes']?fs.realpathSync(args['--fixture-classes']):classes;
for(const value of [classes,fixtureClasses])assert.ok(value!==repo&&!value.startsWith(repo+path.sep),'Use independent classes outside repository');assert.ok(fs.existsSync(path.join(fixtureClasses,'com/training/IntegrationAccountRelationshipsHttpFixture.class')),'Compile synthetic fixture first');
const own=fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'yanxu-account-relationships-http-')),data=path.join(own,'data');fs.mkdirSync(data);const password=crypto.randomBytes(24).toString('hex'),failures=[],pids=[],readEvidence=[],writeEvidence=[],tokens={},sockets=new Set(),env={...process.env,JAVA_TOOL_OPTIONS:'',JDK_JAVA_OPTIONS:'',_JAVA_OPTIONS:'',YANXU_SEMANTIC_PORT:'',YANXU_SEMANTIC_TOKEN:''};
let child,port,ids,checks=0,phase='setup',fatal=null,evidence,configuration;const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms)),digest=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
function check(ok,label){checks++;if(!ok)failures.push(phase+': '+label);}
function same(a,b,label){let ok=true;try{assert.deepEqual(a,b);}catch{ok=false;}check(ok,label);}
function options(resume=false){return ['-Dbind.address=127.0.0.1','-Dbootstrap.demo=false','-Dbootstrap.admin.password='+password,'-Dlogin.email.mode=legacy','-Dintegration.account.relationships.root='+own,'-Dintegration.account.relationships.resume='+resume,'-Dintegration.account.relationships.empty=true','-Ddata.dir='+data,'-Dsemantic.port=','-Dsemantic.token=','-Daccount.import.manifest=','-Daccount.import.manifest.sha256=','-cp',fixtureClasses+path.delimiter+classes+path.delimiter+path.join(repo,'lib','*')];}
async function request(route,body,actor='admin',opts={}){
 const headers={...(tokens[actor]?{'X-Token':tokens[actor]}:{}),...(body!==undefined?{'Content-Type':opts.contentType||'application/json'}:{})},method=opts.method||(body===undefined?'GET':'POST');const r=await fetch(`http://127.0.0.1:${port}/api${route}`,{method,headers,body:body===undefined?undefined:opts.raw?body:JSON.stringify(body),signal:AbortSignal.timeout(15000)}),text=await r.text();let envelope=null;if(text){try{envelope=JSON.parse(text);}catch{throw new Error('Non-JSON response at '+route+' HTTP '+r.status);}}
 if(route.startsWith('/organization/account-relationships')){check(r.headers.get('cache-control')==='no-store','Editor/previews/errors are not cacheable');check(!text.includes(password)&&!text.includes('pbkdf2$')&&!text.includes(own)&&!text.includes('jdbc:'),'No credentials, database or private source path exposed');check(!envelope?.data?.token&&!r.headers.get('set-cookie')?.match(/^yx_session=[^;]/),'Relationship operation never creates target authentication');}
 return {status:r.status,text,envelope,headers:r.headers};
}
async function api(route,body,actor='admin',opts={}){const r=await request(route,body,actor,opts);assert.equal(r.status,200,phase+': '+route+' HTTP '+r.status+' '+r.envelope?.msg);assert.equal(r.envelope?.code,0,route);return r.envelope.data;}
async function denied(route,body,status,label,actor='admin',opts={}){const r=await request(route,body,actor,opts);check(r.status===status,label+' (HTTP '+r.status+')');if(opts.method==='HEAD')same(r.text,'','Rejected HEAD sends no body');else check(r.envelope?.code===status&&!r.envelope?.data,'Error has no target/configuration/token data');return r;}
async function login(name='admin',key=name){const result=await api('/login',{username:name==='admin'?'admin':'synthetic-relation-'+name,password},null);tokens[key]=result.token;return result;}
async function boot(resume=false){const listener=net.createServer();await new Promise((resolve,reject)=>{listener.once('error',reject);listener.listen(0,'127.0.0.1',resolve);});port=listener.address().port;await new Promise(resolve=>listener.close(resolve));child=spawn(java,[...options(resume),'com.training.IntegrationAccountRelationshipsHttpFixture',String(port)],{cwd:repo,env,stdio:'ignore'});if(child.pid)pids.push(child.pid);let error;child.once('error',e=>{error=e;});for(let i=0;i<180;i++){if(error)throw error;assert.equal(child.exitCode,null,'Synthetic Main exited');try{const r=await fetch(`http://127.0.0.1:${port}/api/me`,{signal:AbortSignal.timeout(1000)});await r.text();if(r.status===401){ids=JSON.parse(fs.readFileSync(path.join(own,'fixture.json'),'utf8'));return;}}catch{}await pause(100);}throw new Error('Synthetic Main startup timeout');}
async function stop(){for(const socket of sockets)socket.destroy();sockets.clear();const running=child;child=null;if(!running||running.exitCode!==null||running.signalCode!==null)return;await new Promise(resolve=>{const timer=setTimeout(()=>{if(running.exitCode===null&&running.signalCode===null)running.kill('SIGKILL');},2000);running.once('exit',()=>{clearTimeout(timer);resolve();});running.kill('SIGTERM');});}
async function control(operation,extra={}){const nonce=crypto.randomUUID(),tmp=path.join(own,'control-request.next');fs.writeFileSync(tmp,JSON.stringify({nonce,operation,...extra}),{mode:0o600});fs.renameSync(tmp,path.join(own,'control-request.json'));for(let i=0;i<250;i++){try{const r=JSON.parse(fs.readFileSync(path.join(own,'control-result.json'),'utf8'));if(r.nonce===nonce&&r.ok)return r.data;}catch{}await pause(20);}throw new Error('Synthetic control timeout: '+operation);}
async function readOnly(label,operation){phase=label;const before=await control('snapshot');await operation();const after=await control('snapshot');same(after,before,'All PUBLIC tables unchanged, including workflow and outbox');readEvidence.push({phase:label,tables:Object.keys(before).length,before:digest(before),after:digest(after)});}
const route=(name='subject',action='')=>'/organization/account-relationships/'+ids.accounts[name]+(action?'/'+action:''),person=name=>ids.person_codes[name],editor=name=>api(route(name)),proposal=(leader='leader-b',bp='bp-a',version=configuration.version)=>({expected_version:version,leader_person_code:leader===null?null:person(leader),bp_person_code:bp===null?null:person(bp)});
const preview=(name,body,actor='admin')=>api(route(name,'preview'),body,actor),confirm=(name,value,actor='admin')=>api(route(name,'confirm'),{review_token:value.review_token},actor);
async function deviceState(){return {epochs:await control('device-epochs'),devices:await control('devices')};}
async function publicationTables(before,security,after,affected){
 const accounts=new Set(affected),expectedEpochs=security.epochs.map(row=>({...row,epoch:row.epoch+(accounts.has(row.user_id)?1:0)})),expectedDevices=security.devices.map(row=>({...row,revoked:accounts.has(row.user_id)?true:row.revoked}));
 same(security.epochs.filter(row=>accounts.has(row.user_id)).map(row=>row.user_id).sort((a,b)=>a-b),[...accounts].sort((a,b)=>a-b),'Every affected relationship account has one existing device epoch');
 same(await control('device-epochs'),expectedEpochs,'Only affected relationship accounts increment their device epoch exactly once');
 same(await control('devices'),expectedDevices,'Only affected devices are revoked; every other device field and account remains unchanged');
 same(after,{...before,ORGANIZATION_ACCESS_CONFIG:after.ORGANIZATION_ACCESS_CONFIG,S01_TRUSTED_DEVICE_EPOCHS:after.S01_TRUSTED_DEVICE_EPOCHS,S01_TRUSTED_DEVICES:after.S01_TRUSTED_DEVICES},'Publication changes only configuration history and the precisely checked security rows');
 return {device_epochs_before:security.epochs,device_epochs_after:expectedEpochs,affected_accounts:[...accounts],revoked_device_selectors:expectedDevices.filter(row=>accounts.has(row.user_id)).map(row=>row.selector)};
}
function relation(value){return value===null||Object.keys(value).sort().join(',')==='account_id,eligible,name,person_code,role_codes,username'&&typeof value.person_code==='string'&&typeof value.eligible==='boolean'&&Array.isArray(value.role_codes)&&(value.account_id===null||Number.isSafeInteger(value.account_id));}
function subject(value){same(Object.keys(value).sort(),['account_enabled','account_id','binding_enabled','name','organization_code','person_code','person_enabled','role_codes','username'],'Subject shows only existing account/binding/person facts');}
function editorSchema(value){same(Object.keys(value).sort(),['bp_options','bp_required','combined_person_codes','configuration_version','current','leader_options','leader_required','subject','warnings'],'Exact relationship editor DTO');subject(value.subject);check(typeof value.leader_required==='boolean'&&typeof value.bp_required==='boolean'&&Array.isArray(value.warnings),'Relationship requirements and warnings are explicit');check(Object.keys(value.current).sort().join(',')==='bp,leader'&&relation(value.current.leader)&&relation(value.current.bp),'Current references retain exact relation projection');check([...value.leader_options,...value.bp_options].every(item=>relation(item)&&item.eligible),'Options contain only eligible coded existing people');}
function previewSchema(value){same(Object.keys(value).sort(),['after','before','changed','configuration_version','expires_at','review_token','subject','warnings','workflow_impact'],'Exact preview DTO');subject(value.subject);check(typeof value.changed==='boolean'&&/^[a-f0-9]{64}$/.test(value.review_token)&&Number.isFinite(Date.parse(value.expires_at)),'Preview is explicit, bounded and carries opaque review token');same(value.workflow_impact,{historical_assignments_changed:false,pending_tasks_reassigned:false,combined_workflows_may_pause:value.changed},'Preview never promises to rewrite historical or pending assignments');}
function confirmSchema(value,name,saved){same(Object.keys(value).sort(),['account_id','bp_person_code','configuration_version','leader_person_code','person_code','saved','sessionInvalidated','unchanged'],'Exact confirmation DTO');check(value.saved===saved&&value.unchanged===!saved,'Confirmation distinguishes saved vs unchanged');same([value.account_id,value.person_code],[ids.accounts[name],person(name)],'Confirmation belongs to reviewed target');}
async function savedOnlyRelationships(name,value){
 phase='confirmed change affects only selected relationships';const before=await control('snapshot'),security=await deviceState(),old=(await api('/organization/config')).configuration,result=await confirm(name,value),after=await control('snapshot'),current=(await api('/organization/config')).configuration;
 confirmSchema(result,name,true);check(current.version!==old.version&&current.version===result.configuration_version,'Successful change publishes a fresh original Store version');
 const expected=structuredClone(old);expected.version=current.version;const target=expected.people.find(row=>row.personCode===person(name));target.leaderPersonCode=result.leader_person_code;target.bpPersonCode=result.bp_person_code;
 same(current,expected,'Every original configuration fact except selected leader/BP and version remains identical');const securityEvidence=await publicationTables(before,security,after,[ids.accounts[name]]);
 check(after.ORGANIZATION_ACCESS_CONFIG.count===before.ORGANIZATION_ACCESS_CONFIG.count+1,'Exactly one immutable configuration revision is added');writeEvidence.push({target:person(name),before:digest(before),after:digest(after),configuration_rows_added:1,...securityEvidence});configuration=current;return result;
}
function slowPost(name,action,actor,body,huge=false){const bytes=Buffer.from(JSON.stringify(body)),socket=net.createConnection({host:'127.0.0.1',port});sockets.add(socket);let finishBody;const response=new Promise((resolve,reject)=>{let received='',done=false;const timer=setTimeout(()=>finish(new Error('Slow request preflight/revalidation timed out')),3500);function finish(error,value){if(done)return;done=true;clearTimeout(timer);sockets.delete(socket);socket.destroy();error?reject(error):resolve(value);}socket.on('error',error=>finish(error));socket.on('data',chunk=>{received+=chunk.toString();if(received.includes('\r\n\r\n'))finish(null,{status:Number(/^HTTP\/1\.1 (\d+)/.exec(received)?.[1]),no_store:/cache-control:\s*no-store/i.test(received)});});socket.on('connect',()=>{socket.write('POST /api'+route(name,action)+' HTTP/1.1\r\nHost: 127.0.0.1:'+port+'\r\nConnection: close\r\nContent-Type: application/json\r\nContent-Length: '+(huge?900000:bytes.length)+'\r\n'+(tokens[actor]?'X-Token: '+tokens[actor]+'\r\n':'')+'\r\n'+bytes.subarray(0,1));finishBody=()=>socket.write(bytes.subarray(1));});});return {response,finish:async()=>{for(let i=0;i<50&&!finishBody;i++)await pause(10);assert.ok(finishBody);finishBody();}};}
async function workflow(requestId){let value=(await api('/demands/draft',{request_id:requestId+'-draft',title:'SYNTHETIC RELATION FROZEN ASSIGNMENT',unit:'SYNTHETIC CUSTOMER',business_path:'direct',organization_code:'001',internal_contact_code:person('subject'),category_text:'其他类培训',delivery_mode_text:'线上',period_text:'全天',duration_minutes:'60',participant_count:'2',budget_amount:'0',objectives:'合成关系核对',content:'合成关系核对',teacher_req:'',remark:'synthetic only'},'subject')).workflow;value=(await api('/demands/submit',{id:value.id,expected_version:value.version,request_id:requestId+'-submit'},'subject')).workflow;return value;}
async function runChecks(){
 await boot();for(const name of ['admin','admin2','manager','viewer'])await login(name);
 await readOnly('unconfigured editor cannot fabricate relationships',async()=>{await denied(route(),undefined,409,'No published source configuration cannot be edited');await denied(route(),undefined,409,'HEAD reflects unavailable source configuration','admin',{method:'HEAD'});await denied(route('subject','preview'),{expected_version:'missing',leader_person_code:null,bp_person_code:null},409,'Preview cannot create source configuration');});
 phase='publish explicit synthetic configuration';configuration=JSON.parse(fs.readFileSync(path.join(own,'configuration.json'),'utf8'));await api('/organization/config',{expectedVersion:null,configuration});same(await control('device-epochs'),configuration.accountBindings.map(row=>({user_id:row.accountId,epoch:1})).sort((a,b)=>a.user_id-b.user_id),'Initial publication revokes each configured account exactly once');const seeded=await control('seed-devices');same(seeded.seeded,Object.keys(ids.accounts).length,'Each synthetic account has a device so selective revocation has real coverage');for(const name of ['admin2','subject','leader-a','leader-b','combined-approved'])await login(name);const ordinary=await workflow('synthetic-ordinary');same(ordinary.approval.participants,{submitterId:'P1',leaderId:'P2',bpId:'P3'},'Real submitted ordinary workflow freezes original assignments');let baseline=await control('snapshot');
 await readOnly('administrator boundary is checked before routes methods or slow bodies',async()=>{
  for(const [actor,status] of [[null,401],['manager',403],['viewer',403],['subject',403]]){await denied(route()+'?unknown=1',undefined,status,'Caller authority precedes invalid query',actor);await denied(route('subject','unknown'),{},status,'Unknown child authenticates first',actor);await denied(route(),undefined,status,'HEAD requires current administrator',actor,{method:'HEAD'});}
  await denied(route('subject','unknown'),{},404,'Authenticated unknown subroute remains absent');await denied(route(),{},405,'Editor rejects POST');await denied(route('subject','preview'),undefined,405,'Preview requires POST');
  for(const [actor,status,action] of [[null,401,'preview'],['manager',403,'preview'],['admin',405,'']]){const pending=slowPost('subject',action,actor,{},true);check(Object.keys(await control('snapshot')).length===Object.keys(baseline).length,'Incomplete body never holds shared business lock');const response=await pending.response;check(response.status===status&&response.no_store,'Preflight rejects incomplete request before reading its body');}
 });
 let sourceEditor;
 await readOnly('eligible candidates preserve identities duties and current invalid references',async()=>{
  sourceEditor=await editor('subject');editorSchema(sourceEditor);same(sourceEditor.subject.account_id,ids.accounts.subject,'Editor target is actual bound account');check(sourceEditor.leader_required&&sourceEditor.bp_required,'EMP requires both relationships');same([sourceEditor.current.leader.person_code,sourceEditor.current.bp.person_code],['P2','P3'],'Current values are not silently replaced');const leaders=sourceEditor.leader_options.map(row=>row.person_code),bps=sourceEditor.bp_options.map(row=>row.person_code);check(leaders.includes('P2')&&leaders.includes('P4'),'Same-name accounts remain distinct coded choices');same(sourceEditor.leader_options.find(row=>row.person_code==='P2').name,sourceEditor.leader_options.find(row=>row.person_code==='P4').name,'Fixture exercises actual duplicate display names');check(!leaders.includes('P6')&&!bps.includes('P6'),'Ordinary teacher has no approval candidacy');check(leaders.includes('P7')&&!bps.includes('P7'),'Split LEADER001/BP002 scopes cannot be borrowed across duties');check(!leaders.includes('P17')&&!bps.includes('P5'),'Other-organization duties are excluded');same(sourceEditor.combined_person_codes,['P8'],'Only existing explicit combined evidence is eligible for a joint selection');
  const intersection=await editor('intersection');editorSchema(intersection);same(intersection.leader_options.map(row=>row.person_code),['P11'],'Candidate satisfies intersection of every held RoleRelations rule');const invalid=await editor('invalid-current');editorSchema(invalid);check(invalid.current.leader.person_code==='P15'&&invalid.current.leader.eligible===false&&!invalid.leader_options.some(row=>row.person_code==='P15'),'Invalid existing relation is displayed without automatic substitution');const peer=await editor('peer');check(peer.leader_options.some(row=>row.person_code==='P17')&&!peer.leader_options.some(row=>row.person_code==='P2'),'The target own organization determines candidate scope');await denied(route('unbound'),undefined,409,'Unbound accounts cannot be given implicit person or roles');const head=await request(route(),undefined,'admin',{method:'HEAD'});check(head.status===200&&head.text==='','Valid HEAD reads editor without body');
 });
 await control('retired-disable');await readOnly('disabled but bound subject facts are displayed without implicit activation',async()=>{const value=await editor('retired-leader');check(value.subject.account_enabled===false&&value.subject.binding_enabled===false,'Disabled subject and disabled binding remain distinct source facts');const valuePreview=await preview('retired-leader',proposal('leader-b',null));previewSchema(valuePreview);check(valuePreview.changed===true,'A legitimate disabled binding remains maintainable without inventing activation');const noChange=await preview('retired-leader',proposal(null,null));confirmSchema(await confirm('retired-leader',noChange),'retired-leader',false);});await control('retired-restore');
 await readOnly('flat request parser and strict route/query controls',async()=>{
  for(const suffix of ['?x=1','?x=1&%78=2','?account_id=1'])await denied(route()+suffix,undefined,400,'No query can override account path');for(const id of ['0','01','-1','1.0','1e0','%35','9007199254740992'])await denied('/organization/account-relationships/'+id,undefined,400,'Only canonical positive safe-integer IDs accepted');await denied('/organization/account-relationships/999999',undefined,404,'Unknown actual account remains absent');
  const good=proposal();for(const body of [{...good,role_codes:['LEADER']},{...good,configuration:{}},{...good,expected_version:1},{...good,leader_person_code:[]},{leader_person_code:'P4',bp_person_code:'P3'}])await denied(route('subject','preview'),body,400,'Preview cannot inject or omit source fields');
  for(const raw of ['{"expected_version":"x","expected_version":"y","leader_person_code":null,"bp_person_code":null}','{"expected_version":"x","leader_person_code":null,"leader_person_\\u0063ode":null,"bp_person_code":null}','\u000b'+JSON.stringify(good),JSON.stringify(good)+'\u000c'])await denied(route('subject','preview'),raw,400,'Duplicate decoded keys and illegal JSON whitespace rejected','admin',{raw:true});
  await denied(route('subject','preview'),Buffer.from([0x7b,0x22,0xff,0x22,0x3a,0x22,0x78,0x22,0x7d]),400,'Malformed UTF-8 cannot become replacement-character data','admin',{raw:true});await denied(route('subject','preview'),JSON.stringify(good),415,'JSON media type required','admin',{raw:true,contentType:'text/plain'});await denied(route('subject','preview'),JSON.stringify({...good,expected_version:'x'.repeat(5000)}),413,'Four-KiB bounded body enforced','admin',{raw:true});await denied(route('subject','confirm'),{review_token:'a'.repeat(64),leader_person_code:'P4'},400,'Confirmation accepts only server review token');
 });
 await readOnly('candidate rules self loops required relationships and combined evidence',async()=>{
  for(const [leader,bp] of [['teacher','bp-a'],['leader-other','bp-a'],['leader-b','bp-other'],[null,'bp-a'],['leader-b',null],['combined-unapproved','combined-unapproved'],['combined-split','combined-split']])await denied(route('subject','preview'),proposal(leader,bp),400,'Invalid relation choice cannot create a review');await denied(route('intersection','preview'),proposal('leader-b','bp-a'),400,'Every source-role relationship rule must be satisfied');await denied(route('cycle-a','preview'),proposal('cycle-b',null),400,'Transitive leader cycle is rejected');await denied(route('cycle-a','preview'),proposal('cycle-a',null),400,'Self selection follows configured false rule');const allowed=await preview('self-allowed',proposal('self-allowed',null));previewSchema(allowed);check(allowed.after.leader.person_code==='P18','Explicit configured self relation can be reviewed');
 });
 await readOnly('preview and unchanged confirmation are wholly read-only',async()=>{const unchanged=await preview('subject',proposal('leader-a','bp-a'));previewSchema(unchanged);check(unchanged.changed===false,'Exact unchanged relations are explicit');const result=await confirm('subject',unchanged);confirmSchema(result,'subject',false);same(result.configuration_version,configuration.version,'No-op consumes token without publishing version');await denied(route('subject','confirm'),{review_token:unchanged.review_token},409,'Even no-op review token is one-use');const value=await preview('subject',proposal());previewSchema(value);check(value.changed&&value.before.leader.person_code==='P2'&&value.after.leader.person_code==='P4','Before/after preserve coded distinct people');});
 await readOnly('review tokens are bound to actor session and target',async()=>{const value=await preview('subject',proposal('leader-a','bp-a'));await denied(route('subject','confirm'),{review_token:value.review_token},409,'A second administrator cannot consume another preview','admin2');await login('admin','admin-second');await denied(route('subject','confirm'),{review_token:value.review_token},409,'A second session of the same administrator cannot consume review','admin-second');await denied(route('peer','confirm'),{review_token:value.review_token},409,'Token cannot be redirected to a different path account');const rightful=await confirm('subject',value);confirmSchema(rightful,'subject',false);check(rightful.unchanged===true,'Wrong actor/session/target attempts do not consume the rightful administrator review');});
 for(const [mutation,restore] of [['subject-rename','subject-restore'],['subject-disable','subject-restore'],['candidate-disable','candidate-restore']]){phase='prepare mutable identity preview';const value=await preview('subject',proposal());await control(mutation);await readOnly('confirm revalidates '+mutation,async()=>{await denied(route('subject','confirm'),{review_token:value.review_token},409,'Changed selected account/candidate facts invalidate preview');});await control(restore);}
 phase='review expiry fixture';const expiring=await preview('subject',proposal());await control('expire-reviews');await readOnly('expired server-side preview cannot publish',async()=>{await denied(route('subject','confirm'),{review_token:expiring.review_token},409,'Expired review must be replaced by a fresh explicit preview');});
 await readOnly('slow valid POST rechecks current administrator after body read',async()=>{const pending=slowPost('subject','preview','admin',proposal());await pause(80);await control('downgrade-admin');await pending.finish();const response=await pending.response;check(response.status===403,'Admin downgrade during body read is observed before preview');await control('restore-admin');});
 phase='prepare stale configuration token';const stale=await preview('subject',proposal());const next=structuredClone(configuration);next.version='synthetic-relationships-v2';const versionOnlyBefore=await control('snapshot'),versionOnlySecurity=await deviceState();await api('/organization/config',{expectedVersion:configuration.version,configuration:next});await publicationTables(versionOnlyBefore,versionOnlySecurity,await control('snapshot'),[]);configuration=next;await readOnly('review cannot overwrite a newer full configuration',async()=>{await denied(route('subject','confirm'),{review_token:stale.review_token},409,'Configuration version/hash is checked at confirmation');});
 await control('corrupt-configuration');await readOnly('bad stored source fails without replacement',async()=>{await denied(route(),undefined,503,'Corrupt configuration is not repaired by editor');await denied(route('subject','preview'),proposal(),503,'Corrupt source cannot yield review token');});await control('restore-configuration');
 phase='real changed confirmation';const selected=await preview('subject',proposal());await savedOnlyRelationships('subject',selected);await readOnly('successful change revokes only affected identity and preserves ordinary workflow',async()=>{await denied('/me',undefined,401,'Original target session is revoked','subject');same((await api('/me',undefined,'leader-a')).uid,ids.accounts['leader-a'],'Unchanged colleague session remains valid');await denied(route('subject','confirm'),{review_token:selected.review_token},409,'Consumed changed token cannot publish twice');await login('subject');const stored=(await api('/demands/workflow?id='+ordinary.id,undefined,'subject')).workflow;same(stored.approval.participants,ordinary.approval.participants,'Pending ordinary workflow keeps its original frozen leader/BP');check(stored.approval.paused===false,'Ordinary frozen workflow is not automatically reassigned or paused');});
 phase='administrator edits own bound person';const selfReview=await preview('admin2',proposal(),'admin2'),selfBefore=await control('snapshot'),selfSecurity=await deviceState(),selfOld=(await api('/organization/config')).configuration,selfResult=await confirm('admin2',selfReview,'admin2'),selfAfter=await control('snapshot');confirmSchema(selfResult,'admin2',true);check(selfResult.sessionInvalidated===true,'Own successful relationship change reports session revocation rather than post-commit 401');const selfSecurityEvidence=await publicationTables(selfBefore,selfSecurity,selfAfter,[ids.accounts.admin2]);check(selfAfter.ORGANIZATION_ACCESS_CONFIG.count===selfBefore.ORGANIZATION_ACCESS_CONFIG.count+1,'Own edit publishes exactly one revision before revoking its session');writeEvidence.push({target:'P19',self_edit_session_revoked:true,configuration_rows_added:1,...selfSecurityEvidence});configuration=(await api('/organization/config')).configuration;const selfExpected=structuredClone(selfOld);selfExpected.version=configuration.version;selfExpected.people.find(row=>row.personCode==='P19').leaderPersonCode='P4';same(configuration,selfExpected,'Own administrator edit preserves every other configuration fact');await readOnly('own relationship confirmation revokes only its saved subject',async()=>{await denied('/me',undefined,401,'Self-editing administrator must authenticate again','admin2');same((await api('/me')).uid,1,'Unrelated administrator session remains valid');});
 phase='set explicit existing combined relationship';const combined=await preview('subject',proposal('combined-approved','combined-approved'));await savedOnlyRelationships('subject',combined);await login('subject');const combinedWorkflow=await workflow('synthetic-combined');check(combinedWorkflow.approval.participants.leaderId==='P8'&&combinedWorkflow.approval.participants.bpId==='P8','Real combined workflow uses only supplied explicit evidence');baseline=await control('snapshot');
 phase='concurrent explicit relationship confirmations';const first=await preview('subject',proposal('leader-a','bp-a')),second=await preview('subject',proposal('leader-b','bp-a'));const old=(await api('/organization/config')).configuration,before=await control('snapshot'),security=await deviceState(),responses=await Promise.all([request(route('subject','confirm'),{review_token:first.review_token}),request(route('subject','confirm'),{review_token:second.review_token})]);same(responses.map(row=>row.status).sort(),[200,409],'Concurrent competing reviews create one saved version and one conflict');const after=await control('snapshot');const concurrentSecurityEvidence=await publicationTables(before,security,after,[ids.accounts.subject]);check(after.ORGANIZATION_ACCESS_CONFIG.count===before.ORGANIZATION_ACCESS_CONFIG.count+1,'Concurrent confirmations publish exactly one revision');configuration=(await api('/organization/config')).configuration;const expected=structuredClone(old);expected.version=configuration.version;expected.people.find(row=>row.personCode==='P1').leaderPersonCode=responses.find(row=>row.status===200).envelope.data.leader_person_code;expected.people.find(row=>row.personCode==='P1').bpPersonCode='P3';same(configuration,expected,'Concurrent winner changes only its reviewed relationships');writeEvidence.push({target:'P1',concurrent_statuses:responses.map(row=>row.status),configuration_rows_added:1,...concurrentSecurityEvidence});baseline=after;
 await login('subject');await readOnly('combined old workflow pauses without rewriting frozen assignments',async()=>{const stored=(await api('/demands/workflow?id='+combinedWorkflow.id,undefined,'subject')).workflow;same(stored.approval.participants,combinedWorkflow.approval.participants,'Historical combined approver IDs remain exactly frozen');check(stored.approval.paused===true&&typeof stored.approval.blocked_reason==='string'&&stored.approval.blocked_reason.length>0,'Existing combined rule pauses the old flow after relationship change');});
 phase='prepare review invalidation finality';const samePerson=configuration.people.find(row=>row.personCode==='P1'),invalidated=await preview('subject',{expected_version:configuration.version,leader_person_code:samePerson.leaderPersonCode,bp_person_code:samePerson.bpPersonCode});await control('subject-rename');await readOnly('first authoritative stale confirmation invalidates review',async()=>{await denied(route('subject','confirm'),{review_token:invalidated.review_token},409,'Changed identity facts make the original review invalid');});await control('subject-restore');await readOnly('restored facts cannot resurrect an invalidated review',async()=>{const result=await denied(route('subject','confirm'),{review_token:invalidated.review_token},409,'After first stale result the same old token stays invalid even when facts return');fs.writeFileSync(path.join(own,'review-invalidation-evidence.json'),JSON.stringify({first_stale_status:409,restored_facts_status:result.status,response:result.envelope},null,2),{mode:0o600});});
 phase='prepare revoked administrator review';const revoked=await preview('subject',proposal('leader-b','bp-a'));await control('revoke-admin');await readOnly('session withdrawal blocks editor and confirmation',async()=>{await denied(route(),undefined,401,'Withdrawn administrator session cannot read');await denied(route('subject','confirm'),{review_token:revoked.review_token},401,'Withdrawn administrator session cannot publish');});await login();await readOnly('new session cannot revive old administrator review',async()=>{await denied(route('subject','confirm'),{review_token:revoked.review_token},409,'Token remains bound to the exact old Session');});
 phase='cold restart preview';const pending=await preview('subject',proposal('leader-b','bp-a'));let persisted;await readOnly('stable editor before restart',async()=>{persisted=await editor('subject');});const beforeRestart=await control('snapshot');await stop();same(JSON.parse((await run(java,[...options(true),'com.training.IntegrationAccountRelationshipsHttpFixture','inspect'],{cwd:repo,env,timeout:20000,maxBuffer:65536})).stdout.trim()),beforeRestart,'Stopped database confirms live snapshot exactly');await boot(true);await login();await readOnly('cold restart preserves configuration but drops in-memory reviews',async()=>{same(await editor('subject'),persisted,'Same explicit relationships/candidates after restart');await denied(route('subject','confirm'),{review_token:pending.review_token},409,'Pre-restart review cannot publish after restart');});const final=await control('snapshot');same(final,baseline,'Every table equals the last exactly checked publication baseline after all reads and cold restart');fs.writeFileSync(path.join(own,'database-invariants.json'),JSON.stringify({baseline,before_restart:beforeRestart,final,read_phases:readEvidence,confirmations:writeEvidence},null,2),{mode:0o600});fs.writeFileSync(path.join(own,'editor-example.json'),JSON.stringify(sourceEditor,null,2),{mode:0o600});return {read_only_phases:readEvidence.length,tables_per_read_phase:Object.keys(final).length,protected_tables:Object.keys(final).length-1,synthetic_accounts:Object.keys(ids.accounts).length,ordinary_workflows_frozen:1,combined_workflows_paused_without_rewrite:1};
}
runChecks().then(value=>{evidence=value;}).catch(error=>{fatal=String(error.message||error).replaceAll(password,'[redacted]');process.exitCode=1;}).finally(async()=>{await stop();const stopped=pids.every(pid=>{try{process.kill(pid,0);return false;}catch(error){return error.code==='ESRCH';}});check(stopped,'All synthetic relationship Main processes stopped');const summary={suite:'account-relationships-http',checks,failures,...(fatal?{error:fatal}:{}),...(evidence||{}),server_processes_stopped:stopped,production_touched:false,notifications_sent:false,artifacts:own};fs.writeFileSync(path.join(own,'result.json'),JSON.stringify(summary,null,2),{mode:0o600});console.log(JSON.stringify(summary));if(failures.length||fatal)process.exitCode=1;});
