'use strict';
// New certification-only maintenance through real Main/Auth/M01. Synthetic isolated H2; no production data.
const fs=require('node:fs'),path=require('node:path'),net=require('node:net'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {spawn,execFile}=require('node:child_process'),run=require('node:util').promisify(execFile),args={};
for(let i=2;i<process.argv.length;i+=2){assert.ok(['--java','--classes'].includes(process.argv[i])&&process.argv[i+1],'Use --java PATH --classes DIRECTORY or CLASSES_DIR');args[process.argv[i]]=process.argv[i+1];}
const java=args['--java']||'java',repo=path.resolve(__dirname,'..'),classes=fs.realpathSync(args['--classes']||process.env.CLASSES_DIR||'');
assert.ok(classes!==repo&&!classes.startsWith(repo+path.sep),'Use isolated classes outside repository');
assert.ok(fs.existsSync(path.join(classes,'com/training/IntegrationCertificationMaintenanceHttpFixture.class')),'Compile the new synthetic fixture into isolated classes first');
const own=fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'yanxu-certification-maintenance-http-')),data=path.join(own,'data');fs.mkdirSync(data);
const password=crypto.randomBytes(24).toString('hex'),tokens={},failures=[],servicePids=[],readEvidence=[],base='/course-catalog/scopes';
const env={...process.env,YANXU_SEMANTIC_PORT:'',YANXU_SEMANTIC_TOKEN:''};let child,port,checks=0,phase='setup',fatal=null,ids;
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function check(ok,label){checks++;if(!ok)failures.push(phase+': '+label);}
function same(a,b,label){let ok=true;try{assert.deepEqual(a,b);}catch{ok=false;}check(ok,label);}
function options(resume=false){return ['-Dbind.address=127.0.0.1','-Dbootstrap.demo=false','-Dbootstrap.admin.password='+password,'-Dintegration.certification.maintenance.root='+own,'-Dintegration.certification.maintenance.resume='+resume,'-Ddata.dir='+data,'-Dsemantic.port=','-Dsemantic.token=','-Daccount.import.manifest=','-Daccount.import.manifest.sha256=','-cp',classes+path.delimiter+path.join(repo,'lib','*')];}
async function request(route,body,actor='maintainer',overrides={}){
 const headers={...(tokens[actor]?{'X-Token':tokens[actor]}:{})};if(body!==undefined)headers['Content-Type']=overrides.contentType||'application/json';
 const r=await fetch(`http://127.0.0.1:${port}/api${route}`,{method:overrides.method||(body===undefined?'GET':'POST'),headers,body:body===undefined?undefined:overrides.raw?body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});
 const text=await r.text();let envelope=null;if(text){try{envelope=JSON.parse(text);}catch{throw new Error(route+': non-JSON HTTP '+r.status);}}
 check(!text.includes(own)&&!text.includes(password),'Response contains no fixture path or password');return {status:r.status,text,envelope,headers:r.headers};
}
async function api(route,body,actor='maintainer'){const r=await request(route,body,actor);assert.equal(r.status,200,phase+': '+route+': '+r.status+': '+r.envelope?.msg);assert.equal(r.envelope?.code,0,route);return r.envelope.data;}
async function denied(route,body,actor,status,label,overrides={}){const r=await request(route,body,actor,overrides);check(r.status===status&&r.envelope?.code===status,label+' (HTTP '+r.status+')');check(!r.envelope?.data&&!r.headers.has('content-disposition'),'Rejected response exposes no partial catalog or download');return r;}
async function login(actor){tokens[actor]=(await api('/login',{username:actor==='admin'?'admin':'synthetic-cert-'+actor,password},'anonymous')).token;}
async function boot(resume=false){for(const key of Object.keys(tokens))delete tokens[key];const listener=net.createServer();await new Promise((resolve,reject)=>{listener.once('error',reject);listener.listen(0,'127.0.0.1',resolve);});port=listener.address().port;await new Promise(resolve=>listener.close(resolve));child=spawn(java,[...options(resume),'com.training.IntegrationCertificationMaintenanceHttpFixture',String(port)],{cwd:repo,env,stdio:'ignore'});if(child.pid)servicePids.push(child.pid);let error;child.once('error',e=>{error=e;});for(let i=0;i<150;i++){if(error)throw error;assert.equal(child.exitCode,null,'Synthetic Main exited');try{await login('admin');ids=JSON.parse(fs.readFileSync(path.join(own,'fixture.json'),'utf8'));return;}catch{}await pause(100);}throw new Error('Synthetic Main startup timeout');}
async function stop(){const running=child;child=null;if(!running||running.exitCode!==null||running.signalCode!==null)return;await new Promise(resolve=>{const timer=setTimeout(()=>{if(running.exitCode===null&&running.signalCode===null)running.kill('SIGKILL');},2000);running.once('exit',()=>{clearTimeout(timer);resolve();});running.kill('SIGTERM');});}
async function control(operation){const nonce=crypto.randomUUID(),tmp=path.join(own,'control-request.next');fs.writeFileSync(tmp,JSON.stringify({nonce,operation}),{mode:0o600});fs.renameSync(tmp,path.join(own,'control-request.json'));for(let i=0;i<250;i++){try{const ack=JSON.parse(fs.readFileSync(path.join(own,'control-result.json'),'utf8'));if(ack.nonce===nonce&&ack.ok)return ack.data;}catch{}await pause(20);}throw new Error('Synthetic control timeout: '+operation);}
async function readOnly(label,operation){phase=label;const before=await control('snapshot');await operation();const after=await control('snapshot');same(after,before,'Entire PUBLIC schema row digests remain unchanged');readEvidence.push({phase:label,tables:Object.keys(before).length,before:digest(before),after:digest(after)});}
function digest(value){return crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');}
const route=id=>base+'/'+id,management=id=>api(route(id)+'/certification-management'),preview=(id,body)=>api(route(id)+'/certifications-preview',body),command=(batch,version)=>({batch_id:batch,expected_version:version,confirm:true}),confirm=(id,batch,version,actor='maintainer')=>api(route(id)+'/confirm',command(batch,version),actor);
const body=(version,certifications,tag)=>({expected_version:version,catalog_version:'synthetic-certification-'+tag,certifications,change_comment:'SYNTHETIC explicit certification review '+tag});
const cert=(teacher,course,status='unknown',source='',from='',to='')=>({teacher_code:teacher,course_code:course,status,source_ref:source,valid_from:from,valid_to:to});
const qualify=(id,version,course)=>api(route(id)+'/qualify',{expected_version:version,request:{course_code:course,as_of:'2026-09-23',accepted_levels:[],allowed_cities:[]}},'reader');
const reasons=(qualification,teacher)=>qualification.gaps.find(row=>row.teacher_code===teacher)?.reasons.map(r=>r.code)||[];
function viewCheck(view,id,org,version,counts,codes){same(Object.keys(view).sort(),['can_manage','catalog_version','certifications','courses','organization_code','retained_counts','scope_id','teacher_codes','version'],'Management exposes only documented coded certification material');check(view.scope_id===id&&view.organization_code===org&&view.version===version&&view.can_manage===true,'Management uses trusted scope ownership/current version');same(view.retained_counts,counts,'Retained counts use current snapshot, not historical permanent bindings');same(view.teacher_codes,codes,'Only currently present explicitly bound teacher codes are selectable');for(const c of view.certifications)same(Object.keys(c).sort(),['course_code','source_ref','status','teacher_code','valid_from','valid_to'],'Certification contains only six coded evidence fields');check(!JSON.stringify(view).includes('SYNTHETIC CERT TEACHER')&&!('bindings' in view)&&!('teachers' in view),'Management has no teacher names, metadata lookup or account bindings');}
function previewCheck(p,id,org,version){check(p.schema_version==='m04_preview_v1'&&p.ready===true&&p.confirmation_required===true&&typeof p.batch_id==='string','Valid evidence creates original confirmable preview');check(p.scope_id===id&&p.organization_code===org&&p.current_version===version,'Preview retains exact scope and expected head');for(const key of ['courses','teachers','bindings'])same(p.changes[key],{added:[],updated:[],removed:[]},'Preview contains no '+key+' change');same(p.changes.certifications.removed,[],'Certification maintenance never deletes existing pairs');check(p.changes.certifications.added.length+p.changes.certifications.updated.length>0,'Ready preview contains an actual certification change');}
async function onlyBatch(label,operation){phase=label;const before=await control('snapshot'),result=await operation(),after=await control('snapshot');check(after.M04_CATALOG_BATCHES.count===before.M04_CATALOG_BATCHES.count+1,'Ready preview writes one pending batch');same(Object.fromEntries(Object.entries(after).filter(([n])=>n!=='M04_CATALOG_BATCHES')),Object.fromEntries(Object.entries(before).filter(([n])=>n!=='M04_CATALOG_BATCHES')),'Preview leaves every other PUBLIC table untouched');return result;}
const changedTables=(a,b)=>Object.keys(a).filter(name=>JSON.stringify(a[name])!==JSON.stringify(b[name]));
function publicationCheck(before,after){same(changedTables(before,after),['M04_CATALOG_BATCHES','M04_CATALOG_EVENTS','M04_CATALOG_REVISIONS','M04_CATALOG_SCOPES'],'Confirmation changes only four established catalog publication tables');check(after.M04_CATALOG_REVISIONS.count===before.M04_CATALOG_REVISIONS.count+1&&after.M04_CATALOG_EVENTS.count===before.M04_CATALOG_EVENTS.count+1,'Publication creates exactly one revision and audit event');}
async function invalidPreview(id,requestBody,label){const p=await preview(id,requestBody);check(p.ready===false&&p.data===null&&p.changes===null&&p.batch_id===null&&p.confirmation_required===false&&p.issues.length>0,label);return p;}
async function runChecks(){
 await boot();for(const actor of ['manager','maintainer','reader','colleague','other','unbound'])await login(actor);
 const {retained_scope:retained,empty_scope:empty,empty_courses_scope:noCourses,removed_teachers_scope:removed,partial_teachers_scope:partial,limit_scope:limit,other_scope:other}=ids;
 const baseline=await control('snapshot'),original=await api(route(retained),undefined,'manager');let initial;
 await readOnly('actual M01 independent manage/read and precise management views',async()=>{
  for(const [actor,read,manage] of [['manager',true,true],['maintainer',false,true],['reader',true,false]]){const listing=await api(base,undefined,actor);same(listing.scopes.map(s=>s.scope_id),[retained,empty,noCourses,removed,partial,limit],'Scope list contains only explicitly authorized institutions');check(listing.scopes.every(s=>s.can_read===read&&s.can_manage===manage),'M01 capabilities are independent for '+actor);}
  for(const actor of ['anonymous','admin','unbound','reader','other']){const status=actor==='anonymous'?401:403;await denied(route(retained)+'/certification-management',undefined,actor,status,'No implicit certification manage via role or another institution');await denied(route(retained)+'/certifications-preview',{},actor,status,'Preview checks live authorization before request fields');}
  await denied(route(retained),undefined,'maintainer',403,'Manage-only does not gain original catalog read');same((await api(base,undefined,'other')).scopes.map(s=>s.scope_id),[other],'Other institution remains isolated');
  initial=await management(retained);viewCheck(initial,retained,'001',1,{courses:2,teachers:2,bindings:2},['SYN-T1','SYN-T2']);same(initial.certifications,original.catalog.certifications,'Initial evidence matches exact stored source snapshot');same(initial.courses,original.catalog.courses,'Course options are unchanged saved courses, including disabled course');
  viewCheck(await management(empty),empty,'002',0,{courses:0,teachers:0,bindings:0},[]);same((await management(empty)).catalog_version,null,'Version zero has no implied source material');
  viewCheck(await management(noCourses),noCourses,'004',1,{courses:0,teachers:2,bindings:2},['SYN-T1','SYN-T2']);viewCheck(await management(removed),removed,'005',2,{courses:2,teachers:0,bindings:0},[]);viewCheck(await management(partial),partial,'006',2,{courses:2,teachers:1,bindings:1},['SYN-T1']);
  const q=await qualify(retained,1,'SYN-001');same(q.eligible.map(r=>r.teacher_code),['SYN-T1'],'Actual initial certified teacher is eligible before maintenance');
 });
 await readOnly('concurrent read responses preserve per-request institution and authorization',async()=>{
  const requested=[{scope:retained,actor:'maintainer',status:200},{scope:other,actor:'other',status:200},{scope:retained,actor:'other',status:403},{scope:retained,actor:'anonymous',status:401}];
  const responses=await Promise.all(requested.map(q=>request(route(q.scope)+'/certification-management',undefined,q.actor)));
  fs.writeFileSync(path.join(own,'concurrent-permissions.json'),JSON.stringify({requests:requested,responses:responses.map(r=>({status:r.status,envelope:r.envelope}))},null,2),{mode:0o600});
  for(let i=0;i<requested.length;i++){check(responses[i].status===requested[i].status,'Concurrent response keeps its own authorization status');if(requested[i].status===200)check(responses[i].envelope?.data?.scope_id===requested[i].scope,'Concurrent authorized read keeps its own scope');else check(!responses[i].envelope?.data,'Concurrent denied request receives no other request data');}
 });
 const updated=[cert('SYN-T1','SYN-001','revoked','SYNTHETIC-REVOCATION','2026-01-01','2026-12-31'),cert('SYN-T2','SYN-002','not_certified'),cert('SYN-T2','SYN-001','certified','SYNTHETIC-EXPIRED','2025-01-01','2025-12-31'),cert('SYN-T1','SYN-002','certified','SYNTHETIC-UNDATED')],edit=body(1,updated,'v2-a');
 await readOnly('strict inputs no pair removal and no invalid batch writes',async()=>{
  for(const field of ['courses','teachers','bindings','catalog','teacher_codes','teacher_id','organization_code'])await denied(route(retained)+'/certifications-preview',{...edit,[field]:[]},'maintainer',400,'Client cannot inject retained '+field);
  for(const value of [-1,1.5,'1',null])await denied(route(retained)+'/certifications-preview',{...edit,expected_version:value},'maintainer',400,'Expected version has strict JSON integer type');await denied(route(retained)+'/certifications-preview',{...edit,expected_version:0},'maintainer',409,'Stale snapshot cannot be staged');
  await denied(route(retained)+'/certification-management?x=1&%78=2',undefined,'maintainer',400,'Management accepts no query override or encoded duplicate');await denied(route(retained)+'/certifications-preview?x=1',edit,'maintainer',400,'Preview accepts no query facts');await denied(route(retained)+'/certification-management',{},'maintainer',405,'Management is read only');await denied(route(retained)+'/certifications-preview',undefined,'maintainer',405,'Certification preview is POST only');await denied(route(retained)+'/certifications-preview',JSON.stringify(edit),'maintainer',415,'Preview enforces JSON media',{raw:true,contentType:'text/plain'});
  for(const list of [initial.certifications.slice(1),initial.certifications.map((c,i)=>i?c:{...c,teacher_code:'SYN-T2'}),initial.certifications.map((c,i)=>i?c:{...c,course_code:'SYN-002'})])await denied(route(retained)+'/certifications-preview',{...edit,certifications:list},'maintainer',409,'Existing teacher/course key cannot be deleted or swapped');
  for(const list of [initial.certifications,[...initial.certifications].reverse()])await denied(route(retained)+'/certifications-preview',{...edit,certifications:list},'maintainer',409,'Unchanged evidence or row reorder does not create a batch');
  const invalid=[{...edit,certifications:[...updated,updated[0]]},{...edit,certifications:updated.map((c,i)=>i?c:{...c,status:'approved'})},{...edit,certifications:updated.map((c,i)=>i===2?{...c,source_ref:''}:c)},{...edit,certifications:updated.map((c,i)=>i===2?{...c,valid_from:'2025-02-30'}:c)},{...edit,certifications:updated.map((c,i)=>i===2?{...c,valid_from:'2026-01-01'}:c)},{...edit,certifications:updated.map((c,i)=>i===2?{...c,source_ref:'SYNTHETIC\nINJECTED'}:c)},{...edit,certifications:updated.map((c,i)=>i?c:{...c,teacher_name:'SYNTHETIC FORBIDDEN'})},{...edit,certifications:[...updated,cert('SYN-FOREIGN','SYN-001')]},{...edit,certifications:[...updated,cert('SYN-T1','SYN-FOREIGN')]},{...edit,certifications:null},{...edit,catalog_version:''}];
  for(const requestBody of invalid)await invalidPreview(retained,requestBody,'Invalid state/source/date/pair/shape is returned as issues without accepted data');
  await denied(route(retained)+'/certifications-preview',{...edit,catalog_version:initial.catalog_version},'maintainer',409,'An already published source version cannot be reused');
 });
 await readOnly('empty and historical-only scopes cannot invent or revive identities',async()=>{
  await denied(route(empty)+'/certifications-preview',body(0,[],'zero-noop'),'maintainer',409,'Empty certification list alone cannot configure a zero-version scope');
  await invalidPreview(empty,body(0,[cert('SYN-T1','SYN-001')],'zero-forbidden'),'Zero version cannot create coded teachers/courses');await invalidPreview(noCourses,body(1,[cert('SYN-T1','SYN-001')],'no-courses'),'Current teachers cannot authorize absent courses');await invalidPreview(removed,body(2,[cert('SYN-T1','SYN-001')],'removed'),'Historical permanent bindings cannot resurrect absent current teacher');
  const current=await management(partial);await invalidPreview(partial,body(2,[...current.certifications,cert('SYN-T2','SYN-001')],'partial-forbidden'),'Historical second teacher is not a selectable current coded teacher');
 });
 const many=[];for(const teacher of ['SYN-T1','SYN-T2'])for(let i=0;i<2500;i++)many.push(cert(teacher,'SYN-LIMIT-'+i));
 await readOnly('5001 unique valid-reference rows exceed original table limit',async()=>{const p=await invalidPreview(limit,body(1,[...many,cert('SYN-T1','SYN-LIMIT-2500')],'5001'),'Too many certification pairs are not stored');check(p.issues.some(i=>i.code==='LIMIT'),'5001 boundary fails the row count, not a duplicate or reference trick');});
 const boundary=await onlyBatch('5000 unique valid-reference certification pairs',()=>preview(limit,body(1,many,'5000')));previewCheck(boundary,limit,'007',1);check(boundary.counts.certifications===5000&&boundary.changes.certifications.added.length===5000,'Exactly 5000 current coded pairs are accepted without publishing');
 const staged=await onlyBatch('revocation evidence dates and new pairs preview',()=>preview(retained,edit));previewCheck(staged,retained,'001',1);same(staged.data.courses,original.catalog.courses,'Preview copies saved courses unchanged');same(staged.data.teachers,original.catalog.teachers,'Preview copies saved teacher metadata unchanged');same(staged.data.certifications,updated,'All four statuses and original date strings are retained exactly');check(staged.issues.some(i=>i.code==='VALIDITY_UNSPECIFIED'),'Certified unknown date boundaries remain a warning, never default dates');same(staged.changes.certifications,{added:['SYN-T2/SYN-001','SYN-T1/SYN-002'],updated:['SYN-T1/SYN-001','SYN-T2/SYN-002'],removed:[]},'Preview reports only explicit certification pair additions and updates');
 const competing=await onlyBatch('same-head competing certification preview',()=>preview(retained,body(1,updated,'v2-b')));
 await readOnly('original confirmation ownership and no automatic publication',async()=>{same(await management(retained),initial,'Previews never publish certification facts');for(const actor of ['reader','colleague','other'])await denied(route(retained)+'/confirm',command(staged.batch_id,1),actor,403,'Original preview account/person and institution own confirmation');await denied(route(other)+'/confirm',command(staged.batch_id,1),'other',404,'Another valid scope cannot retrieve this batch');});
 await control('teacher-change');await readOnly('current teacher facts are rechecked and never silently refreshed',async()=>{same((await management(retained)).certifications,initial.certifications,'Management remains read-only over old accepted certification source');await denied(route(retained)+'/certifications-preview',{...edit,catalog_version:'synthetic-no-metadata-refresh'},'maintainer',409,'Certification maintenance cannot rewrite saved teacher metadata');await denied(route(retained)+'/confirm',command(staged.batch_id,1),'maintainer',409,'Original pending batch cannot confirm changed teacher facts');});await control('teacher-restore');
 phase='competing real HTTP confirmations';const preConfirm=await control('snapshot'),pair=await Promise.all([request(route(retained)+'/confirm',command(staged.batch_id,1)),request(route(retained)+'/confirm',command(competing.batch_id,1))]);fs.writeFileSync(path.join(own,'concurrent-confirmations.json'),JSON.stringify({requests:[staged.batch_id,competing.batch_id],responses:pair.map(r=>({status:r.status,envelope:r.envelope}))},null,2),{mode:0o600});same(pair.map(r=>r.status).sort(),[200,409],'One concurrent same-version confirmation wins and one conflicts');for(let i=0;i<pair.length;i++)if(pair[i].status===200)check(pair[i].envelope?.data?.batch_id===[staged.batch_id,competing.batch_id][i],'Successful response belongs to its own requested batch');const winner=pair.find(r=>r.status===200).envelope.data,winningBatch=winner.batch_id,losingBatch=winningBatch===staged.batch_id?competing.batch_id:staged.batch_id;check(winner.status==='CONFIRMED'&&winner.version===2,'Winning confirmation publishes exactly version two');publicationCheck(preConfirm,await control('snapshot'));
 await readOnly('published certification preserves retained objects and affects qualification',async()=>{
  const published=await api(route(retained),undefined,'manager');same(published.catalog.courses,original.catalog.courses,'Confirmation preserves courses and active flags');same(published.catalog.teachers,original.catalog.teachers,'Confirmation preserves coded teacher metadata');same(published.bindings,original.bindings,'Confirmation preserves current explicit bindings');same(published.catalog.certifications,updated,'Confirmation publishes exactly reviewed evidence');same(await api(route(retained)+'/versions/1'),original,'Initial evidence remains readable as an immutable version');
  const q=await qualify(retained,2,'SYN-001');same(q.eligible,[],'Revoked or expired certification is not eligible');check(reasons(q,'SYN-T1').includes('CERTIFICATION_REVOKED')&&reasons(q,'SYN-T2').includes('EXPIRED'),'Original qualifier reports actual revocation and expiry reasons');const inactive=await qualify(retained,2,'SYN-002');check(inactive.ready===false&&inactive.eligible.length===0&&inactive.issues.some(i=>i.code==='COURSE_INACTIVE'),'Even new certified evidence cannot activate a disabled course');
  const history=await api(route(retained)+'/history');same(history.events.map(e=>e.version),[2,1],'Original audit gains exactly one confirmation');same(history.events[0].changes,staged.changes,'Audit contains the exact certification-only diff');const replay=await confirm(retained,winningBatch,1);check(replay.status==='ALREADY_CONFIRMED'&&replay.version===2,'Duplicate confirmation remains idempotent');await denied(route(retained)+'/confirm',command(losingBatch,1),'maintainer',409,'Losing preview cannot overwrite newer evidence');
 });
 const current3=updated.map(c=>c.course_code==='SYN-001'?(c.teacher_code==='SYN-T1'?cert('SYN-T1','SYN-001'):cert('SYN-T2','SYN-001','certified','SYNTHETIC-NEW-CURRENT','2026-01-01','2026-12-31')):c);
 const third=await onlyBatch('unknown status and explicit renewed evidence',()=>preview(retained,body(2,current3,'v3')));previewCheck(third,retained,'001',2);check(third.issues.some(i=>i.code==='UNKNOWN_CERTIFICATION'),'Unknown remains a visible unresolved evidence warning');const thirdBefore=await control('snapshot');check((await confirm(retained,third.batch_id,2)).version===3,'Explicit reviewed renewal produces next version');publicationCheck(thirdBefore,await control('snapshot'));
 await readOnly('unknown is excluded while current explicit certification qualifies',async()=>{const q=await qualify(retained,3,'SYN-001');same(q.eligible.map(r=>r.teacher_code),['SYN-T2'],'Only currently valid explicit certification qualifies');check(reasons(q,'SYN-T1').includes('CERTIFICATION_UNKNOWN'),'Unknown state never counts as qualification');});
 await control('teacher-out');await readOnly('certified teacher still must be currently in roster',async()=>{const q=await qualify(retained,3,'SYN-001');same(q.eligible,[],'Non-active teacher stays ineligible despite saved valid certification');check(reasons(q,'SYN-T2').includes('TEACHER_NOT_ACTIVE'),'Original qualifier rechecks current teacher status');});await control('teacher-in');
 await control('corrupt-certification');await readOnly('corrupt existing source fails closed without auto repair',async()=>{await denied(route(retained)+'/certification-management',undefined,'maintainer',409,'Broken accepted certification reference cannot be projected as editable source');await denied(route(retained)+'/certifications-preview',body(3,current3,'broken-source'),'maintainer',409,'Certification maintenance cannot repair or discard corrupt saved source');});await control('restore-certification');
 const afterFeature=await control('snapshot'),mutable=new Set(['M04_CATALOG_SCOPES','M04_CATALOG_BATCHES','M04_CATALOG_REVISIONS','M04_CATALOG_EVENTS']);same(Object.fromEntries(Object.entries(afterFeature).filter(([n])=>!mutable.has(n))),Object.fromEntries(Object.entries(baseline).filter(([n])=>!mutable.has(n))),'All 45 other tables including users/M01/teacher records/permanent bindings remain unchanged by certification operations');
 const identityPending=await onlyBatch('pending evidence before real M01 configuration change',()=>preview(retained,body(3,current3.map((c,i)=>i?c:{...c,source_ref:'SYNTHETIC NEXT REVIEW'}),'identity-pending'))),beforePolicy=await control('snapshot');
 const config=await api('/organization/config',undefined,'admin'),boundIds=config.configuration.accountBindings.map(binding=>binding.accountId).sort((a,b)=>a-b),policyEvidence=[];let expectedEpochs=await control('device-epochs');
 check(boundIds.length===5&&new Set(boundIds).size===5,'Permission fixture binds exactly five distinct accounts');
 same(expectedEpochs,boundIds.map(user_id=>({user_id,epoch:1})),'Certification operations retain exactly the five initial publication epochs');
 const epochTable=rows=>({count:rows.length,sha256:digest(rows.map(row=>JSON.stringify({epoch:row.epoch,user_id:row.user_id})).sort())});
 async function publishPolicy(previous,next,affected,label){
  const before=await control('snapshot');same(await control('device-epochs'),expectedEpochs,label+': preceding operations preserve the last expected epoch state');
  const changed=new Set(affected),nextEpochs=expectedEpochs.map(row=>({...row,epoch:row.epoch+(changed.has(row.user_id)?1:0)}));
  await api('/organization/config',{expectedVersion:previous,configuration:next},'admin');
  same(await control('device-epochs'),nextEpochs,label+': precisely affected accounts increment once and every other epoch remains unchanged');
  const after=await control('snapshot');same(after,{...before,ORGANIZATION_ACCESS_CONFIG:after.ORGANIZATION_ACCESS_CONFIG,S01_TRUSTED_DEVICE_EPOCHS:epochTable(nextEpochs)},label+': only configuration history and the exact expected device epochs may change');
  check(after.ORGANIZATION_ACCESS_CONFIG.count===before.ORGANIZATION_ACCESS_CONFIG.count+1,label+': exactly one configuration revision is added');
  policyEvidence.push({publication:label,affected_account_ids:[...affected],epochs_before:expectedEpochs,epochs_after:nextEpochs});expectedEpochs=nextEpochs;
 }
 const samePolicy={...config.configuration,version:'synthetic-cert-permissions-v2'};await publishPolicy(config.version,samePolicy,[],'Version-only publication');
 await readOnly('real M01 version publication invalidates pending confirmation',async()=>{await denied(route(retained)+'/confirm',command(identityPending.batch_id,3),'maintainer',409,'Even unchanged grants cannot bypass original preview M01 version');});
 const revoked={...samePolicy,version:'synthetic-cert-permissions-v3',grants:samePolicy.grants.filter(g=>g.roleCode!=='WRITE')};await publishPolicy(samePolicy.version,revoked,boundIds,'Shared grant revocation');
 await readOnly('actual M01 manage revocation and fresh-session permission checks',async()=>{await denied(route(retained)+'/certification-management',undefined,'maintainer',401,'Policy change revokes existing mapped session');await login('maintainer');await denied(route(retained)+'/certification-management',undefined,'maintainer',403,'Fresh login cannot recover removed manage grant');await denied(route(retained)+'/certifications-preview',edit,'maintainer',403,'Fresh session lacks certification write without M01 grant');await denied(route(retained)+'/confirm',command(winningBatch,1),'maintainer',403,'Confirmed batch replay also checks current M01 permission');});
 const restored={...samePolicy,version:'synthetic-cert-permissions-v4'};await publishPolicy(revoked.version,restored,boundIds,'Shared grant restoration');await login('maintainer');await login('manager');
 const afterPolicy=await control('snapshot');same(afterPolicy,{...beforePolicy,ORGANIZATION_ACCESS_CONFIG:afterPolicy.ORGANIZATION_ACCESS_CONFIG,S01_TRUSTED_DEVICE_EPOCHS:epochTable(expectedEpochs)},'Separate permission publications preserve every other table and end at precisely verified device epochs');check(afterPolicy.ORGANIZATION_ACCESS_CONFIG.count===beforePolicy.ORGANIZATION_ACCESS_CONFIG.count+3,'Three explicit policy publications add exactly three revisions');
 await control('revoke-maintainer');await readOnly('session withdrawal applies to new reads writes and replay',async()=>{await denied(route(retained)+'/certification-management',undefined,'maintainer',401,'Revoked session cannot read certification management');await denied(route(retained)+'/certifications-preview',edit,'maintainer',401,'Revoked session denied before stale request');await denied(route(retained)+'/confirm',command(winningBatch,1),'maintainer',401,'Previously confirmed shortcut requires a live session');});await login('maintainer');
 const saved=await management(retained),beforeRestart=await control('snapshot');await stop();const inspected=JSON.parse((await run(java,[...options(true),'com.training.IntegrationCertificationMaintenanceHttpFixture','inspect'],{cwd:repo,env,timeout:20000,maxBuffer:65536})).stdout.trim());same(inspected,beforeRestart,'Stopped Main matches independent full database inspector');await boot(true);await login('maintainer');await login('manager');
 await readOnly('cold restart immutable history and same-actor no-write replay',async()=>{same(await management(retained),saved,'Current evidence and empty dates survive restart exactly');const replay=await confirm(retained,winningBatch,1);check(replay.status==='ALREADY_CONFIRMED'&&replay.version===2&&replay.current_version===3,'Old confirmed batch replays original version without regressing newer evidence');same(await api(route(retained)+'/versions/1'),original,'Historical original evidence remains intact after restart');await denied(route(retained)+'/confirm',command(identityPending.batch_id,3),'maintainer',409,'Pending old identity version stays invalid after restart');});
 const final=await control('snapshot');same(final,beforeRestart,'Restart reads and old confirmation replays change no persistent row');fs.writeFileSync(path.join(own,'database-invariants.json'),JSON.stringify({baseline,after_certification_operations:afterFeature,before_policy:beforePolicy,after_policy:afterPolicy,policy_publications:policyEvidence,before_restart:beforeRestart,final,read_phases:readEvidence},null,2),{mode:0o600});return {read_only_phases:readEvidence.length,tables_per_read_phase:Object.keys(final).length,protected_tables_unchanged:Object.keys(baseline).length-mutable.size,scopes:7,versions:3,current_certification_pairs:4,explicit_policy_revisions:3};
}
let evidence;runChecks().then(value=>{evidence=value;}).catch(error=>{fatal=String(error.message||error).replaceAll(password,'[redacted]');process.exitCode=1;}).finally(async()=>{await stop();const stopped=servicePids.every(pid=>{try{process.kill(pid,0);return false;}catch(e){return e.code==='ESRCH';}});check(stopped,'Every isolated certification-maintenance Main process stopped');const summary={suite:'certification-maintenance-http',checks,failures,...(fatal?{error:fatal}:{}),...(evidence||{}),server_processes_stopped:stopped,production_touched:false,notifications_sent:false,artifacts:own};fs.writeFileSync(path.join(own,'result.json'),JSON.stringify(summary,null,2),{mode:0o600});console.log(JSON.stringify(summary));if(failures.length||fatal)process.exitCode=1;});
