'use strict';
// Administrator inspection through real Main/Auth/M01. Only synthetic isolated H2 and loopback traffic.
const fs=require('node:fs'),path=require('node:path'),net=require('node:net'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {spawn,execFile}=require('node:child_process'),run=require('node:util').promisify(execFile),args={};
for(let i=2;i<process.argv.length;i+=2){assert.ok(['--java','--classes','--fixture-classes'].includes(process.argv[i])&&process.argv[i+1],'Use --java PATH --classes DIRECTORY or CLASSES_DIR');args[process.argv[i]]=process.argv[i+1];}
const java=args['--java']||'java',repo=path.resolve(__dirname,'..'),classes=fs.realpathSync(args['--classes']||process.env.CLASSES_DIR||''),fixtureClasses=args['--fixture-classes']?fs.realpathSync(args['--fixture-classes']):classes;
for(const value of [classes,fixtureClasses])assert.ok(value!==repo&&!value.startsWith(repo+path.sep),'Use independent classes outside repository');assert.ok(fs.existsSync(path.join(fixtureClasses,'com/training/IntegrationAccountPermissionsHttpFixture.class')),'Compile fixture first');
const own=fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'yanxu-account-permissions-http-')),data=path.join(own,'data');fs.mkdirSync(data);const password=crypto.randomBytes(24).toString('hex'),failures=[],pids=[],readEvidence=[],tokens={},env={...process.env,JAVA_TOOL_OPTIONS:'',JDK_JAVA_OPTIONS:'',_JAVA_OPTIONS:'',YANXU_SEMANTIC_PORT:'',YANXU_SEMANTIC_TOKEN:''};
let child,port,ids,checks=0,phase='setup',fatal=null,evidence;const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms)),digest=value=>crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');
function check(ok,label){checks++;if(!ok)failures.push(phase+': '+label);}
function same(a,b,label){let ok=true;try{assert.deepEqual(a,b);}catch{ok=false;}check(ok,label);}
function options(resume=false){return ['-Dbind.address=127.0.0.1','-Dbootstrap.demo=false','-Dbootstrap.admin.password='+password,'-Dlogin.email.mode=legacy','-Dintegration.account.permissions.root='+own,'-Dintegration.account.permissions.resume='+resume,'-Dintegration.account.permissions.empty=true','-Ddata.dir='+data,'-Dsemantic.port=','-Dsemantic.token=','-Daccount.import.manifest=','-Daccount.import.manifest.sha256=','-cp',fixtureClasses+path.delimiter+classes+path.delimiter+path.join(repo,'lib','*')];}
async function request(route,actor='admin',options={}){
 const headers={...(tokens[actor]?{'X-Token':tokens[actor]}:{}),...(options.body!==undefined?{'Content-Type':'application/json'}:{})};const method=options.method||'GET';
 const r=await fetch(`http://127.0.0.1:${port}/api${route}`,{method,headers,body:options.body===undefined?undefined:JSON.stringify(options.body),signal:AbortSignal.timeout(15000)}),text=await r.text();let envelope=null;if(text){try{envelope=JSON.parse(text);}catch{throw new Error('Non-JSON response at '+route+' HTTP '+r.status);}}
 if(route.startsWith('/organization/account-access')){check(r.headers.get('cache-control')==='no-store','Inspection success/error has no-store');check(!text.includes(password)&&!text.includes('pbkdf2$')&&!text.includes(own)&&!text.includes('jdbc:')&&!text.includes('password')&&!text.includes('session_token'),'Inspection never exposes credentials, sessions, database or private paths');check(!envelope?.data?.token&&!r.headers.get('set-cookie')?.match(/^yx_session=[^;]/),'Inspection never creates an impersonated session/cookie');}
 return {status:r.status,text,envelope,headers:r.headers};
}
async function api(route,actor='admin',options={}){const r=await request(route,actor,options);assert.equal(r.status,200,phase+': '+route+' HTTP '+r.status+' '+r.envelope?.msg);assert.equal(r.envelope?.code,0,route);return r.envelope.data;}
async function denied(route,status,label,actor='admin',options={}){const r=await request(route,actor,options);check(r.status===status,label+' (HTTP '+r.status+')');if(options.method!=='HEAD')check(r.envelope?.code===status&&!r.envelope?.data,'Error envelope has no account/configuration details');else same(r.text,'','Error HEAD has no response body');return r;}
async function login(name='admin'){const body={username:name==='admin'?'admin':'synthetic-access-'+name,password};const result=await api('/login',null,{method:'POST',body});tokens[name]=result.token;return result;}
async function boot(resume=false){const listener=net.createServer();await new Promise((resolve,reject)=>{listener.once('error',reject);listener.listen(0,'127.0.0.1',resolve);});port=listener.address().port;await new Promise(resolve=>listener.close(resolve));child=spawn(java,[...options(resume),'com.training.IntegrationAccountPermissionsHttpFixture',String(port)],{cwd:repo,env,stdio:'ignore'});if(child.pid)pids.push(child.pid);let error;child.once('error',e=>{error=e;});for(let i=0;i<180;i++){if(error)throw error;assert.equal(child.exitCode,null,'Synthetic Main exited');try{const r=await fetch(`http://127.0.0.1:${port}/api/me`,{signal:AbortSignal.timeout(1000)});await r.text();if(r.status===401){ids=JSON.parse(fs.readFileSync(path.join(own,'fixture.json'),'utf8'));return;}}catch{}await pause(100);}throw new Error('Synthetic Main startup timeout');}
async function stop(){const running=child;child=null;if(!running||running.exitCode!==null||running.signalCode!==null)return;await new Promise(resolve=>{const timer=setTimeout(()=>{if(running.exitCode===null&&running.signalCode===null)running.kill('SIGKILL');},2000);running.once('exit',()=>{clearTimeout(timer);resolve();});running.kill('SIGTERM');});}
async function control(operation){const nonce=crypto.randomUUID(),tmp=path.join(own,'control-request.next');fs.writeFileSync(tmp,JSON.stringify({nonce,operation}),{mode:0o600});fs.renameSync(tmp,path.join(own,'control-request.json'));for(let i=0;i<250;i++){try{const r=JSON.parse(fs.readFileSync(path.join(own,'control-result.json'),'utf8'));if(r.nonce===nonce&&r.ok)return r.data;}catch{}await pause(20);}throw new Error('Synthetic control timeout: '+operation);}
async function readOnly(label,operation){phase=label;const before=await control('snapshot');await operation();const after=await control('snapshot');same(after,before,'Every PUBLIC table remains unchanged');readEvidence.push({phase:label,tables:Object.keys(before).length,before:digest(before),after:digest(after)});}
const query=(name,organization)=>'/organization/account-access?account_id='+ids.accounts[name]+(organization===undefined?'':'&organization_code='+encodeURIComponent(organization));
const operations=[['demand.read','VIEW'],['demand.write','HANDLE'],['approval.review','HANDLE'],['demand.accept','HANDLE'],['bid.result','HANDLE'],['catalog.read','VIEW'],['catalog.manage','HANDLE'],['delivery.read','VIEW'],['delivery.write','HANDLE'],['delivery.verify','HANDLE'],['reports.read','VIEW'],['reports.export','EXPORT'],['survey.preview','HANDLE'],['summary.read','VIEW'],['summary.edit','HANDLE']];
function schema(value,selected=null){
 same(Object.keys(value).sort(),['configuration_status','configuration_version','decisions','organization_gate_only','organizations','read_only','selected_organization','subject'],'Exact safe inspection DTO');check(value.read_only===true&&value.organization_gate_only===true,'DTO states diagnostic organization-gate-only scope');same(value.selected_organization,selected,'Server reflects exact selected organization');
 same(Object.keys(value.subject).sort(),['account_enabled','account_id','binding_status','home_organization_enabled','name','organization_code','person_code','person_enabled','role_codes','username'],'Subject has only approved account/binding projection');
 check(typeof value.subject.account_enabled==='boolean'&&Array.isArray(value.subject.role_codes)&&value.organizations.every(org=>Object.keys(org).sort().join(',')==='enabled,organization_code'&&typeof org.enabled==='boolean'),'Account and organization enablement are typed booleans');
 if(selected===null)same(value.decisions,[],'No organization selection produces no authorization assertions');else {
  same(value.decisions.map(row=>[row.resource,row.action]),operations,'Only the fifteen currently supported organization gates appear');
  check(value.decisions.every(row=>Object.keys(row).sort().join(',')==='action,allowed,label,matched_rule_ids,reason,resource,status'&&typeof row.allowed==='boolean'&&typeof row.label==='string'&&row.label.length>0&&typeof row.reason==='string'&&row.reason.length>0&&Array.isArray(row.matched_rule_ids)),'Decisions have exact typed explanatory fields');
 }
}
function decision(value,resource,allowed,status,rules=[]){const row=value.decisions.find(row=>row.resource===resource);check(Boolean(row)&&row.allowed===allowed&&row.status===status,resource+' has expected effective result');same(row?.matched_rule_ids,rules,resource+' lists only actual matched rules');}
function allDenied(value,status){check(value.decisions.length===15&&value.decisions.every(row=>row.allowed===false&&row.status===status&&row.matched_rule_ids.length===0),'All current operations fail closed without matched grants');}
async function slowPost(actor,route){const began=Date.now();return new Promise((resolve,reject)=>{const socket=net.createConnection({host:'127.0.0.1',port});let response='',done=false;const timer=setTimeout(()=>finish(new Error('Incomplete POST was read before preflight')),2500);function finish(error,value){if(done)return;done=true;clearTimeout(timer);socket.destroy();error?reject(error):resolve(value);}socket.on('error',error=>finish(error));socket.on('data',chunk=>{response+=chunk.toString();if(response.includes('\r\n\r\n')){const status=Number(/^HTTP\/1\.1 (\d+)/.exec(response)?.[1]);finish(null,{status,elapsed:Date.now()-began,no_store:/cache-control:\s*no-store/i.test(response)});}});socket.on('connect',()=>socket.write('POST /api'+route+' HTTP/1.1\r\nHost: 127.0.0.1:'+port+'\r\nConnection: close\r\nContent-Type: application/json\r\nContent-Length: 900000\r\n'+(tokens[actor]?'X-Token: '+tokens[actor]+'\r\n':'')+'\r\n{'));});}
async function runChecks(){
 await boot();for(const name of ['admin','admin2','manager','viewer','teacher'])await login(name);const initial=await control('snapshot');
 await readOnly('unpublished configuration is useful subject state',async()=>{const value=await api(query('teacher'));schema(value);same(value.configuration_status,'NOT_CONFIGURED','No configuration is not an endpoint error');same(value.configuration_version,null,'Unpublished configuration has no invented version');same(value.organizations,[],'No invented organization choices');same(value.subject.binding_status,'CONFIG_NOT_PUBLISHED','Unpublished differs from an unbound configured account');same([value.subject.person_code,value.subject.organization_code,value.subject.person_enabled,value.subject.home_organization_enabled,value.subject.role_codes],[null,null,null,null,[]],'Unknown personnel facts stay null/empty');same(value.subject.account_id,ids.accounts.teacher,'Actual selected account is returned without pretending to authenticate it');await denied(query('teacher','001'),400,'Organization cannot be chosen before publication');await denied('/organization/account-access?account_id=999999',404,'Unknown account fails without source disclosure');});
 await readOnly('administrator authentication precedes route query and method',async()=>{
  for(const actor of [null,'manager','viewer','teacher']){const status=actor===null?401:403;await denied('/organization/account-access?account_id=bad&actor_id=1',status,'Bad query cannot bypass caller authority',actor);await denied('/organization/account-access/private?account_id=bad',status,'Unknown child authenticates first',actor);await denied(query('teacher'),status,'HEAD has the same administrator boundary',actor,{method:'HEAD'});}
  await denied('/organization/account-access/private?account_id=bad',404,'Authenticated unknown child is not generic CRUD');await denied('/organization/account-access?account_id=bad',405,'Write method is rejected before query/body','admin',{method:'POST',body:{}});
  // This explicit request uses the real administrator rather than a target identity carried in a body.
  await denied(query('teacher'),405,'POST cannot change selected account or grants','admin',{method:'POST',body:{account_id:1,role:'admin',allowed:true}});
  for(const [actor,expected] of [[null,401],['manager',403],['admin',405]]){const slow=slowPost(actor,query('teacher'));const snapshot=await control('snapshot');check(Object.keys(snapshot).length>0,'Independent lock-controlled read proceeds during incomplete body');const result=await slow;check(result.status===expected&&result.elapsed<2500&&result.no_store,'Incomplete POST returns preflight '+expected+' without waiting for body');}
 });
 phase='real organization configuration publication';const configuration=JSON.parse(fs.readFileSync(path.join(own,'configuration.json'),'utf8'));await api('/organization/config','admin',{method:'POST',body:{expectedVersion:null,configuration}});await control('disable-target');const configuredBaseline=await control('snapshot');
 await readOnly('configured subject identities and live target state',async()=>{
  for(const [name,binding,personEnabled,homeEnabled] of [['teacher','BOUND_ENABLED',true,true],['unbound','UNBOUND',null,null],['binding-off','BOUND_DISABLED',true,true],['person-off','BOUND_ENABLED',false,true],['org-off','BOUND_ENABLED',true,false],['admin','UNBOUND',null,null]]){const value=await api(query(name));schema(value);same(value.configuration_status,'CONFIGURED','Published config state is explicit');same(value.configuration_version,configuration.version,'Projection carries current version');same(value.subject.account_id,ids.accounts[name],'Projection preserves exact selected account');same([value.subject.binding_status,value.subject.person_enabled,value.subject.home_organization_enabled],[binding,personEnabled,homeEnabled],'Binding and person/ancestor state are independent');}
  const value=await api(query('disabled','001'));schema(value,'001');same(value.subject.account_enabled,false,'Current users.status overrides enabled organization binding');same(value.subject.binding_status,'BOUND_ENABLED','Disabled account does not rewrite historical enabled binding');allDenied(value,'ACCOUNT_DISABLED');same(value.organizations,[{organization_code:'001',enabled:true},{organization_code:'002',enabled:true},{organization_code:'003',enabled:true},{organization_code:'010',enabled:false},{organization_code:'011',enabled:false}],'Ancestor disablement is reflected in organization choices');
 });
 let teacher001,combined001,combined002;
 await readOnly('real Engine gates do not borrow caller or other-role scopes',async()=>{
  teacher001=await api(query('teacher','001'));schema(teacher001,'001');decision(teacher001,'delivery.read',true,'ALLOWED',['TEACHER_READ']);decision(teacher001,'approval.review',false,'NOT_CONFIGURED');check(teacher001.decisions.filter(row=>row.allowed).length===1,'Ordinary teacher gets only explicitly granted view');
  decision(await api(query('teacher','002')),'delivery.read',false,'DENIED');combined001=await api(query('combined','001'));combined002=await api(query('combined','002'));schema(combined001,'001');schema(combined002,'002');same(combined001.subject.role_codes,['BP','LEADER'],'Both explicit duties remain visible');decision(combined001,'catalog.manage',true,'ALLOWED',['LEADER_CATALOG']);decision(combined001,'delivery.verify',false,'DENIED');decision(combined001,'approval.review',true,'ALLOWED',['LEADER_APPROVAL']);decision(combined002,'catalog.manage',false,'DENIED');decision(combined002,'delivery.verify',true,'ALLOWED',['BP_VERIFY']);decision(combined002,'approval.review',true,'ALLOWED',['BP_APPROVAL']);
  const deniedTarget=await api(query('denied','001'));decision(deniedTarget,'catalog.read',true,'ALLOWED',['CAT_READ']);decision(deniedTarget,'catalog.manage',false,'DENIED',['BLOCK_MANAGE']);decision(await api(query('parent-only','003')),'catalog.manage',false,'DENIED');
  for(const name of ['binding-off','person-off','org-off'])allDenied(await api(query(name,'001')),'DENIED');for(const name of ['unbound','admin'])allDenied(await api(query(name,'001')),'NOT_CONFIGURED');allDenied(await api(query('teacher','011')),'DENIED');
  const before=await control('session-counts');await api(query('combined','002'));await api(query('denied','001'));same(await control('session-counts'),before,'Reading target decisions never mints any target session');
  const responses=await Promise.all([request(query('teacher','001')),request(query('combined','002')),request(query('denied','001'),'manager'),request(query('teacher','001'),null)]);same(responses.map(r=>r.status),[200,200,403,401],'Parallel subjects and forbidden callers remain isolated');same([responses[0].envelope.data.subject.account_id,responses[1].envelope.data.subject.account_id],[ids.accounts.teacher,ids.accounts.combined],'Parallel successful payloads preserve distinct target identities');
 });
 await readOnly('strict filters and HEAD are read-only',async()=>{
  for(const suffix of ['', '?', '?organization_code=001','?account_id=','?account_id=0','?account_id=-1','?account_id=01','?account_id=1.0','?account_id=1e0','?account_id=9007199254740992','?account_id=%2B1','?account_id=1%20','?account_id=%FF','?account_id=%C0%AF','?account_id=1&account_id=1','?account_id=1&account%5Fid=2','?account_id=1&x=1','?account_id=1&','?account_id=1&&organization_code=001','?account_id=1&organization_code=001&organization%5Fcode=002','?account_id=1&organization_code=','?account_id=1&organization_code=%20001','?account_id=1&organization_code=001%00','?account_id=1&organization_code='+encodeURIComponent("001' OR '1'='1"),'?account_id=1&organization_code=999'])await denied('/organization/account-access'+suffix,400,'Malformed/duplicate/unknown filter rejected');
  same((await api('/organization/account-access?%61ccount_id=%35&organization%5Fcode=001')).subject.account_id,ids.accounts.teacher,'Single valid percent encoding resolves to exact typed filter');await denied('/organization/account-access?account_id=9007199254740991',404,'Safe upper-bound ID parses but does not fabricate an account');
  const head=await request(query('teacher','001'),'admin',{method:'HEAD'});check(head.status===200&&head.text==='','HEAD performs authenticated inspection without response body');await denied('/organization/account-access?account_id=bad',400,'HEAD rejects malformed filters','admin',{method:'HEAD'});await denied(query('teacher'),405,'PUT cannot replace configuration','admin',{method:'PUT',body:{}});
 });
 await control('enable-target');await readOnly('target activation is observed without stale results',async()=>{const value=await api(query('disabled','001'));same(value.subject.account_enabled,true,'Latest target status is loaded on each call');decision(value,'delivery.read',true,'ALLOWED',['TEACHER_READ']);});await control('disable-target');
 await control('corrupt-configuration');await readOnly('corrupt stored configuration fails safely',async()=>{await denied(query('teacher','001'),503,'Invalid stored configuration cannot become a misleading deny/grant');await denied(query('teacher'),503,'No-selection subject view also rejects invalid configuration');await denied(query('teacher','001'),403,'Admin authority is checked before corrupt configuration','manager');});await control('restore-configuration');
 await control('configuration-unavailable');await readOnly('unavailable configuration storage fails closed',async()=>{await denied(query('teacher','001'),503,'Database lookup failure yields no configuration or target evidence');await denied(query('teacher','001'),401,'Anonymous caller cannot learn storage failure',null);});await control('configuration-available');
 await control('downgrade-admin');await readOnly('caller role downgrade is checked on every read',async()=>{await denied(query('teacher','001'),403,'Previously issued admin session is no longer an administrator');await denied(query('teacher'),403,'Downgraded HEAD cannot leak a subject','admin',{method:'HEAD'});});await control('restore-admin');
 await control('disable-admin');await readOnly('caller account disablement invalidates stale session',async()=>{await denied(query('teacher'),401,'Disabled account cannot use previous admin cookie/token');});await control('restore-admin');await login();await control('revoke-admin');await readOnly('explicit caller session withdrawal takes immediate effect',async()=>{await denied(query('teacher'),401,'Withdrawn admin session cannot inspect');});await login();
 // Publish through the existing real administrator API, not a test override of Engine rules.
 const protectedTables=value=>Object.fromEntries(Object.entries(value).filter(([name])=>name!=='ORGANIZATION_ACCESS_CONFIG'));
 same(protectedTables(await control('snapshot')),protectedTables(configuredBaseline),'Restored fixture faults leave all non-configuration tables unchanged before legitimate publication');
 const epochsBefore=await control('device-epochs');
 same(epochsBefore.map(row=>row.user_id),configuration.accountBindings.map(row=>row.accountId).sort((a,b)=>a-b),'Epoch baseline covers exactly the previously configured synthetic bindings');
 await control('enable-target');phase='legitimate configuration change';const revised=structuredClone(configuration);revised.version='synthetic-access-v2';revised.grants=revised.grants.filter(row=>row.ruleId!=='TEACHER_READ');revised.accountBindings=revised.accountBindings.filter(row=>row.accountId!==ids.accounts['parent-only']);await api('/organization/config','admin',{method:'POST',body:{expectedVersion:configuration.version,configuration:revised}});await control('disable-target');
 const publishedBaseline=await control('snapshot');
 same(await control('device-epochs'),epochsBefore.map(row=>({...row,epoch:row.epoch+1})),'Shared permission changes revoke every previous binding exactly once, including the removed binding');
 same(protectedTables(publishedBaseline),protectedTables({...configuredBaseline,S01_TRUSTED_DEVICE_EPOCHS:publishedBaseline.S01_TRUSTED_DEVICE_EPOCHS}),'Legitimate publication changes only configuration history and the precisely checked device epochs');
 let persistent;await readOnly('fresh query uses newly published rules and bindings',async()=>{const value=await api(query('teacher','001'));same(value.configuration_version,revised.version,'No stale configuration is cached');decision(value,'delivery.read',false,'NOT_CONFIGURED');same((await api(query('parent-only','001'))).subject.binding_status,'UNBOUND','Legitimate binding removal appears immediately');persistent=await api(query('combined','002'));decision(persistent,'delivery.verify',true,'ALLOWED',['BP_VERIFY']);});
 const beforeRestart=await control('snapshot');await stop();const offline=JSON.parse((await run(java,[...options(true),'com.training.IntegrationAccountPermissionsHttpFixture','inspect'],{cwd:repo,env,timeout:20000,maxBuffer:65536})).stdout.trim());same(offline,beforeRestart,'Stopped-database inspection matches live whole-table digest');await boot(true);await login();
 await readOnly('cold restart preserves exact diagnostic projection',async()=>{same(await api(query('combined','002')),persistent,'Persisted configuration resolves identically after a new Main process');same((await api(query('teacher','001'))).configuration_version,revised.version,'Latest publication is retained after restart');});
 const final=await control('snapshot');same(final,publishedBaseline,'All tables stay unchanged after the legitimate publication, read-only projections and cold restart');fs.writeFileSync(path.join(own,'database-invariants.json'),JSON.stringify({initial,configured:configuredBaseline,published:publishedBaseline,device_epochs_before:epochsBefore,before_restart:beforeRestart,final,read_phases:readEvidence},null,2),{mode:0o600});fs.writeFileSync(path.join(own,'projection-examples.json'),JSON.stringify({teacher:teacher001,leader_scope:combined001,bp_scope:combined002},null,2),{mode:0o600});return {read_only_phases:readEvidence.length,tables_per_read_phase:Object.keys(final).length,protected_tables:Object.keys(final).length-1,synthetic_accounts:Object.keys(ids.accounts).length};
}
runChecks().then(value=>{evidence=value;}).catch(error=>{fatal=String(error.message||error).replaceAll(password,'[redacted]');process.exitCode=1;}).finally(async()=>{await stop();const stopped=pids.every(pid=>{try{process.kill(pid,0);return false;}catch(error){return error.code==='ESRCH';}});check(stopped,'Every isolated permission-inspection Main process stopped');const summary={suite:'account-permissions-http',checks,failures,...(fatal?{error:fatal}:{}),...(evidence||{}),server_processes_stopped:stopped,production_touched:false,notifications_sent:false,artifacts:own};fs.writeFileSync(path.join(own,'result.json'),JSON.stringify(summary,null,2),{mode:0o600});console.log(JSON.stringify(summary));if(failures.length||fatal)process.exitCode=1;});
