import { tmpdir as testTmpdir } from 'node:os';
import { chromium } from 'playwright';
import { writeFile, readFile, mkdir, mkdtemp, realpath, access } from 'node:fs/promises';
import { createServer } from 'node:net';
import { spawn } from 'node:child_process';
import { dirname, resolve, join, delimiter, sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomBytes } from 'node:crypto';
import assert from 'node:assert/strict';
// Original SPA, real Main and cookie sessions; isolated synthetic H2 only.
const app=resolve(dirname(fileURLToPath(import.meta.url)),'..'), args={};
for(let i=2;i<process.argv.length;i+=2){assert.ok(['--java','--classes'].includes(process.argv[i])&&process.argv[i+1]);args[process.argv[i]]=process.argv[i+1];}
assert.ok(args['--java']&&args['--classes']);const classes=await realpath(args['--classes']);assert.ok(classes!==app&&!classes.startsWith(app+sep));
for(const name of ['Main','IntegrationCourseMaintenanceHttpFixture'])await access(join(classes,'com/training/'+name+'.class'));
const own=await mkdtemp(join(testTmpdir(), 'yanxu-course-maintenance-http-browser-')),password=randomBytes(24).toString('hex'),classpath=classes+delimiter+join(app,'lib','*');
let browser,child,base,fixture,log='',error=null,checks=0;const screenshots=[],browserErrors=[],outsideRequests=[],unexpectedFailures=[],expectedFailures=[],tokens={};
const pause=ms=>new Promise(yes=>setTimeout(yes,ms));const check=(yes,label)=>{assert.ok(yes,label);checks++;};const equal=(a,b,label)=>{assert.deepEqual(a,b,label);checks++;};
async function api(path,body,actor='manager'){const response=await fetch(base+'/api'+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(tokens[actor]?{'X-Token':tokens[actor]}:{})},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(10000)});const value=await response.json();assert.equal(response.status,200,path+': '+value.msg);assert.equal(value.code,0,path+': '+value.msg);return value.data;}
async function boot(width){const data=join(own,'data-'+width);await mkdir(data);for(const key of Object.keys(tokens))delete tokens[key];const listener=createServer();await new Promise(yes=>listener.listen(0,'127.0.0.1',yes));const port=listener.address().port;await new Promise(yes=>listener.close(yes));base='http://127.0.0.1:'+port;
child=spawn(args['--java'],['-Dbind.address=127.0.0.1','-Dbootstrap.demo=false','-Dbootstrap.admin.password='+password,'-Ddata.dir='+data,'-Dintegration.course.maintenance.root='+own,'-Dsemantic.port=','-Dsemantic.token=','-cp',classpath,'com.training.IntegrationCourseMaintenanceHttpFixture',String(port)],{cwd:app,env:{...process.env,YANXU_SEMANTIC_PORT:'',YANXU_SEMANTIC_TOKEN:''},stdio:['ignore','pipe','pipe']});child.stdout.on('data',b=>log=(log+b).slice(-24000));child.stderr.on('data',b=>log=(log+b).slice(-24000));let failure;child.once('error',e=>failure=e);
for(let i=0;i<180;i++){if(failure)throw failure;assert.equal(child.exitCode,null);try{tokens.manager=(await api('/login',{username:'synthetic-course-manager',password},'anonymous')).token;fixture=JSON.parse(await readFile(join(own,'fixture.json'),'utf8'));return;}catch{}await pause(100);}throw Error('Synthetic Main not ready');}
async function stop(){if(!child||child.exitCode!==null||child.signalCode!==null)return;await new Promise(yes=>{const timer=setTimeout(()=>child.kill('SIGKILL'),2500);child.once('exit',()=>{clearTimeout(timer);yes();});child.kill('SIGTERM');});}
async function contextFor(width,actor){const context=await browser.newContext({viewport:{width,height:1000},reducedMotion:'reduce',deviceScaleFactor:1});await context.route('**/*',route=>{const url=new URL(route.request().url());if(url.origin===base){if(url.pathname==='/api/visitor-context')return route.abort();return route.continue();}if(url.protocol==='data:')return route.continue();outsideRequests.push(url.origin);return route.abort();});const response=await context.request.post(base+'/api/login',{data:{username:'synthetic-course-'+actor,password}});equal(response.status(),200,width+' '+actor+' actual cookie login');equal((await response.json()).code,0,'Session valid');const page=await context.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>browserErrors.push(String(e)));page.on('dialog',async d=>{browserErrors.push('native dialog '+d.type());await d.dismiss();});page.on('response',r=>{const path=new URL(r.url()).pathname;if(path.startsWith('/api/')&&r.status()>=400)([401,409].includes(r.status())?expectedFailures:unexpectedFailures).push({width,path,status:r.status()});});return{context,page};}
async function open(page,scope){await page.goto(base+'/#/teachers');await page.locator('#teacher-course-catalog').click();await page.locator('[data-k="scope_id"]').selectOption(String(scope));}
const field=(page,key,row)=>page.locator('[data-maintenance-field="'+key+'"]'+(row===undefined?'':'[data-row="'+row+'"]'));
const action=(page,key)=>page.locator('[data-maintenance-action="'+key+'"]');
const notice=page=>page.locator('[data-maintenance-notice]');
async function editMeta(page,version){await field(page,'catalog_version').fill(version);await field(page,'change_comment').fill('SYNTHETIC 课程新增、名称和启停核对');}
async function ready(page){await field(page,'catalog_version').waitFor();await page.waitForFunction(()=>!document.querySelector('[data-maintenance-field="catalog_version"]')?.disabled);}
async function saved(page){await page.waitForFunction(()=>document.querySelector('[data-maintenance-notice]')?.textContent.includes('已保存，课程资料已刷新'));}
async function noOverflow(page,label){const size=await page.evaluate(()=>({width:innerWidth,page:document.documentElement.scrollWidth,surfaces:[...document.querySelectorAll('.modal,[data-course-maintenance], [data-course-maintenance] .table-wrap')].filter(n=>n.clientWidth).map(n=>[n.clientWidth,n.scrollWidth])}));check(size.page<=size.width+1&&size.surfaces.every(([a,b])=>b<=a+1),label+': '+JSON.stringify(size));}
async function shot(page,name){const path=join(own,name+'.png');await page.screenshot({path,fullPage:false,animations:'disabled'});screenshots.push(path);}
async function verify(width){
const {context,page}=await contextFor(width,'manager'), calls=[];page.on('request',r=>{if(r.url().includes('/api/course-catalog/'))calls.push(r);});
try{
 await open(page,fixture.retained_scope);await ready(page);check(await page.locator('[data-catalog-form="query"]').isVisible(),'Read/manage original qualification remains');check(await field(page,'course_code',0).isDisabled(),'Existing code locked');check(await action(page,'preview').isDisabled(),'No-change preview disabled');const original=await api('/course-catalog/scopes/'+fixture.retained_scope);equal([original.catalog.teachers.length,original.catalog.certifications.length,original.bindings.length],[2,2,2],'Real retained fixture');
 await field(page,'course_name',0).fill('SYNTHETIC 新课程名称与明确说明');await field(page,'active',1).selectOption('false');await editMeta(page,'synthetic-ui-'+width);await action(page,'add').click();await field(page,'course_code',2).fill('NEW-'+width);await field(page,'course_name',2).fill('SYNTHETIC 新增课程');equal(calls.filter(r=>r.method()==='POST').length,0,'Typing never sends preview');await noOverflow(page,'editor '+width);await page.locator('[data-course-maintenance]').evaluate(n=>n.scrollIntoView({block:'start'}));await shot(page,'course-maintenance-editor-'+width);
 await action(page,'preview').click();await page.waitForFunction(()=>document.querySelector('[data-maintenance-notice]')?.textContent.includes('尚未生效'));check(await action(page,'confirm').isEnabled(),'Real saved preview allows separate confirm');equal(calls.filter(r=>r.url().endsWith('/confirm')).length,0,'Preview never confirms itself');check((await page.locator('[data-course-maintenance]').textContent()).includes('保存前'),'Before/after displayed');await noOverflow(page,'preview '+width);await action(page,'confirm').evaluate(n=>n.scrollIntoView({block:'start'}));await shot(page,'course-maintenance-preview-'+width);
 const mask=await page.locator('#modal-mask').elementHandle();await action(page,'confirm').click();await saved(page);check(await mask.evaluate(n=>n===document.querySelector('#modal-mask')),'Save preserves owned modal');const after=await api('/course-catalog/scopes/'+fixture.retained_scope);equal(after.version,2,'Exactly one committed version');for(const key of ['teachers','certifications'])equal(after.catalog[key],original.catalog[key],key+' retained byte-for-value');equal(after.bindings,original.bindings,'Bindings retained');equal(after.catalog.courses.map(r=>r.active),[true,false,true],'Disable and addition persisted');equal(calls.filter(r=>r.url().endsWith('/course-management')).length,2,'Current management reread after confirmation');equal(calls.filter(r=>new URL(r.url()).pathname==='/api/course-catalog/scopes/'+fixture.retained_scope).length,2,'Current read-only directory reread');
 // Draft switching uses the original modal guard; no native confirmation.
 await field(page,'course_name',0).fill('UNSAVED SYNTHETIC');await page.locator('[data-k="scope_id"]').selectOption(String(fixture.empty_scope));await action(page,'stay').click();equal(await field(page,'course_name',0).inputValue(),'UNSAVED SYNTHETIC','Return preserves draft');await page.locator('[data-k="scope_id"]').selectOption(String(fixture.empty_scope));await action(page,'discard').click();await ready(page);check((await notice(page).textContent()).includes('尚无已保存课程'),'Explicit discard selects authorized zero version');await page.locator('#modal-x').click();
 if(width===1280){
  // Unknown confirmation transport: real server commits; only response delivery fails.
  await page.locator('#teacher-course-catalog').click();await page.locator('[data-k="scope_id"]').selectOption(String(fixture.retained_scope));await ready(page);await field(page,'course_name',0).fill('SYNTHETIC response recovery');await editMeta(page,'synthetic-recovery');await action(page,'preview').click();await page.waitForFunction(()=>document.querySelector('[data-maintenance-action="confirm"]')?.disabled===false);let lost=0;
  await page.route('**/api/course-catalog/scopes/'+fixture.retained_scope+'/confirm',async route=>{const response=await route.fetch();equal(response.status(),200,'Unknown-result test actually confirmed on server');lost++;await route.abort('failed');});await action(page,'confirm').click();await page.waitForFunction(()=>document.querySelector('[data-maintenance-notice]')?.textContent.includes('尚未确认'));await page.unroute('**/api/course-catalog/scopes/'+fixture.retained_scope+'/confirm');const batches=calls.filter(r=>r.url().endsWith('/confirm')).map(r=>r.postDataJSON().batch_id);check(await action(page,'preview').isDisabled()&&await field(page,'course_name',0).isDisabled(),'Unknown outcome freezes new preview/input');await action(page,'confirm').click();await saved(page);equal(lost,1,'One real response loss');const retried=calls.filter(r=>r.url().endsWith('/confirm')).at(-1).postDataJSON();equal(retried.batch_id,batches.at(-1),'Idempotent retry uses exact prior batch');equal((await api('/course-catalog/scopes/'+fixture.retained_scope)).version,3,'Unknown retry never creates extra version');
  // Known success plus failed management refresh preserves success wording.
  await field(page,'course_name',0).fill('SYNTHETIC saved refresh failure');await editMeta(page,'synthetic-refresh-failure');await action(page,'preview').click();await page.waitForFunction(()=>document.querySelector('[data-maintenance-action="confirm"]')?.disabled===false);await page.route('**/api/course-catalog/scopes/'+fixture.retained_scope+'/course-management',route=>route.abort('failed'));await action(page,'confirm').click();await page.waitForFunction(()=>document.querySelector('[data-maintenance-notice]')?.textContent.includes('已保存，当前列表刷新失败'));check(await action(page,'confirm').isDisabled(),'Known success cannot reconfirm after refresh failure');await page.unroute('**/api/course-catalog/scopes/'+fixture.retained_scope+'/course-management');await action(page,'refresh').click();await ready(page);equal(await field(page,'course_name',0).inputValue(),'SYNTHETIC saved refresh failure','Explicit refresh recovers confirmed current values');
  // Another real manager wins CAS; old batch cannot overwrite.
  await field(page,'course_name',0).fill('SYNTHETIC stale draft');await editMeta(page,'synthetic-stale');await action(page,'preview').click();await page.waitForFunction(()=>document.querySelector('[data-maintenance-action="confirm"]')?.disabled===false);tokens.colleague=(await api('/login',{username:'synthetic-course-colleague',password},'anonymous')).token;const old=await api('/course-catalog/scopes/'+fixture.retained_scope+'/course-management',undefined,'colleague');old.courses[0].course_name='SYNTHETIC colleague won';const p=await api('/course-catalog/scopes/'+fixture.retained_scope+'/courses-preview',{expected_version:old.version,catalog_version:'synthetic-concurrent',courses:old.courses,change_comment:'SYNTHETIC concurrent course change'},'colleague');await api('/course-catalog/scopes/'+fixture.retained_scope+'/confirm',{batch_id:p.batch_id,expected_version:old.version,confirm:true},'colleague');await action(page,'confirm').click();await page.waitForFunction(()=>document.querySelector('[data-maintenance-notice]')?.textContent.includes('目录版本或师资依据已变化'));equal(await page.locator('[data-maintenance-field]').count(),0,'CAS clears old draft and confirmation');await action(page,'refresh').click();await ready(page);equal(await field(page,'course_name',0).inputValue(),'SYNTHETIC colleague won','Explicit refresh reads winning version');
  // Delayed actual read does not mount into a closed/replaced scope modal.
  await page.locator('#modal-x').click();let release,intercepted=false;const gate=new Promise(yes=>release=yes);await page.route('**/api/course-catalog/scopes/'+fixture.retained_scope+'/course-management',async route=>{const response=await route.fetch();intercepted=true;await gate;try{await route.fulfill({response});}catch{}});await page.locator('#teacher-course-catalog').click();await page.locator('[data-k="scope_id"]').selectOption(String(fixture.retained_scope));for(let i=0;!intercepted&&i<100;i++)await pause(20);check(intercepted,'Delayed result came from real management GET');await page.locator('#modal-x').click();await action(page,'discard').click();release();await pause(100);equal(await page.locator('#modal-mask').count(),0,'Delayed management response cannot reopen closed modal');await page.unroute('**/api/course-catalog/scopes/'+fixture.retained_scope+'/course-management');
 }
}finally{await context.close();}
 const write=await contextFor(width,'maintainer'),requests=[];write.page.on('request',r=>{if(r.url().includes('/api/course-catalog/'))requests.push(r);});try{
 await open(write.page,fixture.empty_scope);await ready(write.page);check(!await write.page.locator('[data-catalog-form="query"]').count(),'Manage-only has no qualification');const count=width===1280?21:1;for(let i=0;i<count;i++){await action(write.page,'add').click();await field(write.page,'course_code',i).fill('FIRST-'+i);await field(write.page,'course_name',i).fill('SYNTHETIC 首批课程 '+i);}if(count>20){await action(write.page,'previous').click();equal(await field(write.page,'course_name',0).inputValue(),'SYNTHETIC 首批课程 0','Real pagination retains draft');await field(write.page,'course_name',0).fill('SYNTHETIC 第一页修改');await action(write.page,'next').click();equal(await field(write.page,'course_code',20).inputValue(),'FIRST-20','Second page remains');}
 await editMeta(write.page,'first-version-'+width);await action(write.page,'preview').click();await write.page.waitForFunction(()=>document.querySelector('[data-maintenance-action="confirm"]')?.disabled===false);await action(write.page,'confirm').click();await saved(write.page);const first=await api('/course-catalog/scopes/'+fixture.empty_scope);equal(first.version,1,'Authorized first version persisted');equal(first.catalog.courses.length,count,'All pages saved');equal(first.catalog.teachers,[],'First version invents no teachers');equal(requests.filter(r=>/^\/api\/course-catalog\/scopes\/\d+$/.test(new URL(r.url()).pathname)||r.url().endsWith('/qualify')).length,0,'Manage-only never requests protected read/qualify');await noOverflow(write.page,'manage-only '+width);
 await write.page.locator('[data-k="scope_id"]').selectOption(String(fixture.empty_courses_scope));await ready(write.page);check((await write.page.locator('[data-course-maintenance]').textContent()).includes('保留 2 位师资'),'Published empty-course catalog retains teachers');await action(write.page,'add').click();await field(write.page,'course_code',0).fill('RETAIN-FIRST');await field(write.page,'course_name',0).fill('SYNTHETIC 有师资首课');await editMeta(write.page,'retained-first-'+width);await action(write.page,'preview').click();await write.page.waitForFunction(()=>document.querySelector('[data-maintenance-action="confirm"]')?.disabled===false);await action(write.page,'confirm').click();await saved(write.page);const retained=await api('/course-catalog/scopes/'+fixture.empty_courses_scope);equal([retained.catalog.teachers.length,retained.bindings.length],[2,2],'Adding first course retains existing teacher-only snapshot');
 equal((await write.context.request.post(base+'/api/logout',{data:{}})).status(),200,'Real logout');await action(write.page,'refresh').click();await write.page.waitForFunction(()=>!document.querySelector('#modal-mask'));equal(await write.page.locator('[data-course-maintenance]').count(),0,'Expired cookie clears course maintenance');
 }finally{await write.context.close();}
 const read=await contextFor(width,'reader'),reads=[];read.page.on('request',r=>reads.push(r.url()));try{await open(read.page,fixture.retained_scope);await read.page.locator('[data-catalog-form="query"]').waitFor();equal(await read.page.locator('[data-course-maintenance]').count(),0,'Read-only original view has no editor');equal(reads.filter(url=>url.endsWith('/course-management')||url.endsWith('/courses-preview')).length,0,'Read-only sends no management request');await noOverflow(read.page,'readonly '+width);}finally{await read.context.close();}
}
try{browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || undefined,headless:true});for(const width of [1280,390,320]){await boot(width);await verify(width);await stop();}equal(browserErrors,[],'No browser errors/native dialogs');equal(outsideRequests,[],'No outside requests');equal(unexpectedFailures,[],'No unexpected API failure');}catch(e){error=e;}finally{await browser?.close();await stop();await writeFile(join(own,'server.log'),log.replaceAll(password,'[synthetic password redacted]'),{mode:0o600});const result={ok:!error,checks,classes,temporaryDirectory:own,screenshots,browserErrors,outsideRequests,unexpectedFailures,expectedFailures,temporaryServiceStopped:!child||child.exitCode!==null||child.signalCode!==null,...(error?{error:error.stack||String(error)}:{})};await writeFile(join(own,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));}if(error)process.exitCode=1;
