'use strict';
// Actual original users page, modal, API and provisioning module; synthetic data and transport only.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const base=fs.readFileSync(path.join(__dirname,'IntegrationAccountBindingsUI.test.cjs'),'utf8');
const support=vm.runInNewContext(base.slice(0,base.indexOf('(async () => {')).replace('pages.replace(','pages.replaceAll(')+'\n({harness,NodeStub,fixture});',{require,__dirname,console,structuredClone,AbortController,setImmediate});
const moduleSource=fs.readFileSync(path.join(__dirname,'../web/modules/identity/account-provisioning.js'),'utf8');
let checks=0;const check=(v,l)=>{assert.ok(v,l);checks++;},equal=(v,e,l)=>{assert.deepEqual(JSON.parse(JSON.stringify(v)),e,l);checks++;},tick=()=>new Promise(r=>setImmediate(r)),deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};};
const endpoint='/api/organization/account-provisioning';
function sample(size=3){const organizations=[{organization_code:'SYN-ROOT',display_name:'合成组织目录',kind:'ROOT',parent_organization_code:null,enabled:true,office_code:null},{organization_code:'SYN-REGION',display_name:'合成区域',kind:'REGION',parent_organization_code:'SYN-ROOT',enabled:true,office_code:null},{organization_code:'SYN-BRANCH',display_name:'合成分公司',kind:'BRANCH',parent_organization_code:'SYN-REGION',enabled:true,office_code:null}];
 const person=(n,role)=>({reference:'synthetic-row-'+n,account_id:n+20,name:n===2||n===3?'合成同名人员':'合成人员 '+n,organization_code:'SYN-BRANCH',organization_name:'合成分公司',account_enabled:false,binding_enabled:false,person_enabled:true,role_codes:['MEMBER',role],role_scopes:[{role_code:'MEMBER',organization_codes:[],organization_names:[]},{role_code:role,organization_codes:['SYN-BRANCH'],organization_names:['合成分公司']}],leader_reference:role==='SUBMITTER'?'synthetic-row-2':null,bp_reference:role==='SUBMITTER'?'synthetic-row-3':null,route_status:role==='SUBMITTER'?'ROUTE_PREPARED':'SELF_REVIEW'});
 const people=Array.from({length:size},(_,i)=>person(i+1,i===1?'BRANCH_RESPONSIBLE':i===2?'BP':'SUBMITTER'));
 const grants=['BRANCH_RESPONSIBLE','BRANCH_LEAD','BP'].flatMap(role=>[{rule_id:role+'-read',role_code:role,resource:'demand.read',action:'VIEW',effect:'ALLOW',scope:'RESPONSIBLE_ORGS'},{rule_id:role+'-review',role_code:role,resource:'approval.review',action:'HANDLE',effect:'ALLOW',scope:'RESPONSIBLE_ORGS'}]);for(const [resource,action]of [['demand.read','VIEW'],['demand.write','HANDLE']])grants.push({rule_id:resource,role_code:'SUBMITTER',resource,action,effect:'ALLOW',scope:'OWN_ORG'});
 return{policy_version:'M01-INITIAL-PROVISIONING-v1',batch_key:'synthetic-batch',source_fingerprint:'a'.repeat(64),intake_revision:1,proposed_version:'SYN-PREPARED-1',review_token:'c'.repeat(64),expires_at:new Date(Date.now()+300000).toISOString(),permissions_published:false,accounts_activated:false,can_operate:false,requires_account_activation:true,office_codes_status:'UNKNOWN',summary:{account_count:size,approval_people_count:2,approval_duties_count:2,ordinary_people_count:size-2,region_count:1,branch_count:1,home_organization_count:0,route_prepared_count:size-2,route_blocked_count:2,route_blocked_counts:{SELF_REVIEW:2},accounts_enabled:0,accounts_disabled:size,bindings_enabled:0},diff:{initial_configuration:true,organizations_added:3,people_added:size,bindings_added:size,enabled_bindings_added:0,grants_added:grants.length,combined_assignments_added:0},validation:{configuration_valid:true},organizations,people,grants,combined_assignments:[],issues:people.filter(p=>p.route_status!=='ROUTE_PREPARED').map(p=>({code:p.route_status,reference:p.reference,organization_code:p.organization_code,message:'请核对本人审批安排'})),warnings:[]};}
function saved(v){return{prepared:true,published:true,policy_version:v.policy_version,batch_key:v.batch_key,source_fingerprint:v.source_fingerprint,intake_revision:v.intake_revision,proposed_version:v.proposed_version,configuration_version:v.proposed_version,configuration_valid:true,permissions_published:true,accounts_activated:false,can_operate:false,account_count:v.summary.account_count,route_prepared_count:v.summary.route_prepared_count,route_blocked_count:v.summary.route_blocked_count,requires_account_activation:true,bindings_enabled:0,sessionInvalidated:false};}
function harness({role='admin',value=sample(),published=false,override,moduleFailure=false,moduleGate}={}){let state={configuration_present:published,configuration_version:published?'SYN-EXISTING':null,account_count:published?value.summary.account_count:0,bindings_enabled:0,can_prepare:!published},controller,host;
 const h=support.harness({configuration:null,fetchOverride:(url,opts,normal,respond)=>{const fallback=()=>{if(url===endpoint)return respond(state);if(url===endpoint+'/preview')return respond(value);if(url===endpoint+'/confirm'){h.configuration=structuredClone(support.fixture());h.configuration.version=value.proposed_version;state={configuration_present:true,configuration_version:value.proposed_version,account_count:value.summary.account_count,bindings_enabled:0,can_prepare:false};return respond(saved(value));}return normal(url,opts);};return override?override(url,opts,fallback,respond,{state:()=>state,set:v=>state=v}):fallback();}});h.sandbox.state.user.role=role;
 vm.runInContext('{'+moduleSource.replace('export function createAccountProvisioning','function createAccountProvisioning')+';globalThis.provisioningModule=createAccountProvisioning;}',h.sandbox);const load=h.sandbox.loadIdentityModule;h.sandbox.loadIdentityModule=async url=>{if(!url.includes('/account-provisioning.js?'))return load(url);h.imports.push(url);if(moduleGate)await moduleGate.promise;if(moduleFailure)throw Error('Synthetic module failure');return{createAccountProvisioning(context){host=context;controller=h.sandbox.provisioningModule(context);return controller;}};};
 h.button=()=>h.content.querySelector('#user-provisioning-open');h.open=()=>h.button().onclick();h.node=k=>h.modal()?.querySelector('[data-provisioning-'+k+']');h.click=k=>h.node(k).onclick();h.view=async key=>{h.node('view').value=key;h.node('view').onchange();await tick();};h.reads=()=>h.calls.filter(c=>c.url===endpoint);h.writes=tail=>h.calls.filter(c=>c.url===endpoint+'/'+tail);h.controller=()=>controller;h.host=()=>host;h.state=()=>state;return h;
}
(async()=>{
 const h=harness();await h.mount();check(h.button()?.textContent==='配置人员岗位','Admin toolbar entry on original users page');equal(h.reads().length,0,'No list-time provisioning request');await h.open();const mask=h.modal();equal(h.reads().length,1,'Opening reads status only');equal(h.writes('preview').length,0,'Status does not automatically prepare');check(!h.node('generate').disabled&&h.node('confirm').disabled,'Explicit generation precedes confirmation');await h.click('generate');equal(JSON.parse(h.writes('preview')[0].opts.body),{},'Preview sends exactly empty object');check(h.node('summary').textContent.includes('3 人')&&h.node('summary').textContent.includes('全部业务绑定保持停用'),'Actual synthetic counts and no activation claim');check(h.node('table').textContent.includes('账号 ID 22')&&h.node('table').textContent.includes('账号 ID 23'),'Same-name people distinguished by receipt account identity');check(!h.modal().textContent.includes('SYN-BRANCH')&&!h.modal().textContent.includes('cccccccc')&&!h.modal().textContent.includes('source_fingerprint'),'Technical identifiers and tokens absent from display');await h.view('issues');check(h.node('table').textContent.includes('本人不能审批本人'),'Every blocked route has ordinary business explanation');equal(h.node('table').querySelectorAll('tr[data-row-id]').length,2,'Blocked rows are complete');await h.view('grants');check(h.node('table').textContent.includes('此岗位明确负责的分公司')&&h.node('table').textContent.includes('本人所属分公司'),'Role range scopes remain distinct');await h.view('organizations');check(h.node('table').textContent.includes('合成分公司'),'Organization names replace technical IDs');equal(h.writes('confirm').length,0,'Viewing never publishes');await h.click('confirm');equal(JSON.parse(h.writes('confirm')[0].opts.body),{batch_key:'synthetic-batch',review_token:'c'.repeat(64)},'Confirm sends only original batch and review token');check(h.modal()===mask&&h.node('notice').textContent.includes('岗位配置已保存')&&h.node('notice').textContent.includes('仍待启用'),'Saved fact retained in original modal');check(h.node('generate').disabled&&h.node('confirm').disabled&&!h.node('table').textContent,'Saved state clears old review and prevents repeat');check(h.node('details').hidden,'Saved state hides unused review controls');equal(h.calls.filter(c=>c.url==='/api/organization/config').length,2,'Save refreshes original binding snapshot');equal(h.calls.filter(c=>c.url==='/api/organization/me').length,2,'Save refreshes original current identity panel');equal(h.invalidations,0,'No inferred global session invalidation');await h.click('close');check(!h.modal(),'Explicit close completes original modal');
 for(const role of ['manager','viewer']){const x=harness({role});await x.mount();check(!x.button(),role+' has no provisioning entry');equal(x.reads().length,0,role+' sends no request');x.sandbox.beginRouteEpoch();}
 const existing=harness({published:true});await existing.mount();await existing.open();check(existing.node('generate').disabled&&existing.node('status').textContent.includes('不能由此覆盖'),'Existing configuration cannot be overwritten');await existing.click('generate');equal(existing.writes('preview').length,0,'Disabled existing-config action cannot POST by direct invocation');existing.controller().destroy();
 const many=harness({value:sample(23)});await many.mount();await many.open();await many.click('generate');equal(many.node('table').querySelectorAll('tr[data-row-id]').length,20,'Review uses twenty-row pages');await many.click('next');equal(many.node('table').querySelectorAll('tr[data-row-id]').length,3,'Remaining rows shown without dropping people');await many.view('issues');equal(many.node('pagination').textContent,'共 2 项 · 第 1 / 1 页','Switch view resets valid page');many.sandbox.closeModal();check(many.node('guard').textContent.includes('尚未保存'),'Unpublished preview uses local close guard');await many.click('stay');check(!many.node('confirm').disabled,'Staying keeps reviewed proposal');many.sandbox.closeModal();await many.click('discard');check(!many.modal(),'Deliberate discard closes only own modal');
 const evil=sample();evil.people[0].name='<img src=x onerror=alert(1)>';evil.warnings=['<script>bad()</script>'];const safe=harness({value:evil});await safe.mount();await safe.open();await safe.click('generate');check(!safe.modal().querySelector('img,script')&&safe.node('table').textContent.includes(evil.people[0].name),'Names and warnings render escaped text');safe.controller().destroy();
 const invalid=[v=>v.policy_version='OTHER',v=>v.source_fingerprint='bad',v=>v.review_token='bad',v=>v.expires_at='bad',v=>v.accounts_activated=true,v=>v.can_operate=true,v=>v.permissions_published=true,v=>v.requires_account_activation=false,v=>v.validation.configuration_valid=false,v=>v.office_codes_status='KNOWN',v=>v.people.pop(),v=>v.people[0].account_id=v.people[1].account_id,v=>v.people[0].reference=v.people[1].reference,v=>v.people[0].role_codes=['MEMBER','ADMIN'],v=>v.people[0].role_scopes[1].organization_codes=['WRONG'],v=>v.people[0].role_scopes[1].organization_names=['WRONG'],v=>v.people[0].leader_reference=v.people[0].reference,v=>v.people[1].leader_reference='synthetic-row-3',v=>v.people[0].binding_enabled=true,v=>{v.people[0].role_scopes[0].organization_codes=['SYN-BRANCH'];v.people[0].role_scopes[0].organization_names=['合成分公司'];},v=>v.people[0].leader_reference='synthetic-row-3',v=>v.issues.pop(),v=>v.issues[0].code='NO_BP',v=>v.organizations[2].parent_organization_code='SYN-BRANCH',v=>v.organizations[1].office_code='GUESS',v=>v.summary.route_blocked_counts.SELF_REVIEW=1,v=>v.summary.accounts_disabled=0,v=>v.diff.enabled_bindings_added=1,v=>v.diff.grants_added=999,v=>v.grants[0].resource='delivery.verify',v=>v.grants[0].scope='ALL',v=>{v.grants.pop();v.diff.grants_added--;},v=>v.grants[0].role_code='SUBMITTER',v=>v.intake_revision='1',v=>v.combined_assignments.push({}),v=>v.warnings=null];for(const mutate of invalid){const value=sample();mutate(value);const x=harness({value});await x.mount();await x.open();await x.click('generate');check(x.node('confirm').disabled&&!x.node('table').textContent,'Incomplete or inconsistent proposal fails closed');x.controller().destroy();}
 for(const bad of [v=>v.can_prepare=false,v=>v.configuration_present=true,v=>v.account_count=-1,v=>v.bindings_enabled=2]){const x=harness({override:async(url,opts,normal,respond)=>{if(url!==endpoint)return normal();const v=JSON.parse(await(await normal()).text()).data;bad(v);return respond(v);}});await x.mount();await x.open();check(x.node('generate').disabled&&!x.node('status').textContent,'Malformed status cannot enable generator');x.controller().destroy();}
 for(const phase of ['read','preview','confirm'])for(const code of [401,403,409,503]){const x=harness({override:(url,opts,normal,respond)=>url===(phase==='read'?endpoint:endpoint+'/'+phase)?respond(null,code):normal()});await x.mount();await x.open();if(phase!=='read'){await x.click('generate');if(phase==='confirm')await x.click('confirm');}if(code===401||code===403)check(!x.modal(),phase+' '+code+' clears private state');else{check(x.node('confirm').disabled&&!x.node('table').textContent,phase+' '+code+' clears former review');if(phase==='confirm'&&code===503)check(x.node('notice').textContent.includes('尚未核实'),'Uncertain server failure never claims non-save');}x.sandbox.beginRouteEpoch();}
 const expired=sample();expired.expires_at='2000-01-01T00:00:00Z';const expiry=harness({value:expired});await expiry.mount();await expiry.open();await expiry.click('generate');check(expiry.node('confirm').disabled,'Expired review cannot be confirmed');expiry.controller().destroy();
 const gate=deferred(),double=harness({override:(url,opts,normal)=>url.endsWith('/confirm')?gate.promise.then(normal):normal()});await double.mount();await double.open();await double.click('generate');const saving=double.click('confirm');await tick();await double.click('confirm');equal(double.writes('confirm').length,1,'Double click has one transaction');check(double.sandbox.closeModal()===false&&double.node('read').disabled,'Confirm prevents close and query race');gate.resolve();await saving;double.controller().destroy();
 const slowGate=deferred(),slow=harness();await slow.mount();await slow.open();const originalSaved=slow.host().onSaved;slow.host().onSaved=async()=>{await slowGate.promise;await originalSaved();};await slow.click('generate');const slowSave=slow.click('confirm');await tick();check(slow.node('read').disabled&&slow.node('generate').disabled,'Post-save parent refresh remains busy');await slow.click('read');await slow.click('generate');await slow.click('next');equal(slow.reads().length,1,'Slow parent refresh cannot be overtaken by new query');equal(slow.writes('preview').length,1,'Slow parent refresh cannot trigger a second proposal');slowGate.resolve();await slowSave;check(slow.node('notice').textContent.includes('已保存'),'Slow parent continuation retains completed result');slow.controller().destroy();
 let breakRefresh=false;const broken=harness({override:(url,opts,normal,respond)=>breakRefresh&&url==='/api/organization/config'?respond(null,503):normal()});await broken.mount();await broken.open();await broken.click('generate');breakRefresh=true;await broken.click('confirm');check(broken.node('notice').textContent.includes('已保存')&&broken.node('notice').textContent.includes('刷新失败'),'Known saved and failed parent refresh are separate facts');check(broken.node('confirm').disabled,'Known save is never offered for retry');broken.controller().destroy();
 for(const committed of [true,false]){const x=harness({override:async(url,opts,normal)=>{if(url.endsWith('/confirm')){if(committed)await normal();throw Error('Synthetic lost response');}return normal();}});await x.mount();await x.open();await x.click('generate');await x.click('confirm');check(x.node('notice').textContent.includes('尚未核实')&&x.node('generate').disabled&&x.node('confirm').disabled,'Unknown result clears token and blocks all writes');await x.click('confirm');equal(x.writes('confirm').length,1,'Unknown token is never resent');await x.click('read');await x.click('discard');await tick();if(committed){check(x.node('notice').textContent.includes('已保存'),'Matching proposed version proves the unknown save');equal(x.calls.filter(c=>c.url==='/api/organization/config').length,2,'Resolved save refreshes original binding snapshot');}else check(!x.node('generate').disabled&&x.node('notice').textContent.includes('尚无'),'Absent configuration permits only a new explicit proposal');x.controller().destroy();}
 const different=harness({override:async(url,opts,normal,respond,remote)=>{if(url.endsWith('/confirm')){remote.set({configuration_present:true,configuration_version:'SOMEONE-ELSE',account_count:3,bindings_enabled:0,can_prepare:false});throw Error('Synthetic unknown');}return normal();}});await different.mount();await different.open();await different.click('generate');await different.click('confirm');await different.click('read');await different.click('discard');await tick();check(different.node('notice').textContent.includes('未将其认作本次保存结果')&&different.node('generate').disabled,'Another version is never mistaken for our publication');different.controller().destroy();
 for(const mutate of [v=>v.published=false,v=>v.permissions_published=false,v=>v.accounts_activated=true,v=>v.bindings_enabled=1,v=>v.configuration_version='OTHER',v=>v.batch_key='OTHER',v=>v.account_count=999,v=>delete v.sessionInvalidated]){const x=harness({override:async(url,opts,normal,respond)=>{const r=await normal();if(!url.endsWith('/confirm'))return r;const v=JSON.parse(await r.text()).data;mutate(v);return respond(v);}});await x.mount();await x.open();await x.click('generate');await x.click('confirm');check(x.node('notice').textContent.includes('尚未核实')&&x.node('confirm').disabled,'Unverified receipt cannot claim save or enable resend');x.controller().destroy();}
 const self=harness({override:async(url,opts,normal,respond)=>{const r=await normal();if(!url.endsWith('/confirm'))return r;const v=JSON.parse(await r.text()).data;v.sessionInvalidated=true;return respond(v);}});await self.mount();await self.open();await self.click('generate');await self.click('confirm');equal(self.invalidations,1,'Explicit validated session invalidation uses original login path');check(!self.modal(),'Session change clears publication details');
 for(const phase of ['read','preview','confirm']){const late=deferred(),x=harness({override:(url,opts,normal)=>url===(phase==='read'?endpoint:endpoint+'/'+phase)?late.promise.then(normal):normal()});await x.mount();let pending;if(phase==='read')pending=x.open();else{await x.open();if(phase==='confirm')await x.click('generate');pending=x.click(phase==='preview'?'generate':'confirm');}await tick();x.sandbox.state.user={uid:99,role:'admin'};late.resolve();await pending;check(!x.modal()&&x.invalidations===0,'Late '+phase+' cannot render or log out a new identity');}
 const late=deferred(),closed=harness({override:(url,opts,normal)=>url.endsWith('/preview')?late.promise.then(normal):normal()});await closed.mount();await closed.open();const pending=closed.click('generate');await tick();closed.sandbox.closeModal();await closed.click('discard');closed.sandbox.openModal('其他窗口','<p>保留</p>');const other=closed.modal();late.resolve();await pending;closed.controller().destroy();check(closed.modal()===other,'Late response and destroy preserve another modal owner');closed.sandbox.closeModal();
 const blocked=harness();await blocked.mount();await blocked.open();await blocked.click('close');blocked.host().openModal=()=>null;await blocked.controller().open();equal(blocked.reads().length,1,'Original close guard refusing modal does not bind or fetch');blocked.controller().destroy();
 const moduleBad=harness({moduleFailure:true});await moduleBad.mount();await moduleBad.open();check(!moduleBad.modal()&&moduleBad.toasts.some(t=>t.message.includes('现有账号仍可维护')),'Optional module failure preserves original account maintenance');equal(moduleBad.reads().length,0,'Module failure makes no provisioning request');
 const importGate=deferred(),importLate=harness({moduleGate:importGate});await importLate.mount();const importing=importLate.open();await tick();importLate.sandbox.beginRouteEpoch();importGate.resolve();await importing;check(!importLate.modal()&&!importLate.reads().length,'Late module import after route change never opens stale dialog');
 const onlyPaths=h.calls.filter(c=>c.url.includes('account-provisioning'));check(onlyPaths.every(c=>!c.url.includes('?')&&['GET','POST'].includes(c.opts.method)),'Provisioning uses only exact contracted routes');
 console.log('Integration account provisioning UI: '+checks+' checks passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
