'use strict';
// New course-only maintenance through real Main/Auth/M01. Synthetic isolated H2; no production data.
const fs=require('node:fs'),path=require('node:path'),net=require('node:net'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {spawn,execFile}=require('node:child_process'),run=require('node:util').promisify(execFile),args={};
for(let i=2;i<process.argv.length;i+=2){assert.ok(['--java','--classes'].includes(process.argv[i])&&process.argv[i+1],'Use --java PATH --classes DIRECTORY or CLASSES_DIR');args[process.argv[i]]=process.argv[i+1];}
const java=args['--java']||'java',repo=path.resolve(__dirname,'..'),classes=fs.realpathSync(args['--classes']||process.env.CLASSES_DIR||'');
assert.ok(classes!==repo&&!classes.startsWith(repo+path.sep),'Use isolated classes outside repository');
assert.ok(fs.existsSync(path.join(classes,'com/training/IntegrationCourseMaintenanceHttpFixture.class')),'Compile the new synthetic fixture into isolated classes first');
const own=fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'yanxu-course-maintenance-http-')),data=path.join(own,'data');fs.mkdirSync(data);
const password=crypto.randomBytes(24).toString('hex'),tokens={},failures=[],servicePids=[],readEvidence=[],base='/course-catalog/scopes';
const env={...process.env,YANXU_SEMANTIC_PORT:'',YANXU_SEMANTIC_TOKEN:''};let child,port,checks=0,phase='setup',fatal=null,ids;
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function check(ok,label){checks++;if(!ok)failures.push(phase+': '+label);}
function same(a,b,label){let ok=true;try{assert.deepEqual(a,b);}catch{ok=false;}check(ok,label);}
function options(resume=false){return ['-Dbind.address=127.0.0.1','-Dbootstrap.demo=false','-Dbootstrap.admin.password='+password,'-Dintegration.course.maintenance.root='+own,'-Dintegration.course.maintenance.resume='+resume,'-Ddata.dir='+data,'-Dsemantic.port=','-Dsemantic.token=','-Daccount.import.manifest=','-Daccount.import.manifest.sha256=','-cp',classes+path.delimiter+path.join(repo,'lib','*')];}
async function request(route,body,actor='maintainer',overrides={}){
 const headers={...(tokens[actor]?{'X-Token':tokens[actor]}:{})};if(body!==undefined)headers['Content-Type']=overrides.contentType||'application/json';
 const r=await fetch(`http://127.0.0.1:${port}/api${route}`,{method:overrides.method||(body===undefined?'GET':'POST'),headers,body:body===undefined?undefined:overrides.raw?body:JSON.stringify(body),signal:AbortSignal.timeout(15000)});
 const text=await r.text();let envelope=null;if(text){try{envelope=JSON.parse(text);}catch{throw new Error(route+': non-JSON HTTP '+r.status);}}
 check(!text.includes(own)&&!text.includes(password),'Response contains no fixture path or password');return {status:r.status,text,envelope,headers:r.headers};
}
async function api(route,body,actor='maintainer'){const r=await request(route,body,actor);assert.equal(r.status,200,phase+': '+route+': '+r.status+': '+r.envelope?.msg);assert.equal(r.envelope?.code,0,route);return r.envelope.data;}
async function denied(route,body,actor,status,label,overrides={}){const r=await request(route,body,actor,overrides);check(r.status===status&&r.envelope?.code===status,label+' (HTTP '+r.status+')');check(!r.envelope?.data&&!r.headers.has('content-disposition'),'Rejected response exposes no partial catalog or download');return r;}
async function login(actor){tokens[actor]=(await api('/login',{username:actor==='admin'?'admin':'synthetic-course-'+actor,password},'anonymous')).token;}
async function boot(resume=false){for(const key of Object.keys(tokens))delete tokens[key];const listener=net.createServer();await new Promise((resolve,reject)=>{listener.once('error',reject);listener.listen(0,'127.0.0.1',resolve);});port=listener.address().port;await new Promise(resolve=>listener.close(resolve));child=spawn(java,[...options(resume),'com.training.IntegrationCourseMaintenanceHttpFixture',String(port)],{cwd:repo,env,stdio:'ignore'});if(child.pid)servicePids.push(child.pid);let error;child.once('error',e=>{error=e;});for(let i=0;i<150;i++){if(error)throw error;assert.equal(child.exitCode,null,'Synthetic Main exited');try{await login('admin');ids=JSON.parse(fs.readFileSync(path.join(own,'fixture.json'),'utf8'));return;}catch{}await pause(100);}throw new Error('Synthetic Main startup timeout');}
async function stop(){const running=child;child=null;if(!running||running.exitCode!==null||running.signalCode!==null)return;await new Promise(resolve=>{const timer=setTimeout(()=>{if(running.exitCode===null&&running.signalCode===null)running.kill('SIGKILL');},2000);running.once('exit',()=>{clearTimeout(timer);resolve();});running.kill('SIGTERM');});}
async function control(operation){const nonce=crypto.randomUUID(),tmp=path.join(own,'control-request.next');fs.writeFileSync(tmp,JSON.stringify({nonce,operation}),{mode:0o600});fs.renameSync(tmp,path.join(own,'control-request.json'));for(let i=0;i<250;i++){try{const ack=JSON.parse(fs.readFileSync(path.join(own,'control-result.json'),'utf8'));if(ack.nonce===nonce&&ack.ok)return ack.data;}catch{}await pause(20);}throw new Error('Synthetic control timeout: '+operation);}
async function readOnly(label,operation){phase=label;const before=await control('snapshot');await operation();const after=await control('snapshot');same(after,before,'Entire PUBLIC schema row digests remain unchanged');readEvidence.push({phase:label,tables:Object.keys(before).length,before:digest(before),after:digest(after)});}
function digest(value){return crypto.createHash('sha256').update(JSON.stringify(value)).digest('hex');}
const route=id=>base+'/'+id,management=id=>api(route(id)+'/course-management'),preview=(id,body)=>api(route(id)+'/courses-preview',body),confirm=(id,batch,version,actor='maintainer')=>api(route(id)+'/confirm',{batch_id:batch,expected_version:version,confirm:true},actor);
const body=(version,courses,tag)=>({expected_version:version,catalog_version:'synthetic-maintenance-'+tag,courses,change_comment:'SYNTHETIC explicit course maintenance '+tag});
function viewCheck(view,id,org,version,counts){same(Object.keys(view).sort(),['can_manage','catalog_version','courses','organization_code','retained_counts','scope_id','version'],'Management DTO exposes exactly course fields and retained counts');check(view.scope_id===id&&view.organization_code===org&&view.version===version&&view.can_manage===true,'Management identifies exact trusted scope/version');same(view.retained_counts,counts,'Retained teacher/certification/binding counts are exact');for(const course of view.courses)same(Object.keys(course).sort(),['active','course_code','course_name'],'Course row excludes teacher identity and bindings');check(!JSON.stringify(view).includes('SYN-T')&&!JSON.stringify(view).includes('SYNTHETIC COURSE TEACHER'),'Management DTO contains no teacher identifiers or names');}
function previewCheck(p,id,org,version){check(p.schema_version==='m04_preview_v1'&&p.ready===true&&p.confirmation_required===true&&typeof p.batch_id==='string','Valid maintenance produces original confirmable preview');check(p.scope_id===id&&p.organization_code===org&&p.current_version===version,'Preview carries exact scope and original version');for(const key of ['teachers','certifications','bindings'])same(p.changes[key],{added:[],updated:[],removed:[]},'Preview has no '+key+' changes');same(p.changes.courses.removed,[],'Course maintenance never removes a code');}
async function onlyBatch(label,operation){phase=label;const before=await control('snapshot'),result=await operation(),after=await control('snapshot');check(after.M04_CATALOG_BATCHES.count===before.M04_CATALOG_BATCHES.count+1,'Ready preview persists exactly one pending batch');for(const name of Object.keys(before))if(name!=='M04_CATALOG_BATCHES')assert.deepEqual(after[name],before[name],label+': only pending batch may change: '+name);check(true,'Preview leaves every non-batch table unchanged');return result;}
async function runChecks(){
 await boot();for(const actor of ['manager','maintainer','reader','colleague','other','unbound'])await login(actor);
 const {retained_scope:retained,empty_scope:empty,empty_courses_scope:emptyCourses,other_scope:other}=ids;
 const baseline=await control('snapshot'),original=await api(route(retained),undefined,'manager'),emptyOriginal=await api(route(emptyCourses),undefined,'manager');let initial;
 await readOnly('real M01 capabilities and manage-only access',async()=>{
  for(const [actor,read,manage] of [['manager',true,true],['maintainer',false,true],['reader',true,false]]){
   const listing=await api(base,undefined,actor);same(listing.scopes.map(s=>s.scope_id),[retained,empty,emptyCourses],'Only authorized synthetic institutions are listed');
   for(const scope of listing.scopes){same(Object.keys(scope).sort(),['can_manage','can_read','organization_code','scope_id','version'],'Scope rows expose independent capabilities');check(scope.can_read===read&&scope.can_manage===manage,'Capabilities follow M01 '+actor+' grants');}
  }
  same((await api(base,undefined,'other')).scopes.map(s=>s.scope_id),[other],'Cross-institution account sees only its own scope');
  for(const actor of ['anonymous','admin','unbound'])await denied(base,undefined,actor,actor==='anonymous'?401:403,'Legacy admin/manager and anonymous have no implicit catalog grant');
  for(const actor of ['reader','other','admin','anonymous']){const status=actor==='anonymous'?401:403;await denied(route(retained)+'/course-management',undefined,actor,status,'Management requires actual same-institution manage');await denied(route(retained)+'/courses-preview',{},actor,status,'POST cannot use read or legacy role as manage');}
  await denied(route(retained),undefined,'maintainer',403,'Manage permission does not imply original catalog read');
  initial=await management(retained);viewCheck(initial,retained,'001',1,{teachers:2,certifications:2,bindings:2});same(initial.courses,original.catalog.courses,'Management reads exact saved courses');
  const zero=await management(empty);viewCheck(zero,empty,'002',0,{teachers:0,certifications:0,bindings:0});same(zero.courses,[],'Zero version is editable empty course list');same(zero.catalog_version,null,'Zero version is unknown catalog version');
  const retainedEmpty=await management(emptyCourses);viewCheck(retainedEmpty,emptyCourses,'004',1,{teachers:2,certifications:0,bindings:2});same(retainedEmpty.courses,[],'Published empty course list retains teacher records');
 });
 const changed=initial.courses.map((c,i)=>({...c,...(i===0?{course_name:'合成课程甲修订'}:{active:false})}));changed.push({course_code:'SYN-003',course_name:'合成新增课程',active:true});const edit=body(1,changed,'revision-2');
 await readOnly('strict course request and no invalid pending batches',async()=>{
  for(const key of ['teachers','certifications','bindings','catalog','organization_code','teacher_id'])await denied(route(retained)+'/courses-preview',{...edit,[key]:[]},'maintainer',400,'Caller cannot inject '+key);
  for(const value of [-1,1.5,'1',null])await denied(route(retained)+'/courses-preview',{...edit,expected_version:value},'maintainer',400,'Expected version must be an actual nonnegative safe integer');
  await denied(route(retained)+'/courses-preview',{...edit,expected_version:0},'maintainer',409,'Stale version cannot stage course edits');
  await denied(route(retained)+'/course-management?scope_id=1&%73cope_id=2',undefined,'maintainer',400,'Unknown/encoded duplicate query cannot override stored scope');
  await denied(route(retained)+'/courses-preview?version=1',edit,'maintainer',400,'Preview takes no query overrides');
  await denied(route(retained)+'/course-management',{},'maintainer',405,'Management read cannot mutate');await denied(route(retained)+'/courses-preview',undefined,'maintainer',405,'Preview requires POST');
  await denied(route(retained)+'/courses-preview',JSON.stringify(edit),'maintainer',415,'Preview only accepts JSON media',{raw:true,contentType:'text/plain'});
  for(const courses of [initial.courses.slice(1),initial.courses.map((c,i)=>i?c:{...c,course_code:'REPLACED-CODE'})])await denied(route(retained)+'/courses-preview',{...edit,courses},'maintainer',409,'Existing course code cannot be deleted or renamed');
  for(const courses of [initial.courses,[...initial.courses].reverse()])await denied(route(retained)+'/courses-preview',{...edit,courses},'maintainer',409,'No-op and reorder alone do not store batches');
  const invalid=[{...edit,courses:[...changed,changed[0]]},{...edit,courses:changed.map((c,i)=>i?c:{...c,active:'true'})},{...edit,courses:changed.map((c,i)=>i?c:{...c,fee_rate:123})},{...edit,catalog_version:''},{...edit,courses:null}];
  for(const requestBody of invalid){const result=await preview(retained,requestBody);check(result.ready===false&&result.batch_id===null&&result.confirmation_required===false&&result.changes===null&&result.data===null&&result.issues.length>0,'Invalid course field yields issues with no accepted catalog or batch');check(result.scope_id===retained&&result.organization_code==='001','Invalid preview still identifies only its authorized scope');}
  const tooMany=Array.from({length:5001},(_,i)=>({course_code:'SYN-LIMIT-'+i,course_name:'合成边界课程 '+i,active:true}));const rejected=await preview(empty,body(0,tooMany,'5001'));check(rejected.ready===false&&rejected.batch_id===null&&rejected.changes===null&&rejected.issues.some(i=>i.code==='LIMIT'),'5001 rows exceed the original core limit');
 });
 const boundary=await onlyBatch('5000 course upper bound',()=>preview(empty,body(0,Array.from({length:5000},(_,i)=>({course_code:'SYN-LIMIT-'+i,course_name:'合成边界课程 '+i,active:true})),'5000')));previewCheck(boundary,empty,'002',0);check(boundary.counts.courses===5000&&boundary.changes.courses.added.length===5000,'Exactly 5000 courses are a valid unconfirmed boundary');
 const newCourses=[{course_code:'0007',course_name:'合成首门课程',active:true},{course_code:'Syn.Mixed_2',course_name:'合成停用课程',active:false}];const first=await onlyBatch('zero version first course preview',()=>preview(empty,body(0,newCourses,'first')));previewCheck(first,empty,'002',0);same(first.data.teachers,[],'First courses do not invent teacher codes');same(first.data.certifications,[],'First courses do not invent certifications');
 await readOnly('original confirmation ownership and scope protections',async()=>{check((await management(empty)).version===0,'Preview has not published zero-version scope');for(const actor of ['reader','colleague','other'])await denied(route(empty)+'/confirm',{batch_id:first.batch_id,expected_version:0,confirm:true},actor,403,'Original confirmer is restricted to preview actor and institution');await denied(route(other)+'/confirm',{batch_id:first.batch_id,expected_version:0,confirm:true},'other',404,'Authorized other scope cannot see this batch');});
 phase='confirm first courses';check((await confirm(empty,first.batch_id,0)).version===1,'Manage-only actor can publish first courses using original confirm');same((await management(empty)).courses,newCourses,'Leading zeros, case and active boolean are saved exactly');
 await readOnly('first confirmation replay is idempotent',async()=>{const replay=await confirm(empty,first.batch_id,0);check(replay.status==='ALREADY_CONFIRMED'&&replay.version===1,'Exact retry returns immutable original confirmation');});
 const emptyFirst=await onlyBatch('first course preserves published teacher-only catalog',()=>preview(emptyCourses,body(1,[{course_code:'SYN-FIRST',course_name:'合成既有师资首课',active:true}],'teacher-only-first')));previewCheck(emptyFirst,emptyCourses,'004',1);same(emptyFirst.data.teachers,emptyOriginal.catalog.teachers,'Published empty course list retains coded teacher metadata');same(emptyFirst.data.certifications,[],'First course does not certify existing teachers');await confirm(emptyCourses,emptyFirst.batch_id,1);const emptyPublished=await api(route(emptyCourses),undefined,'manager');same(emptyPublished.bindings,emptyOriginal.bindings,'Existing permanent bindings survive first course publication');
 const staged=await onlyBatch('rename deactivate and add with frozen retained facts',()=>preview(retained,edit));previewCheck(staged,retained,'001',1);same(staged.data.teachers,original.catalog.teachers,'Preview copies saved teacher metadata exactly');same(staged.data.certifications,original.catalog.certifications,'Preview copies all certifications including unknown status');same(staged.changes.courses,{added:['SYN-003'],updated:['SYN-001','SYN-002'],removed:[]},'Preview reports only requested course changes');
 const competing=await preview(retained,body(1,changed,'competing'));
 await control('teacher-change');await readOnly('current teacher changes block staging and confirmation without metadata refresh',async()=>{same((await management(retained)).courses,initial.courses,'Read remains available without rewriting saved teacher facts');await denied(route(retained)+'/courses-preview',{...edit,catalog_version:'synthetic-metadata-must-not-refresh'},'maintainer',409,'Course-only preview cannot silently update stored teacher metadata');await denied(route(retained)+'/confirm',{batch_id:staged.batch_id,expected_version:1,confirm:true},'maintainer',409,'Changed current teacher facts invalidate original confirmation');});await control('teacher-restore');
 phase='publish retained catalog courses';const confirmed=await confirm(retained,staged.batch_id,1);check(confirmed.status==='CONFIRMED'&&confirmed.version===2,'Original confirmation publishes exactly one new immutable version');
 await readOnly('immutable prior version stale CAS and retained certification history',async()=>{
  await denied(route(retained)+'/confirm',{batch_id:competing.batch_id,expected_version:1,confirm:true},'maintainer',409,'Competing stale batch cannot replace current courses');
  await denied(route(retained)+'/courses-preview',edit,'maintainer',409,'Old snapshot cannot stage another update');
  const published=await api(route(retained),undefined,'manager');same(published.catalog.courses,changed,'Current course list contains only explicit edits');same(published.catalog.teachers,original.catalog.teachers,'Publication retains coded teacher facts byte-for-value');same(published.catalog.certifications,original.catalog.certifications,'Deactivation preserves certification evidence');same(published.bindings,original.bindings,'Publication preserves existing teacher identity bindings');same(await api(route(retained)+'/versions/1'),original,'Prior catalog version remains exact and independently readable');
  const history=await api(route(retained)+'/history');same(history.events.map(e=>e.version),[2,1],'Original audit records one new confirmation');same(history.events[0].changes,staged.changes,'Original audit stores the same course-only changes');
  const qualification=await api(route(retained)+'/qualify',{expected_version:2,request:{course_code:'SYN-002',as_of:'2026-09-23',accepted_levels:[],allowed_cities:[]}},'reader');check(qualification.ready===false&&qualification.eligible.length===0&&qualification.issues.some(i=>i.code==='COURSE_INACTIVE'),'Deactivated course stops original eligibility while retaining history');
  const replay=await confirm(retained,staged.batch_id,1);check(replay.status==='ALREADY_CONFIRMED'&&replay.version===2,'Original confirm remains idempotent after publication');
 });
 await control('corrupt-certification');await readOnly('broken existing certification fails closed without repair',async()=>{await denied(route(retained)+'/course-management',undefined,'maintainer',409,'Bad retained certification reference cannot become an empty editable catalog');await denied(route(retained)+'/courses-preview',body(2,[...changed,{course_code:'SYN-004',course_name:'合成不能覆盖损坏依据',active:true}],'corrupt'),'maintainer',409,'Pure courses cannot repair or discard corrupt retained data');});await control('restore-certification');
 await control('revoke-maintainer');await readOnly('session withdrawal is checked on every new route',async()=>{await denied(route(retained)+'/course-management',undefined,'maintainer',401,'Revoked session cannot read maintenance');await denied(route(retained)+'/courses-preview',edit,'maintainer',401,'Revoked session is denied before stale input');await denied(route(retained)+'/confirm',{batch_id:staged.batch_id,expected_version:1,confirm:true},'maintainer',401,'Already-confirmed shortcut also reauthenticates');});await login('maintainer');
 const beforeRestart=await control('snapshot'),mutable=new Set(['M04_CATALOG_SCOPES','M04_CATALOG_BATCHES','M04_CATALOG_REVISIONS','M04_CATALOG_EVENTS']),protectedBefore={},protectedAfter={};for(const name of Object.keys(baseline))if(!mutable.has(name)){protectedBefore[name]=baseline[name];protectedAfter[name]=beforeRestart[name];}same(protectedAfter,protectedBefore,'Course maintenance preserves all users/M01/teachers/permanent bindings and business tables');
 const savedManagement=await management(retained);await stop();const inspected=JSON.parse((await run(java,[...options(true),'com.training.IntegrationCourseMaintenanceHttpFixture','inspect'],{cwd:repo,env,timeout:20000,maxBuffer:65536})).stdout.trim());same(inspected,beforeRestart,'Offline full database digest matches stopped Main');await boot(true);await login('maintainer');await login('manager');
 await readOnly('cold restart preserves immutable publication and retry',async()=>{same(await management(retained),savedManagement,'Course management retains exact persisted version after restart');const replay=await confirm(retained,staged.batch_id,1);check(replay.status==='ALREADY_CONFIRMED'&&replay.version===2&&replay.current_version===2,'Fresh same-actor session safely replays original confirmation after restart');same(await api(route(retained)+'/versions/1'),original,'Historical catalog and retained facts survive restart');await denied(route(retained)+'/confirm',{batch_id:competing.batch_id,expected_version:1,confirm:true},'maintainer',409,'Unconfirmed old competing batch stays stale after restart');});
 const final=await control('snapshot');same(final,beforeRestart,'Restart and all durable reads/replays leave database unchanged');fs.writeFileSync(path.join(own,'database-invariants.json'),JSON.stringify({baseline,before_restart:beforeRestart,final,read_phases:readEvidence},null,2),{mode:0o600});return {read_only_phases:readEvidence.length,tables_per_read_phase:Object.keys(final).length,protected_tables_unchanged:Object.keys(protectedBefore).length,scopes:4,retained_teachers:2,retained_certifications:2};
}
let evidence;runChecks().then(value=>{evidence=value;}).catch(error=>{fatal=String(error.message||error).replaceAll(password,'[redacted]');process.exitCode=1;}).finally(async()=>{await stop();const stopped=servicePids.every(pid=>{try{process.kill(pid,0);return false;}catch(e){return e.code==='ESRCH';}});check(stopped,'Every isolated course-maintenance Main process stopped');const summary={suite:'course-maintenance-http',checks,failures,...(fatal?{error:fatal}:{}),...(evidence||{}),server_processes_stopped:stopped,production_touched:false,notifications_sent:false,artifacts:own};fs.writeFileSync(path.join(own,'result.json'),JSON.stringify(summary,null,2),{mode:0o600});console.log(JSON.stringify(summary));if(failures.length||fatal)process.exitCode=1;});
