'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const base=fs.readFileSync(path.join(__dirname,'IntegrationSummaryFormalUI.test.cjs'),'utf8').replace("'mountProjectSummary.js'","'mountProjectSummary.photos.js'");
if(process.argv[2]==='--formal'||process.argv[2]==='--legacy'){
 const script=base.replace("if(process.argv[2] === '--legacy')",`if(${process.argv[2]==='--legacy'})`);
 vm.runInNewContext(script,{require,__dirname,console,process,structuredClone,AbortController,DOMException,URL,URLSearchParams,Buffer,setImmediate,Blob,Response});
}else{
const prefix=base.slice(0,base.indexOf('\n(async()=>{'))+'\nglobalThis.helpers={formal,setup,lib,word};\n}';
const env={require,__dirname,console,process:{argv:[]},structuredClone,AbortController,DOMException,URL,URLSearchParams,Buffer,setImmediate,Blob,Response};vm.runInNewContext(prefix,env);const {formal,setup,lib}=env.helpers;
let checks=0;const check=(v,m)=>{assert.ok(v,m);checks++},eq=(a,b,m)=>{assert.deepEqual(JSON.parse(JSON.stringify(a)),b,m);checks++};
const bytes=Buffer.from([137,80,78,71,13,10,26,10,0,1,2,3]),first='a'.repeat(32),second='b'.repeat(32);
const photo=(id=first,caption='合成图注')=>({photo_id:id,caption,width:2,height:2,content_type:'image/png',byte_size:bytes.length});
const view=(photos=[photo()],status='DRAFT',edit=true)=>{const d=formal(status,null,edit);d.photo_policy=d.workflow.photo_policy='PROJECT_UPLOADS_VERSIONED';d.current.photos=photos;return d};
const image=(id=first,override={})=>new Response(bytes,{headers:{'Content-Type':'image/png','Content-Disposition':`attachment; filename="photo-${id}.png"`,'Cache-Control':'no-store','Content-Length':String(bytes.length),...override}});
const upload=(id=second)=>({photo_id:id,project_id:5,width:2,height:2,content_type:'image/png',byte_size:bytes.length,uploaded_at:'2026-09-23T00:00:00Z',replayed:false});
const make=({initial=view(),fetchOverride,writer=false}={})=>{
 const h=setup({initial,writer,fetchOverride:(url,opts,normal,respond,remote)=>{
  const fallback=()=>{const u=new URL(url,'http://local');if(u.pathname.endsWith('/photos/content'))return image(u.searchParams.get('photo_id'));if(u.pathname.endsWith('/photos/upload'))return respond(upload());if(u.pathname.endsWith('/save')){const body=JSON.parse(opts.body),old=remote.get(),next=structuredClone(old);next.version=next.revision=next.latest_version=next.workflow.revision=old.version+1;next.current=lib.revision(next.version,body.content);next.current.photos=body.photos?.map(p=>photo(p.photo_id,p.caption))||old.current.photos;remote.set(next);return respond(next)}return normal()};return fetchOverride?fetchOverride(url,opts,fallback,respond,remote):fallback();
 }});h.sandbox.btoa=s=>Buffer.from(s,'binary').toString('base64');let seq=0;h.sandbox.URL.createObjectURL=()=>`blob:photo-${++seq}`;h.imgReads=()=>h.calls.filter(c=>c.url.includes('/photos/content?'));h.photoSlot=()=>h.modal()?.querySelector('[data-summary-photo-slot]');h.choose=file=>{h.modal().querySelector('[data-summary-photo-file]').files=[file]};h.file=()=>({type:'image/png',size:bytes.length,arrayBuffer:async()=>Uint8Array.from(bytes).buffer});return h;
};
(async()=>{
 const h=make();await h.mount();await h.open();await lib.tick();check(h.photoSlot().textContent.includes('项目总结照片'),'photo policy enables actual photo controls');check(!h.modal().textContent.includes('暂不接入照片文件'),'photo policy corrects placeholder-only intro');eq(new URL(h.imgReads()[0].url,'http://local').searchParams.get('revision'),'1','saved photo preview uses fixed body revision');check(h.photoSlot().querySelector('img')?.src==='blob:photo-1','authorized response becomes local Blob preview');check(h.imgReads()[0].opts.credentials==='same-origin'&&h.imgReads()[0].opts.cache==='no-store','image read uses current same-origin cookie and no-store');
 const caption=h.photoSlot().querySelector('[data-photo-caption="0"]');caption.value=' 修改图注 <script> ';await h.emit(caption,'input');check(h.button('submit').disabled,'photo caption dirty blocks formal submit');await h.click('save');eq(JSON.parse(h.requests('save')[0].opts.body).photos,[{photo_id:first,caption:' 修改图注 <script> '}],'save sends exact ordered ID and caption without metadata');check(h.field('caption0').value==='课堂授课','legacy publicity photoCaptions remain separate');
 h.choose(h.file());await h.click('photo-upload');await lib.tick();const request=JSON.parse(h.requests('photos/upload')[0].opts.body);eq(Object.keys(request).sort(),['content_type','data_base64','expected_version','project_id','request_id'],'upload body excludes paths, names, URL and actor');eq(request.data_base64,bytes.toString('base64'),'upload contains raw Base64 rather than data URL');check(h.imgReads().some(c=>c.url.includes(second)&&new URL(c.url,'http://local').searchParams.get('revision')==='0'),'newly uploaded private draft uses revision0');check(h.button('submit').disabled&&h.modal().textContent.includes('尚未保存到总结版本'),'upload alone does not save body or enable submit');
 await h.emit(h.photoSlot().querySelector('[data-photo-up="1"]'),'click');await h.click('save');eq(JSON.parse(h.requests('save').at(-1).opts.body).photos.map(p=>p.photo_id),[second,first],'photo reorder is saved in exact array order');await h.emit(h.photoSlot().querySelector('[data-photo-remove="0"]'),'click');await h.emit(h.photoSlot().querySelector('[data-photo-remove="0"]'),'click');await h.click('save');eq(JSON.parse(h.requests('save').at(-1).opts.body).photos,[],'explicit empty array removes new revision photos');check(h.revoked.length>0,'rerender revokes old image URLs');h.leave();check(!h.modal(),'route disposal removes photo editor');
 const keep=make();await keep.mount();await keep.open();await keep.edit('issues','只修改正文');await keep.click('save');eq(JSON.parse(keep.requests('save')[0].opts.body).photos,[{photo_id:first,caption:'合成图注'}],'ordinary body save preserves existing references');
 const zero=view([]);zero.version=zero.revision=zero.latest_version=zero.workflow.revision=0;zero.current=null;zero.workflow.capabilities.submit=zero.capabilities.submit=false;zero.workflow.capabilities.refresh_sources=zero.capabilities.refresh_sources=false;const fresh=make({initial:zero});await fresh.mount();await fresh.open();fresh.choose(fresh.file());await fresh.click('photo-upload');eq(JSON.parse(fresh.requests('photos/upload')[0].opts.body).expected_version,0,'new summary can upload against revision0');await fresh.click('save');eq(JSON.parse(fresh.requests('save')[0].opts.body).photos,[{photo_id:second,caption:''}],'new photo joins first saved body revision');
 for(const file of [{type:'image/gif',size:12},{type:'image/png',size:5*1024*1024+1},{type:'image/png',size:1,arrayBuffer:async()=>Uint8Array.of(0).buffer}]){const bad=make();await bad.mount();await bad.open();bad.choose(file);await bad.click('photo-upload');eq(bad.requests('photos/upload').length,0,'invalid upload is rejected before HTTP');}
 const full=make({initial:view(Array.from({length:10},(_,i)=>photo(i.toString(16).padStart(32,'0'))))});await full.mount();await full.open();check(full.button('photo-upload').disabled,'ten photos disables new upload');
 const noEdit=make({initial:view([photo()],'SUBMITTED',false)});await noEdit.mount();await noEdit.open();check(!noEdit.button('photo-upload')&&!noEdit.photoSlot().querySelector('[data-photo-caption]'),'submitted or readonly summary has no mutating photo controls');
 for(const bad of [[photo(),photo()], [{...photo(),photo_id:'../../leak'}], [{...photo(),caption:'x'.repeat(501)}], [{...photo(),content_type:'text/html'}]]){const malformed=make({initial:view(bad)});await malformed.mount();check(!malformed.panel().querySelector('[data-summary-open]'),'invalid frozen photo schema rejected');}
 let firstTry=true;const retry=make({fetchOverride:(url,opts,normal)=>{if(url.endsWith('/photos/upload')&&firstTry){firstTry=false;throw Error('response lost')}return normal()}});await retry.mount();await retry.open();retry.choose(retry.file());await retry.click('photo-upload');check(retry.button('save').disabled&&retry.button('photo-upload').disabled&&!retry.button('retry').disabled,'unknown upload blocks competing mutations');await retry.click('retry');eq(retry.requests('photos/upload')[0].opts.body,retry.requests('photos/upload')[1].opts.body,'upload retry reuses exact request and bytes');check(retry.photoSlot().querySelectorAll('[data-photo-caption]').length===2,'replayed upload does not duplicate photo');
 for(const status of [401,403]){const denied=make({fetchOverride:(url,opts,normal)=>url.includes('/photos/content?')?new Response('{}',{status}):normal()});await denied.mount();await denied.open();await lib.tick();check(!denied.modal(),'photo read '+status+' clears old body and image controls');}
 for(const headers of [{'Content-Type':'text/html'},{'Content-Disposition':'attachment; filename="wrong.png"'},{'Cache-Control':'public'},{'Content-Length':'9000000'}]){const invalid=make({fetchOverride:(url,opts,normal)=>url.includes('/photos/content?')?image(first,headers):normal()});await invalid.mount();await invalid.open();await lib.tick();check(!invalid.photoSlot().querySelector('img'),'invalid binary response never becomes photo');}
 const saved=make({fetchOverride:(url,opts,normal,respond)=>{if(url.includes('/revision?')){const r=lib.revision(1);r.photos=[photo(first,'历史照片图注')];return respond(r)}return normal()}});await saved.mount();await saved.open();await saved.click('preview');await lib.tick();check(saved.modal().querySelector('#summary-revision').textContent.includes('历史照片图注'),'saved preview includes fixed-version photos and caption');check(saved.modal().querySelector('#summary-revision').querySelector('img'),'saved preview uses authorized blob');await saved.click('return');check(saved.revoked.length>0,'leaving historical preview revokes preview URLs');
 const wait=lib.deferred();const late=make({fetchOverride:(url,opts,normal)=>url.includes('/photos/content?')?wait.promise:normal()});await late.mount();await late.open();late.leave();wait.resolve(image());await lib.tick();check(!late.modal()&&late.content.textContent==='后续页面','late photo response cannot restore prior route');
 const unknownIdentity=lib.deferred();const identity=make({fetchOverride:(url,opts,normal)=>url.includes('/photos/content?')?unknownIdentity.promise:normal()});await identity.mount();await identity.open();identity.sandbox.state.user={uid:92,role:'viewer'};unknownIdentity.resolve(image());await lib.tick();check(!identity.modal(),'identity change clears pending authorized photo view');

 for(const status of [401,403,409]){const rejected=make({fetchOverride:(url,opts,normal,respond)=>url.endsWith('/photos/upload')?respond(null,status):normal()});await rejected.mount();await rejected.open();await rejected.edit('issues','上传冲突保留正文');rejected.choose(rejected.file());await rejected.click('photo-upload');if(status===409){check(rejected.field('issues').value==='上传冲突保留正文'&&rejected.button('keep-local'),'upload409 preserves body and demands explicit latest-version reconciliation');check(rejected.photoSlot().querySelector('[data-photo-caption="0"]').value==='合成图注','upload conflict preserves existing photo references')}else check(!rejected.modal(),'upload'+status+' clears local body and photo information');}
 const approvedPhoto=make({initial:view([photo()],'APPROVED',true),writer:true});await approvedPhoto.mount();await approvedPhoto.open();const approvedCaption=approvedPhoto.photoSlot().querySelector('[data-photo-caption="0"]');approvedCaption.value='已批准后更改图注';await approvedPhoto.emit(approvedCaption,'input');check(approvedPhoto.button('export').disabled,'unsaved photo changes cannot export an older approved version as current');await approvedPhoto.emit(approvedPhoto.button('export'),'click');eq(approvedPhoto.requests('export').length,0,'programmatic export also rejects photo dirtiness');
 const longCaption=make();await longCaption.mount();await longCaption.open();const longField=longCaption.photoSlot().querySelector('[data-photo-caption="0"]');longField.value='字'.repeat(501);await longCaption.emit(longField,'input');await longCaption.click('save');eq(longCaption.requests('save').length,0,'caption exceeds500 rejected before save HTTP');
 const savedComparison=make({fetchOverride:(url,opts,normal,respond)=>{if(url.includes('/comparison?')){const before=lib.revision(1),after=lib.revision(2);before.photos=[photo(first,'原图注')];after.photos=[photo(second,'新版图注')];return respond({project_id:5,from_revision:1,to_revision:2,latest_version:2,before,after,read_only:true,synthetic:false,draft_only:true})}if(url.includes('/history?'))return respond({project_id:5,synthetic:false,total:1,offset:0,limit:20,items:[{revision:2,status:'DRAFT',operation:'SAVE',saved_at:'2026-09-23T00:00:00Z'}]});return normal()}});await savedComparison.mount();await savedComparison.open();await savedComparison.click('show-history');const binding=savedComparison.bindings.at(-1);await binding.actions[1].onClick(binding.rows[0]);await lib.tick();check(savedComparison.modal().querySelector('#summary-revision').textContent.includes('原图注')&&savedComparison.modal().querySelector('#summary-revision').textContent.includes('新版图注'),'comparison presents both immutable photo captions separately');check(savedComparison.imgReads().some(c=>c.url.includes(second)&&c.url.includes('revision=2'))&&savedComparison.imgReads().some(c=>c.url.includes(first)&&c.url.includes('revision=1')),'comparison photo fetches remain pinned to each revision');
 const lostUpload=lib.deferred();const disposedUpload=make({fetchOverride:(url,opts,normal)=>url.endsWith('/photos/upload')?lostUpload.promise:normal()});await disposedUpload.mount();await disposedUpload.open();disposedUpload.choose(disposedUpload.file());const uploading=disposedUpload.click('photo-upload');await lib.tick();disposedUpload.leave();lostUpload.resolve(new Response(JSON.stringify({code:0,data:upload()})));await uploading;check(!disposedUpload.modal()&&disposedUpload.content.textContent==='后续页面','late upload response cannot mutate a later route');
 console.log(JSON.stringify({suite:'private-original-summary-photos-ui',checks,status:'passed'}));
})().catch(e=>{console.error(e);process.exitCode=1});
}
