import { tmpdir as testTmpdir } from 'node:os';
import { chromium } from 'playwright';
import { mkdir,mkdtemp,realpath,access,writeFile,readFile,rename } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { createServer } from 'node:net';
import { randomBytes,randomUUID,createHash } from 'node:crypto';
import { dirname,resolve,join,delimiter,sep } from 'node:path';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
// Real original SPA, Main/API and cookie login. Only isolated synthetic fixture data; no business response mocks.
const app=resolve(dirname(fileURLToPath(import.meta.url)),'..'),args={};
for(let i=2;i<process.argv.length;i+=2){assert.ok(['--java','--classes','--fixture-classes'].includes(process.argv[i])&&process.argv[i+1]);args[process.argv[i]]=process.argv[i+1];}
assert.ok(args['--java']&&args['--classes']);const classes=await realpath(args['--classes']);assert.ok(classes!==app&&!classes.startsWith(app+sep));
const fixtureClasses=args['--fixture-classes']?await realpath(args['--fixture-classes']):classes;assert.ok(fixtureClasses!==app&&!fixtureClasses.startsWith(app+sep));
await access(join(classes,'com/training/Main.class'));await access(join(fixtureClasses,'com/training/IntegrationAccountRelationshipsHttpFixture.class'));
const own=await mkdtemp(join(testTmpdir(), 'yanxu-account-relationships-http-browser-')),password=randomBytes(24).toString('hex'),classpath=[fixtureClasses,classes,join(app,'lib','*')].join(delimiter);
const inspectedFiles=['web/app.js','web/modules/identity/account-relationships.js','scripts/IntegrationAccountRelationshipsBrowser.mjs'];
const sourceHashes=async()=>Object.fromEntries(await Promise.all(inspectedFiles.map(async file=>[file,createHash('sha256').update(await readFile(join(app,file))).digest('hex')])));
const testedSourceSha256=await sourceHashes();
let browser,child,base,fixture,error=null,log='',checks=0;const screenshots=[],browserErrors=[],outsideRequests=[],failures=[],contexts=new Set();
const pause=ms=>new Promise(yes=>setTimeout(yes,ms)),check=(value,label)=>{assert.ok(value,label);checks++;},equal=(value,expected,label)=>{assert.deepEqual(value,expected,label);checks++;};
async function control(operation){const nonce=randomUUID();await writeFile(join(own,'control-request.next'),JSON.stringify({nonce,operation}));await rename(join(own,'control-request.next'),join(own,'control-request.json'));for(let i=0;i<150;i++){try{const r=JSON.parse(await readFile(join(own,'control-result.json'),'utf8'));if(r.nonce===nonce){assert.equal(r.ok,true);return r.data;}}catch{}await pause(20);}throw Error('Synthetic control timeout');}
async function boot(label,empty=false){await writeFile(join(own,'control-request.json'),'{}');const data=join(own,'data-'+label);await mkdir(data);const listener=createServer();await new Promise(yes=>listener.listen(0,'127.0.0.1',yes));const port=listener.address().port;await new Promise(yes=>listener.close(yes));base='http://127.0.0.1:'+port;
 child=spawn(args['--java'],['-Dbind.address=127.0.0.1','-Dbootstrap.demo=false','-Dlogin.email.mode=legacy','-Dbootstrap.admin.password='+password,'-Ddata.dir='+data,'-Dintegration.account.relationships.root='+own,'-Dintegration.account.relationships.empty='+empty,'-Dsemantic.port=','-Dsemantic.token=','-cp',classpath,'com.training.IntegrationAccountRelationshipsHttpFixture',String(port)],{cwd:app,env:{...process.env,YANXU_SEMANTIC_PORT:'',YANXU_SEMANTIC_TOKEN:''},stdio:['ignore','pipe','pipe']});child.stdout.on('data',b=>log=(log+b).slice(-24000));child.stderr.on('data',b=>log=(log+b).slice(-24000));let startupError;child.once('error',e=>startupError=e);
 for(let i=0;i<180;i++){if(startupError)throw startupError;assert.equal(child.exitCode,null,'Synthetic Main alive');try{const r=await fetch(base+'/',{signal:AbortSignal.timeout(1000)});if(r.ok){fixture=JSON.parse(await readFile(join(own,'fixture.json'),'utf8'));return;}}catch{}await pause(100);}throw Error('Synthetic Main startup timeout');}
async function stop(){if(!child||child.exitCode!==null||child.signalCode!==null)return;await new Promise(yes=>{const timer=setTimeout(()=>child.kill('SIGKILL'),2500);child.once('exit',()=>{clearTimeout(timer);yes();});child.kill('SIGTERM');});}
async function contextFor(width,actor='admin'){const context=await browser.newContext({viewport:{width,height:1000},deviceScaleFactor:1,reducedMotion:'reduce'});contexts.add(context);await context.route('**/*',route=>{const u=new URL(route.request().url());if(u.origin===base||u.protocol==='data:'){if(u.pathname==='/api/visitor-context')return route.abort();return route.continue();}outsideRequests.push(u.origin);return route.abort();});const response=await context.request.post(base+'/api/login',{data:{username:actor==='admin'?'admin':'synthetic-relation-'+actor,password}});equal(response.status(),200,'Actual cookie login '+actor);equal((await response.json()).code,0,'Cookie login envelope');const page=await context.newPage();page.setDefaultTimeout(12000);page.on('pageerror',e=>browserErrors.push(String(e)));page.on('dialog',async d=>{browserErrors.push('Native '+d.type());await d.dismiss();});page.on('response',r=>{const path=new URL(r.url()).pathname;if(path.startsWith('/api/')&&r.status()>=400)failures.push({width,path,status:r.status()});});return{context,page};}
async function closeContext(context){await context.close();contexts.delete(context);}
async function rowAction(page,id,label){const row=page.locator('#tbl [data-row-id="'+id+'"]'),button=row.getByRole('button',{name:label,exact:true});if(await button.isVisible())await button.click();else{await row.locator('summary').click();await page.getByRole('button',{name:label,exact:true}).click();}}
const part=(page,key)=>page.locator('[data-relationships-'+key+']');
const endpoint=id=>'/organization/account-relationships/'+id;
async function api(context,path,body){const response=await context.request.fetch(base+'/api'+path,{method:body===undefined?'GET':'POST',...(body===undefined?{}:{data:body})});equal(response.status(),200,'Real API '+path.split('/').at(-1));const value=await response.json();equal(value.code,0,'Successful server envelope');return value.data;}
async function ready(page){await page.waitForFunction(()=>document.querySelector('[data-relationships-leader]')?.disabled===false&&document.querySelector('[data-relationships-read]')?.disabled===false);}
async function open(page,key){await rowAction(page,fixture.accounts[key],'维护负责人/BP');await ready(page);}
async function close(page,discard=false){await part(page,'close').click();if(discard&&await part(page,'discard').isVisible())await part(page,'discard').click();await page.locator('#modal-mask').waitFor({state:'detached'});}
async function preview(page){await part(page,'preview').click();await page.waitForFunction(()=>document.querySelector('[data-relationships-confirm]')?.disabled===false);}
async function reread(page,discard=false){await part(page,'read').click();if(discard&&await part(page,'discard').isVisible())await part(page,'discard').click();await ready(page);}
async function saved(page){await page.waitForFunction(()=>document.querySelector('[data-relationships-notice]')?.textContent.includes('已保存')&&document.querySelector('[data-relationships-read]')?.disabled===false);}
async function noOverflow(page,label){const d=await page.evaluate(()=>({width:innerWidth,page:document.documentElement.scrollWidth,surfaces:[...document.querySelectorAll('.modal,[data-relationships-review],[data-relationships-review] .table-wrap,#modal-mask .toolbar')].filter(n=>n.clientWidth).map(n=>[n.clientWidth,n.scrollWidth])}));check(d.page<=d.width+1&&d.surfaces.every(([a,b])=>b<=a+1),label+': '+JSON.stringify(d));}
async function shot(page,name){const path=join(own,name+'.png');await page.screenshot({path,fullPage:false,animations:'disabled'});screenshots.push(path);}
async function tableLeader(page,expected){const cell=page.locator('#tbl [data-row-id="'+fixture.accounts.subject+'"] td[data-label="负责人/BP"]');await cell.waitFor();check((await cell.textContent()).includes('负责人：'+expected),'Original account row reflects saved relationship '+expected);}
async function mainCase(width){const {context,page}=await contextFor(width),calls=[];page.on('request',r=>{if(new URL(r.url()).pathname.startsWith('/api/organization/account-relationships/'))calls.push(r);});try{
 await page.goto(base+'/#/users');await page.locator('#tbl tbody tr').first().waitFor();equal(calls.length,0,'No row-by-row relationship reads');const before=await control('snapshot'),original=await api(context,'/organization/config');await open(page,'subject');equal(await page.locator('#modal-title').textContent(),'维护负责人/BP','Original modal host');equal(await part(page,'leader').inputValue(),'P2','Current leader explicitly retained');equal(await part(page,'bp').inputValue(),'P3','Current BP explicitly retained');const choices=await part(page,'leader').locator('option').allTextContents();check(choices.filter(v=>v.includes('SYNTHETIC SAME DISPLAY NAME')).length===2&&choices.some(v=>v.includes('账号 ID 6'))&&choices.some(v=>v.includes('账号 ID 8')),'Same-name candidates remain distinguishable');const leaderValues=await part(page,'leader').locator('option').evaluateAll(nodes=>nodes.map(n=>n.value)),bpValues=await part(page,'bp').locator('option').evaluateAll(nodes=>nodes.map(n=>n.value));check(leaderValues.includes('P7')&&!bpValues.includes('P7'),'Combined split role range is not merged');check(!leaderValues.includes('P6')&&!bpValues.includes('P6'),'Ordinary teacher is not offered as an approver');equal(calls.filter(r=>r.method()==='POST').length,0,'GET opens without modifying or previewing');
 await part(page,'leader').selectOption('P4');await part(page,'leader').evaluate(n=>n.scrollIntoView({block:'center'}));await noOverflow(page,'editor '+width);await shot(page,'account-relationships-editor-'+width);await preview(page);const body=calls.filter(r=>r.url().endsWith('/preview')).at(-1).postDataJSON();equal(Object.keys(body).sort(),['bp_person_code','expected_version','leader_person_code'],'Preview exact three-key contract');equal([body.leader_person_code,body.bp_person_code],['P4','P3'],'Explicit pair only');check((await part(page,'review').textContent()).includes('账号 ID 6')&&(await part(page,'review').textContent()).includes('账号 ID 8'),'Before/after preserves identities');check((await page.locator('.modal-body').textContent()).includes('不会转派待办'),'Existing assignment limitation shown');await part(page,'review').evaluate(n=>n.scrollIntoView({block:'start'}));await noOverflow(page,'preview '+width);await shot(page,'account-relationships-preview-'+width);equal(await control('snapshot'),before,'GET and preview leave every persisted table unchanged');
 await part(page,'leader').selectOption('P2');check(await part(page,'confirm').isDisabled()&&!(await part(page,'review').textContent()),'Any choice change invalidates prior confirmation');await part(page,'leader').selectOption('P4');await preview(page);await part(page,'confirm').click();await saved(page);equal(Object.keys(calls.filter(r=>r.url().endsWith('/confirm')).at(-1).postDataJSON()),['review_token'],'Confirm sends only its reviewed token');await tableLeader(page,'P4');equal(await part(page,'leader').inputValue(),'P4','Current modal reread after save');const after=await api(context,'/organization/config'),expected=structuredClone(original.configuration);expected.version=after.configuration.version;expected.people.find(p=>p.personCode==='P1').leaderPersonCode='P4';equal(after.configuration,expected,'Only selected person leader and version changed');
 const unchanged=await control('snapshot');await preview(page);await part(page,'confirm').click();await page.getByText('当前关系未变化，无需重复保存。',{exact:true}).waitFor();equal(await control('snapshot'),unchanged,'No-op confirm writes no version');await close(page);await rowAction(page,fixture.accounts.subject,'绑定人员');check((await page.locator('[data-k="bindingLeader"]').inputValue()).includes('P4'),'Next original binding editor uses refreshed relationship snapshot');await page.locator('#modal-x').click();
 await open(page,'invalid-current');equal(await part(page,'leader').inputValue(),'P15','Invalid existing leader not silently replaced');check((await part(page,'current').textContent()).includes('当前不可选'),'Invalid old relation remains explicit');await close(page);await rowAction(page,fixture.accounts.unbound,'维护负责人/BP');await page.waitForFunction(()=>document.querySelector('[data-relationships-notice]')?.textContent.includes('暂不能维护'));check(await part(page,'preview').isDisabled(),'Unbound account cannot edit');await close(page);
 if(width===1280){
  await open(page,'subject');await part(page,'leader').selectOption('P9');await part(page,'bp').selectOption('P9');const preCount=calls.filter(r=>r.url().endsWith('/preview')).length;await part(page,'preview').click();await page.getByText('同一人员兼任负责人和 BP 尚未具备明确依据，请重新选择。',{exact:true}).waitFor();equal(calls.filter(r=>r.url().endsWith('/preview')).length,preCount,'Missing combined evidence does not create review');await part(page,'leader').selectOption('P8');await part(page,'bp').selectOption('P8');await preview(page);check(!await part(page,'confirm').isDisabled(),'Explicit combined evidence can be previewed');await close(page,true);
  await open(page,'intersection');const eligible=await part(page,'leader').locator('option:not([value=""])').evaluateAll(nodes=>nodes.map(n=>n.value));equal(eligible,['P11'],'Candidates satisfy all source-role rules');await close(page);await open(page,'cycle-a');check(!(await part(page,'leader').locator('option').evaluateAll(nodes=>nodes.map(n=>n.value))).includes('P13'),'Cycle-producing candidate excluded');await close(page);
  await control('subject-disable');await open(page,'subject');check((await part(page,'subject').textContent()).includes('账号停用')&&!await part(page,'leader').isDisabled(),'Disabled trusted source may prepare relationships without activation');await close(page);await control('subject-restore');
  await open(page,'subject');await part(page,'leader').selectOption('P2');await preview(page);const pendingConfig=api(context,endpoint(fixture.accounts.subject));const staleEditor=await pendingConfig;const newer=await api(context,endpoint(fixture.accounts.subject)+'/preview',{expected_version:staleEditor.configuration_version,leader_person_code:'P2',bp_person_code:'P3'});await api(context,endpoint(fixture.accounts.subject)+'/confirm',{review_token:newer.review_token});const conflict=page.waitForResponse(r=>r.url().endsWith('/confirm'));await part(page,'confirm').click();equal((await conflict).status(),409,'Actual concurrent version rejects old review');check(await part(page,'confirm').isDisabled()&&await part(page,'leader').isDisabled(),'Stale review cannot be reused');await reread(page);equal(await part(page,'leader').inputValue(),'P2','Explicit read shows concurrent saved relation');await tableLeader(page,'P2');
  await part(page,'leader').selectOption('P4');await preview(page);await control('candidate-disable');const rejected=page.waitForResponse(r=>r.url().endsWith('/confirm'));await part(page,'confirm').click();equal((await rejected).status(),409,'Live candidate account change invalidates reviewed selection');await control('candidate-restore');await reread(page);
  await part(page,'leader').selectOption('P4');await preview(page);const confirmUrl='**/api/organization/account-relationships/'+fixture.accounts.subject+'/confirm';await page.route(confirmUrl,async route=>{const actual=await route.fetch();equal(actual.status(),200,'Unknown-result transaction really saved');await route.abort('failed');});await part(page,'confirm').click();await page.waitForFunction(()=>document.querySelector('[data-relationships-notice]')?.textContent.includes('尚未核实'));check(await part(page,'confirm').isDisabled()&&await part(page,'preview').isDisabled(),'Unknown outcome cannot submit again');const confirmCount=calls.filter(r=>r.url().endsWith('/confirm')).length;await part(page,'confirm').evaluate(n=>n.click());equal(calls.filter(r=>r.url().endsWith('/confirm')).length,confirmCount,'Disabled unknown confirmation makes no retry POST');await page.unroute(confirmUrl);await reread(page,true);equal(await part(page,'leader').inputValue(),'P4','Explicit query recovers actual saved relation');await tableLeader(page,'P4');
  await part(page,'leader').selectOption('P2');await preview(page);await page.route('**/api/organization/config',async route=>{const actual=await route.fetch();equal(actual.status(),200,'Refresh-failure test reads real configuration');await route.abort('failed');});await part(page,'confirm').click();await page.getByText('已保存，账号列表刷新失败，请关闭后刷新用户页。',{exact:true}).waitFor();check(await part(page,'confirm').isDisabled(),'Saved result remains known after parent list refresh failure');await page.unroute('**/api/organization/config');await close(page);await page.reload();await page.locator('#tbl tbody tr').first().waitFor();await tableLeader(page,'P2');await open(page,'subject');
  await part(page,'leader').selectOption('P4');await preview(page);let release,held=false;const gate=new Promise(yes=>release=yes);await page.route('**/api/organization/config',async route=>{const actual=await route.fetch();equal(actual.status(),200,'Slow onSaved uses real parent configuration');held=true;await gate;try{await route.fulfill({response:actual});}catch{}});await part(page,'confirm').click();for(let i=0;!held&&i<100;i++)await pause(20);check(held,'Parent refresh held after actual confirmed write');check(await part(page,'read').isDisabled()&&await part(page,'preview').isDisabled()&&await part(page,'leader').isDisabled(),'Post-save parent refresh prevents new read/edit round');await part(page,'read').evaluate(n=>n.click());await part(page,'preview').evaluate(n=>n.click());release();await saved(page);await page.unroute('**/api/organization/config');equal(await part(page,'leader').inputValue(),'P4','Old save continuation only renders its completed refresh');await part(page,'leader').selectOption('P2');await preview(page);check((await part(page,'review').textContent()).includes('账号 ID 6'),'New round begins safely after prior refresh');await close(page,true);
  await open(page,'subject');await part(page,'leader').selectOption('P2');let lateRelease,lateHeld=false;const lateGate=new Promise(yes=>lateRelease=yes),previewUrl='**/api/organization/account-relationships/'+fixture.accounts.subject+'/preview';await page.route(previewUrl,async route=>{const actual=await route.fetch();equal(actual.status(),200,'Late preview is real server result');lateHeld=true;await lateGate;try{await route.fulfill({response:actual});}catch{}});await part(page,'preview').click();for(let i=0;!lateHeld&&i<100;i++)await pause(20);check(lateHeld,'Real preview held');await close(page,true);await page.evaluate(()=>{location.hash='#/dashboard';});await page.locator('#priority-list').waitFor();lateRelease();await pause(80);equal(await part(page,'review').count(),0,'Late preview never reopens closed target after navigation');await page.unroute(previewUrl);
 }
 check(calls.every(r=>!new URL(r.url()).search),'All relationship paths omit query parameters');
 }finally{await closeContext(context);}
 if(width===1280){const self=await contextFor(width,'admin2');try{await self.page.goto(base+'/#/users');await self.page.locator('#tbl tbody tr').first().waitFor();await open(self.page,'admin2');await part(self.page,'leader').selectOption('P4');await preview(self.page);const response=self.page.waitForResponse(r=>r.url().endsWith('/confirm'));await part(self.page,'confirm').click();const value=(await(await response).json()).data;check(value.saved&&value.sessionInvalidated,'Editing current administrator returns explicit invalidation');await self.page.locator('#login-form').waitFor();equal(await self.page.locator('[data-relationships-subject]').count(),0,'Original login clears all relationship details');equal((await self.context.request.get(base+'/api/me')).status(),401,'Revoked administrator cookie no longer authenticates');}finally{await closeContext(self.context);}
  const viewer=await contextFor(width,'viewer');try{const reads=[];viewer.page.on('request',r=>{if(r.url().includes('/organization/account-relationships/'))reads.push(r.url());});await viewer.page.goto(base+'/#/users');await viewer.page.locator('#priority-list').waitFor();equal(await viewer.page.getByRole('button',{name:'维护负责人/BP',exact:true}).count(),0,'Non-admin has no editing entry');equal(reads,[],'Non-admin never reads relationship editor');}finally{await closeContext(viewer.context);}}
}
async function emptyCase(){const {context,page}=await contextFor(1280);try{await page.goto(base+'/#/users');await page.locator('#tbl tbody tr').first().waitFor();const before=await control('snapshot');await rowAction(page,fixture.accounts.subject,'维护负责人/BP');await page.waitForFunction(()=>document.querySelector('[data-relationships-notice]')?.textContent.includes('暂不能维护'));check(await part(page,'leader').isDisabled()&&await part(page,'preview').isDisabled(),'Unpublished source cannot be edited or auto-configured');equal(await control('snapshot'),before,'Unpublished editor creates no configuration');}finally{await closeContext(context);}}
try{browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE || undefined,headless:true});for(const width of [1280,390,320]){await boot(width);await mainCase(width);await stop();}await boot('empty',true);await emptyCase();await stop();equal(browserErrors,[],'No browser errors/native dialogs');equal(outsideRequests,[],'No external requests');equal(await sourceHashes(),testedSourceSha256,'Tested sources remained unchanged');}catch(e){error=e;}finally{for(const context of contexts)await context.close().catch(()=>{});await browser?.close();await stop();await writeFile(join(own,'server.log'),log.replaceAll(password,'[synthetic password redacted]'),{mode:0o600});const result={ok:!error,checks,classes,fixtureClasses,temporaryDirectory:own,testedSourceSha256,screenshots,browserErrors,outsideRequests,expectedFailureResponses:failures,browserClosed:true,temporaryServiceStopped:!child||child.exitCode!==null||child.signalCode!==null,...(error?{error:error.stack||String(error)}:{})};await writeFile(join(own,'result.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));}if(error)process.exitCode=1;
