'use strict';
// Real original summary host + modal/API. Only transport and DOM are synthetic.
const fs = require('node:fs'), path = require('node:path'), vm = require('node:vm'), assert = require('node:assert/strict');
const base = fs.readFileSync(path.join(__dirname, 'IntegrationSummariesUI.test.cjs'), 'utf8');
const support = vm.runInNewContext(base.slice(0, base.indexOf('\n(async () => {')) + '\n({ harness, content, sources, revision, view, deliverySources, deliveryFacts });', { require, __dirname, console, structuredClone, AbortController, DOMException, URL, URLSearchParams, Buffer, setImmediate });
const tick = () => new Promise(yes => setImmediate(yes));
const deferred = () => { let resolve; const promise = new Promise(yes => { resolve = yes; }); return { promise, resolve }; };
let checks = 0;
const check = (value, label) => { assert.ok(value, label); checks++; };
const equal = (value, expected, label) => { assert.deepEqual(JSON.parse(JSON.stringify(value)), expected, label); checks++; };
const body = suffix => ({ achievements: '成果' + suffix, issues: '问题' + suffix, nextSteps: '计划' + suffix, publicity: { title: 'SYNTHETIC 总结' + suffix, introduction: ' 引言\n第二行 ', sections: [{ heading: '理论', body: '正文 A' }, { heading: '研讨', body: '正文 B' }], photoCaptions: ['授课图注', '研讨图注'] } });
const facts = actual => support.deliverySources({ ...support.deliveryFacts(), actual, planned: null, payable: '9007199254740993.12345678' });
const rev = (number, text = body(number), source = facts(number === 1 ? '0' : '1.33')) => support.revision(number, text, source);
const dto = (before = rev(1), after = rev(2), latest = 9) => ({ project_id: 5, from_revision: before?.revision || 0, to_revision: after.revision, latest_version: latest, before, after, read_only: true, synthetic: false, draft_only: true });
function harness({ version = 2, edit = true, revision, comparison, override } = {}) {
  const h = support.harness({ initial: support.view(version, body(version), edit, facts('1.33')), fetchOverride: (url, opts, normal, respond, remote) => {
    const parsed = new URL(url, 'http://synthetic');
    const fallback = () => parsed.pathname === '/api/training-summaries/revision' ? respond(revision || rev(Number(parsed.searchParams.get('revision')))) : parsed.pathname === '/api/training-summaries/comparison' ? respond(comparison || dto(Number(parsed.searchParams.get('from_revision')) ? rev(Number(parsed.searchParams.get('from_revision'))) : null, rev(Number(parsed.searchParams.get('to_revision'))))) : normal();
    return override ? override(url, opts, fallback, respond, remote) : fallback();
  } });
  h.viewer = () => h.modal()?.querySelector('#summary-revision');
  h.previewRequests = () => h.calls.filter(call => call.url.startsWith('/api/training-summaries/revision?'));
  h.compareRequests = () => h.calls.filter(call => call.url.startsWith('/api/training-summaries/comparison?'));
  h.compare = async (number = 2) => { await h.click('show-history'); const binding = h.bindings.at(-1); const action = binding.actions.find(action => action.l === '与上一版对照'); check(action, 'Original history row offers explicit adjacent comparison'); await action.onClick({ revision: number }); await tick(); };
  return h;
}
(async () => {
  const h = harness(); await h.mount(); check(h.panel().querySelector('[data-summary-preview-open]') && !h.panel().querySelector('[data-summary-preview-open]').disabled, 'Original project area offers saved preview');
  await h.open(); const mask = h.modal(), input = h.field('body1'); await h.edit('body1', '本地尚未保存'); await h.click('preview');
  check(h.modal() === mask && h.field('body1') === input && h.modal().querySelector('#summary-editor').hidden, 'Preview hides but never destroys original input controls');
  check(h.viewer().textContent.includes('草稿 · 第 2 版') && h.viewer().textContent.includes('保存于') && !h.viewer().textContent.includes('本地尚未保存'), 'Saved revision and time are explicit; draft text never enters saved preview');
  check(h.viewer().textContent.includes('保存时的业务数据') && !h.viewer().textContent.includes('冻结业务来源'), 'Saved preview uses business-facing source wording');
  equal(h.viewer().querySelector('[data-summary-sections]').querySelectorAll('li').map(item => item.textContent), ['理论正文 A', '研讨正文 B'], 'Preview retains chapter order');
  equal(h.viewer().querySelector('[data-summary-captions]').querySelectorAll('li').map(item => item.textContent), ['授课图注', '研讨图注'], 'Preview retains text-only caption order');
  check(h.viewer().textContent.includes(' 引言\n第二行 ') && h.viewer().querySelector('p[style]'), 'Whitespace and newlines remain presentation text');
  check(!h.viewer().textContent.includes('ACTOR-SYNTH') && !h.viewer().textContent.includes('a'.repeat(64)), 'Saved preview excludes actor IDs and source hashes');
  await h.click('return'); check(!h.modal().querySelector('#summary-editor').hidden && h.field('body1') === input && input.value === '本地尚未保存', 'Returning restores the exact unsaved input nodes and values');
  await h.click('preview'); equal(h.previewRequests().length, 2, 'Every preview rechecks the real revision API'); await h.click('return');
  await h.compare(); equal(h.compareRequests().length, 1, 'Comparison is one atomic GET'); equal(h.previewRequests().length, 2, 'Comparison does not assemble two independent revision reads');
  check(h.viewer().textContent.includes('当前可见字段') && h.viewer().textContent.includes('最新第 9 版') && h.viewer().textContent.includes('按位置比较'), 'Comparison explains visibility, latest metadata and positional matching');
  check(h.viewer().querySelector('table.tbl') && h.viewer().querySelector('th').getAttribute('scope') === 'col' && h.viewer().querySelector('td').getAttribute('data-label') === '项目', 'Comparison uses original accessible responsive table');
  check(h.viewer().textContent.includes('已核对实际课时') && h.viewer().textContent.includes('0') && h.viewer().textContent.includes('1.33'), 'Visible frozen aggregate differences preserve zero as data');
  await h.click('return'); await h.click('save'); equal(JSON.parse(h.requests('save')[0].opts.body).expected_version, 2, 'Latest comparison metadata never rebases editor CAS'); check(!h.viewer().textContent, 'Saving clears previous read-only viewer');
  const fresh = harness({ version: 0 }); await fresh.mount(); check(fresh.panel().querySelector('[data-summary-preview-open]').disabled, 'Project preview disabled before first save'); await fresh.open(); check(fresh.button('preview').disabled, 'Editor preview also disabled without a saved revision');
  const panel = harness(); await panel.mount(); await panel.emit(panel.panel().querySelector('[data-summary-preview-open]'), 'click'); check(panel.viewer().querySelector('[data-summary-preview]') && panel.previewRequests().length === 1, 'Project entry opens saved view in original modal after fresh reads');
  for (const edit of [true, false]) { const readonly = harness({ edit }); await readonly.mount(); await readonly.open(); await readonly.click('preview'); check(readonly.viewer().querySelector('[data-summary-preview]') && !readonly.viewer().querySelector('input,textarea'), 'Saved viewer is readonly regardless of current edit/archive capability'); if (!edit) check(!readonly.button('save') && readonly.field('achievements').disabled, 'Archive capability keeps retained editor readonly'); }
  const first = harness({ version: 1, comparison: dto(null, rev(1), 1) }); await first.mount(); await first.open(); await first.compare(1); check(first.viewer().textContent.includes('首次保存前（尚无已保存版本） → 第 1 版') && first.viewer().textContent.includes('章节数量') && !first.viewer().textContent.includes('ACTOR-SYNTH'), 'Initial draft compares to empty origin without invented previous content');
  const shuffled = body(1); shuffled.publicity.sections.reverse(); shuffled.publicity.photoCaptions.reverse(); shuffled.publicity.sections.push({ heading: '', body: '' });
  const sequence = harness({ comparison: dto(rev(1), rev(2, shuffled)) }); await sequence.mount(); await sequence.open(); await sequence.compare(); check(sequence.viewer().textContent.includes('位置 1 · 章节标题') && sequence.viewer().textContent.includes('位置 2 · 文字图注') && sequence.viewer().textContent.includes('位置 3 · 章节正文'), 'Array reordering and blank additions remain positional differences');
  const same = harness({ comparison: dto(rev(1, body(1)), rev(2, body(1), facts('0'))) }); await same.mount(); await same.open(); await same.compare(); check(same.viewer().textContent.includes('当前可见字段未发现变化') && !same.viewer().textContent.includes('全部'), 'No-difference statement is limited to current visible projection');
  const oldUnavailable = { ...support.sources(), delivery: { status: 'UNAVAILABLE', reason: 'DELIVERY_READ_REQUIRED', value: null } };
  const regained = harness({ comparison: dto(rev(1, body(1), oldUnavailable), rev(2)) }); await regained.mount(); await regained.open(); await regained.compare(); check(regained.viewer().textContent.includes('1.33') && regained.viewer().textContent.includes('9007199254740993.12345678') && !regained.viewer().textContent.includes('均按当前权限隐藏'), 'Historic READ_REQUIRED without visibility flag does not hide newly authorized available sources');
  const historicallyMissing = harness({ revision: rev(2, body(2), oldUnavailable) }); await historicallyMissing.mount(); await historicallyMissing.open(); await historicallyMissing.click('preview'); check(historicallyMissing.viewer().textContent.includes('本版尚未带入') && !historicallyMissing.viewer().textContent.includes('按当前权限隐藏'), 'Historical missing delivery is not described as current permission denial');
  const hiddenBefore = facts('98765.43'), hiddenAfter = facts('87654.32'); hiddenBefore.visibility = hiddenAfter.visibility = 'DELIVERY_HIDDEN';
  const hidden = harness({ comparison: dto(rev(1, body(1), hiddenBefore), rev(2, body(2), hiddenAfter)), revision: rev(2, body(2), hiddenAfter) }); await hidden.mount(); await hidden.open(); await hidden.compare(); check(hidden.viewer().textContent.includes('两侧均按当前权限隐藏') && !/98765|87654|900719925/.test(hidden.viewer().textContent), 'Current hidden projection removes both sides even if response accidentally includes values'); await hidden.click('return'); await hidden.click('preview'); check(!hidden.viewer().querySelector('[data-summary-delivery]')?.querySelector('table') && !hidden.viewer().textContent.includes('87654'), 'Preview also honors current visibility flag before any data');
  const unknown = facts(null), zero = facts('0'); unknown.project.value.participant_count = null; zero.project.value.participant_count = 0; unknown.delivery.value.payable = null;
  const precision = harness({ comparison: dto(rev(1, body(1), unknown), rev(2, body(1), zero)) }); await precision.mount(); await precision.open(); await precision.compare(); const rows = precision.viewer().querySelector('tbody').querySelectorAll('tr').map(row => row.querySelectorAll('td').map(cell => cell.textContent)); check(rows.some(row => row[0] === '项目人数' && row[1] === '未记录' && row[2] === '0') && rows.some(row => row[0] === '计酬课时' && row[2] === '9007199254740993.12345678'), 'Null, genuine zero and long decimal are never coerced or rounded');
  const evil = '<img src=x onerror=alert(1)><script>alert(1)</script>', malicious = body(2); malicious.publicity.title = evil; malicious.publicity.sections[0].body = evil; malicious.publicity.photoCaptions[0] = evil;
  const escaped = harness({ revision: rev(2, malicious), comparison: dto(rev(1), rev(2, malicious)) }); await escaped.mount(); await escaped.open(); await escaped.click('preview'); check(escaped.viewer().textContent.includes(evil) && !escaped.viewer().querySelector('img,script'), 'Preview HTML is inert escaped text'); await escaped.click('return'); await escaped.compare(); check(escaped.viewer().textContent.includes(evil) && !escaped.viewer().querySelector('img,script'), 'Comparison cells do not execute text markup');
  for (const status of [401, 403]) { const revoked = harness({ override: (url, opts, normal, respond) => url.includes('/training-summaries/comparison?') ? respond(null, status) : normal() }); await revoked.mount(); await revoked.open(); await revoked.edit('issues', '敏感本地正文'); await revoked.compare(); check(!revoked.modal(), status + ': atomic comparison permission loss clears whole private editor/viewer'); }
  for (const change of [result => { result.project_id = 99; }, result => { result.from_revision = 0; }, result => { result.after.revision = 99; }, result => { result.before.synthetic = true; }, result => { result.read_only = false; }]) { const response = dto(); change(response); const malformed = harness({ comparison: response }); await malformed.mount(); await malformed.open(); await malformed.compare(); check(!malformed.viewer().querySelector('table') && malformed.viewer().textContent.includes('暂时无法读取'), 'Mismatched/unsafe atomic envelope is not displayed'); }
  let unknownSave = true; const pending = harness({ override: (url, opts, normal) => { if (url.endsWith('/training-summaries/save') && unknownSave) throw Error('SYNTHETIC network uncertainty'); return normal(); } }); await pending.mount(); await pending.open(); await pending.click('save'); check(pending.button('preview').disabled && pending.button('show-history').disabled && pending.previewRequests().length === 0, 'Unknown save result disables all new saved-content reads');
  const late = deferred(), delayed = harness({ override: (url, opts, normal, respond) => url.includes('/training-summaries/revision?') ? late.promise.then(respond) : normal() }); await delayed.mount(); await delayed.open(); const previewing = delayed.click('preview'); await tick(); await delayed.click('return'); check(delayed.previewRequests()[0].opts.signal.aborted, 'Returning aborts in-flight preview'); late.resolve(rev(2)); await previewing; check(!delayed.viewer().textContent && !delayed.modal().querySelector('#summary-editor').hidden, 'Late cancelled response does not resurrect preview');
  const stale = deferred(), mutate = harness({ override: (url, opts, normal, respond) => url.includes('/training-summaries/comparison?') ? stale.promise.then(respond) : normal() }); await mutate.mount(); await mutate.open(); const reading = mutate.compare(); for (let i = 0; !mutate.compareRequests().length && i < 20; i++) await tick(); await mutate.click('save'); stale.resolve(dto()); await reading; check(!mutate.viewer().textContent && mutate.compareRequests()[0].opts.signal.aborted, 'Saving cancels earlier comparison before adopting a new summary version');
  const leaving = deferred(), route = harness({ override: (url, opts, normal, respond) => url.includes('/training-summaries/revision?') ? leaving.promise.then(respond) : normal() }); await route.mount(); await route.open(); const opening = route.click('preview'); await tick(); route.leave(); leaving.resolve(rev(2)); await opening; check(!route.modal() && route.previewRequests()[0].opts.signal.aborted, 'Route cleanup aborts preview and prevents delayed data from crossing projects');
  const dirty = harness(); await dirty.mount(); await dirty.open(); await dirty.edit('issues', '保留未存正文'); await dirty.click('preview'); await dirty.click('view-close'); check(dirty.modal() && dirty.button('stay') && dirty.field('issues').value === '保留未存正文', 'Viewer close uses original inline dirty guard'); await dirty.click('stay'); await dirty.click('return'); check(dirty.field('issues').value === '保留未存正文', 'Guard and return preserve original draft');
  check(h.calls.filter(call => call.url.includes('/training-summaries/revision?') || call.url.includes('/training-summaries/comparison?')).every(call => call.opts.method === 'GET' && call.opts.signal), 'All preview/comparison requests use original authenticated read-only transport');
  console.log(JSON.stringify({ ok: true, suite: 'original summary saved preview and atomic comparison', checks, transport: 'synthetic', browser: false, database: false }));
})().catch(error => { console.error(error); process.exitCode = 1; });
