'use strict';
// Real server-pinned import preview/account lookup/commit. Synthetic sources and isolated H2 only.
const fs=require('node:fs'),path=require('node:path'),net=require('node:net'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{spawn,execFile}=require('node:child_process'),{promisify}=require('node:util'),run=promisify(execFile),args={};
for(let i=2;i<process.argv.length;i+=2){assert.ok(['--java','--classes'].includes(process.argv[i])&&process.argv[i+1],'Use --java PATH --classes DIRECTORY or CLASSES_DIR');args[process.argv[i]]=process.argv[i+1];}
const java=args['--java']||'java',repo=path.resolve(__dirname,'..'),classes=fs.realpathSync(args['--classes']||process.env.CLASSES_DIR||'');assert.ok(classes!==repo&&!classes.startsWith(repo+path.sep),'Use isolated classes outside repository');
assert.ok(fs.existsSync(path.join(classes,'com/training/IntegrationBranchCoverageHttpFixture.class'))&&fs.existsSync(path.join(classes,'com/training/OrganizationAccountImportSourceTest.class')),'Compile new fixture and existing synthetic source fixture');
const own=fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'yanxu-branch-coverage-http-')),data=path.join(own,'data');fs.mkdirSync(data);
const password=crypto.randomBytes(24).toString('hex'),tokens={},failures=[],servicePids=[],readEvidence=[],base='/organization/account-import',roles=['BRANCH_RESPONSIBLE','BRANCH_LEAD','BP'];
const env={...process.env,YANXU_SEMANTIC_PORT:'',YANXU_SEMANTIC_TOKEN:''};let pins,child,port,checks=0,phase='setup',fatal=null,linked,manager,spare;
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function check(ok,label){checks++;if(!ok)failures.push(phase+': '+label);}
function same(a,b,label){let ok=true;try{assert.deepEqual(a,b);}catch{ok=false;}check(ok,label);}
function options(resume=false){return ['-Dbind.address=127.0.0.1','-Dbootstrap.demo=false','-Dbootstrap.admin.password='+password,'-Dintegration.branch.coverage.root='+own,'-Dintegration.branch.coverage.resume='+resume,'-Ddata.dir='+data,'-Dsemantic.port=','-Dsemantic.token=',...(pins?['-Daccount.import.manifest='+pins.manifest,'-Daccount.import.manifest.sha256='+pins.sha256]:['-Daccount.import.manifest=','-Daccount.import.manifest.sha256=']),'-cp',classes+path.delimiter+path.join(repo,'lib','*')];}
async function fixture(operation){const r=await run(java,[...options(true),'com.training.IntegrationBranchCoverageHttpFixture',operation],{cwd:repo,env,timeout:20000,maxBuffer:65536});return JSON.parse(r.stdout.trim());}
function privateResponse(r,label){check(!r.text.includes(own)&&!r.text.includes('/sources/')&&!r.text.includes('000SYN')&&!r.text.includes('source_staff_id'),label+' reveals no source path or HR identifier');check(r.headers.get('cache-control')==='no-store',label+' is not cacheable');}
async function request(route,body,actor='admin',overrides={}){
 const headers={...(tokens[actor]?{'X-Token':tokens[actor]}:{})};if(body!==undefined)headers['Content-Type']=overrides.contentType||'application/json';
 const r=await fetch(`http://127.0.0.1:${port}/api${route}`,{method:overrides.method||(body===undefined?'GET':'POST'),headers,body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(10000)});
 const text=await r.text();let envelope=null;if(text){try{envelope=JSON.parse(text);}catch{throw new Error(route+': non-JSON HTTP '+r.status);}}
 const result={status:r.status,text,envelope,headers:r.headers};if(route.startsWith(base))privateResponse(result,'Import HTTP');return result;
}
async function api(route,body,actor='admin'){const r=await request(route,body,actor);assert.equal(r.status,200,phase+': '+route+': '+r.status+': '+r.envelope?.msg);assert.equal(r.envelope?.code,0,route);return r.envelope.data;}
async function denied(route,body,actor,status,label,overrides={}){const r=await request(route,body,actor,overrides);check(r.status===status&&(overrides.method==='HEAD'?r.text==='':r.envelope?.code===status),label+' (HTTP '+r.status+': '+r.envelope?.msg+')');check(!r.envelope?.data?.branchCoverage&&!r.envelope?.data?.rows&&!r.headers.has('content-disposition'),'Rejected response exposes no partial candidate or coverage data');check(!r.text.includes('SYNTHETIC PRIVATE'),'Rejected response reveals no candidate name');return r;}
async function login(actor){tokens[actor]=(await api('/login',{username:actor==='admin'?'admin':'synthetic-branch-'+actor,password},'anonymous')).token;}
async function boot(resume=false){for(const key of Object.keys(tokens))delete tokens[key];const listener=net.createServer();await new Promise((resolve,reject)=>{listener.once('error',reject);listener.listen(0,'127.0.0.1',resolve);});port=listener.address().port;await new Promise(resolve=>listener.close(resolve));child=spawn(java,[...options(resume),'com.training.IntegrationBranchCoverageHttpFixture',String(port)],{cwd:repo,env,stdio:'ignore'});if(child.pid)servicePids.push(child.pid);let error;child.once('error',e=>{error=e;});for(let i=0;i<150;i++){if(error)throw error;assert.equal(child.exitCode,null,'Synthetic pinned import Main exited');try{await login('admin');return;}catch{}await pause(100);}throw new Error('Synthetic Main startup timeout');}
async function stop(){const running=child;child=null;if(!running||running.exitCode!==null||running.signalCode!==null)return;await new Promise(resolve=>{const timer=setTimeout(()=>{if(running.exitCode===null&&running.signalCode===null)running.kill('SIGKILL');},2000);running.once('exit',()=>{clearTimeout(timer);resolve();});running.kill('SIGTERM');});}
async function control(operation){const nonce=crypto.randomUUID(),tmp=path.join(own,'control-request.next');fs.writeFileSync(tmp,JSON.stringify({nonce,operation}),{mode:0o600});fs.renameSync(tmp,path.join(own,'control-request.json'));for(let i=0;i<200;i++){try{const ack=JSON.parse(fs.readFileSync(path.join(own,'control-result.json'),'utf8'));if(ack.nonce===nonce&&ack.ok)return ack.data;}catch{}await pause(20);}throw new Error('Synthetic control timeout: '+operation);}
async function readOnly(label,operation){phase=label;const before=await control('snapshot');await operation();const after=await control('snapshot');same(Object.keys(after),Object.keys(before),'Read keeps schema unchanged');for(const name of Object.keys(before))same(after[name],before[name],'Read leaves full '+name+' contents unchanged');readEvidence.push({phase:label,tables:Object.keys(before).length,before:crypto.createHash('sha256').update(JSON.stringify(before)).digest('hex'),after:crypto.createHash('sha256').update(JSON.stringify(after)).digest('hex')});}
const preview=()=>api(base+'/preview'),lookup=id=>api(base+'/accounts/'+id);
function decisions(view,proof){return {expectedRevision:view.revision,sourceFingerprint:view.sourceFingerprint,reviewToken:view.reviewToken,decisions:view.rows.map(row=>({reference:row.reference,action:row.reference==='teacher-row-4'?'LINK_EXISTING':'CREATE_PENDING',accountId:row.reference==='teacher-row-4'?linked:null,accountProof:row.reference==='teacher-row-4'?proof.proof:null,reviewed:true}))};}
function verifyCoverage(view,receipt=null,linkedEnabled=true){
 check(view.permissionsPublished===false&&view.accountsActivated===false,'Coverage never claims activation or published authorization');check(view.rows.length===7&&view.summary.historicalExcluded===2,'Complete candidate intake and historical exclusions remain intact');
 check(view.imported===Boolean(receipt),'Preview reports only actual persisted receipt state');
 const coverage=view.branchCoverage;assert.ok(Array.isArray(coverage),'branchCoverage must be a typed array');
 same(coverage.map(row=>row.branch),['SYNTHETIC BRANCH A','SYNTHETIC BRANCH B','SYNTHETIC BRANCH C'],'Coverage retains trusted organization order');
 const specs=[{region:'SYNTHETIC REGION ONE',leaders:[['teacher-row-4','BRANCH_RESPONSIBLE'],['teacher-row-5','BRANCH_RESPONSIBLE'],['teacher-row-8','BRANCH_LEAD']],bp:['teacher-row-7'],combined:[]},{region:'SYNTHETIC REGION ONE',leaders:[['lead-row-9','BRANCH_LEAD']],bp:['teacher-row-7'],combined:[]},{region:'SYNTHETIC REGION TWO',leaders:[['teacher-row-6','BRANCH_RESPONSIBLE']],bp:['teacher-row-6'],combined:['teacher-row-6']}];
 const receiptRows=new Map((receipt?.rows||[]).map(row=>[row.reference,row])),candidateRows=new Map(view.rows.map(row=>[row.reference,row]));
 for(let i=0;i<coverage.length;i++){
  const branch=coverage[i],expected=specs[i];same(Object.keys(branch).sort(),['bpCandidates','branch','canApprove','combinedCandidates','defaultHandlerReference','leaderCandidates','preparationOnly','readOnly','region','routingStatus'],'Branch projection has exact safe fields');
  check(branch.region===expected.region&&branch.defaultHandlerReference===null&&branch.canApprove===false,'Region is trusted and no default handler or approval grant is invented');check(branch.readOnly===true&&branch.preparationOnly===true,'Coverage explicitly remains read-only preparation');
  check(branch.routingStatus===(i===0?'MULTIPLE_IDENTITIES_RETAINED_ROUTING_PENDING':'ROLE_EVIDENCE_PREPARED'),'Routing retains all multiple identities without choosing a person');
  same(branch.leaderCandidates.map(c=>[c.reference,...c.roleKinds]),expected.leaders,'All responsible and lead candidates retained in source row order');same(branch.bpCandidates.map(c=>c.reference),expected.bp,'BP coverage follows only confirmed branch scope');same(branch.combinedCandidates,expected.combined,'Combined duties require explicit evidence in this branch');
  for(const [kind,candidates]of [['leader',branch.leaderCandidates],['bp',branch.bpCandidates]])for(const c of candidates){
   same(Object.keys(c).sort(),['accountId','accountState','reference','roleKinds'],'Candidate points to reference without duplicate personal fields');check(candidateRows.has(c.reference),'Coverage reference belongs to original preview rows');
   check(c.roleKinds.length>0&&c.roleKinds.every(r=>roles.includes(r)&&(kind==='bp'?r==='BP':r!=='BP')),'Each duty remains independently typed');
   const r=receiptRows.get(c.reference),expectedId=r?.accountId??null,expectedState=!receipt?'NOT_RECEIVED':c.reference==='teacher-row-4'&&linkedEnabled?'RECEIVED_ENABLED':'RECEIVED_DISABLED';
   check(c.accountId===expectedId&&c.accountState===expectedState,'Coverage account ID/state comes from the checked receipt and live users');
   check(candidateRows.get(c.reference).accountId===expectedId,'Coverage reference and original candidate account link agree');
  }
 }
 const ordinary=candidateRows.get('teacher-row-3');check(ordinary.approvalRoles.length===0&&ordinary.approvalEligibility==='NO_APPROVAL_ROLE','Ordinary teacher remains a candidate without an approval duty');
 check(!JSON.stringify(coverage).includes('teacher-row-3'),'Same-name ordinary teacher is never merged into role coverage');check(ordinary.name===candidateRows.get('teacher-row-4').name&&ordinary.reference!==candidateRows.get('teacher-row-4').reference,'Synthetic same-name people keep distinct references');
 check(candidateRows.get('teacher-row-6').combinedDutiesRequiresWorkflowReview===true,'Explicit combined duty still needs workflow review');
 if(receipt){check(view.reviewToken===null,'Imported preview issues no new commit review token');same(view.receipt.rows,receipt.rows,'Preview preserves exact committed reference/account receipt');}
}
async function runChecks(){
 pins=await fixture('prepare');await boot();
 linked=await api('/users',{username:'synthetic-branch-linked',name:'SYNTHETIC EXISTING VIEWER',role:'viewer',status:1,password});manager=await api('/users',{username:'synthetic-branch-manager',name:'SYNTHETIC MANAGER',role:'manager',status:1,password});spare=await api('/users',{username:'synthetic-branch-spare',name:'SYNTHETIC SPARE',role:'viewer',status:1,password});await login('linked');await login('manager');
 let first,proof,body;
 await readOnly('unreceived coverage and explicit account ID review',async()=>{first=await preview();verifyCoverage(first);proof=await lookup(linked);check(proof.accountId===linked&&proof.available===true&&typeof proof.proof==='string','Original per-ID lookup supplies explicit existing-account proof');verifyCoverage(await preview());body=decisions(first,proof);});
 await readOnly('private authority and narrow original protocol',async()=>{
  for(const actor of ['anonymous','linked','manager']){const status=actor==='anonymous'?401:403;await denied(base+'/preview',undefined,actor,status,'Only real admin may inspect coverage');await denied(base+'/accounts/'+linked,undefined,actor,status,'Only real admin may lookup linkage');}
  await denied(base+'/preview?manifest=client',undefined,'admin',400,'Browser cannot supply server pin paths');await denied(base+'/preview?branch=A&branch=B',undefined,'admin',400,'Query cannot filter or ambiguously replace complete coverage');await denied(base+'/preview',{},'admin',405,'POST cannot perform preview');
  await denied(base+'/commit',{...body,branchCoverage:[]},'admin',400,'Client cannot commit invented role coverage');
 });
 const candidateFile=path.join(own,'sources','candidates.json'),candidateBytes=fs.readFileSync(candidateFile);fs.appendFileSync(candidateFile,'\n');
 await readOnly('changed pinned source fails before intake',async()=>{await denied(base+'/preview',undefined,'admin',409,'Changed verified candidate source fails safely');await denied(base+'/commit',body,'admin',409,'Source change invalidates pending intake command');});fs.writeFileSync(candidateFile,candidateBytes);
 const manifestBytes=fs.readFileSync(pins.manifest);fs.writeFileSync(pins.manifest,'SYNTHETIC CHANGED MANIFEST');
 await readOnly('changed manifest closes preview and lookup',async()=>{await denied(base+'/preview',undefined,'admin',503,'Changed startup-pinned manifest cannot reopen data');await denied(base+'/accounts/'+linked,undefined,'admin',503,'Per-ID lookup also respects startup pins');});fs.writeFileSync(pins.manifest,manifestBytes);
 await readOnly('restored manifest requires new review',async()=>{await denied(base+'/commit',body,'admin',409,'Restoring server file never revives old in-memory review token');first=await preview();verifyCoverage(first);proof=await lookup(linked);body=decisions(first,proof);});
 const beforeCommit=await control('snapshot'),epochsBeforeCommit=await control('device-epochs');phase='real original intake commit';const receipt=await api(base+'/commit',body);check(receipt.permissionsPublished===false&&receipt.accountsActivated===false,'Commit only prepares accounts and retains unpublished duty evidence');check(receipt.rows.length===7&&new Set(receipt.rows.map(r=>r.accountId)).size===7,'Each distinct reference has one distinct durable account association');check(receipt.rows.find(r=>r.reference==='teacher-row-4').accountId===linked,'Explicit linked ID survives original receipt');
 same(await control('device-epochs'),epochsBeforeCommit,'Account intake preserves all trusted-device epochs');
 let expectedEpochs=epochsBeforeCommit;
 async function verifyStatusEpoch(label){const next=new Map(expectedEpochs.map(row=>[row.user_id,row.epoch]));next.set(linked,(next.get(linked)||0)+1);expectedEpochs=[...next].sort((a,b)=>a[0]-b[0]).map(([user_id,epoch])=>({user_id,epoch}));same(await control('device-epochs'),expectedEpochs,label+' increments only the linked account epoch exactly once');}
 let imported;
 await readOnly('received coverage and unchanged identity receipt',async()=>{imported=await preview();verifyCoverage(imported,receipt);const replay=await api(base+'/commit',body);check(replay.replayed===true,'Exact original commit retry replays existing receipt');same(replay.rows,receipt.rows,'Idempotent intake keeps exact reference mappings');const reused=await lookup(linked);check(reused.available===false&&reused.proof===null,'Imported account can no longer be proposed as a free duplicate');check((await api('/organization/config')).configuration===null,'Import coverage never publishes an M01 permission configuration');});
 await api('/users',{id:linked,username:'synthetic-branch-linked',name:'SYNTHETIC EXISTING VIEWER',role:'viewer',status:0});
 await verifyStatusEpoch('Disabling the linked account');
 await readOnly('live received account status remains advisory',async()=>{verifyCoverage(await preview(),receipt,false);await denied(base+'/preview',undefined,'linked',401,'Disabling linked account revokes its real session');});
 await api('/users',{id:linked,username:'synthetic-branch-linked',name:'SYNTHETIC EXISTING VIEWER',role:'viewer',status:1});
 await verifyStatusEpoch('Restoring the linked account');const verifiedEpochTable=(await control('snapshot')).S01_TRUSTED_DEVICE_EPOCHS;
 await control('revoke-admin');await readOnly('revoked admin session',async()=>{await denied(base+'/preview',undefined,'admin',401,'Coverage rechecks actual session validity');});await login('admin');
 await control('capture');
 for(const fault of ['fault-missing-person','fault-person-account','fault-receipt-account','fault-receipt-duplicate']){
  await control(fault);await readOnly('corrupt receipt association '+fault,async()=>{await denied(base+'/preview',undefined,'admin',409,'Receipt/people/users association must remain fully verifiable');await denied(base+'/preview',undefined,'manager',403,'Nonadmin cannot learn receipt corruption state');});await control('restore');
 }
 await readOnly('restored original receipt projection',async()=>{same((await preview()).branchCoverage,imported.branchCoverage,'Restored complete association yields original coverage without migration');});
 same(await control('device-epochs'),expectedEpochs,'Receipt fault tests preserve the precisely verified account epochs');
 const beforeRestart=await control('snapshot');for(const name of Object.keys(beforeCommit))if(!['USERS','ORGANIZATION_ACCOUNT_IMPORT_STATE','ORGANIZATION_ACCOUNT_IMPORT_PEOPLE','ORGANIZATION_ACCOUNT_IMPORT_BATCHES'].includes(name))same(beforeRestart[name],name==='S01_TRUSTED_DEVICE_EPOCHS'?verifiedEpochTable:beforeCommit[name],'Intake preserves '+name+' at its verified baseline');
 check(beforeRestart.USERS.count-beforeCommit.USERS.count===6&&beforeRestart.ORGANIZATION_ACCOUNT_IMPORT_PEOPLE.count===7&&beforeRestart.ORGANIZATION_ACCOUNT_IMPORT_BATCHES.count===1,'Only six pending users and one seven-reference receipt were created');
 await stop();same(await fixture('inspect'),beforeRestart,'Offline whole-database digest agrees');await boot(true);await login('manager');
 await readOnly('durable coverage after original Main restart',async()=>{const restarted=await preview();verifyCoverage(restarted,receipt);same(restarted.branchCoverage,imported.branchCoverage,'Restart preserves checked role coverage and live account state');await denied(base+'/commit',body,'admin',409,'Previous process review token cannot replay after restart');await denied(base+'/preview',undefined,'manager',403,'Restart never grants original manager role admin import access');});const final=await control('snapshot');same(final,beforeRestart,'Restart and read-only projection do not change persisted rows');
 fs.writeFileSync(path.join(own,'database-invariants.json'),JSON.stringify({before_commit:beforeCommit,before_restart:beforeRestart,final,read_phases:readEvidence},null,2),{mode:0o600});fs.writeFileSync(path.join(own,'synthetic-coverage.json'),JSON.stringify({before:first.branchCoverage,after:imported.branchCoverage,receipt_rows:receipt.rows},null,2),{mode:0o600});return {read_only_phases:readEvidence.length,tables_per_read_phase:Object.keys(final).length,branches:3,candidates:7,pending_users_created:6};
}
let evidence;runChecks().then(value=>{evidence=value;}).catch(error=>{fatal=String(error.message||error).replaceAll(password,'[redacted]');process.exitCode=1;}).finally(async()=>{await stop();const stopped=servicePids.every(pid=>{try{process.kill(pid,0);return false;}catch(e){return e.code==='ESRCH';}});check(stopped,'All isolated pinned-import Main processes stopped');const summary={suite:'branch-coverage-http',checks,failures,...(fatal?{error:fatal}:{}),...(evidence||{}),server_processes_stopped:stopped,production_touched:false,notifications_sent:false,artifacts:own};fs.writeFileSync(path.join(own,'result.json'),JSON.stringify(summary,null,2),{mode:0o600});console.log(JSON.stringify(summary));if(failures.length||fatal)process.exitCode=1;});
