package com.training;

import com.sun.net.httpserver.HttpServer;
import java.io.*;
import java.lang.reflect.*;
import java.math.BigDecimal;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.MessageDigest;
import java.time.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.zip.*;
import static com.training.OrganizationAccess.*;

/** Actual Api HTTP, real M01/M04/M05/M06, and a caller-owned fresh synthetic H2 only. */
public final class M05CodingTest {
    private static final String PASSWORD="SYNTHETIC-M05-FORMAL-ONLY", BASE="/api/delivery-settlement/coding";
    private static final String DAY=LocalDate.now(ZoneId.of("Asia/Shanghai")).minusDays(1).toString(), TODAY=LocalDate.now(ZoneId.of("Asia/Shanghai")).toString();
    private static final Map<String,String> TOKENS=new LinkedHashMap<>();
    private static final List<Map<String,Object>> TRACE=new ArrayList<>();
    private static Auth.Session admin,worker,outsider;
    private static long scope,otherScope,catalogVersion; private static int checks,requests,port,accessVersion;
    private static Path artifacts; private static String phase="setup";
    private static final List<String> LEDGER_TABLES=List.of("m05_financial_chains","m05_financial_entries","m05_payment_events","m05_delivery_facts","m05_fact_revisions","m05_settlement_snapshots");
    @FunctionalInterface private interface Work {void run()throws Exception;}
    @SuppressWarnings("unchecked") private static Map<String,Object> obj(Object v){return (Map<String,Object>)v;}
    @SuppressWarnings("unchecked") private static List<Map<String,Object>> rows(Object v){return (List<Map<String,Object>>)v;}
    private static Map<String,Object> map(Object... v){Map<String,Object>m=new LinkedHashMap<>();for(int i=0;i<v.length;i+=2)m.put((String)v[i],v[i+1]);return m;}
    private static Map<String,Object> copy(Map<String,Object> v){return obj(Json.parse(Json.write(v)));}
    private static long n(Object v){return new BigDecimal(v.toString()).longValueExact();}
    private static String req(){return "CODING-TEST-"+(++requests);}
    private static void check(boolean ok,String label){checks++;if(!ok)throw new AssertionError(phase+": "+label);}
    private static void eq(Object a,Object b,String label){check(Objects.equals(a,b),label+" expected="+b+" actual="+a);}
    private static Object invoke(Class<?> owner,String name,Class<?>[] types,Object... args)throws Exception {Method m=owner.getDeclaredMethod(name,types);m.setAccessible(true);try{return m.invoke(null,args);}catch(InvocationTargetException e){if(e.getCause() instanceof Exception cause)throw cause;throw e;}}
    private static Map<String,Object> proof(){return map("evidence_note","隔离验收：已逐项核对业务来源、正式目录和实际金额，记录与本次申请一致。","evidence_reference","合成验收材料 / 编码核验 / 第1条");}
    private static Map<String,Object> withProof(Map<String,Object>b){b.putAll(proof());return b;}
    private static String digest(String s)throws Exception{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}
    private static String fingerprint(List<String> selected)throws Exception {
        synchronized(Api.MUTATION_LOCK){Map<String,Object> tables=new TreeMap<>();List<String> names=new ArrayList<>(selected);
            if(names.isEmpty())for(Map<String,Object> r:Db.query("SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='PUBLIC' AND TABLE_TYPE='BASE TABLE' ORDER BY TABLE_NAME"))names.add(r.get("table_name").toString());
            for(String name:names){List<String> records=new ArrayList<>();for(Map<String,Object> row:Db.query("SELECT * FROM "+name))records.add(Json.write(new TreeMap<>(row)));Collections.sort(records);tables.put(name,records);}return digest(Json.write(tables));}
    }
    private record Response(int status,byte[] bytes,String contentType,String disposition) {Map<String,Object> json(){return obj(Json.parse(new String(bytes,StandardCharsets.UTF_8)));}}
    private static Response http(String route,Map<String,Object> body,String actor)throws Exception {
        HttpURLConnection c=(HttpURLConnection)new URL("http://127.0.0.1:"+port+route).openConnection();c.setConnectTimeout(10000);c.setReadTimeout(15000);c.setRequestMethod(body==null?"GET":"POST");
        if(TOKENS.containsKey(actor))c.setRequestProperty("X-Token",TOKENS.get(actor));
        if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");try(OutputStream out=c.getOutputStream()){out.write(Json.write(body).getBytes(StandardCharsets.UTF_8));}}
        int status=c.getResponseCode();byte[] bytes;try(InputStream in=status<400?c.getInputStream():c.getErrorStream()){bytes=in==null?new byte[0]:in.readAllBytes();}
        Response r=new Response(status,bytes,c.getHeaderField("Content-Type"),c.getHeaderField("Content-Disposition"));c.disconnect();
        synchronized(TRACE){TRACE.add(map("phase",phase,"route",route,"actor",actor,"status",status,"bytes",bytes.length));}return r;
    }
    private static String errorText(Response r){return r.status==200?"":new String(r.bytes,0,Math.min(r.bytes.length,800),StandardCharsets.UTF_8);}
    private static Map<String,Object> api(String route,Map<String,Object> body,String actor)throws Exception {Response r=http(route,body,actor);check(r.status==200,route+" HTTP "+r.status+" "+errorText(r));Map<String,Object>envelope=r.json();eq(n(envelope.get("code")),0L,"success envelope");return obj(envelope.get("data"));}
    private static Map<String,Object> api(String route,Map<String,Object> body)throws Exception{return api(route,body,"worker");}
    private static void denied(String route,Map<String,Object>body,String actor,int status,String label)throws Exception {String before=fingerprint(List.of());Response r=http(route,body,actor);eq(r.status,status,label+" HTTP "+errorText(r));eq(fingerprint(List.of()),before,label+" no database writes");}
    private static Configuration config(String version,Set<String> omitted){
        Set<String> roles=Set.of("OPERATOR","REPORTER");RelationRule optional=new RelationRule(false,roles,false,false);List<Grant>grants=new ArrayList<>();
        for(String resource:List.of("delivery.read","delivery.write","delivery.verify","settlement.submit","settlement.review","settlement.configure","settlement.confirm","settlement.correct","settlement.pay","reports.read","reports.export","catalog.read","catalog.manage"))if(!omitted.contains(resource))grants.add(new Grant("G-"+resource,"OPERATOR",resource,resource.endsWith(".read")?Action.VIEW:resource.endsWith(".export")?Action.EXPORT:Action.HANDLE,Effect.ALLOW,Scope.OWN_ORG,Set.of()));
        for(String resource:List.of("reports.read","reports.export"))grants.add(new Grant("R-"+resource,"REPORTER",resource,resource.endsWith(".read")?Action.VIEW:Action.EXPORT,Effect.ALLOW,Scope.OWN_ORG,Set.of()));
        return new Configuration(version,new CodeRules("[0-9]{3}","[0-9]{4}","[A-Z]+"),roles,List.of(new Organization("001",null,true),new Organization("002",null,true)),
            List.of(new Person("0002","001",Set.of(),null,null,Set.of("OPERATOR"),true),new Person("0003","002",Set.of(),null,null,Set.of("OPERATOR"),true),new Person("0005","001",Set.of(),null,null,Set.of("OPERATOR"),true),new Person("0006","001",Set.of(),null,null,Set.of("REPORTER"),true)),
            List.of(new RoleRelations("OPERATOR",optional,optional),new RoleRelations("REPORTER",optional,optional)),List.of(new AccountBinding(2,"0002",true),new AccountBinding(3,"0003",true),new AccountBinding(5,"0005",true),new AccountBinding(6,"0006",true)),grants);
    }
    private static void publishAccess(Set<String> omitted)throws Exception {
        String expected=accessVersion==0?null:"CODING-ACCESS-"+accessVersion;
        admin=Auth.get(Auth.login("formal-admin",PASSWORD));OrganizationAccessStore.publish(admin,expected,config("CODING-ACCESS-"+(++accessVersion),omitted));
        for(String actor:List.of("admin","worker","outsider","unbound","colleague","reporter"))TOKENS.put(actor,Auth.login("formal-"+actor,PASSWORD));worker=Auth.get(TOKENS.get("worker"));outsider=Auth.get(TOKENS.get("outsider"));admin=Auth.get(TOKENS.get("admin"));
    }
    private static void setup(Path data)throws Exception {
        invoke(M05FormalWorkflowTest.class,"fixtures",new Class<?>[]{Path.class},data);
        Db.exec("ALTER TABLE teachers ADD teacher_level VARCHAR(40) DEFAULT '讲师'");Db.exec("ALTER TABLE teachers ADD base_city VARCHAR(40) DEFAULT '杭州'");
        for(long teacher:List.of(21L,22L))Db.exec("INSERT INTO teachers(id,name,status,fee_rate,teacher_level,base_city) VALUES(?,?,'在库',99999,'讲师','杭州')",teacher,"PRIVATE-CODING-TEACHER-"+teacher);
        for(int id:List.of(5,6))Db.exec("INSERT INTO users VALUES(?,?,?,?,?,1)",id,id==5?"formal-colleague":"formal-reporter",Auth.hash(PASSWORD),"PRIVATE-USER-"+id,"viewer");
        CourseCatalogIntegration.init();DeliverySettlementIntegration.init();publishAccess(Set.of());scope=n(CourseCatalogIntegration.registerScope(worker,"001").get("scope_id"));otherScope=n(CourseCatalogIntegration.registerScope(outsider,"002").get("scope_id"));
    }
    private static Map<String,Object> flow()throws Exception{return api("/api/delivery-settlement/workflow?dispatch_id=101",null);}
    private static Map<String,Object> flowBody()throws Exception{Map<String,Object>v=flow();return map("dispatch_id",101,"expected_version",v.get("version"),"expected_fact_version",v.get("fact_version"),"request_id",req());}
    private static void teaching()throws Exception {
        Map<String,Object>f=api("/api/delivery-settlement/save",map("dispatch_id",101,"expected_version",0,"request_id",req(),"estimated_hours","2.00","planned_hours","2.00","actual_minutes","90","payable_hours","2.00"));
        api("/api/delivery-settlement/verify",map("dispatch_id",101,"expected_version",f.get("version"),"request_id",req(),"evidence_code","SYNTHETIC-TEACHING-CHECK"));
        Map<String,Object>b=flowBody();b.put("claim",invoke(M05FormalWorkflowTest.class,"claim",new Class<?>[]{String.class,String.class},"LECTURER","NO"));api("/api/delivery-settlement/workflow/save",b);
        api("/api/delivery-settlement/workflow/submit",withProof(flowBody()));b=withProof(flowBody());b.put("decision","APPROVE");api("/api/delivery-settlement/workflow/review",b);
        b=flowBody();b.put("expected_settings_version",flow().get("settings_version"));Map<String,Object>v=api("/api/delivery-settlement/workflow/confirm",b);eq(obj(v.get("financial")).get("amount"),"200.00","real 200.00 frozen teaching");
        b=withProof(flowBody());b.put("expected_snapshot_code",obj(v.get("financial")).get("head_snapshot_code"));b.put("payment_date",TODAY);b.put("amount","200.00");api("/api/delivery-settlement/workflow/payment",b);
    }
    private static Map<String,Object> catalog(String version,boolean changed){return map("schema_version","m04_catalog_v1","catalog_version",version,"courses",List.of(map("course_code","00030","course_name",changed?"合成课程新名称":"合成课程","active",true),map("course_code","00031","course_name","合成更正课程","active",true)),"teachers",List.of(map("teacher_code","00020","teacher_level","讲师","city","杭州"),map("teacher_code","00021","teacher_level","讲师","city","杭州")),"certifications",List.of());}
    private static void publishCatalog(boolean changed)throws Exception {
        Map<String,Object>p=api("/api/course-catalog/scopes/"+scope+"/preview",map("expected_version",catalogVersion,"catalog",catalog("CODING-CATALOG-"+(catalogVersion+1),changed),"bindings",List.of(map("teacher_code","00020","teacher_id",20),map("teacher_code","00021","teacher_id",21)),"change_comment","隔离合成目录：核对真实绑定后发布"));
        eq(p.get("ready"),true,"actual catalog preview ready");api("/api/course-catalog/scopes/"+scope+"/confirm",map("expected_version",catalogVersion,"batch_id",p.get("batch_id"),"confirm",true));catalogVersion++;
    }
    private static Map<String,Object> coding(String chain)throws Exception{return api(BASE+"?chain_code="+chain,null);}
    private static String head(String chain)throws Exception{synchronized(Api.MUTATION_LOCK){return DeliverySettlementLedger.head(chain).get("current_entry_code").toString();}}
    private static Map<String,Object> previewBody(String chain,String course)throws Exception {Map<String,Object>r=coding(chain);Map<String,Object>b=withProof(map("chain_code",chain,"expected_version",r.get("version"),"expected_entry_code",head(chain),"scope_id",scope,"expected_catalog_version",catalogVersion,"course_code",course,"request_id",req()));if(n(r.get("version"))>0)b.putAll(map("reason_note","隔离验收：核对历史编码关联后明确更正，保留原审计版本。","reason_reference","合成更正核准单第1号"));return b;}
    private static Map<String,Object> confirmBody(String chain,Map<String,Object>preview)throws Exception{return map("chain_code",chain,"expected_version",preview.get("version"),"expected_entry_code",preview.get("expected_entry_code"),"preview_code",preview.get("preview_code"),"request_id",req());}
    private static Map<String,Object> codeChain(String chain,String course)throws Exception{Map<String,Object>p=api(BASE+"/preview",previewBody(chain,course));return api(BASE+"/confirm",confirmBody(chain,p));}
    private static String query(String basis,String start,String end){return "start="+start+"&end="+end+"&date_basis="+basis+"&organizations=001";}
    private static Map<String,Object> report(String q)throws Exception{return api("/api/management-settlement-reports?"+q,null,"reporter");}
    private static void workbook(String q,Map<String,Object>r,String name,String teacher,String course,String amount)throws Exception {
        String before=fingerprint(List.of());Response download=http("/api/management-settlement-reports/export?"+q+"&snapshot_version="+r.get("snapshot_version"),null,"reporter");eq(download.status,200,"nonempty real HTTP XLSX");check(download.contentType.startsWith("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),"XLSX content type");check(download.disposition.contains(".xlsx"),"attachment filename");check(download.bytes.length>1000&&download.bytes[0]=='P'&&download.bytes[1]=='K',"actual ZIP bytes");
        Files.write(artifacts.resolve(name),download.bytes);StringBuilder text=new StringBuilder();int sheets=0;
        var factory=javax.xml.parsers.DocumentBuilderFactory.newInstance();factory.setNamespaceAware(true);factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl",true);factory.setFeature("http://xml.org/sax/features/external-general-entities",false);factory.setFeature("http://xml.org/sax/features/external-parameter-entities",false);
        try(ZipInputStream zip=new ZipInputStream(new ByteArrayInputStream(download.bytes))){ZipEntry e;while((e=zip.getNextEntry())!=null){check(!e.getName().matches("(?i).*(vba|macro|externalLink|embedded|oleObject).*"),"no active workbook content");if(e.getName().endsWith(".xml")||e.getName().endsWith(".rels")){String xml=new String(zip.readAllBytes(),StandardCharsets.UTF_8);var doc=factory.newDocumentBuilder().parse(new ByteArrayInputStream(xml.getBytes(StandardCharsets.UTF_8)));eq(doc.getElementsByTagNameNS("*","f").getLength(),0,"no formulas");var rel=doc.getElementsByTagNameNS("*","Relationship");for(int i=0;i<rel.getLength();i++)check(!"External".equals(((org.w3c.dom.Element)rel.item(i)).getAttribute("TargetMode")),"no external relationship");if(e.getName().startsWith("xl/worksheets/"))sheets++;text.append(xml);}}}
        eq(sheets,5,"five workbook sheets");check(text.toString().contains(">"+teacher+"</t>")&&text.toString().contains(">"+course+"</t>"),"leading zero official codes remain text");check(text.toString().contains(">"+amount+"</v>"),"exact frozen money in numeric cell");check(!text.toString().contains("PRIVATE-")&&!text.toString().contains("SYNTHETIC TEACHER")&&!text.toString().contains("合成验收材料")&&!text.toString().contains("TEACHER-20"),"XLSX excludes names evidence and system IDs");eq(fingerprint(List.of()),before,"report download leaves all tables unchanged");
    }
    private static Map<String,Object> caseBody(String code,long version){return map("project_id",10,"case_code",code,"expected_version",version,"request_id",req());}
    private static Map<String,Object> caseCommand(String code)throws Exception{return caseBody(code,n(api("/api/delivery-settlement/cases?case_code="+code,null).get("version")));}
    private static Map<String,Object> completeCase(String code,String kind,Map<String,Object>payload)throws Exception {Map<String,Object>b=caseBody(code,0);b.put("kind",kind);b.put("payload",payload);api("/api/delivery-settlement/cases/save",b);api("/api/delivery-settlement/cases/submit",withProof(caseCommand(code)));b=withProof(caseCommand(code));b.put("decision","APPROVE");api("/api/delivery-settlement/cases/review",b);return api("/api/delivery-settlement/cases/confirm",caseCommand(code));}
    private static void mainChecks()throws Exception {
        phase="actual paid teaching";teaching();String chain="DISPATCH-101",q=query("TEACHING",DAY,TODAY),paidQuery=query("PAYMENT",TODAY,TODAY);Map<String,Object>missing=report(q);eq(obj(missing.get("totals")).get("amount"),"200.00","uncoded amount visible");eq(missing.get("export_available"),false,"missing codes block export");denied("/api/management-settlement-reports/export?"+q+"&snapshot_version="+missing.get("snapshot_version"),null,"reporter",409,"uncoded nonempty export");
        phase="catalog and coding permissions";eq(n(coding(chain).get("version")),0L,"coding initial revision zero");denied(BASE+"?chain_code="+chain,null,"anonymous",401,"anonymous coding read");denied(BASE+"?chain_code="+chain,null,"admin",403,"legacy admin no bypass");denied(BASE+"?chain_code="+chain,null,"outsider",403,"other institution no bypass");
        eq(obj(api(BASE+"/options?chain_code="+chain+"&scope_id="+scope,null).get("catalog")).get("status"),"NOT_CONFIGURED","empty catalog explicitly unavailable");denied(BASE+"/preview",previewBody(chain,"00030"),"worker",400,"unpublished catalog has no valid positive revision");publishCatalog(false);api(BASE+"/options?chain_code="+chain+"&scope_id="+scope,null);
        Map<String,Object>b=previewBody(chain,"FAKE-COURSE");denied(BASE+"/preview",b,"worker",409,"unknown course");
        for(String field:List.of("teacher_id","teacher_code","amount","catalog_digest")){b=previewBody(chain,"00030");b.put(field,field.equals("teacher_id")?21:"FORGED");denied(BASE+"/preview",b,"worker",400,"client cannot inject "+field);}
        b=previewBody(chain,"00030");b.put("scope_id",otherScope);denied(BASE+"/preview",b,"worker",403,"unauthorized catalog scope");b=previewBody(chain,"00030");b.put("expected_entry_code","OTHER-HEAD");denied(BASE+"/preview",b,"worker",409,"stale frozen financial head");
        phase="first audited overlay";String frozen=fingerprint(LEDGER_TABLES);Map<String,Object>previewRequest=previewBody(chain,"00030"),p=api(BASE+"/preview",previewRequest);String afterPreview=fingerprint(List.of());Map<String,Object>same=api(BASE+"/preview",previewRequest);eq(same,p,"preview exact retry");eq(fingerprint(List.of()),afterPreview,"preview retry no duplicate records");
        Map<String,Object>confirmRequest=confirmBody(chain,p);denied(BASE+"/confirm",confirmRequest,"colleague",409,"preview bound to actual account");Map<String,Object>coded=api(BASE+"/confirm",confirmRequest);eq(n(coded.get("version")),1L,"first audited coding revision");String committed=fingerprint(List.of());api(BASE+"/confirm",confirmRequest);eq(fingerprint(List.of()),committed,"confirm retry no duplicate records");eq(fingerprint(LEDGER_TABLES),frozen,"coding leaves original facts ledger payment raw bytes unchanged");
        publishAccess(Set.of("settlement.correct"));committed=fingerprint(List.of());Map<String,Object>firstRetry=api(BASE+"/confirm",confirmRequest);eq(n(confirmRequest.get("expected_version")),0L,"replayed command remains original first confirmation");eq(firstRetry.get("current"),coded.get("current"),"first confirmation retry does not require correction authority");eq(obj(firstRetry.get("capabilities")).get("can_correct"),false,"retry returns current revoked correction capability");eq(fingerprint(List.of()),committed,"first confirmation retry after grant change has no writes");publishAccess(Set.of());
        Map<String,Object>r=report(q);eq(r.get("export_available"),true,"coded nonempty month exportable");eq(rows(r.get("details")).get(0).get("teacher_code"),"00020","teacher code derived from catalog binding");eq(rows(r.get("details")).get(0).get("course_id"),null,"no invented course record ID");eq(obj(r.get("totals")).get("amount"),"200.00","coded amount unchanged");workbook(q,r,"teaching-coded.xlsx","00020","00030","200.00");Map<String,Object>cash=report(paidQuery);workbook(paidQuery,cash,"payment-coded.xlsx","00020","00030","200.00");
        phase="historical catalog and code correction";String current=Json.write(coding(chain).get("current"));publishCatalog(true);eq(Json.write(coding(chain).get("current")),current,"catalog update never rewrites saved coding");eq(obj(report(q).get("totals")).get("amount"),"200.00","catalog update never reprices");
        b=previewBody(chain,"00031");b.remove("reason_note");b.remove("reason_reference");denied(BASE+"/preview",b,"worker",400,"correction requires real reason");Map<String,Object>catalogPreviewRequest=previewBody(chain,"00031");p=api(BASE+"/preview",catalogPreviewRequest);Map<String,Object>staleCatalogConfirm=confirmBody(chain,p);publishCatalog(true);String beforeStaleReplay=fingerprint(List.of());Map<String,Object>staleReplay=api(BASE+"/preview",catalogPreviewRequest);eq(staleReplay.get("can_confirm"),false,"identical preview retry after catalog publication cannot claim confirmation capability");eq(staleReplay.get("preview_code"),p.get("preview_code"),"stale replay retains the original preview identity");eq(fingerprint(List.of()),beforeStaleReplay,"stale preview replay has no writes");eq(obj(coding(chain).get("capabilities")).get("can_confirm"),false,"ordinary read agrees with stale preview capability");denied(BASE+"/confirm",staleCatalogConfirm,"worker",409,"catalog publication invalidates preview");
        Map<String,Object>permissionPreviewRequest=previewBody(chain,"00031");p=api(BASE+"/preview",permissionPreviewRequest);Map<String,Object>stalePermissionConfirm=confirmBody(chain,p);String oldToken=TOKENS.get("worker");publishAccess(Set.of("catalog.read"));TOKENS.put("expired",oldToken);denied(BASE+"/confirm",stalePermissionConfirm,"expired",401,"revoked real session");denied(BASE+"/confirm",stalePermissionConfirm,"worker",409,"access publication invalidates previous preview");denied(BASE+"/preview",permissionPreviewRequest,"worker",403,"identical preview retry cannot swallow revoked catalog read permission");denied(BASE+"/preview",previewBody(chain,"00031"),"worker",403,"current catalog read permission required");eq(report(q).get("export_available"),true,"frozen coding reports do not require current catalog grant");publishAccess(Set.of());
        p=api(BASE+"/preview",previewBody(chain,"00031"));Map<String,Object>a=confirmBody(chain,p),other=copy(a);other.put("request_id",req());ExecutorService race=Executors.newFixedThreadPool(2);try {Future<Response>x=race.submit(()->http(BASE+"/confirm",a,"worker")),y=race.submit(()->http(BASE+"/confirm",other,"worker"));List<Integer>status=new ArrayList<>(List.of(x.get().status,y.get().status));Collections.sort(status);eq(status,List.of(200,409),"parallel CAS has one coding commit");}finally{race.shutdownNow();}
        eq(n(coding(chain).get("version")),2L,"one correction revision");eq(rows(coding(chain).get("history")).size(),1,"prior coding revision retained separately from current");eq(n(rows(coding(chain).get("history")).get(0).get("version")),1L,"first audit remains in history");eq(n(obj(coding(chain).get("current")).get("version")),2L,"latest audit is current");denied("/api/management-settlement-reports/export?"+q+"&snapshot_version="+r.get("snapshot_version"),null,"reporter",409,"old download snapshot invalid after coding correction");eq(fingerprint(LEDGER_TABLES),frozen,"catalog and coding correction never mutate original ledger");
        phase="development members and historical legacy";Map<String,Object>joint=completeCase("CODING-JOINT","DEVELOPMENT",obj(invoke(M05CasesTest.class,"dev",new Class<?>[]{String.class,boolean.class},"CODING-JOINT-DELIVERABLE",true)));List<Map<String,Object>>jointChains=rows(obj(joint.get("confirmation")).get("chains"));eq(jointChains.size(),2,"real joint case creates two independent member chains");String beforeBranches=fingerprint(LEDGER_TABLES);for(Map<String,Object>h:jointChains)codeChain(h.get("chain_code").toString(),"00030");eq(fingerprint(LEDGER_TABLES),beforeBranches,"joint overlay preserves financial bytes");
        Map<String,Object>migration=completeCase("CODING-LEGACY","MIGRATION",obj(invoke(M05CasesTest.class,"migration",new Class<?>[]{String.class},"合成旧台账 / 编码测试 / 唯一第1条")));String legacy=rows(obj(migration.get("confirmation")).get("chains")).get(0).get("chain_code").toString();
        Map<String,Object>adjustment=withProof(map("chain_code",legacy,"expected_entry_code",head(legacy),"reason_note","隔离验收：根据原始材料明确改至另一业务日。","reason_reference","合成旧账更正单","service_date",LocalDate.parse(DAY).minusDays(2).toString(),"amount","200.00","legacy_rule_code","原培训课酬管理标准〔2025〕第3号","source_note","隔离验收：旧台账跨日更正总额为200元。","original_approval_note","隔离验收：已逐项核对原制度核准依据。"));completeCase("CODING-LEGACY-ADJUST","ADJUSTMENT",adjustment);
        beforeBranches=fingerprint(LEDGER_TABLES);codeChain(legacy,"00030");eq(fingerprint(LEDGER_TABLES),beforeBranches,"legacy coding preserves historical actual payment");
        synchronized(Api.MUTATION_LOCK){Map<String,Object>source=DeliverySettlementIntegration.financialSource(worker,10,false);List<Map<String,Object>>events=rows(source.get("accrual_entries")).stream().filter(e->legacy.equals(e.get("chain_code"))).toList();eq(events.size(),3,"legacy crossdate has original reversal and rebook");check(events.stream().allMatch(e->"00020".equals(e.get("teacher_code"))&&"00030".equals(e.get("course_code"))&&e.get("course_id")==null),"same audited codes cover every chain accrual without invented IDs");check(source.get("coding_versions") instanceof List<?> && source.get("coding_coverage") instanceof Map<?,?>,"formal source carries explicit coding metadata and coverage");}
        Map<String,Object>beforeMonthOutside=report(q);codeChain(legacy,"00031");denied("/api/management-settlement-reports/export?"+q+"&snapshot_version="+beforeMonthOutside.get("snapshot_version"),null,"reporter",409,"coding outside selected date still invalidates complete source version");
        postLinkChecks(legacy,chain,q);extraChecks(chain,q);System.out.println("M05Coding: "+checks+" checks passed (actual Api HTTP, fresh synthetic H2, r18 baseline plus isolated candidates)");
    }
    private static void rejects(int status,Work work,String label)throws Exception {String before=fingerprint(List.of());try{work.run();throw new AssertionError("Expected rejection: "+label);}catch(Api.ApiException e){eq(e.code,status,label+" "+e.getMessage());}eq(fingerprint(List.of()),before,label+" no writes");}
    private static void extraChecks(String chain,String q)throws Exception {
        phase="catalog capture immutable binding";Map<String,Object>capture=copy(obj(obj(coding(chain).get("current")).get("capture")));
        synchronized(Api.MUTATION_LOCK){CourseCatalogIntegration.validateCapturedCoding(copy(capture));check(true,"frozen capture survives JSON roundtrip");}
        for(String field:List.of("teacher_id","teacher_code","catalog_scope_id","course_code","catalog_digest")){Map<String,Object>bad=copy(capture);bad.put(field,switch(field){case "teacher_id"->21L;case "catalog_scope_id"->otherScope;case "catalog_digest"->"f".repeat(64);default->"FORGED-CODE";});rejects(409,()->{synchronized(Api.MUTATION_LOCK){CourseCatalogIntegration.validateCapturedCoding(bad);}},"frozen capture rejects "+field);}
        Map<String,Object>unboundPayload=obj(invoke(M05CasesTest.class,"migration",new Class<?>[]{String.class},"合成旧台账 / 未绑定讲师22 / 唯一第2条"));unboundPayload.put("teacher_id",22);Map<String,Object>unbound=completeCase("CODING-UNBOUND","MIGRATION",unboundPayload);String noTeacher=rows(obj(unbound.get("confirmation")).get("chains")).get(0).get("chain_code").toString();Map<String,Object>options=api(BASE+"/options?chain_code="+noTeacher+"&scope_id="+scope,null);eq(obj(options.get("catalog")).get("status"),"TEACHER_UNBOUND","unbound real teacher not guessed from course or name");denied(BASE+"/preview",previewBody(noTeacher,"00030"),"worker",409,"different teacher cannot reuse a catalog binding");
        phase="expired preview";Map<String,Object>p=api(BASE+"/preview",previewBody(chain,"00030"));String previewCode=p.get("preview_code").toString();Map<String,Object>row=Db.one("SELECT * FROM m05_coding_previews WHERE preview_code=?",previewCode),payload=obj(Json.parse(row.get("payload").toString()));String now=Instant.now().minusSeconds(901).toString(),expired=Instant.parse(now).plusSeconds(900).toString();payload.put("created_at",now);payload.put("expires_at",expired);
        Class<?> codingClass=Class.forName("com.training.DeliverySettlementCoding");String hash=(String)invoke(codingClass,"digest",new Class<?>[]{Object.class},payload);
        Db.exec("UPDATE m05_coding_previews SET created_at=?,expires_at=?,payload=?,payload_digest=? WHERE preview_code=?",now,expired,Json.write(payload),hash,previewCode);
        try{denied(BASE+"/confirm",confirmBody(chain,p),"worker",409,"elapsed 15 minute preview cannot commit");}finally{Db.exec("UPDATE m05_coding_previews SET created_at=?,expires_at=?,payload=?,payload_digest=? WHERE preview_code=?",row.get("created_at"),row.get("expires_at"),row.get("payload"),row.get("payload_digest"),previewCode);}
        phase="append-only coding and catalog damage fails closed";String stableLedger=fingerprint(LEDGER_TABLES);Map<String,Object>revision=Db.one("SELECT * FROM m05_coding_revisions WHERE chain_code=? AND version=1",chain);
        Db.exec("UPDATE m05_coding_revisions SET payload=? WHERE chain_code=? AND version=1","{broken",chain);
        try{damageRejected(chain,q,"malformed earliest coding revision");}finally{Db.exec("UPDATE m05_coding_revisions SET payload=? WHERE chain_code=? AND version=1",revision.get("payload"),chain);}
        Db.exec("DELETE FROM m05_coding_revisions WHERE chain_code=? AND version=1",chain);
        try{damageRejected(chain,q,"missing earliest coding revision");}finally{Db.exec("INSERT INTO m05_coding_revisions VALUES(?,?,?,?,?,?,?)",revision.get("chain_code"),revision.get("version"),revision.get("record_code"),revision.get("payload"),revision.get("actor_code"),revision.get("account_id"),revision.get("confirmed_at"));}
        Map<String,Object>oldCatalog=Db.one("SELECT payload FROM m04_catalog_revisions WHERE scope_id=? AND version=1",scope);Db.exec("UPDATE m04_catalog_revisions SET payload=? WHERE scope_id=? AND version=1","{broken",scope);
        try{damageRejected(chain,q,"damaged historical catalog revision");}finally{Db.exec("UPDATE m04_catalog_revisions SET payload=? WHERE scope_id=? AND version=1",oldCatalog.get("payload"),scope);}
        Map<String,Object>latest=Db.one("SELECT * FROM m05_coding_revisions WHERE chain_code=? AND version=2",chain);String original=latest.get("payload").toString();Map<String,Object>bad=obj(Json.parse(original)),badPreview=obj(bad.get("preview_snapshot"));String used=badPreview.get("preview_code").toString();Map<String,Object>usedPreview=Db.one("SELECT payload,payload_digest FROM m05_coding_previews WHERE preview_code=?",used);
        bad.put("evidence_note","篡改测试：不是原确认人的说明。");bad.put("evidence_reference","篡改测试：替换原凭据位置。");badPreview.put("evidence_note",bad.get("evidence_note"));badPreview.put("evidence_reference",bad.get("evidence_reference"));String altered=Json.write(bad),alteredPreview=Json.write(badPreview),alteredDigest=(String)invoke(codingClass,"digest",new Class<?>[]{Object.class},badPreview);
        Db.exec("UPDATE m05_coding_heads SET payload=? WHERE chain_code=?",altered,chain);Db.exec("UPDATE m05_coding_revisions SET payload=? WHERE chain_code=? AND version=2",altered,chain);Db.exec("UPDATE m05_coding_previews SET payload=?,payload_digest=? WHERE preview_code=?",alteredPreview,alteredDigest,used);
        try {Map<String,Object>descriptor=obj(invoke(codingClass,"descriptor",new Class<?>[]{Map.class},bad));rejects(409,()->DeliverySettlementEvidence.resolve(bad.get("evidence_code").toString(),10,"001",chain,"SETTLEMENT-CODING",descriptor),"registered immutable proof rejects coordinated note and reference rewrite");damageRejected(chain,q,"coordinated head revision and preview note rewrite");}
        finally{Db.exec("UPDATE m05_coding_heads SET payload=? WHERE chain_code=?",original,chain);Db.exec("UPDATE m05_coding_revisions SET payload=? WHERE chain_code=? AND version=2",original,chain);Db.exec("UPDATE m05_coding_previews SET payload=?,payload_digest=? WHERE preview_code=?",usedPreview.get("payload"),usedPreview.get("payload_digest"),used);}
        eq(fingerprint(LEDGER_TABLES),stableLedger,"corruption rejection never writes old financial records");eq(report(q).get("export_available"),true,"valid restoration recovers coded selected report");
        phase="separate correction authority";publishAccess(Set.of("settlement.correct"));denied(BASE+"/preview",previewBody(chain,"00030"),"worker",403,"correction requires separate exact grant");publishAccess(Set.of());
    }
    private static void postLinkChecks(String legacy,String teaching,String q)throws Exception {
        phase="legitimate financial activity after coding";Map<String,Object>before=coding(legacy);String codingBytes=fingerprint(List.of("m05_coding_heads","m05_coding_revisions","m05_coding_previews","m05_coding_requests"));
        Map<String,Object>adjustment=withProof(map("chain_code",legacy,"expected_entry_code",head(legacy),"reason_note","隔离验收：关联编码以后，按原制度合法追加十元差额。","reason_reference","合成旧账追加核准单","service_date",LocalDate.parse(DAY).minusDays(2).toString(),"amount","210.00","legacy_rule_code","原培训课酬管理标准〔2025〕第3号","source_note","隔离验收：原始凭据核实总额210元。","original_approval_note","隔离验收：追加差额的原制度核准已经核实。"));completeCase("CODING-POSTLINK-ADJUST","ADJUSTMENT",adjustment);
        Map<String,Object>pay=withProof(caseCommand("CODING-POSTLINK-ADJUST"));pay.putAll(map("chain_code",legacy,"expected_entry_code",head(legacy),"payment_date",TODAY,"amount","60.00"));api("/api/delivery-settlement/cases/payment",pay);
        Map<String,Object>after=coding(legacy);eq(after.get("current"),before.get("current"),"legal adjustment and payment preserve the original coding audit");check(!Objects.equals(after.get("current_entry_code"),before.get("current_entry_code")),"read exposes new actual financial head separately");eq(fingerprint(List.of("m05_coding_heads","m05_coding_revisions","m05_coding_previews","m05_coding_requests")),codingBytes,"legitimate financial activity does not rewrite any coding rows");
        synchronized(Api.MUTATION_LOCK){Map<String,Object>source=DeliverySettlementIntegration.financialSource(worker,10,false);List<Map<String,Object>>events=rows(source.get("accrual_entries")).stream().filter(e->legacy.equals(e.get("chain_code"))).toList();eq(events.size(),4,"later lawful adjustment extends chain");check(events.stream().allMatch(e->"00020".equals(e.get("teacher_code"))&&"00031".equals(e.get("course_code"))),"new and old accruals retain selected catalog identity");eq(DeliverySettlementLedger.balance(legacy).get("balance"),"0.00","real post-link payment settles 60.00 remaining");}
        Map<String,Object>cash=report(query("PAYMENT",TODAY,TODAY));List<Map<String,Object>>paid=rows(cash.get("details")).stream().filter(e->legacy.equals(e.get("chain_code"))).toList();eq(paid.size(),1,"post-link actual payment appears once");eq(paid.get(0).get("amount"),"60.00","post-link payment exact amount");eq(paid.get(0).get("teacher_code"),"00020","new payment inherits teacher code from unchanged reference");eq(paid.get(0).get("course_code"),"00031","new payment inherits audited course code");
        phase="archived project coding remains readable";Map<String,Object>pending=api(BASE+"/preview",previewBody(teaching,"00030")),pendingConfirm=confirmBody(teaching,pending),pendingPreview=previewBody(teaching,"00030");Object status=Db.one("SELECT status FROM projects WHERE id=10").get("status");Db.exec("UPDATE projects SET status='已归档' WHERE id=10");
        try {Map<String,Object>archived=coding(legacy);eq(archived.get("current"),before.get("current"),"archive status does not erase historical coded identity");eq(obj(archived.get("capabilities")).get("can_preview"),false,"archive read disables writes");eq(report(q).get("export_available"),true,"archived project coded report remains available");denied(BASE+"/preview",pendingPreview,"worker",409,"archived project cannot write new coding preview");denied(BASE+"/confirm",pendingConfirm,"worker",409,"archived project cannot commit old prepared preview");}
        finally{Db.exec("UPDATE projects SET status=? WHERE id=10",status);}
    }
    private static void damageRejected(String chain,String q,String label)throws Exception {denied(BASE+"?chain_code="+chain,null,"worker",409,label+" coding read");denied("/api/management-settlement-reports?"+q,null,"reporter",409,label+" report read");}
    private static Object normalized(Object v){if(v instanceof Number n)return new BigDecimal(n.toString()).stripTrailingZeros();if(v instanceof Map<?,?> m){Map<String,Object>sorted=new TreeMap<>();m.forEach((k,x)->sorted.put(k.toString(),normalized(x)));return sorted;}if(v instanceof List<?>l)return l.stream().map(M05CodingTest::normalized).toList();return v;}
    private static String responseDigest(Map<String,Object> v)throws Exception {Map<String,Object>m=copy(v);m.remove("capabilities");return digest(Json.write(normalized(m)));}
    private static void loginExisting()throws Exception {TOKENS.put("worker",Auth.login("formal-worker",PASSWORD));worker=Auth.get(TOKENS.get("worker"));check(worker!=null,"existing persisted account authenticates after database restart");}
    private static void assertRecovered(Map<String,Object>request,String expected,long version,String label)throws Exception {Map<String,Object>r=api(BASE+"/confirm",request);eq(n(r.get("version")),version,label+" preserves original response version");eq(responseDigest(r),expected,label+" reconstructs true original current and history prefix");eq(rows(r.get("history")).size(),Math.toIntExact(version-1),label+" exact original history prefix length");}
    private static void longCreate(Path data)throws Exception {
        phase="long-history paid source and catalog";teaching();publishCatalog(false);String chain="DISPATCH-101",entry=head(chain),ledger=fingerprint(LEDGER_TABLES);Map<String,Object>firstRequest=null,lastRequest=null,firstView=null,lastView=null;
        String note="隔离长历史："+"合成核验说明。".repeat(280),reference="合成长材料/".repeat(70);int revisions=26;
        phase="long legitimate audit confirmations";
        for(int version=0;version<revisions;version++) {
            Map<String,Object>b=map("chain_code",chain,"expected_version",version,"expected_entry_code",entry,"scope_id",scope,"expected_catalog_version",catalogVersion,"course_code",version%2==0?"00030":"00031","evidence_note",note+" 第"+(version+1)+"次明确确认。","evidence_reference",reference,"request_id",req());
            if(version>0)b.putAll(map("reason_note",note+" 本次修正保留原审计记录。","reason_reference",reference));
            Map<String,Object>p=api(BASE+"/preview",b),command=confirmBody(chain,p),v=api(BASE+"/confirm",command);eq(n(v.get("version")),(long)version+1,"long history append accepted");
            if(version==0){firstRequest=copy(command);firstView=v;}lastRequest=copy(command);lastView=v;
            if((version+1)%5==0)System.out.println("M05Coding long: "+(version+1)+" legitimate revisions confirmed");
        }
        int characters=Json.write(lastView).length();check(characters>250000,"decoded Json.write(view) exceeds original 250000-character parser limit; actual="+characters);eq(fingerprint(LEDGER_TABLES),ledger,"long coding history leaves original ledger and cash byte-for-byte unchanged");
        int minConfirm=Integer.MAX_VALUE,maxConfirm=0,maxReceipt=0,totalReceipt=0;List<Map<String,Object>>receipts=Db.query("SELECT operation,response FROM m05_coding_requests ORDER BY request_id");eq(receipts.size(),revisions*2,"one preview and confirmation receipt per revision");
        for(Map<String,Object>r:receipts){String encoded=r.get("response").toString();totalReceipt+=encoded.length();Map<String,Object>receipt=obj(Json.parse(encoded));eq(receipt.get("schema_version"),"m05_coding_receipt_v1","compact receipt schema");check(encoded.length()<=16384,"each new receipt has fixed 16K upper bound");check(!receipt.containsKey("history")&&!receipt.containsKey("current")&&!receipt.containsKey("candidate"),"new receipt never persists an aggregate view");maxReceipt=Math.max(maxReceipt,encoded.length());if("confirm".equals(r.get("operation"))){minConfirm=Math.min(minConfirm,encoded.length());maxConfirm=Math.max(maxConfirm,encoded.length());}}
        check(maxConfirm-minConfirm<200,"receipt size stays constant as audit history grows");String firstHash=responseDigest(firstView),lastHash=responseDigest(lastView),stable=fingerprint(List.of());
        phase="oversized aggregate response replay";assertRecovered(lastRequest,lastHash,revisions,"latest large response replay");assertRecovered(firstRequest,firstHash,1,"old request replay after many corrections");eq(fingerprint(List.of()),stable,"large and old request retries have no writes");
        Class<?>owner=Class.forName("com.training.DeliverySettlementCoding");Map<String,Object>stored=Db.one("SELECT response,response_digest FROM m05_coding_requests WHERE account_id=2 AND request_id=?",lastRequest.get("request_id"));
        phase="legacy large response compatibility";Db.exec("UPDATE m05_coding_requests SET response=?,response_digest=? WHERE account_id=2 AND request_id=?",Json.write(lastView),invoke(owner,"digest",new Class<?>[]{Object.class},lastView),lastRequest.get("request_id"));
        try {String before=fingerprint(List.of());assertRecovered(lastRequest,lastHash,revisions,"legacy full response above 250000 characters");eq(fingerprint(List.of()),before,"legacy retry performs no migration or rewriting");Map<String,Object>forged=copy(lastView);rows(forged.get("history")).get(0).put("evidence_note","篡改旧聚合响应的历史说明");Db.exec("UPDATE m05_coding_requests SET response=?,response_digest=? WHERE account_id=2 AND request_id=?",Json.write(forged),invoke(owner,"digest",new Class<?>[]{Object.class},forged),lastRequest.get("request_id"));denied(BASE+"/confirm",lastRequest,"worker",409,"legacy response must match real immutable audit history");}
        finally{Db.exec("UPDATE m05_coding_requests SET response=?,response_digest=? WHERE account_id=2 AND request_id=?",stored.get("response"),stored.get("response_digest"),lastRequest.get("request_id"));}
        phase="compact receipt semantic tampering";Map<String,Object>receipt=obj(Json.parse(stored.get("response").toString()));
        for(String field:List.of("version","record_digest","response_context")){Map<String,Object>bad=copy(receipt);if(field.equals("version"))bad.put(field,revisions+1);else if(field.equals("record_digest"))bad.put(field,"f".repeat(64));else obj(bad.get(field)).put("project_id",11);
            Db.exec("UPDATE m05_coding_requests SET response=?,response_digest=? WHERE account_id=2 AND request_id=?",Json.write(bad),invoke(owner,"digest",new Class<?>[]{Object.class},bad),lastRequest.get("request_id"));
            try{denied(BASE+"/confirm",lastRequest,"worker",409,"tampered compact receipt "+field+" remains rejected with recomputed envelope digest");}finally{Db.exec("UPDATE m05_coding_requests SET response=?,response_digest=? WHERE account_id=2 AND request_id=?",stored.get("response"),stored.get("response_digest"),lastRequest.get("request_id"));}}
        eq(fingerprint(List.of()),stable,"restoring temporary corruption returns to exact complete database state");
        phase="database shutdown and reopen";synchronized(Api.MUTATION_LOCK){Db.exec("SHUTDOWN");}loginExisting();assertRecovered(lastRequest,lastHash,revisions,"reopened H2 same original request");eq(fingerprint(List.of()),stable,"database reopen and request recovery do not mutate rows");
        Map<String,Object>plan=map("schema_version","synthetic_long_coding_replay_v1","data_directory",data.toString(),"first_request",firstRequest,"first_hash",firstHash,"last_request",lastRequest,"last_hash",lastHash,"version",revisions,"database_hash",stable,"ledger_hash",ledger,"response_characters",characters,"max_receipt_characters",maxReceipt);
        Files.writeString(data.resolve("coding-replay-plan.json"),Json.write(plan));Files.writeString(artifacts.resolve("long-history-result.json"),Json.write(map("revisions",revisions,"response_characters",characters,"max_receipt_characters",maxReceipt,"total_receipt_characters",totalReceipt,"receipt_count",receipts.size(),"checks",checks,"ledger_before",ledger,"ledger_after",fingerprint(LEDGER_TABLES),"database_reopen_passed",true,"old_full_response_compatibility_passed",true)));
        System.out.println("M05Coding long-create: "+checks+" checks passed; "+revisions+" revisions; decoded response="+characters+" chars; max receipt="+maxReceipt+" chars");
    }
    private static void longReplay(Path data)throws Exception {
        phase="fresh JVM replay from persisted H2";Map<String,Object>plan=obj(Json.parse(Files.readString(data.resolve("coding-replay-plan.json"))));eq(plan.get("schema_version"),"synthetic_long_coding_replay_v1","explicit private restart checkpoint");eq(plan.get("data_directory"),data.toString(),"checkpoint belongs to this exact temporary database");loginExisting();String stable=plan.get("database_hash").toString();eq(fingerprint(List.of()),stable,"cold JVM loaded exact persisted database");
        Map<String,Object>last=obj(plan.get("last_request")),first=obj(plan.get("first_request"));assertRecovered(last,plan.get("last_hash").toString(),n(plan.get("version")),"cold JVM latest request recovery");assertRecovered(first,plan.get("first_hash").toString(),1,"cold JVM initial request recovery");eq(fingerprint(List.of()),stable,"cold restart retries leave all rows unchanged");eq(fingerprint(LEDGER_TABLES),plan.get("ledger_hash"),"cold restart retains original financial rows");
        Files.writeString(artifacts.resolve("cold-restart-result.json"),Json.write(map("checks",checks,"passed",true,"version",plan.get("version"),"response_characters",plan.get("response_characters"),"database_unchanged",true,"separate_jvm",true)));System.out.println("M05Coding long-replay: "+checks+" checks passed (separate JVM, persisted synthetic H2, original request IDs)");
    }
    public static void main(String[]args)throws Exception {
        if(args.length<2||args.length>3)throw new IllegalArgumentException("Fresh empty data directory and artifact directory required");String mode=args.length==3?args[2]:"standard";if(!Set.of("standard","long-create","long-replay").contains(mode))throw new IllegalArgumentException("Unknown test mode");Path data=Path.of(args[0]).toAbsolutePath().normalize();if(!Files.isDirectory(data)||Files.isSymbolicLink(data))throw new IllegalArgumentException("Real empty directory required");artifacts=Path.of(args[1]).toAbsolutePath().normalize();Files.createDirectories(artifacts);
        if(mode.equals("long-replay")){if(!Files.isRegularFile(data.resolve("coding-replay-plan.json")))throw new IllegalArgumentException("Explicit synthetic restart plan required");System.setProperty("data.dir",data.toString());}else{try(var files=Files.list(data)){if(files.findAny().isPresent())throw new IllegalArgumentException("Fresh empty H2 required");}setup(data);}
        HttpServer server=HttpServer.create(new InetSocketAddress("127.0.0.1",0),0);ExecutorService executor=Executors.newFixedThreadPool(4);server.setExecutor(executor);server.createContext("/api/",Api::handle);server.start();port=server.getAddress().getPort();
        try{if(mode.equals("long-create"))longCreate(data);else if(mode.equals("long-replay"))longReplay(data);else mainChecks();}finally{server.stop(0);executor.shutdownNow();Files.writeString(artifacts.resolve(mode+"-http-trace.json"),Json.write(TRACE));Db.exec("SHUTDOWN");}
    }
}
