package com.training;

import com.sun.net.httpserver.*;
import java.io.*;
import java.lang.reflect.*;
import java.net.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.sql.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.zip.*;
import org.h2.api.Trigger;
import static com.training.OrganizationAccess.*;
import static com.training.SurveySummaryImportsPolicy.*;

/** Candidate-only tests. Fresh synthetic H2, synthetic XLSX, and isolated loopback HTTP. Never Db.init(). */
public final class M07FormalTest {
    private static final String PASS="SYNTHETIC-M07-FORMAL-ONLY";
    private static final List<String> TABLES=List.of("m07_policy_revisions","m07_policy_heads","m07_result_heads","m07_result_events","m07_file_claims","m07_result_requests");
    private static Auth.Session admin,author,reviewer,outsider,reader,publisher,wrongRole;
    private static String authorToken,reviewerToken,readerToken;
    private static long nextProject=100;private static int nextRequest=1,identityVersion,passed,failed;
    private static String policyVersion="POLICY-1";
    @FunctionalInterface interface Work {void run()throws Exception;}
    private static void check(boolean x,String m){if(!x)throw new AssertionError(m);}
    private static void eq(Object a,Object b){check(Objects.equals(a,b),"expected="+a+" actual="+b);}
    private static void run(String label,Work w){try{w.run();passed++;System.out.println("PASS "+label);}catch(Throwable e){failed++;System.out.println("FAIL "+label+": "+e.getClass().getSimpleName()+" "+e.getMessage());}}
    private static void rejects(int code,Work w)throws Exception{try{w.run();throw new AssertionError("expected "+code);}catch(Api.ApiException e){eq(code,e.code);}}
    @SuppressWarnings("unchecked")private static Map<String,Object> map(Object o){return(Map<String,Object>)o;}
    @SuppressWarnings("unchecked")private static List<Map<String,Object>> list(Object o){return(List<Map<String,Object>>)o;}
    private static long n(Object o){return new java.math.BigDecimal(o.toString()).longValueExact();}
    private static String request(){return "REQ-"+nextRequest++;}
    private static Map<String,Object> copy(Map<String,Object> m){return map(Json.parse(Json.write(m)));}
    private static void sql(String q,Object...args)throws Exception{synchronized(Api.MUTATION_LOCK){Db.exec(q,args);}}
    private static Policy policy(String version,boolean confirmed){return new Policy(version,true,"SYNTHETIC-EVIDENCE",confirmed,Set.of("REVIEWER"));}
    private static Configuration identity(){
        RelationRule optional=new RelationRule(false,Set.of("AUTHOR","REVIEWER","READER","PUBLISHER"),false,false);
        List<Grant> grants=new ArrayList<>();
        for(String role:List.of("AUTHOR","REVIEWER","READER","PUBLISHER"))grants.add(new Grant(role+"-READ",role,"survey.read",Action.VIEW,Effect.ALLOW,Scope.OWN_ORG,Set.of()));
        for(String resource:List.of("survey.preview","survey.import","survey.review"))grants.add(new Grant("AUTHOR-"+resource,"AUTHOR",resource,Action.HANDLE,Effect.ALLOW,Scope.OWN_ORG,Set.of()));
        grants.add(new Grant("REVIEW","REVIEWER","survey.review",Action.HANDLE,Effect.ALLOW,Scope.OWN_ORG,Set.of()));
        grants.add(new Grant("POLICY","PUBLISHER","survey.policy",Action.HANDLE,Effect.ALLOW,Scope.OWN_ORG,Set.of()));
        List<Person> people=List.of(new Person("0002","001",Set.of(),null,null,Set.of("AUTHOR","REVIEWER"),true),new Person("0003","001",Set.of(),null,null,Set.of("REVIEWER"),true),new Person("0004","002",Set.of(),null,null,Set.of("AUTHOR","REVIEWER"),true),new Person("0005","001",Set.of(),null,null,Set.of("READER"),true),new Person("0006","001",Set.of(),null,null,Set.of("PUBLISHER"),true),new Person("0007","001",Set.of(),null,null,Set.of("AUTHOR"),true));
        List<AccountBinding> bindings=new ArrayList<>();for(long id=2;id<=7;id++)bindings.add(new AccountBinding(id,String.format("%04d",id),true));
        return new Configuration("IDENTITY-"+(++identityVersion),new CodeRules("[0-9]{3}","[0-9]{4}","[A-Z]+"),Set.of("AUTHOR","REVIEWER","READER","PUBLISHER"),List.of(new Organization("001",null,true),new Organization("002",null,true)),people,List.of(new RoleRelations("AUTHOR",optional,optional),new RoleRelations("REVIEWER",optional,optional),new RoleRelations("READER",optional,optional),new RoleRelations("PUBLISHER",optional,optional)),bindings,grants);
    }
    private static void publishIdentity(Configuration candidate)throws Exception{Configuration old=OrganizationAccessStore.configuration();OrganizationAccessStore.publish(admin,old==null?null:old.version(),candidate);loginAll();}
    private static Configuration altered(Configuration c,List<Person>people,List<AccountBinding>bindings,List<Grant>grants){return new Configuration("IDENTITY-"+(++identityVersion),c.codeRules(),c.roleCodes(),c.organizations(),people,c.relations(),bindings,grants,c.combinedApprovals());}
    private static void loginAll()throws Exception{authorToken=Auth.login("u2",PASS);author=Auth.get(authorToken);reviewerToken=Auth.login("u3",PASS);reviewer=Auth.get(reviewerToken);outsider=Auth.get(Auth.login("u4",PASS));readerToken=Auth.login("u5",PASS);reader=Auth.get(readerToken);publisher=Auth.get(Auth.login("u6",PASS));wrongRole=Auth.get(Auth.login("u7",PASS));}
    private static void fixture(Path path)throws Exception{
        System.setProperty("data.dir",path.toString());
        Db.exec("CREATE TABLE users(id BIGINT PRIMARY KEY,username VARCHAR(64) UNIQUE,password VARCHAR(128),name VARCHAR(64),role VARCHAR(16),status INT)");
        // Current Auth/M01 also require the real first-bind and trusted-device schemas.
        FirstBindStore.init(); TrustedDevices.init();
        Db.exec("CREATE TABLE projects(id BIGINT PRIMARY KEY,demand_id BIGINT,title VARCHAR(200),status VARCHAR(32))");
        Db.exec("CREATE TABLE workflow_demands(demand_id BIGINT PRIMARY KEY,organization_code VARCHAR(120),data_revision BIGINT,version BIGINT,draft BOOLEAN)");
        Db.exec("CREATE TABLE workflow_acceptances(demand_id BIGINT PRIMARY KEY,project_id BIGINT UNIQUE,data_revision BIGINT,team_code VARCHAR(120),actor_code VARCHAR(120),created_at VARCHAR(40))");
        String hash=Auth.hash(PASS);for(int id=1;id<=8;id++)Db.exec("INSERT INTO users VALUES(?,?,?,?,?,1)",id,"u"+id,hash,"SYNTHETIC USER "+id,id==1?"admin":"viewer");
        admin=Auth.get(Auth.login("u1",PASS));OrganizationAccessStore.init();publishIdentity(identity());SurveySummaryImportsFormal.init();SurveySummaryImportsFormal.init();
        check(Db.get().getMetaData().getURL().contains(path.resolve("training").toString()),"isolated H2 required");
    }
    private static long project(String org)throws Exception{long id=++nextProject;sql("INSERT INTO workflow_demands VALUES(?,?,1,1,FALSE)",id,org);sql("INSERT INTO projects VALUES(?,?,?,'进行中')",id,id,"SYNTHETIC PROJECT "+id);sql("INSERT INTO workflow_acceptances VALUES(?,?,1,'TEAM','ACTOR','2026-01-01T00:00:00Z')",id,id);return id;}
    private static Map<String,Object> upload(long id,String marker,String score,long replaces,String reason)throws Exception{return new LinkedHashMap<>(Map.of("fileName","SYNTHETIC_PRIVATE_FILENAME.xlsx","xlsxBase64",Base64.getEncoder().encodeToString(xlsx(marker,score)),"projectId",id,"replacesId",replaces,"reason",reason));}
    private static Map<String,Object> prepare(long id,String marker,String score)throws Exception{return SurveySummaryImportsFormal.prepare(author,upload(id,marker,score,0,""));}
    private static Map<String,Object> confirmBody(long id,Map<String,Object>ticket){return new LinkedHashMap<>(Map.of("project_id",id,"preview_token",ticket.get("preview_token"),"request_id",request(),"acknowledged",true));}
    private static long save(long id,String marker,String score)throws Exception{return n(SurveySummaryImportsFormal.confirm(author,confirmBody(id,prepare(id,marker,score))).get("result_version"));}
    private static Map<String,Object> reviewBody(long id,long imported,String decision,String reason)throws Exception{return new LinkedHashMap<>(Map.of("project_id",id,"import_id",imported,"expected_version",n(SurveySummaryImportsFormal.read(reviewer,id).get("version")),"decision",decision,"reason",reason,"request_id",request()));}
    private static Map<String,Object> approve(long id,long imported)throws Exception{return SurveySummaryImportsFormal.review(reviewer,reviewBody(id,imported,"APPROVE",""));}
    private static List<Map<String,Object>> records(long id)throws Exception{return list(SurveySummaryImportsFormal.read(author,id).get("records"));}
    private static Map<String,Object> snapshot(long id)throws Exception{return SurveySummaryImportsFormal.captureReviewed(reader,id,"001");}
    private static Map<String,Object> counts()throws Exception{Map<String,Object>m=new TreeMap<>();for(String t:TABLES)m.put(t,Db.count(t));return m;}
    private static Map<String,Object> dbSnapshot()throws Exception{Map<String,Object>m=new TreeMap<>();for(String t:TABLES)m.put(t,Db.query("SELECT * FROM "+t));return m;}
    @SuppressWarnings("unchecked")private static void expire(String token)throws Exception{Field f=SurveySummaryImportsFormal.class.getDeclaredField("TICKETS");f.setAccessible(true);Object ticket=((Map<String,?>)f.get(null)).get(token);Field expires=ticket.getClass().getDeclaredField("expires");expires.setAccessible(true);expires.setLong(ticket,System.currentTimeMillis()-1);}

    public static void main(String[]args)throws Exception{
        if(args.length!=1)throw new IllegalArgumentException("Fresh synthetic data directory required");Path path=Path.of(args[0]).toAbsolutePath().normalize();if(!Files.isDirectory(path)||Files.isSymbolicLink(path))throw new IllegalArgumentException("Fresh real directory required");try(var s=Files.list(path)){if(s.findAny().isPresent())throw new IllegalArgumentException("Directory must be empty");}
        try{
            fixture(path);
            run("idempotent init creates six empty tables",()->{for(String t:TABLES)eq(0L,Db.count(t));});
            run("unconfigured formal blocked but draft preview works",()->{long p=project("001");var u=upload(p,"gate","8",0,"");rejects(409,()->SurveySummaryImportsFormal.prepare(author,u));Map<String,Object>legacy=new LinkedHashMap<>(u);legacy.remove("reason");legacy.remove("replacesId");eq("PREVIEW",SurveySummaryImportsIntegration.preview(author,legacy).get("state"));eq("POLICY_NOT_CONFIRMED",snapshot(p).get("reason"));});
            run("unconfirmed policy not persisted",()->{Map<String,Object>before=counts();rejects(409,()->SurveySummaryImportsFormal.configure(publisher,"001",null,policy("UNCONFIRMED",false)));eq(before,counts());});
            run("old admin cannot configure business policy",()->rejects(403,()->SurveySummaryImportsFormal.configure(admin,"001",null,policy("POLICY-ADMIN",true))));
            run("policy reviewer role must exist in M01",()->rejects(409,()->SurveySummaryImportsFormal.configure(publisher,"001",null,new Policy("UNKNOWN-ROLE",true,"TEST",true,Set.of("UNKNOWN")))));
            run("explicit trusted policy publication",()->{SurveySummaryImportsFormal.configure(publisher,"001",null,policy(policyVersion,true));eq(1L,Db.count("m07_policy_heads"));eq(1L,Db.count("m07_policy_revisions"));});
            run("policy CAS and version reuse rejected",()->{rejects(409,()->SurveySummaryImportsFormal.configure(publisher,"001",null,policy("POLICY-NEW",true)));rejects(409,()->SurveySummaryImportsFormal.configure(publisher,"001",policyVersion,policy(policyVersion,true)));});
            run("unauthorized reader cannot prepare",()->{long p=project("001");rejects(403,()->SurveySummaryImportsFormal.prepare(reader,upload(p,"reader","8",0,"")));});
            run("cross organization rejects before base64 decode",()->{long p=project("002");var u=upload(p,"cross","8",0,"");u.put("xlsxBase64","PRIVATE%%%INVALID");rejects(403,()->SurveySummaryImportsFormal.prepare(author,u));});
            run("prepare is aggregate-only and changes no tables",()->{long p=project("001");var before=dbSnapshot();var t=prepare(p,"SYNTHETIC_PRIVATE_IDENTITY","8");eq("READY_TO_CONFIRM",t.get("state"));eq(true,t.get("canConfirm"));eq(true,t.get("policyConfirmed"));eq(before,dbSnapshot());String json=Json.write(t);check(!json.contains("SYNTHETIC_PRIVATE"),"private identity/file name leaked");check(!json.contains("xlsxBase64")&&!json.contains("fileFingerprint"),"raw upload leaked");});
            run("new batch whitespace reason rejects without persisting",()->{long p=project("001");var before=dbSnapshot();rejects(400,()->SurveySummaryImportsFormal.prepare(author,upload(p,"space-reason","8",0,"   ")));eq(before,dbSnapshot());});
            run("server summary cannot be supplied at confirmation",()->{long p=project("001");var b=confirmBody(p,prepare(p,"injected","8"));b.put("summary",Map.of());rejects(400,()->SurveySummaryImportsFormal.confirm(author,b));});
            run("explicit acknowledgement required",()->{long p=project("001");var b=confirmBody(p,prepare(p,"ack","8"));b.put("acknowledged",false);rejects(400,()->SurveySummaryImportsFormal.confirm(author,b));b.put("acknowledged",true);eq("PENDING_REVIEW",SurveySummaryImportsFormal.confirm(author,b).get("state"));});
            run("wrong actor cannot poison valid ticket",()->{long p=project("001");var b=confirmBody(p,prepare(p,"owner","8"));rejects(403,()->SurveySummaryImportsFormal.confirm(wrongRole,b));eq("PENDING_REVIEW",SurveySummaryImportsFormal.confirm(author,b).get("state"));});
            run("wrong target cannot poison valid ticket",()->{long p=project("001"),other=project("001");var b=confirmBody(p,prepare(p,"target","8"));var bad=copy(b);bad.put("project_id",other);rejects(403,()->SurveySummaryImportsFormal.confirm(author,bad));eq("PENDING_REVIEW",SurveySummaryImportsFormal.confirm(author,b).get("state"));});
            run("new login same account cannot use previous session ticket",()->{long p=project("001");var b=confirmBody(p,prepare(p,"session","8"));Auth.Session second=Auth.get(Auth.login("u2",PASS));rejects(403,()->SurveySummaryImportsFormal.confirm(second,b));eq("PENDING_REVIEW",SurveySummaryImportsFormal.confirm(author,b).get("state"));});
            run("expired ticket never confirms",()->{long p=project("001");var b=confirmBody(p,prepare(p,"expiry","8"));expire((String)b.get("preview_token"));rejects(409,()->SurveySummaryImportsFormal.confirm(author,b));rejects(409,()->SurveySummaryImportsFormal.confirm(author,b));});
            run("source change observed then restored cannot revive ticket",()->{long p=project("001");var b=confirmBody(p,prepare(p,"source","8"));sql("UPDATE projects SET title='CHANGED' WHERE id=?",p);try{rejects(409,()->SurveySummaryImportsFormal.confirm(author,b));}finally{sql("UPDATE projects SET title=? WHERE id=?","SYNTHETIC PROJECT "+p,p);}rejects(409,()->SurveySummaryImportsFormal.confirm(author,b));});
            run("confirm receipt idempotent but new request needs new ticket",()->{long p=project("001");var b=confirmBody(p,prepare(p,"replay","8"));var a=SurveySummaryImportsFormal.confirm(author,b);long count=Db.count("m07_result_events");var replay=SurveySummaryImportsFormal.confirm(author,b);eq(true,replay.get("replayed"));eq(a.get("result_version"),replay.get("result_version"));eq(count,Db.count("m07_result_events"));b.put("request_id",request());rejects(409,()->SurveySummaryImportsFormal.confirm(author,b));});
            run("request id different content conflicts without writing",()->{long p=project("001");var first=confirmBody(p,prepare(p,"requestA","8"));SurveySummaryImportsFormal.confirm(author,first);var second=confirmBody(p,prepare(p,"requestB","9"));second.put("request_id",first.get("request_id"));long c=Db.count("m07_result_events");rejects(409,()->SurveySummaryImportsFormal.confirm(author,second));eq(c,Db.count("m07_result_events"));});
            run("pending invisible to M08 and independent approval activates",()->{long p=project("001"),imported=save(p,"approve","8");eq("NO_REVIEWED_RESULT",snapshot(p).get("reason"));var r=reviewBody(p,imported,"APPROVE","");rejects(403,()->SurveySummaryImportsFormal.review(author,r));rejects(403,()->SurveySummaryImportsFormal.review(wrongRole,r));approve(p,imported);eq("APPROVED",records(p).get(0).get("state"));var snap=snapshot(p);eq("AVAILABLE",snap.get("status"));SurveySummaryImportsFormal.validateReviewedSnapshot(snap);eq(imported,n(list(map(snap.get("value")).get("results")).get(0).get("import_id")));});
            run("review requires explicit review permission",()->{long p=project("001"),v=save(p,"readreview","8");rejects(403,()->SurveySummaryImportsFormal.review(reader,reviewBody(p,v,"APPROVE","")));});
            run("reject requires reason and never activates",()->{long p=project("001"),v=save(p,"reject","8");rejects(400,()->SurveySummaryImportsFormal.review(reviewer,reviewBody(p,v,"REJECT","")));SurveySummaryImportsFormal.review(reviewer,reviewBody(p,v,"REJECT","SYNTHETIC REJECTION"));eq("REJECTED",records(p).get(0).get("state"));eq("NO_REVIEWED_RESULT",snapshot(p).get("reason"));eq("DUPLICATE",prepare(p,"reject","8").get("state"));});
            run("review reasons persist separately from revision reasons across reopen",M07FormalTest::reviewReasonProjection);
            run("same file denied in project but allowed in another",()->{long p=project("001"),q=project("001");save(p,"samefile","8");var dup=prepare(p,"samefile","8");eq("DUPLICATE",dup.get("state"));eq(false,dup.get("canConfirm"));eq("READY_TO_CONFIRM",prepare(q,"samefile","8").get("state"));});
            run("same scores different file stays a candidate",()->{long p=project("001");save(p,"person-a","8");var t=prepare(p,"person-b","8");eq(true,t.get("canConfirm"));eq("SAME_SCORES_CANDIDATE",map(t.get("duplicate")).get("status"));});
            run("revision preserves active old value until separately reviewed",()->{long p=project("001"),old=save(p,"old","8");approve(p,old);var t=SurveySummaryImportsFormal.prepare(author,upload(p,"revised","9",old,"SYNTHETIC CORRECTION"));long replacement=n(SurveySummaryImportsFormal.confirm(author,confirmBody(p,t)).get("result_version"));eq(old,n(list(map(snapshot(p).get("value")).get("results")).get(0).get("import_id")));approve(p,replacement);var all=records(p);eq(2,all.size());eq("SUPERSEDED",all.get(0).get("state"));eq("APPROVED",all.get(1).get("state"));eq(replacement,n(list(map(snapshot(p).get("value")).get("results")).get(0).get("import_id")));});
            run("rejected revision leaves approved predecessor active",()->{long p=project("001"),old=save(p,"oldrej","8");approve(p,old);var t=SurveySummaryImportsFormal.prepare(author,upload(p,"newrej","9",old,"CORRECTION"));long v=n(SurveySummaryImportsFormal.confirm(author,confirmBody(p,t)).get("result_version"));SurveySummaryImportsFormal.review(reviewer,reviewBody(p,v,"REJECT","WRONG"));eq(old,n(list(map(snapshot(p).get("value")).get("results")).get(0).get("import_id")));});
            run("revision needs reason and exact latest series tip",()->{long p=project("001"),old=save(p,"targetold","8");rejects(400,()->SurveySummaryImportsFormal.prepare(author,upload(p,"no-reason","9",old,"")));var t=SurveySummaryImportsFormal.prepare(author,upload(p,"tipnew","9",old,"CORRECTION"));SurveySummaryImportsFormal.confirm(author,confirmBody(p,t));rejects(409,()->SurveySummaryImportsFormal.prepare(author,upload(p,"staletip","10",old,"CORRECTION")));});
            run("separate approved batches are not averaged together",()->{long p=project("001"),a=save(p,"batcha","2");approve(p,a);long b=save(p,"batchb","10");approve(p,b);eq(2,list(map(snapshot(p).get("value")).get("results")).size());});
            run("read and M08 capture change no formal table",()->{long p=project("001"),v=save(p,"readonly","8");approve(p,v);var before=dbSnapshot();SurveySummaryImportsFormal.read(author,p);snapshot(p);SurveySummaryImportsFormal.validateReviewedSnapshot(snapshot(p));eq(before,dbSnapshot());});
            run("M08 denies missing read grant and wrong organization",()->{long p=project("001");rejects(403,()->SurveySummaryImportsFormal.captureReviewed(outsider,p,"001"));rejects(403,()->SurveySummaryImportsFormal.captureReviewed(reader,p,"002"));eq(false,SurveySummaryImportsFormal.canReadReviewed(outsider,"001"));});
            run("M08 unavailable after trustworthy source changes",()->{long p=project("001"),v=save(p,"source-new","8");approve(p,v);sql("UPDATE workflow_demands SET version=2 WHERE demand_id=?",p);try{eq("SOURCE_CHANGED_REVIEW_REQUIRED",snapshot(p).get("reason"));}finally{sql("UPDATE workflow_demands SET version=1 WHERE demand_id=?",p);}});
            run("M08 old snapshot remains valid after live policy change",()->{long p=project("001"),v=save(p,"policynew","8");approve(p,v);var old=snapshot(p);String next="POLICY-"+(++identityVersion+100);SurveySummaryImportsFormal.configure(publisher,"001",policyVersion,policy(next,true));policyVersion=next;eq("POLICY_CHANGED_REVIEW_REQUIRED",snapshot(p).get("reason"));SurveySummaryImportsFormal.validateReviewedSnapshot(old);});
            run("new policy same file requires explicit revision and fresh review",M07FormalTest::policyRecalculation);
            run("same account new person and same person new account cannot self review",M07FormalTest::identitySeparation);
            run("review role cannot borrow another role organization grant",M07FormalTest::reviewScope);
            run("observed policy change cannot revive old ticket after restoration",M07FormalTest::policyTicket);
            run("approved snapshot tamper rejected",()->{long p=project("001"),v=save(p,"snap","8");approve(p,v);var bad=copy(snapshot(p));map(bad.get("value")).put("project_id",999);rejects(409,()->SurveySummaryImportsFormal.validateReviewedSnapshot(bad));});
            run("unknown aggregate fields fail validation even with new checksum",()->{long p=project("001"),v=save(p,"shape","8");approve(p,v);var bad=copy(snapshot(p));var result=list(map(bad.get("value")).get("results")).get(0);map(result.get("summary")).put("raw","PRIVATE");Map<String,Object>base=new LinkedHashMap<>(bad);base.remove("source_version");bad.put("source_version",SurveySummaryImportsFormal.hash(base));rejects(409,()->SurveySummaryImportsFormal.validateReviewedSnapshot(bad));});
            run("same ticket concurrent confirmation has one append",M07FormalTest::concurrentConfirm);
            run("two reviewers cannot decide same pending result twice",M07FormalTest::concurrentReview);
            run("failed transactional insert rolls back every ledger table",M07FormalTest::rollback);
            run("corrupt event and missing file claim fail closed",M07FormalTest::corruption);
            run("observed ledger corruption invalidates confirmation ticket",M07FormalTest::corruptionTicket);
            run("receipt cannot point at another valid event",M07FormalTest::receiptCorruption);
            run("file claim policy corruption fails closed",M07FormalTest::claimCorruption);
            run("M08 capture inside transaction is read only",()->{long p=project("001"),v=save(p,"txread","8");approve(p,v);var before=dbSnapshot();Db.transaction(()->{eq("AVAILABLE",snapshot(p).get("status"));check(!Db.get().getAutoCommit(),"capture committed caller transaction");return null;});eq(before,dbSnapshot());});
            run("M08 storage failure is sanitized503 without cause",M07FormalTest::captureFailure);
            run("legacy guard rejects delete and rebind without committing caller transaction",M07FormalTest::legacyGuard);
            run("archived project is readable but cannot write or revive observed ticket",M07FormalTest::archiveGuard);
            run("aggregate persistence contains no individual upload data",()->{String all=Json.write(dbSnapshot());check(!all.contains("SYNTHETIC_PRIVATE_FILENAME")&&!all.contains("SYNTHETIC_PRIVATE_IDENTITY")&&!all.contains("xlsxBase64"),"private upload persisted");});
            run("cold connection reopen preserves validated ledger",()->{long p=project("001"),v=save(p,"reopen","8");approve(p,v);String before=Json.write(SurveySummaryImportsFormal.read(author,p));Db.get().close();eq(before,Json.write(SurveySummaryImportsFormal.read(author,p)));});
            run("isolated HTTP confirm review and private request cache",()->http(false));
            run("HTTP storage failure is sanitized503",()->http(true));
        }finally{try{Db.get().close();}catch(Exception ignored){}}
        System.out.println("M07 FORMAL SCENARIOS passed="+passed+" failed="+failed+" (synthetic isolated handler; no shared installation)");if(failed>0)throw new AssertionError(failed+" scenarios failed");
    }
    private static void concurrentConfirm()throws Exception{long p=project("001");var b=confirmBody(p,prepare(p,"race","8"));ExecutorService pool=Executors.newFixedThreadPool(2);CountDownLatch start=new CountDownLatch(1);try{List<Future<Map<String,Object>>>f=new ArrayList<>();for(int i=0;i<2;i++)f.add(pool.submit(()->{start.await();return SurveySummaryImportsFormal.confirm(author,b);}));start.countDown();int replays=0;for(var job:f)if(Boolean.TRUE.equals(job.get(10,TimeUnit.SECONDS).get("replayed")))replays++;eq(1,replays);eq(1,records(p).size());}finally{start.countDown();pool.shutdownNow();pool.awaitTermination(5,TimeUnit.SECONDS);}}
    private static void concurrentReview()throws Exception{long p=project("001"),v=save(p,"reviewrace","8");var b=reviewBody(p,v,"APPROVE","");var other=copy(b);other.put("request_id",request());ExecutorService pool=Executors.newFixedThreadPool(2);CountDownLatch start=new CountDownLatch(1);try{List<Future<Integer>>f=new ArrayList<>();for(var input:List.of(b,other))f.add(pool.submit(()->{start.await();try{SurveySummaryImportsFormal.review(reviewer,input);return 200;}catch(Api.ApiException e){return e.code;}}));start.countDown();List<Integer>statuses=new ArrayList<>();for(var job:f)statuses.add(job.get(10,TimeUnit.SECONDS));Collections.sort(statuses);eq(List.of(200,409),statuses);eq(2L,n(SurveySummaryImportsFormal.read(author,p).get("version")));}finally{start.countDown();pool.shutdownNow();pool.awaitTermination(5,TimeUnit.SECONDS);}}
    public static final class FailInsert implements Trigger{public void init(Connection c,String schema,String name,String table,boolean before,int type){}public void fire(Connection c,Object[]old,Object[]row)throws SQLException{throw new SQLException("SYNTHETIC_INSERT_FAILURE","45000");}public void close(){}public void remove(){}}
    private static void rollback()throws Exception{long p=project("001");var b=confirmBody(p,prepare(p,"rollback","8"));var before=dbSnapshot();sql("CREATE TRIGGER m07_synthetic_fail BEFORE INSERT ON m07_file_claims FOR EACH ROW CALL 'com.training.M07FormalTest$FailInsert'");try{try{SurveySummaryImportsFormal.confirm(author,b);throw new AssertionError("injected failure required");}catch(SQLException|Api.ApiException expected){}eq(before,dbSnapshot());}finally{sql("DROP TRIGGER m07_synthetic_fail");}eq("PENDING_REVIEW",SurveySummaryImportsFormal.confirm(author,b).get("state"));}
    private static void corruption()throws Exception{long p=project("001");save(p,"corrupt","8");Map<String,Object>event=Db.one("SELECT * FROM m07_result_events WHERE project_id=? AND version=1",p);sql("UPDATE m07_result_events SET event_hash=? WHERE project_id=? AND version=1","f".repeat(64),p);try{rejects(409,()->SurveySummaryImportsFormal.read(author,p));}finally{sql("UPDATE m07_result_events SET event_hash=? WHERE project_id=? AND version=1",event.get("event_hash"),p);}Map<String,Object>claim=Db.one("SELECT * FROM m07_file_claims WHERE project_id=?",p);sql("DELETE FROM m07_file_claims WHERE project_id=?",p);try{rejects(409,()->SurveySummaryImportsFormal.read(author,p));}finally{sql("INSERT INTO m07_file_claims VALUES(?,?,?,?)",p,claim.get("file_hash"),claim.get("policy_hash"),claim.get("import_version"));}}
    private static void corruptionTicket()throws Exception{long p=project("001");save(p,"corruptbase","8");var b=confirmBody(p,prepare(p,"corruptnew","9"));var event=Db.one("SELECT event_hash FROM m07_result_events WHERE project_id=? AND version=1",p);sql("UPDATE m07_result_events SET event_hash=? WHERE project_id=? AND version=1","f".repeat(64),p);try{rejects(409,()->SurveySummaryImportsFormal.confirm(author,b));}finally{sql("UPDATE m07_result_events SET event_hash=? WHERE project_id=? AND version=1",event.get("event_hash"),p);}rejects(409,()->SurveySummaryImportsFormal.confirm(author,b));}
    private static void policyRecalculation()throws Exception{long p=project("001"),old=save(p,"policy-recalc","8");approve(p,old);String next="_RECALC-"+(++identityVersion);SurveySummaryImportsFormal.configure(publisher,"001",policyVersion,new Policy(next,false,"SYNTHETIC-REVISED-RULE",true,Set.of("REVIEWER")));policyVersion=next;eq("DUPLICATE",prepare(p,"policy-recalc","8").get("state"));rejects(400,()->SurveySummaryImportsFormal.prepare(author,upload(p,"policy-recalc","8",old,"")));var t=SurveySummaryImportsFormal.prepare(author,upload(p,"policy-recalc","8",old,"POLICY CHANGE"));eq("EXPLICIT_POLICY_RECALCULATION",map(t.get("duplicate")).get("status"));long revised=n(SurveySummaryImportsFormal.confirm(author,confirmBody(p,t)).get("result_version"));eq("POLICY_CHANGED_REVIEW_REQUIRED",snapshot(p).get("reason"));approve(p,revised);var snap=snapshot(p);eq("AVAILABLE",snap.get("status"));SurveySummaryImportsFormal.validateReviewedSnapshot(snap);eq(revised,n(list(map(snap.get("value")).get("results")).get(0).get("import_id")));eq("DUPLICATE",SurveySummaryImportsFormal.prepare(author,upload(p,"policy-recalc","8",revised,"SAME POLICY RETRY")).get("state"));eq(2L,n(Db.one("SELECT COUNT(*) AS n FROM m07_file_claims WHERE project_id=?",p).get("n")));}
    private static void identitySeparation()throws Exception{long p=project("001"),v=save(p,"identity-split","8");Configuration c=OrganizationAccessStore.configuration();List<AccountBinding>bindings=new ArrayList<>();for(var b:c.accountBindings())bindings.add(new AccountBinding(b.accountId(),b.accountId()==2?"0003":b.accountId()==3?"0002":b.personCode(),b.enabled()));try{publishIdentity(altered(c,c.people(),bindings,c.grants()));var body=reviewBody(p,v,"APPROVE","");rejects(403,()->SurveySummaryImportsFormal.review(author,body));rejects(403,()->SurveySummaryImportsFormal.review(reviewer,body));eq("PENDING_REVIEW",records(p).get(0).get("state"));}finally{publishIdentity(identity());}}
    private static void reviewScope()throws Exception{long p=project("001"),v=save(p,"role-scope","8");Configuration c=OrganizationAccessStore.configuration();List<Person>people=new ArrayList<>();for(var who:c.people())people.add(who.personCode().equals("0003")?new Person("0003","001",Set.of(),null,null,Set.of("AUTHOR","REVIEWER"),true):who);List<Grant>grants=new ArrayList<>();for(var g:c.grants())grants.add(g.ruleId().equals("REVIEW")?new Grant("REVIEW","REVIEWER","survey.review",Action.HANDLE,Effect.ALLOW,Scope.NAMED_ORGS,Set.of("002")):g);try{publishIdentity(altered(c,people,c.accountBindings(),grants));check(OrganizationAccessStore.authorize(reviewer,"survey.review",Action.HANDLE,"001").allowed(),"fixture must match non-policy role");rejects(403,()->SurveySummaryImportsFormal.review(reviewer,reviewBody(p,v,"APPROVE","")));grants=new ArrayList<>(c.grants());grants.add(new Grant("EXPLICIT-DENY","REVIEWER","survey.review",Action.HANDLE,Effect.DENY,Scope.OWN_ORG,Set.of()));publishIdentity(altered(c,c.people(),c.accountBindings(),grants));rejects(403,()->SurveySummaryImportsFormal.review(reviewer,reviewBody(p,v,"APPROVE","")));}finally{publishIdentity(identity());}}
    private static void policyTicket()throws Exception{long p=project("001");var b=confirmBody(p,prepare(p,"policy-ticket","8"));String old=policyVersion,next="POLICY-TICKET-"+(++identityVersion);SurveySummaryImportsFormal.configure(publisher,"001",old,policy(next,true));policyVersion=next;rejects(409,()->SurveySummaryImportsFormal.confirm(author,b));sql("UPDATE m07_policy_heads SET version_code=? WHERE organization_code='001'",old);try{rejects(409,()->SurveySummaryImportsFormal.confirm(author,b));}finally{sql("UPDATE m07_policy_heads SET version_code=? WHERE organization_code='001'",next);}}
    private static void receiptCorruption()throws Exception{long p=project("001");var b=confirmBody(p,prepare(p,"receipt-a","8"));long original=n(SurveySummaryImportsFormal.confirm(author,b).get("result_version"));long other=save(p,"receipt-b","9");sql("UPDATE m07_result_requests SET result_version=? WHERE account_id=2 AND request_id=?",other,b.get("request_id"));try{rejects(409,()->SurveySummaryImportsFormal.confirm(author,b));}finally{sql("UPDATE m07_result_requests SET result_version=? WHERE account_id=2 AND request_id=?",original,b.get("request_id"));}eq(true,SurveySummaryImportsFormal.confirm(author,b).get("replayed"));}
    private static void claimCorruption()throws Exception{long p=project("001");save(p,"claim-policy","8");var claim=Db.one("SELECT * FROM m07_file_claims WHERE project_id=?",p);sql("UPDATE m07_file_claims SET policy_hash=? WHERE project_id=?","f".repeat(64),p);try{rejects(409,()->SurveySummaryImportsFormal.read(author,p));rejects(409,()->snapshot(p));}finally{sql("UPDATE m07_file_claims SET policy_hash=? WHERE project_id=?",claim.get("policy_hash"),p);}}
    private static void captureFailure()throws Exception{long p=project("001");sql("ALTER TABLE m07_policy_heads RENAME TO m07_synthetic_hidden_heads");try{try{snapshot(p);throw new AssertionError("expected storage failure");}catch(Api.ApiException safe){eq(503,safe.code);eq("评分汇总来源暂时无法读取，请稍后重试",safe.getMessage());eq(null,safe.getCause());eq(0,safe.getSuppressed().length);}}finally{sql("ALTER TABLE m07_synthetic_hidden_heads RENAME TO m07_policy_heads");}eq("NO_REVIEWED_RESULT",snapshot(p).get("reason"));}
    private static void legacyGuard()throws Exception{long p=project("001"),other=project("001");save(p,"legacy-guard","8");var before=dbSnapshot();sql("CREATE TABLE m07_synthetic_guard_marker(id BIGINT PRIMARY KEY)");try{try{Db.transaction(()->{Db.exec("INSERT INTO m07_synthetic_guard_marker VALUES(1)");rejects(409,()->SurveySummaryImportsFormal.guardLegacyProjectMutation("delete",p,null));rejects(409,()->SurveySummaryImportsFormal.guardLegacyProjectMutation("update",p,Map.of("demand_id",other)));SurveySummaryImportsFormal.guardLegacyProjectMutation("update",p,Map.of("demand_id",p,"title","SYNTHETIC RETAINED SOURCE"));check(!Db.get().getAutoCommit(),"guard changed transaction ownership");throw new SQLException("SYNTHETIC_CALLER_ROLLBACK","45002");});throw new AssertionError("caller rollback required");}catch(SQLException expected){eq("45002",expected.getSQLState());}eq(0L,Db.count("m07_synthetic_guard_marker"));eq(before,dbSnapshot());}finally{sql("DROP TABLE m07_synthetic_guard_marker");}}
    private static void archiveGuard()throws Exception{long p=project("001"),pending=save(p,"archive-pending","8");var ticket=confirmBody(p,prepare(p,"archive-ticket","9"));var review=reviewBody(p,pending,"APPROVE","");sql("UPDATE projects SET status='已归档' WHERE id=?",p);try{eq(1,records(p).size());rejects(409,()->prepare(p,"archive-new","7"));rejects(409,()->SurveySummaryImportsFormal.confirm(author,ticket));rejects(409,()->SurveySummaryImportsFormal.review(reviewer,review));eq("PENDING_REVIEW",records(p).get(0).get("state"));}finally{sql("UPDATE projects SET status='进行中' WHERE id=?",p);}rejects(409,()->SurveySummaryImportsFormal.confirm(author,ticket));eq(1,records(p).size());approve(p,pending);eq("APPROVED",records(p).get(0).get("state"));}
    private static void reasons(Map<String,Object>record,String importReason,String reviewReason){eq(importReason,record.get("reason"));eq(reviewReason,record.get("review_reason"));}
    private static long reviewReasonFixture()throws Exception{
        long p=project("001"),rejected=save(p,"reason-rejected","8");
        SurveySummaryImportsFormal.review(reviewer,reviewBody(p,rejected,"REJECT","第3题口径不符"));
        // Assert the user-visible failure first, so the old implementation reproduces the missing rejection detail.
        reasons(records(p).get(0),"","第3题口径不符");
        var revision=SurveySummaryImportsFormal.prepare(author,upload(p,"reason-revision","9",rejected,"修正第3题"));
        long revised=n(SurveySummaryImportsFormal.confirm(author,confirmBody(p,revision)).get("result_version"));
        reasons(records(p).get(1),"修正第3题","");
        SurveySummaryImportsFormal.review(reviewer,reviewBody(p,revised,"REJECT","第3题仍需复核"));
        long pending=save(p,"reason-pending","7");
        long approvedEmpty=save(p,"reason-approved-empty","6");approve(p,approvedEmpty);
        long approvedText=save(p,"reason-approved-text","5");SurveySummaryImportsFormal.review(reviewer,reviewBody(p,approvedText,"APPROVE","已核对原始评分"));
        check(pending>revised,"fixture independent pending batch");assertReviewReasons(records(p));return p;
    }
    private static void assertReviewReasons(List<Map<String,Object>>rows){eq(5,rows.size());reasons(rows.get(0),"","第3题口径不符");reasons(rows.get(1),"修正第3题","第3题仍需复核");reasons(rows.get(2),"","");eq("PENDING_REVIEW",rows.get(2).get("state"));reasons(rows.get(3),"","");eq("APPROVED",rows.get(3).get("state"));reasons(rows.get(4),"","已核对原始评分");eq("APPROVED",rows.get(4).get("state"));}
    private static void reviewReasonProjection()throws Exception{
        long p=reviewReasonFixture();var before=dbSnapshot();var frozen=copy(snapshot(p));String source=SurveySummaryImportsFormal.canonical(frozen),frozenJson=Json.write(frozen);Object sourceVersion=frozen.get("source_version");String visible=Json.write(SurveySummaryImportsFormal.read(author,p));
        SurveySummaryImportsFormal.validateReviewedSnapshot(frozen);check(!source.contains("review_reason"),"M08 source schema changed");
        eq(before,dbSnapshot());Db.get().close();assertReviewReasons(records(p));eq(visible,Json.write(SurveySummaryImportsFormal.read(author,p)));
        var live=snapshot(p);eq(source,SurveySummaryImportsFormal.canonical(live));eq(sourceVersion,live.get("source_version"));SurveySummaryImportsFormal.validateReviewedSnapshot(frozen);eq(frozenJson,Json.write(frozen));eq(before,dbSnapshot());
    }

    private static String cell(String ref,String value){return "<c r=\""+ref+"\" t=\"inlineStr\"><is><t>"+value.replace("&","&amp;").replace("<","&lt;")+"</t></is></c>";}
    private static byte[]xlsx(String marker,String score)throws Exception{String ns="http://schemas.openxmlformats.org/spreadsheetml/2006/main",rel="http://schemas.openxmlformats.org/officeDocument/2006/relationships";StringBuilder sheet=new StringBuilder("<worksheet xmlns=\"").append(ns).append("\"><sheetData><row r=\"1\">").append(cell("A1","record"));for(int i=0;i<10;i++)sheet.append(cell((char)('B'+i)+"1",SurveySummaryImportsResponses.QUESTION_LABELS.get(i)));sheet.append("</row><row r=\"2\">").append(cell("A2",marker));for(int i=0;i<10;i++)sheet.append(cell((char)('B'+i)+"2",score));sheet.append("</row></sheetData></worksheet>");Map<String,String>parts=new LinkedHashMap<>();parts.put("[Content_Types].xml","<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"xml\" ContentType=\"application/xml\"/></Types>");parts.put("xl/workbook.xml","<workbook xmlns=\""+ns+"\" xmlns:r=\""+rel+"\"><sheets><sheet name=\""+SurveySummaryImportsResponses.SHEET_NAME+"\" sheetId=\"1\" r:id=\"one\"/></sheets></workbook>");parts.put("xl/_rels/workbook.xml.rels","<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"one\" Type=\""+rel+"/worksheet\" Target=\"worksheets/sheet1.xml\"/></Relationships>");parts.put("xl/worksheets/sheet1.xml",sheet.toString());ByteArrayOutputStream out=new ByteArrayOutputStream();try(ZipOutputStream zip=new ZipOutputStream(out)){for(var p:parts.entrySet()){ZipEntry e=new ZipEntry(p.getKey());e.setTime(0);zip.putNextEntry(e);zip.write(p.getValue().getBytes(StandardCharsets.UTF_8));zip.closeEntry();}}return out.toByteArray();}
    private static Map<String,Object>httpCall(int port,String method,String path,String token,Map<String,Object>body,int status)throws Exception{HttpURLConnection c=(HttpURLConnection)new URL("http://127.0.0.1:"+port+path).openConnection();c.setRequestMethod(method);c.setReadTimeout(10000);c.setConnectTimeout(5000);if(token!=null)c.setRequestProperty("X-Token",token);try{if(body!=null){c.setDoOutput(true);c.setRequestProperty("Content-Type","application/json");byte[]bytes=Json.write(body).getBytes(StandardCharsets.UTF_8);c.setFixedLengthStreamingMode(bytes.length);try(OutputStream o=c.getOutputStream()){o.write(bytes);}}eq(status,c.getResponseCode());InputStream in=status>=400?c.getErrorStream():c.getInputStream();String text=in==null?"":new String(in.readAllBytes(),StandardCharsets.UTF_8);check(!text.contains("SYNTHETIC_PRIVATE"),"HTTP private upload leaked");return text.isEmpty()?Map.of():map(Json.parse(text));}finally{c.disconnect();}}
    private static void http(boolean failureOnly)throws Exception{
        Constructor<?>wrapper=Class.forName("com.training.Api$RequestExchange").getDeclaredConstructor(HttpExchange.class);wrapper.setAccessible(true);Method flush=Api.class.getDeclaredMethod("flushResponse",HttpExchange.class);flush.setAccessible(true);Field bodyName=Api.class.getDeclaredField("BODY_ATTRIBUTE");bodyName.setAccessible(true);String bodyKey=(String)bodyName.get(null);
        HttpServer server=HttpServer.create(new InetSocketAddress("127.0.0.1",0),0);ExecutorService pool=Executors.newFixedThreadPool(4);server.setExecutor(pool);
        server.createContext("/",raw->{HttpExchange ex=raw;try{ex=(HttpExchange)wrapper.newInstance(raw);Auth.Session s;synchronized(Api.MUTATION_LOCK){s=Auth.get(Api.token(ex));}if(SurveySummaryImportsIntegration.matches(ex.getRequestURI().getPath())){SurveySummaryImportsIntegration.handle(ex,s);return;}if(ex.getRequestMethod().equals("POST")){byte[]bytes=ex.getRequestBody().readNBytes(1048577);if(bytes.length>1048576)throw new Api.ApiException(413,"TEST_LIMIT");ex.setAttribute(bodyKey,Json.parse(new String(bytes,StandardCharsets.UTF_8)));}if(!SurveySummaryImportsFormal.handle(ex,s))Api.err(ex,404,"TEST_NOT_FOUND");}catch(Api.ApiException safe){Api.err(ex,safe.code,safe.getMessage());}catch(Exception unexpected){Api.err(ex,500,"TEST_INTERNAL");}finally{try{flush.invoke(null,ex);}catch(Exception ignored){}ex.close();}});server.start();int port=server.getAddress().getPort();
        try{long p=project("001");if(failureOnly){sql("ALTER TABLE m07_policy_heads RENAME TO m07_synthetic_hidden_heads");try{var error=httpCall(port,"GET","/api/survey-results?project_id="+p,readerToken,null,503);eq("评分汇总服务暂时不可用，请稍后重试",error.get("msg"));String encoded=Json.write(error);check(!encoded.contains("SELECT")&&!encoded.contains("m07_")&&!encoded.contains("Jdbc")&&!encoded.contains("Exception"),"storage detail leaked");}finally{sql("ALTER TABLE m07_synthetic_hidden_heads RENAME TO m07_policy_heads");}httpCall(port,"GET","/api/survey-results?project_id="+p,readerToken,null,200);return;}var prepared=map(httpCall(port,"POST","/api/survey-response-imports/prepare",authorToken,upload(p,"http","8",0,""),200).get("data"));eq("READY_TO_CONFIRM",prepared.get("state"));var b=confirmBody(p,prepared);var receipt=map(httpCall(port,"POST","/api/survey-results/confirm",authorToken,b,200).get("data"));long imported=n(receipt.get("result_version"));httpCall(port,"GET","/api/survey-results?project_id="+p,readerToken,null,200);httpCall(port,"POST","/api/survey-results/review",authorToken,reviewBody(p,imported,"APPROVE",""),403);httpCall(port,"POST","/api/survey-results/review",reviewerToken,reviewBody(p,imported,"APPROVE",""),200);httpCall(port,"GET","/api/survey-results?project_id="+p,null,null,401);httpCall(port,"GET","/api/survey-results?project_id="+p+"&project_id="+p,authorToken,null,400);httpCall(port,"POST","/api/survey-results/confirm?x=1",authorToken,b,400);httpCall(port,"GET","/api/survey-results/confirm",authorToken,null,405);httpCall(port,"POST","/api/survey-results/configure",authorToken,Map.of(),404);
            httpCall(port,"POST","/api/survey-response-imports/prepare",readerToken,upload(p,"forbidden","8",0,""),403);var nested=upload(p,"nested","8",0,"");nested.put("reason",Map.of("private","SYNTHETIC_PRIVATE"));httpCall(port,"POST","/api/survey-response-imports/prepare",authorToken,nested,400);var large=upload(p,"large","8",0,"");large.put("xlsxBase64",Base64.getEncoder().encodeToString(new byte[5*1024*1024+1]));httpCall(port,"POST","/api/survey-response-imports/prepare",authorToken,large,413);large.put("xlsxBase64","A".repeat(7*1024*1024));httpCall(port,"POST","/api/survey-response-imports/prepare",authorToken,large,413);
            long reasonsProject=reviewReasonFixture();var frozen=copy(snapshot(reasonsProject));String source=SurveySummaryImportsFormal.canonical(frozen),frozenJson=Json.write(frozen);Object sourceVersion=frozen.get("source_version");var reasonView=map(httpCall(port,"GET","/api/survey-results?project_id="+reasonsProject,readerToken,null,200).get("data"));assertReviewReasons(list(reasonView.get("records")));Db.get().close();var reopened=map(httpCall(port,"GET","/api/survey-results?project_id="+reasonsProject,readerToken,null,200).get("data"));assertReviewReasons(list(reopened.get("records")));eq(Json.write(reasonView),Json.write(reopened));var live=snapshot(reasonsProject);eq(source,SurveySummaryImportsFormal.canonical(live));eq(sourceVersion,live.get("source_version"));SurveySummaryImportsFormal.validateReviewedSnapshot(frozen);eq(frozenJson,Json.write(frozen));
            ExecutorService requests=Executors.newFixedThreadPool(2);try{long q=project("001");List<Future<Map<String,Object>>>jobs=List.of(requests.submit(()->httpCall(port,"GET","/api/survey-results?project_id="+p,authorToken,null,200)),requests.submit(()->httpCall(port,"GET","/api/survey-results?project_id="+q,authorToken,null,200)));eq(p,n(map(jobs.get(0).get().get("data")).get("project_id")));eq(q,n(map(jobs.get(1).get().get("data")).get("project_id")));}finally{requests.shutdownNow();requests.awaitTermination(5,TimeUnit.SECONDS);}
        }finally{server.stop(0);pool.shutdownNow();pool.awaitTermination(5,TimeUnit.SECONDS);}
    }
}
