package com.training;
import java.util.*;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.util.zip.*;
import java.io.*;
import static com.training.OrganizationAccess.*;

/** Joint test using the actual M07 formal candidate, not a provider double. Synthetic data only. */
public final class M08ReviewedSurveyTest {
    static int checks;static long serial;
    static void check(boolean ok,String message){checks++;if(!ok)throw new AssertionError(message);}
    static void eq(Object a,Object b){check(Objects.equals(a,b),"expected "+a+", got "+b);}
    @SuppressWarnings("unchecked") static Map<String,Object> m(Object o){return(Map<String,Object>)o;}
    static Auth.Session s(int id){return M08FormalTest.s(id);}
    static long n(Object o){return new java.math.BigDecimal(o.toString()).longValueExact();}
    static Map<String,Object> source()throws Exception{return m(m(M08FormalTest.read(101).get("sources")).get("feedback"));}
    static long importSurvey(String label,String score,long replaces)throws Exception{
        var preview=SurveySummaryImportsFormal.prepare(s(2),Map.of("fileName","synthetic.xlsx","xlsxBase64",Base64.getEncoder().encodeToString(xlsx(label,score)),"projectId",101,"replacesId",replaces,"reason",replaces==0?"":"合成更正"));eq("READY_TO_CONFIRM",preview.get("state"));var result=SurveySummaryImportsFormal.confirm(s(2),Map.of("project_id",101,"preview_token",preview.get("preview_token"),"request_id","joint-import-"+(++serial),"acknowledged",true));eq("PENDING_REVIEW",result.get("state"));return n(result.get("result_version"));
    }
    static void approve(long id)throws Exception{SurveySummaryImportsFormal.review(s(6),Map.of("project_id",101,"import_id",id,"expected_version",n(SurveySummaryImportsFormal.read(s(6),101).get("version")),"decision","APPROVE","reason","","request_id","joint-review-"+(++serial)));}
    static void approveSummary()throws Exception{TrainingSummariesWorkflow.mutate("submit",s(2),M08FormalTest.body(101));M08FormalTest.review(5,101,"BRANCH","APPROVE");eq("APPROVED",M08FormalTest.review(6,101,"BP","APPROVE").get("status"));}
    static String exportXml()throws Exception{var download=TrainingSummariesWorkflow.export(s(7),M08FormalTest.body(101));try(ZipInputStream zip=new ZipInputStream(new ByteArrayInputStream(download.bytes()))){for(ZipEntry e;(e=zip.getNextEntry())!=null;)if(e.getName().equals("word/document.xml"))return new String(zip.readAllBytes(),StandardCharsets.UTF_8);}throw new AssertionError();}
    public static void main(String[] args)throws Exception{
        Path dir=Path.of(args[0]).toAbsolutePath().normalize();if(!Files.isDirectory(dir)||Files.isSymbolicLink(dir))throw new IllegalArgumentException();try(var files=Files.list(dir)){if(files.findAny().isPresent())throw new IllegalArgumentException();}
        try{M08FormalTest.fixture(dir);Configuration old=OrganizationAccessStore.configuration();List<Grant> grants=new ArrayList<>(old.grants());for(String resource:List.of("survey.preview","survey.import"))grants.add(new Grant("JOINT"+resource,"FULL",resource,Action.HANDLE,Effect.ALLOW,Scope.OWN_ORG,Set.of()));grants.add(new Grant("JOINTREVIEW","BP","survey.review",Action.HANDLE,Effect.ALLOW,Scope.OWN_ORG,Set.of()));grants.add(new Grant("JOINTPOLICY","ADMIN","survey.policy",Action.HANDLE,Effect.ALLOW,Scope.OWN_ORG,Set.of()));OrganizationAccessStore.publish(s(1),old.version(),new Configuration("JOINT-M01",old.codeRules(),old.roleCodes(),old.organizations(),old.people(),old.relations(),old.accountBindings(),grants,old.combinedApprovals()));M08FormalTest.login();SurveySummaryImportsFormal.init();
            TrainingSummariesFeedbackSource.connect(new TrainingSummariesFeedbackSource.ReviewedProvider(){public Map<String,Object>capture(Auth.Session s,long p,String o)throws Exception{return SurveySummaryImportsFormal.captureReviewed(s,p,o);}public void validate(Object snapshot)throws Exception{SurveySummaryImportsFormal.validateReviewedSnapshot(snapshot);}});
            System.setProperty("training.summary.review.order","BRANCH_THEN_BP");System.setProperty("training.summary.review.policyVersion","JOINT-SYNTHETIC-REVIEW");
            M08FormalTest.save(2,101,"联合来源验收总结");eq("POLICY_NOT_CONFIRMED",source().get("reason"));
            SurveySummaryImportsFormal.configure(s(7),"001",null,new SurveySummaryImportsPolicy.Policy("JOINT-1",true,"SYNTHETIC-EVIDENCE",true,Set.of("BP")));eq(true,M08FormalTest.read(101).get("source_changed"));M08FormalTest.refresh(2,101);eq("NO_REVIEWED_RESULT",source().get("reason"));
            long first=importSurvey("SYNTHETIC_PRIVATE_FIRST","8",0);eq(false,M08FormalTest.read(101).get("source_changed"));eq("NO_REVIEWED_RESULT",source().get("reason"));approve(first);eq(true,M08FormalTest.read(101).get("source_changed"));M08FormalTest.refresh(2,101);eq("AVAILABLE",source().get("status"));SurveySummaryImportsFormal.validateReviewedSnapshot(source());
            long frozenVersion=n(M08FormalTest.read(101).get("version"));String frozen=Db.one("SELECT sources_json FROM m08_summary_revisions WHERE project_id=101 AND revision=?",frozenVersion).get("sources_json").toString();approveSummary();String firstWord=exportXml();check(firstWord.contains("8.00"),"Word uses actual M07 exact mean");check(!firstWord.contains("SYNTHETIC_PRIVATE"),"Word excludes raw answer marker");
            long replacement=importSurvey("SYNTHETIC_PRIVATE_REPLACEMENT","9",first);eq(false,M08FormalTest.read(101).get("source_changed"));check(exportXml().contains("8.00"),"pending replacement keeps approved source");approve(replacement);eq(true,M08FormalTest.read(101).get("source_changed"));M08FormalTest.rejects(409,()->exportXml());
            M08FormalTest.save(2,101,"根据已复核问卷修订");M08FormalTest.refresh(2,101);approveSummary();check(exportXml().contains("9.00"),"new approved M08 reflects separately approved replacement");eq(frozen,Db.one("SELECT sources_json FROM m08_summary_revisions WHERE project_id=101 AND revision=?",frozenVersion).get("sources_json"));
            var hidden=TrainingSummariesIntegration.read(s(3),101);eq(null,m(hidden.get("sources")).get("source_version"));eq("SURVEY_READ_REQUIRED",m(m(hidden.get("sources")).get("feedback")).get("reason"));check(!Json.write(hidden).contains("JOINT-1"),"no hidden policy fingerprint");
            var current=Db.one("SELECT event_json FROM m07_result_events WHERE project_id=101 AND version=1");String original=current.get("event_json").toString();Db.exec("UPDATE m07_result_events SET event_json='{}' WHERE project_id=101 AND version=1");try{M08FormalTest.rejects(409,()->M08FormalTest.read(101));TrainingSummariesIntegration.read(s(3),101);checks++;}finally{Db.exec("UPDATE m07_result_events SET event_json=? WHERE project_id=101 AND version=1",original);}
            SurveySummaryImportsFormal.configure(s(7),"001","JOINT-1",new SurveySummaryImportsPolicy.Policy("JOINT-2",false,"SYNTHETIC-CHANGED-EVIDENCE",true,Set.of("BP")));eq(true,M08FormalTest.read(101).get("source_changed"));M08FormalTest.rejects(409,()->exportXml());eq(false,TrainingSummariesIntegration.read(s(3),101).get("source_changed"));
            var snapshot=M08FormalTest.tables();TrainingSummariesWorkflow.read(s(2),101);TrainingSummariesIntegration.comparison(s(3),101,1,frozenVersion);eq(snapshot,M08FormalTest.tables());
            Auth.Session oldSession=s(2);Configuration prior=OrganizationAccessStore.configuration();List<Grant> kept=prior.grants().stream().filter(g->!(g.roleCode().equals("FULL")&&g.resource().equals("survey.read"))).toList();
            OrganizationAccessStore.publish(s(1),prior.version(),new Configuration("JOINT-M01-REVOKED",prior.codeRules(),prior.roleCodes(),prior.organizations(),prior.people(),prior.relations(),prior.accountBindings(),kept,prior.combinedApprovals()));M08FormalTest.login();
            M08FormalTest.rejects(401,()->TrainingSummariesIntegration.read(oldSession,101));var afterRevoke=M08FormalTest.read(101);eq("SURVEY_READ_REQUIRED",m(m(afterRevoke.get("sources")).get("feedback")).get("reason"));eq(null,m(afterRevoke.get("sources")).get("source_version"));eq(false,afterRevoke.get("source_changed"));eq(frozen,Db.one("SELECT sources_json FROM m08_summary_revisions WHERE project_id=101 AND revision=?",frozenVersion).get("sources_json"));
            System.out.println("M08ReviewedSurvey: "+checks+" joint checks passed using actual M07 candidate + real Auth/M01/M05/M08; synthetic H2 and XLSX only.");
        }finally{System.clearProperty("training.summary.review.order");System.clearProperty("training.summary.review.policyVersion");Db.get().close();}
    }
    private static String cell(String ref,String value){return "<c r=\""+ref+"\" t=\"inlineStr\"><is><t>"+value.replace("&","&amp;").replace("<","&lt;")+"</t></is></c>";}
    private static byte[]xlsx(String marker,String score)throws Exception{String ns="http://schemas.openxmlformats.org/spreadsheetml/2006/main",rel="http://schemas.openxmlformats.org/officeDocument/2006/relationships";StringBuilder sheet=new StringBuilder("<worksheet xmlns=\"").append(ns).append("\"><sheetData><row r=\"1\">").append(cell("A1","record"));for(int i=0;i<10;i++)sheet.append(cell((char)('B'+i)+"1",SurveySummaryImportsResponses.QUESTION_LABELS.get(i)));sheet.append("</row><row r=\"2\">").append(cell("A2",marker));for(int i=0;i<10;i++)sheet.append(cell((char)('B'+i)+"2",score));sheet.append("</row></sheetData></worksheet>");Map<String,String>parts=new LinkedHashMap<>();parts.put("[Content_Types].xml","<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\"><Default Extension=\"xml\" ContentType=\"application/xml\"/></Types>");parts.put("xl/workbook.xml","<workbook xmlns=\""+ns+"\" xmlns:r=\""+rel+"\"><sheets><sheet name=\""+SurveySummaryImportsResponses.SHEET_NAME+"\" sheetId=\"1\" r:id=\"one\"/></sheets></workbook>");parts.put("xl/_rels/workbook.xml.rels","<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"><Relationship Id=\"one\" Type=\""+rel+"/worksheet\" Target=\"worksheets/sheet1.xml\"/></Relationships>");parts.put("xl/worksheets/sheet1.xml",sheet.toString());ByteArrayOutputStream out=new ByteArrayOutputStream();try(ZipOutputStream zip=new ZipOutputStream(out)){for(var p:parts.entrySet()){ZipEntry e=new ZipEntry(p.getKey());e.setTime(0);zip.putNextEntry(e);zip.write(p.getValue().getBytes(StandardCharsets.UTF_8));zip.closeEntry();}}return out.toByteArray();}
}
