'use strict';
// Actual Main/Auth HTTP, independent H2 and private synthetic memory sender; no real mail configuration.
const fs=require('node:fs'),path=require('node:path'),net=require('node:net'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const {spawn,execFile}=require('node:child_process'),run=require('node:util').promisify(execFile),args={};
for(let i=2;i<process.argv.length;i+=2){assert.ok(['--java','--classes','--overlay','--app'].includes(process.argv[i])&&process.argv[i+1],'Use --java PATH --classes PRODUCT_OUT --overlay FIXTURE_OUT --app APP');args[process.argv[i]]=process.argv[i+1];}
const java=args['--java']||'java',app=fs.realpathSync(args['--app']||path.resolve(__dirname, '..'));
const classes=fs.realpathSync(args['--classes']||process.env.CLASSES_DIR||''),overlay=fs.realpathSync(args['--overlay']||classes);
for(const dir of [classes,overlay])assert.ok(dir!==app&&!dir.startsWith(app+path.sep),'Use independently compiled temporary classes');
assert.ok(fs.existsSync(path.join(overlay,'com/training/S01AccountEmailMaintenanceHttpFixture.class')),'Compile the scripts-only fixture into an independent overlay first');
const own=fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'yanxu-account-email-maintenance-http-')),data=path.join(own,'data');fs.mkdirSync(data,{mode:0o700});
const password=crypto.randomBytes(24).toString('hex'),failures=[],pids=[],readEvidence=[],tokens={},sockets=new Set();
const env={...process.env};for(const key of Object.keys(env))if(/^YANXU_LOGIN_(SMTP_|MAIL_)/.test(key))delete env[key];
Object.assign(env,{YANXU_LOGIN_MAIL_TRANSPORT:'disabled',JAVA_TOOL_OPTIONS:'',JDK_JAVA_OPTIONS:'',_JAVA_OPTIONS:'',YANXU_SEMANTIC_PORT:'',YANXU_SEMANTIC_TOKEN:'',YANXU_CITY_PLANNING_COLLECTION_FILE:''});
let child,port,ids,checks=0,phase='setup',fatal=null,launchMode='legacy';
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms)),uuid=()=>crypto.randomUUID(),base='/account-email-maintenance';
function check(ok,label){checks++;if(!ok)failures.push(phase+': '+label);}
function same(a,b,label){let ok=true;try{assert.deepEqual(a,b);}catch{ok=false;}check(ok,label);}
function options(resume=false){return ['-Dbind.address=127.0.0.1','-Dbootstrap.demo=false','-Dbootstrap.admin.password='+password,'-Dintegration.account.email.maintenance.root='+own,'-Dintegration.account.email.maintenance.resume='+resume,'-Ddata.dir='+data,'-Dlogin.email.mode='+launchMode,'-Dsemantic.port=','-Dsemantic.token=','-Daccount.import.manifest=','-Daccount.import.manifest.sha256=','-cp',overlay+path.delimiter+classes+path.delimiter+path.join(app,'lib','*')];}
async function request(route,body,actor='admin',opt={}){
 const auth=opt.cookie?{Cookie:opt.cookie}:tokens[actor]?{'X-Token':tokens[actor]}:{};
 const headers={...auth};if(body!==undefined&&opt.contentType!==null)headers['Content-Type']=opt.contentType||'application/json';
 const response=await fetch(`http://127.0.0.1:${port}/api${route}`,{method:opt.method||(body===undefined?'GET':'POST'),headers,body:body===undefined?undefined:opt.raw?body:JSON.stringify(body),signal:AbortSignal.timeout(25000)});
 const text=await response.text();let envelope=null;if(text){try{envelope=JSON.parse(text);}catch{throw new Error('Non-JSON response '+route+' HTTP '+response.status);}}
 check(!text.includes(password)&&!text.includes('pbkdf2$')&&!text.includes(own),'Response exposes no password, hash or private path');
 if(route.startsWith(base)||route.startsWith('/login'))check(response.headers.get('cache-control')==='no-store','Sensitive response is not cached');
 if(route.startsWith('/login'))check(!text.includes('@example.invalid'),'Login does not expose candidate email');
 return {status:response.status,envelope,text,headers:response.headers};
}
async function api(route,body,actor='admin',opt={}){const r=await request(route,body,actor,opt);assert.equal(r.status,200,phase+': '+route+' HTTP '+r.status+': '+r.envelope?.msg);assert.equal(r.envelope?.code,0,route);return r.envelope.data;}
function cookie(r){const value=r.headers.get('set-cookie')||'';return /^yx_session=[^;]+/.test(value)&&!/Max-Age=0(?:;|$)/i.test(value)?value.split(';')[0]:null;}
async function denied(route,body,actor,status,label,opt={}){const r=await request(route,body,actor,opt);check(r.status===status&&(opt.method==='HEAD'?r.text==='':r.envelope?.code===status),label+' (HTTP '+r.status+')');check(!r.envelope?.data&&!cookie(r),label+' yields no data or usable session cookie');return r;}
async function boot(resume=false){
 for(const key of Object.keys(tokens))delete tokens[key];const probe=net.createServer();await new Promise((resolve,reject)=>{probe.once('error',reject);probe.listen(0,'127.0.0.1',resolve);});port=probe.address().port;await new Promise(resolve=>probe.close(resolve));
 const log=fs.openSync(path.join(own,'fixture.log'),'a',0o600);child=spawn(java,[...options(resume),'com.training.S01AccountEmailMaintenanceHttpFixture',String(port)],{cwd:app,env,stdio:['ignore',log,log]});fs.closeSync(log);if(child.pid)pids.push(child.pid);
 let startupError;child.once('error',error=>{startupError=error;});
 for(let i=0;i<180;i++){if(startupError)throw startupError;assert.equal(child.exitCode,null,'Synthetic Main exited; inspect private fixture.log');try{const response=await fetch(`http://127.0.0.1:${port}/api/me`,{signal:AbortSignal.timeout(1000)});await response.text();if(response.status===401){ids=JSON.parse(fs.readFileSync(path.join(own,'fixture.json'),'utf8'));return;}}catch{}await pause(100);}throw new Error('Synthetic Main startup timeout');
}
async function stop(){for(const socket of sockets)socket.destroy();sockets.clear();const current=child;child=null;if(!current||current.exitCode!==null||current.signalCode!==null)return;await new Promise(resolve=>{const timer=setTimeout(()=>{if(current.exitCode===null&&current.signalCode===null)current.kill('SIGKILL');},2000);current.once('exit',()=>{clearTimeout(timer);resolve();});current.kill('SIGTERM');});}
async function control(operation,extra={}){const nonce=uuid(),temporary=path.join(own,'control-request.next');fs.writeFileSync(temporary,JSON.stringify({nonce,operation,...extra}),{mode:0o600});fs.renameSync(temporary,path.join(own,'control-request.json'));for(let i=0;i<250;i++){let ack;try{ack=JSON.parse(fs.readFileSync(path.join(own,'control-result.json'),'utf8'));}catch{}if(ack?.nonce===nonce){assert.equal(ack.ok,true,'Synthetic control '+operation+' failed');return ack.data;}await pause(20);}throw new Error('Synthetic control timeout: '+operation);}
const stats=()=>control('stats'),freshWindow=()=>control('advance',{millis:3600001}),read=(name,actor='admin')=>api(base+'?user_id='+ids.accounts[name],undefined,actor);
const command=(name,revision,email,request_id=uuid())=>({user_id:ids.accounts[name],expected_revision:revision,request_id,email,confirmed_username:ids.usernames[name],purpose:'LOGIN_VERIFICATION'});
const mailbox=()=>JSON.parse(fs.readFileSync(path.join(own,'mailbox.json'),'utf8'));
function latest(email){const mail=mailbox().filter(row=>row.email===email).at(-1);assert.ok(mail,'Missing synthetic in-memory delivery');assert.match(mail.code,/^[0-9]{6}$/);return mail;}
async function login(name){const r=await request('/login',{username:ids.usernames[name],password},'anonymous');assert.equal(r.status,200,'Legacy login failed');check(typeof r.envelope?.data?.token==='string'&&Boolean(cookie(r)),'Legacy login returns actual Auth token and cookie');tokens[name]=r.envelope.data.token;return {token:tokens[name],cookie:cookie(r),user:r.envelope.data.user};}
async function begin(name){const before=await stats(),r=await request('/login',{username:ids.usernames[name],password},'anonymous');assert.equal(r.status,200,'Required first factor HTTP '+r.status+': '+r.envelope?.msg);const challenge=r.envelope.data;same(Object.keys(challenge).sort(),['challenge_id','expires_at','masked_email','resend_after','status'],'Password response is challenge-only DTO');check(challenge.status==='EMAIL_REQUIRED'&&/^[a-f0-9]{64}$/.test(challenge.challenge_id)&&challenge.masked_email==='***@***','Required challenge is opaque and fully masked');check(!challenge.token&&!cookie(r),'Password alone issues no token or session cookie');same((await stats()).sessions,before.sessions,'Password alone adds no Auth session');return challenge;}
async function complete(name,challenge,email){const before=await stats(),mail=latest(email),r=await request('/login/email/verify',{challenge_id:challenge.challenge_id,code:mail.code},'anonymous');assert.equal(r.status,200,'Required verification failed: '+r.envelope?.msg);check(Boolean(cookie(r))&&typeof r.envelope?.data?.token==='string','Only actual code verification creates token and cookie');check(!mail.held_lock,'Synthetic sender executes outside business lock');same((await stats()).sessions,before.sessions+1,'Verification adds exactly one Auth session');tokens[name]=r.envelope.data.token;const session={token:tokens[name],cookie:cookie(r),user:r.envelope.data.user};same((await api('/me',undefined,'anonymous',{cookie:session.cookie})).uid,ids.accounts[name],'Verified cookie represents password-proven target');return session;}
async function verified(name,email){await freshWindow();return complete(name,await begin(name),email);}
async function readOnly(label,fn){phase=label;const before=await control('snapshot');await fn();const after=await control('snapshot');same(after,before,'Rejected/read-only operation leaves every PUBLIC table unchanged');await expectDevices(label);readEvidence.push({phase:label,tables:Object.keys(before).length,unchanged:JSON.stringify(before)===JSON.stringify(after)});}
function structure(value,name,revision,email,history,reauth=false){
 same(Object.keys(value).sort(),['account_kind','can_save','duplicate_email','email','history','name','reauthentication_required','revision','status','user_id','username'],'Maintenance DTO has exactly documented fields');
 check(value.user_id===ids.accounts[name]&&value.username===ids.usernames[name]&&value.name!==undefined,'Current server identity appears in DTO');
 check(value.account_kind===(['imported','pending','imported_empty'].includes(name)?'IMPORTED':'EXISTING'),'Source comes from real import relation');
 check(value.revision===revision&&value.email===email&&value.status===(email===null?'MISSING':'PENDING_VERIFICATION'),'Version/email/candidate-only status match');
 check(value.can_save===true&&typeof value.duplicate_email==='boolean'&&value.reauthentication_required===reauth,'Save capability, duplicate and self-change flags are typed');
 check(value.history.length===history,'History records only actual revisions');
 for(const row of value.history)check(Number.isInteger(row.revision)&&row.revision>0&&[1,2].includes(row.actor_user_id)&&Number.isFinite(Date.parse(row.recorded_at))&&row.status===(row.email===null?'MISSING':'PENDING_VERIFICATION'),'Historical actor, time and candidate-only status are server data');
}
// R26 contract extension: setup explicitly maintains users 2, 5, 1 once each.
// Expectations advance only at the successful change steps below, never from observed epochs.
const expectedDeviceEpochs=new Map([[1,1],[2,1],[5,1]]),deviceEvidence=[];
async function expectDevices(label){
 const expected={epochs:[...expectedDeviceEpochs].sort((a,b)=>a[0]-b[0]).map(([user_id,epoch])=>({user_id,epoch})),devices:0};
 const actual=await control('device-projection');
 same(actual,expected,'Exact device epoch vector and zero registered devices: '+label);
 deviceEvidence.push({phase:label,expected,actual});
}
async function changedEmail(name,label){
 const uid=ids.accounts[name];expectedDeviceEpochs.set(uid,(expectedDeviceEpochs.get(uid)||0)+1);
 await expectDevices(label);
}
async function slowRequest(body,actor='admin',route=base){
 const bytes=Buffer.from(body),socket=net.createConnection({host:'127.0.0.1',port});sockets.add(socket);await new Promise((resolve,reject)=>{socket.once('connect',resolve);socket.once('error',reject);});
 let received='',finish;const response=new Promise(resolve=>{finish=resolve;}),timer=setTimeout(()=>{finish({status:0,timeout:true});socket.destroy();},2500);
 socket.on('data',chunk=>{received+=chunk.toString('utf8');if(received.includes('\r\n\r\n')){clearTimeout(timer);finish({status:Number(/^HTTP\/1\.[01] (\d{3})/.exec(received)?.[1])});socket.destroy();}});
 socket.on('error',()=>{clearTimeout(timer);finish({status:0,error:true});});socket.on('close',()=>sockets.delete(socket));
 socket.write('POST /api'+route+' HTTP/1.1\r\nHost: 127.0.0.1:'+port+'\r\nConnection: close\r\nContent-Type: application/json\r\nContent-Length: '+bytes.length+'\r\n'+(tokens[actor]?'X-Token: '+tokens[actor]+'\r\n':'')+'\r\n');socket.write(bytes.subarray(0,bytes.length-1));
 return {response,finish:()=>{if(!socket.destroyed)socket.write(bytes.subarray(bytes.length-1));}};
}
async function runChecks(){
 await boot();for(const name of ['admin','admin2','manager','viewer','native','imported'])await login(name);
 const baseline=await control('snapshot');await expectDevices('bootstrap has exactly three actual maintenance changes');check((await stats()).mail_count===0,'Legacy setup and password login perform no delivery');
 await readOnly('initial sources and query-only read',async()=>{structure(await read('native'),'native',1,'native@example.invalid',1);structure(await read('imported'),'imported',1,'imported@example.invalid',1);structure(await read('admin'),'admin',1,'admin@example.invalid',1);structure(await read('native_empty'),'native_empty',0,null,0);structure(await read('imported_empty'),'imported_empty',0,null,0);});
 await readOnly('authorization happens before body and query parsing',async()=>{
  for(const actor of ['anonymous','manager','viewer']){const status=actor==='anonymous'?401:403;await denied(base+'?unexpected=1',undefined,actor,status,'Actor cannot read candidate data');await denied(base+'?unexpected=1','{',actor,status,'Actor rejected before malformed body',{raw:true});await denied(base,'not-json',actor,status,'Actor rejected before media parsing',{raw:true,contentType:'text/plain'});const slow=await slowRequest('{"unfinished":"a"}',actor,base+'?unexpected=1');const result=await slow.response;check(result.status===status&&!result.timeout,'Unauthorized request never waits for incomplete body');}
 });
 await readOnly('strict six-field HTTP protocol',async()=>{
  for(const suffix of ['', '?user_id=0','?user_id=-1','?user_id=1.5','?user_id=9007199254740992','?user_id=5&user_id=5','?user_id=5&%75ser_id=5','?user_id=5&other=1'])await denied(base+suffix,undefined,'admin',400,'GET rejects malformed or duplicate query');
  for(const suffix of ['?','?user_id=5','?extra=1'])await denied(base+suffix,command('native',1,'strict@example.invalid'),'admin',400,'POST accepts no query');
  await denied(base+'/unknown',undefined,'admin',404,'Unknown maintenance action has no fallback');await denied(base+'?user_id=9999999',undefined,'admin',404,'Nonexistent target is unavailable');
  for(const method of ['PUT','DELETE','HEAD'])await denied(base+'?user_id=5',undefined,'admin',405,'Only GET and POST supported',{method});
  const body=command('native',1,'strict@example.invalid');
  for(const key of Object.keys(body)){const missing={...body};delete missing[key];await denied(base,missing,'admin',400,'All six fields are required: '+key);}
  for(const key of ['actor_user_id','verified','role','password','status','account_kind','history'])await denied(base,{...body,[key]:true},'admin',400,'Client cannot supply '+key);
  for(const invalid of [null,true,-1,1.5,9007199254740992,{},[]])await denied(base,{...body,expected_revision:invalid},'admin',400,'Revision accepts only exact safe nonnegative integer');
  for(const invalid of [null,true,0,-1,1.5,9007199254740992,{},[]])await denied(base,{...body,user_id:invalid},'admin',400,'User id accepts only exact safe positive integer');
  for(const invalid of ['',null,123,'not-uuid',uuid()+'0'])await denied(base,{...body,request_id:invalid},'admin',400,'Request id accepts UUID shape only');
  for(const invalid of [null,true,'','ACCOUNT_ACTIVATION'])await denied(base,{...body,purpose:invalid},'admin',400,'Purpose fixed to login verification');
  for(const invalid of [null,[],true,''])await denied(base,{...body,confirmed_username:invalid},'admin',400,'Explicit username text required');
  await denied(base,{...body,confirmed_username:'wrong-synthetic-name'},'admin',409,'Confirmation must match current exact username');
  for(const invalid of [true,[],{},'line\r\nbreak@example.invalid','two@@example.invalid','中文@example.invalid'])await denied(base,{...body,email:invalid},'admin',400,'Email rejects non-ASCII and header injection');
  const raw=JSON.stringify(body);
  for(const bad of [raw.replace('"user_id":5','"user_id":5,"user_id":5'),raw.replace('"email":','"em\\u0061il":"duplicate@example.invalid","email":'),raw.replace('"expected_revision":1','"expected_revision":1.0000000000000000001'),raw.replace('"user_id":5','"user_id":5.0000000000000000001'),'\u000b'+raw])await denied(base,bad,'admin',400,'Raw parser rejects decoded duplicates, fractional precision and illegal whitespace',{raw:true});
  await denied(base,raw,'admin',415,'Maintenance accepts JSON media only',{raw:true,contentType:'text/plain'});
  await denied(base,JSON.stringify({...body,email:'x'.repeat(1024*1024)}),'admin',413,'Real host body limit remains active',{raw:true});
 });
 phase='native CAS, UUID, session withdrawal and ordered history';
 const first=command('native',1,'native-new@EXAMPLE.INVALID'),firstView=await api(base,first);structure(firstView,'native',2,'native-new@example.invalid',2);await changedEmail('native','native first successful change to revision 2');
 await denied('/me',undefined,'native',401,'Changing target candidate withdraws its old legacy session');
 const nativeSession=await login('native');await readOnly('same-value save preserves revision and active session except request audit',async()=>{await denied(base,command('native',1,'stale@example.invalid'),'admin',409,'Stale CAS rejects without writes');});
 const beforeSame=await control('snapshot'),sameValue=await api(base,command('native',2,'native-new@example.invalid'));structure(sameValue,'native',2,'native-new@example.invalid',2);same((await api('/me',undefined,'native')).uid,5,'Same-value save does not revoke target session');const afterSame=await control('snapshot');
 for(const name of Object.keys(beforeSame))if(name!=='S01_ACCOUNT_EMAIL_MAINTENANCE_REQUESTS')same(afterSame[name],beforeSame[name],'Same-value save only adds request audit: '+name);await expectDevices('same-value native save adds audit only');
 await readOnly('UUID replay and collision checks',async()=>{structure(await api(base,first),'native',2,'native-new@example.invalid',2);structure(await api(base,{...first,request_id:first.request_id.toUpperCase()}),'native',2,'native-new@example.invalid',2);same((await api('/me',undefined,'native')).uid,5,'Replay leaves later target session valid');await denied(base,{...first,email:'different@example.invalid'},'admin',409,'UUID cannot change payload');await denied(base,first,'admin2',409,'UUID cannot change real actor');await denied(base,{...first,user_id:6,confirmed_username:ids.usernames.imported},'admin',409,'UUID cannot change target');await denied(base,{...first,expected_revision:2},'admin',409,'UUID cannot change CAS');});
 structure(await api(base,command('native',2,null)),'native',3,null,3);await changedEmail('native','native clear to revision 3');structure(await api(base,command('native',3,'native-final@example.invalid')),'native',4,'native-final@example.invalid',4);await changedEmail('native','native change to revision 4');
 await readOnly('old replay returns current state without restoring email',async()=>{structure(await api(base,first),'native',4,'native-final@example.invalid',4);});
 phase='existing first-empty audit and concurrent CAS';
 structure(await api(base,command('native_empty',0,'   ')),'native_empty',0,null,0);await expectDevices('first-empty same-value creates no epoch');
 const race=await Promise.all([request(base,command('native_empty',0,'race-a@example.invalid')),request(base,command('native_empty',0,'race-b@example.invalid'))]);same(race.map(r=>r.status).sort(),[200,409],'Concurrent expected revision produces one success and one conflict');const winner=await read('native_empty');structure(winner,'native_empty',1,winner.email,1);await changedEmail('native_empty','two concurrent requests cause exactly one successful change');
 phase='active imported continuity and both source duplicate protections';
 structure(await api(base,command('imported',1,'imported-new@example.invalid')),'imported',2,'imported-new@example.invalid',2);await changedEmail('imported','active imported maintenance changes revision 1 to 2');await denied('/me',undefined,'imported',401,'Active imported change withdraws prior legacy session');
 await readOnly('cross-source current duplicates fail closed',async()=>{await denied(base,command('native',4,'IMPORTED-NEW@example.invalid'),'admin',409,'Existing cannot duplicate imported current address');await denied(base,command('imported',2,'NATIVE-FINAL@example.invalid'),'admin',409,'Imported cannot duplicate existing current address');await denied('/account-email-preparation',{user_id:7,expected_revision:0,request_id:uuid(),email:'NATIVE-FINAL@example.invalid'},'admin',409,'Old preparation cannot collide with native maintenance');await denied('/account-email-preparation?user_id=6',undefined,'admin',409,'Old preparation remains unavailable after activation');});
 structure(await api(base,command('imported_empty',0,'native@example.invalid')),'imported_empty',1,'native@example.invalid',1);await changedEmail('imported_empty','first imported maintenance changes empty to revision 1');
 const pendingPrepare={user_id:7,expected_revision:0,request_id:uuid(),email:'pending@example.invalid'};await api('/account-email-preparation',pendingPrepare);await expectDevices('legacy pending preparation does not change device epochs');
 await readOnly('UUID cannot cross original preparation and maintenance',async()=>{await denied(base,command('pending',1,'pending-next@example.invalid',pendingPrepare.request_id),'admin',409,'Preparation UUID cannot become maintenance UUID');});
 const pendingMaintenance=command('pending',1,'pending-next@example.invalid');structure(await api(base,pendingMaintenance),'pending',2,'pending-next@example.invalid',2);await changedEmail('pending','pending maintenance changes revision 1 to 2');
 await readOnly('reverse UUID namespace protection',async()=>{await denied('/account-email-preparation',{user_id:7,expected_revision:2,request_id:pendingMaintenance.request_id,email:'pending-third@example.invalid'},'admin',409,'Maintenance UUID cannot become preparation UUID');});
 phase='live account rename confirmation';await control('rename-native');
 await readOnly('rename requires current confirmation but preserves historical chain',async()=>{const view=await read('native');check(view.username==='synthetic-maintenance-native-renamed'&&view.history.length===4,'Normal rename retains candidate history');await denied(base,command('native',4,'renamed@example.invalid'),'admin',409,'Old username confirmation cannot mutate renamed target');await denied(base,first,'admin',409,'Old request cannot replay after current username changed');});
 const renamed={...command('native',4,'native-final@example.invalid'),confirmed_username:'synthetic-maintenance-native-renamed'};await api(base,renamed);await control('restore-native-name');await expectDevices('renamed confirmation same-value save does not change epoch');
 phase='slow-body authorization is revalidated';
 for(const [operation,status]of [['revoke-admin',401],['downgrade-admin',403]]){const before=await control('snapshot'),slow=await slowRequest(JSON.stringify(command('native',4,'must-not-save@example.invalid')));await pause(100);await control(operation);slow.finish();check((await slow.response).status===status,'Live '+operation+' rechecked after body');if(operation==='downgrade-admin')await control('restore-admin');await login('admin');same(await control('snapshot'),before,'Authorization fault restored without maintenance writes');await expectDevices('slow body authorization failure '+operation);}
 phase='legacy administrator self-change';const selfLegacy=command('admin',1,'admin-legacy@example.invalid');structure(await api(base,selfLegacy),'admin',2,'admin-legacy@example.invalid',2,true);await changedEmail('admin','legacy administrator self-change to revision 2');await denied('/me',undefined,'admin',401,'Legacy self-change revokes current administrator');await login('admin');
 await readOnly('self replay and same-value semantics',async()=>{structure(await api(base,selfLegacy),'admin',2,'admin-legacy@example.invalid',2,false);same((await api('/me')).uid,1,'Self replay preserves new administrator session');});
 phase='required real first and second factors';await control('mode-required');await freshWindow();
 await verified('admin2','admin2@example.invalid');await verified('admin','admin-legacy@example.invalid');await verified('native','native-final@example.invalid');await verified('imported','imported-new@example.invalid');
 await readOnly('required password is never sufficient',async()=>{await denied('/login',{username:ids.usernames.native,password:'synthetic-wrong-password'},'anonymous',401,'Incorrect password cannot send challenge');await denied('/login',{username:ids.usernames.pending,password},'anonymous',401,'Pending imported account stays inactive');});
 phase='required native change invalidates ready code and verified session';await freshWindow();const oldChallenge=await begin('native'),oldCode=latest('native-final@example.invalid').code;
 structure(await api(base,command('native',4,'native-required@example.invalid')),'native',5,'native-required@example.invalid',5);await changedEmail('native','required native change to revision 5');await denied('/me',undefined,'native',401,'Required target session withdrawn on change');await denied('/login/email/verify',{challenge_id:oldChallenge.challenge_id,code:oldCode},'anonymous',401,'Ready code cannot survive candidate change');await verified('native','native-required@example.invalid');
 phase='required administrator self-change commits before withdrawal';const requiredSelf=command('admin',2,'admin-required@example.invalid');structure(await api(base,requiredSelf),'admin',3,'admin-required@example.invalid',3,true);await changedEmail('admin','required administrator self-change to revision 3');await denied('/me',undefined,'admin',401,'Required self-change revokes prior verified session');await verified('admin','admin-required@example.invalid');
 await readOnly('required self replay does not revoke replacement session',async()=>{structure(await api(base,requiredSelf),'admin',3,'admin-required@example.invalid',3,false);same((await api('/me')).uid,1,'Replacement verified session survives replay');});
 structure(await api(base,command('admin',3,'admin-required@example.invalid')),'admin',3,'admin-required@example.invalid',3,false);await expectDevices('required administrator same-value save does not change epoch');same((await api('/me')).uid,1,'Required same-value self-save does not revoke');
 phase='sender in flight is invalidated by maintenance';await freshWindow();await control('sender-hold');const pendingSend=request('/login',{username:ids.usernames.native,password},'anonymous');let waiting=false;
 for(let i=0;i<200;i++){try{waiting=JSON.parse(fs.readFileSync(path.join(own,'sender-waiting.json'),'utf8')).waiting;}catch{}if(waiting)break;await pause(20);}check(waiting,'Synthetic sender pauses during real login HTTP');
 structure(await api(base,command('native',5,'native-after-flight@example.invalid')),'native',6,'native-after-flight@example.invalid',6);await changedEmail('native','successful email change while sender waits');await control('sender-release');const sent=await pendingSend;check(sent.status===401&&!sent.envelope?.data?.token&&!cookie(sent),'Email mutation during send cannot finish old challenge');check((await stats()).sender_lock_violations===0,'No synthetic delivery ever held business lock');
 phase='required clearing and failed delivery never bypass verification';const nativeEmpty=await read('native_empty');structure(await api(base,command('native_empty',nativeEmpty.revision,null)),'native_empty',nativeEmpty.revision+1,null,2);await changedEmail('native_empty','required clearing makes second native-empty change');
 await readOnly('required missing email and sender failure',async()=>{await denied('/login',{username:ids.usernames.native_empty,password},'anonymous',409,'Cleared candidate cannot fall back to password-only login');await freshWindow();await control('sender-fail');await denied('/login',{username:ids.usernames.imported,password},'anonymous',503,'Failed synthetic delivery cannot issue session');await control('sender-normal');});
 const final=await control('snapshot');for(const name of Object.keys(baseline))if(name!=='S01_TRUSTED_DEVICE_EPOCHS'&&!/^S01_ACCOUNT_EMAIL_(?:MAINTENANCE_)?(?:HEADS|REVISIONS|REQUESTS)$/.test(name))same(final[name],baseline[name],'All original non-email tables and trusted devices remain unchanged: '+name);await expectDevices('final exact epochs after all successful and rejected changes');
 phase='stopped inspection and required cold restart';const persisted=await read('native');await stop();const inspected=JSON.parse((await run(java,[...options(true),'com.training.S01AccountEmailMaintenanceHttpFixture','inspect'],{cwd:app,env,timeout:20000,maxBuffer:262144})).stdout.trim());same(inspected,final,'Independent stopped database inspection matches live final snapshot');launchMode='required';await boot(true);await verified('admin','admin-required@example.invalid');same(await read('native'),persisted,'Actual Main restart preserves both candidate and complete history');same(await control('snapshot'),final,'Cold initialization and login write no persistent data');await expectDevices('cold initialization and required verification preserve exact epochs');
 fs.writeFileSync(path.join(own,'database-invariants.json'),JSON.stringify({baseline,final,inspected,read_phases:readEvidence,device_epoch_evidence:deviceEvidence},null,2),{mode:0o600});
 return {device_epoch_checkpoints:deviceEvidence.length,expected_device_epochs:[...expectedDeviceEpochs].sort((a,b)=>a[0]-b[0]),actual_email_changes_after_bootstrap:12,registered_devices_expected:0,read_only_phases:readEvidence.length,public_tables:Object.keys(final).length,fixture_accounts:Object.keys(ids.accounts).length,sender_network_calls:0,real_mail_transport:'disabled',product_classes:classes,fixture_overlay:overlay};
}
let evidence;runChecks().then(value=>{evidence=value;}).catch(error=>{fatal=(phase+': '+String(error.message||error)).replaceAll(password,'[redacted]');process.exitCode=1;}).finally(async()=>{await stop();const stopped=pids.every(pid=>{try{process.kill(pid,0);return false;}catch(error){return error.code==='ESRCH';}});check(stopped,'Every owned synthetic Main process stopped');const summary={suite:'s01-account-email-maintenance-http',checks,failures,...(fatal?{error:fatal}:{}),...(evidence||{}),server_processes_stopped:stopped,production_touched:false,notifications_sent:false,artifacts:own};fs.writeFileSync(path.join(own,'result.json'),JSON.stringify(summary,null,2),{mode:0o600});console.log(JSON.stringify(summary));if(failures.length||fatal)process.exitCode=1;});
