#!/usr/bin/env node
'use strict';
const fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict'), crypto = require('node:crypto');
const root = path.resolve(__dirname, '..'), read = file => fs.readFileSync(path.join(root,file));
let checks = 0;
const check = (condition,label) => { assert.ok(condition,label); checks++; };
const css = read('web/v13.css').toString(), app = read('web/app.js').toString(), scene = read('web/scene/login-book-three.js').toString();
const asset = read('web/assets/login-background-v13r10.webp'), original = read('design/login/v13r10-originals/silver-light-background.png');
check(asset.toString('ascii',0,4) === 'RIFF' && asset.toString('ascii',8,12) === 'WEBP','browser asset is WebP');
check(asset.length < 50000,'background budget <50KB');
check(crypto.createHash('sha256').update(asset).digest('hex') === 'ce1824cbf10caab8f0151eddfea4aec75b34141c32236402b3550d048c27804f','reviewed compressed background is unchanged');
check(original.readUInt32BE(16) === 1586 && original.readUInt32BE(20) === 992,'full-size original is retained');
check(crypto.createHash('sha256').update(original).digest('hex') === 'cd964012831a92a549d07fd986ca599e58427ac2831f5fa4d49906f1172f0873','original was not repainted or overwritten');
const ambient = css.match(/\.login-ambient \{([^}]+)\}/)[1];
check(/inset:\s*0/.test(ambient) && /position:\s*absolute/.test(ambient),'background covers its login parent');
check(/z-index:\s*-1/.test(ambient) && /pointer-events:\s*none/.test(ambient),'decoration cannot intercept form or book input');
check(ambient.includes("url('/assets/login-background-v13r10.webp')") && ambient.includes('cover no-repeat'),'local artwork fills proportionally without tiling');
check(ambient.includes('#f7f9fc'),'image failure has a stable light fallback');
check(app.includes('<div class="login-ambient" aria-hidden="true"><span></span></div>'),'single decorative light sweep, not two blur blobs');
check(app.indexOf('class="login-ambient"') > app.indexOf('function renderLogin()'),'background is owned by the login view');
check(!scene.includes('new THREE.PlaneGeometry(4.4, 2.9)') && !scene.includes('shadowCanvas'),'oversized clipped shadow plane removed');
check(css.includes('.login-visual::before { display: none; }'),'old local radial halo removed');
check(css.includes('filter: drop-shadow(0 12px 14px #344b7012)'),'shadow follows transparent book silhouette');
check(/@media \(prefers-reduced-motion: reduce\) \{ html body\.yx-v13 \.login-ambient span \{ animation: none; \}/.test(css),'reduced motion stops background animation');
const pause = css.match(/\.login-learning:is\(([^)]+)\) \.login-ambient span \{ animation-play-state: paused; \}/)?.[1] || '';
for (const state of ['paused','loading','loading-visual','unavailable','focused','hidden','reduced']) check(pause.includes('"'+state+'"'),'background pauses during '+state);
check(css.includes('.login-learning:has(#login-form:focus-within) .login-ambient span'),'form focus pauses without depending on WebGL');
check(css.includes('.login-learning:has(#login-form[aria-busy="true"]) .login-ambient span { animation-play-state: paused; }'),'form request pauses without depending on WebGL');
for (const file of ['index.html','answer.html','materials.html','updates.html']) check(read('web/'+file).toString().includes('v13.css?v=20260906v13r10'),'shared stylesheet cache '+file);
console.log(JSON.stringify({ok:true,suite:'R10 login background asset and isolation',checks,bytes:asset.length}));
