'use strict';
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const assert = require('node:assert/strict');
const root = path.resolve(__dirname, '..');
const browser = JSON.parse(vm.runInNewContext(fs.readFileSync(path.join(root, 'web/regions.js'), 'utf8') + '\nJSON.stringify(YX_REGION_CITIES)'));
const backend = fs.readFileSync(path.join(root, 'src/com/training/RegionDirectory.java'), 'utf8');
const parsed = {};
for (const match of backend.matchAll(/CITIES\.put\("([^"]+)",[^\n]*Arrays\.asList\(([^)]+)\)/g)) parsed[match[1]] = JSON.parse(`[${match[2]}]`);
assert.deepEqual(browser, parsed, 'browser/server city dictionaries must stay identical');
assert.equal(Object.values(browser).flat().length, 371);
assert.ok(browser['吉林'].includes('吉林'));
assert.ok(browser['新疆'].includes('喀什地区'));
assert.ok(browser['西藏'].includes('阿里地区'));
assert.deepEqual(browser['重庆'], ['重庆']);
const html = fs.readFileSync(path.join(root, 'web/index.html'), 'utf8');
assert.ok(html.indexOf('src="/regions.js') < html.indexOf('src="/app.js'), 'suggestions load before application');
console.log('Region dictionary parity: 7 passed (371 entries)');
