// Pure rendering checks; no browser, network, model or real route data.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const source = fs.readFileSync('web/app.js', 'utf8');
const start = source.indexOf('  function railVerificationMarkup(');
const end = source.indexOf('  function adjacentScheduleMarkup(', start);
assert(start >= 0 && end > start);
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
const render = vm.runInNewContext(`(${source.slice(start, end).trim()})`, { esc, icon: () => '' });
const leg = { from_city: '灰度甲城', to_city: '灰度乙城', reference_minutes: 120, research_on: '2026-09-07', source_url: 'https://example.com/test' };
const ref = { status: 'city_transport_reference', eligibility: 'rail', outbound: leg, return: { ...leg, reference_minutes: 135 }, version: 1, review_due_on: '2026-12-06' };
const html = render({ route_reference: ref });
assert.match(html, /高铁优先 · 城市交通参考/);
assert.match(html, /120 分钟/); assert.match(html, /135 分钟/);
assert.match(html, /不代表授课日班次、余票或到场保证/);
assert(!html.includes('undefined')); assert(!html.includes('车次'));
assert.match(render({ route_reference: { ...ref, eligibility: 'air' } }), /航空备选/);
const evil = render({ route_reference: { ...ref, outbound: { ...leg, from_city: '<img src=x>', source_url: 'javascript:alert(1)' } } });
assert(!evil.includes('<img')); assert(!evil.includes('javascript:'));
const pending = render({ route_reference: { status: 'city_reference_pending' } });
assert.match(pending, /待复核/); assert(!pending.includes('分钟'));
const publicLeg={...leg,from_endpoint:'灰度甲站',to_endpoint:'灰度乙站',source_published_on:'2026-01-27'};
const publicHtml=render({route_reference:{...ref,reference_basis:'public_city_reference',near_threshold:true,outbound:publicLeg,return:publicLeg}});
assert.match(publicHtml,/公开通达参考/);assert.match(publicHtml,/2026-01-27/);assert.match(publicHtml,/灰度甲站/);
assert.match(publicHtml,/接近范围边界.*重点复核交通时间/);assert(!publicHtml.includes('人工认证通过'));
const scheduleLeg={...publicLeg,service_state:'published_schedule_baseline',effective_from:'2026-01-26'};
const scheduleHtml=render({route_reference:{...ref,reference_basis:'public_city_reference',outbound:scheduleLeg,return:scheduleLeg}});
assert.match(scheduleHtml,/已生效运行图公告参考/); assert.match(scheduleHtml,/公告实施日期 2026-01-26/);
assert.match(scheduleHtml,/未核验出行当天运行情况/); assert(!publicHtml.includes('已生效运行图公告参考'));
const scheduleEvil=render({route_reference:{...ref,reference_basis:'public_city_reference',outbound:{...scheduleLeg,effective_from:'<img src=x>'},return:scheduleLeg}});
assert(!scheduleEvil.includes('<img'));
const interval={kind:'open_interval',original_text:'3小时40多分钟',display:'220 < 分钟 < 240',lower_minutes:220,upper_minutes:240,lower_inclusive:false,upper_inclusive:false,precision:'colloquial_within_hour_inference',inference_notice:'依据中文时长表述解释，非公布精确上界'};
const typedLeg={...publicLeg,duration_bounds:interval};delete typedLeg.reference_minutes;
const typedHtml=render({route_reference:{...ref,reference_basis:'public_city_reference',duration_representation:'typed_city_bounds',outbound:typedLeg,return:typedLeg}});
assert.match(typedHtml,/3小时40多分钟/);assert.match(typedHtml,/非公布精确上界/);assert.match(typedHtml,/220 &lt; 分钟 &lt; 240/);
assert(!typedHtml.includes('undefined'));assert(!typedHtml.includes('null'));assert(!typedHtml.includes('240 分钟'));
assert.match(typedHtml,/城市范围/);
const boundsEvil=render({route_reference:{...ref,outbound:{...typedLeg,duration_bounds:{...interval,original_text:'<img src=x>',inference_notice:'<script>alert(1)</script>'}},return:typedLeg}});
assert(!boundsEvil.includes('<img'));assert(!boundsEvil.includes('<script>'));
assert(source.includes("dispatchFit.time_score_applicable === false"));
assert(source.includes('[0, 1, 2, 3, 4, null].map'));
console.log('City reference UI: 31 assertions passed');
