'use strict';
const fs = require('node:fs'), vm = require('node:vm'), assert = require('node:assert/strict');
const app = fs.readFileSync(require('node:path').join(__dirname, '../web/app.js'), 'utf8');
const start = app.indexOf('  function semanticEvidenceMarkup('), end = app.indexOf('  function renderRecommendationResults(', start);
const context = {icon: () => '<i></i>', esc: text => String(text ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')};
vm.createContext(context); vm.runInContext(app.slice(start,end), context);
let checks=0; const check=(ok,label)=>{assert.ok(ok,label);checks++;};
check(context.semanticEvidenceMarkup(null)==='', 'no fictitious model output');
for(const score of [NaN,Infinity,1.1,-1.1,'0.8',null]) check(context.semanticEvidenceMarkup({status:'ready',similarity:score,evidence:['主讲课程']})==='', 'invalid score omitted');
const html=context.semanticEvidenceMarkup({status:'ready',similarity:.712345,evidence:['<script>alert(1)</script>']});
check(html.includes('0.712') && !html.includes('71.2%'), 'similarity not probability');
check(!html.includes('<script>') && html.includes('&lt;script&gt;'), 'evidence escaped');
check(html.includes('不代表资历已核实'), 'claim not verification');
check(context.railVerificationMarkup({})==='', 'online/no-rail remains uncluttered');
check(context.railVerificationMarkup({route_reference:{status:'not_required'}})==='', 'online does not show unneeded travel warning');
const route=context.railVerificationMarkup({route_reference:{status:'reference_available',upper_minutes:120,return_upper_minutes:180,message:'<script>',checked_on:'<img>'}});
check(route.includes('120 分钟') && route.includes('180 分钟'), 'both reference directions displayed');
check(!route.includes('<script>') && route.includes('&lt;script&gt;') && !route.includes('<img>'), 'route evidence escaped');
check(!context.railVerificationMarkup({route_reference:{status:'no_reference',upper_minutes:0}}).includes('0 分钟'), 'unknown duration not zero');
check(app.includes('匹配前三 · 第三名同分全部保留') && !app.includes('[3, 5, 10].map'), 'no conflicting count selector');
const rail=context.railVerificationMarkup({rail:{departure_city:'<img>',destination_city:'上海',official_query_url:'javascript:alert(1)',fare:0,verified:true}});
check(rail.includes('https://www.12306.cn/index/') && !rail.includes('javascript:'), 'provider cannot inject link');
check(rail.includes('尚未连接班次数据') && !rail.includes('免费'), 'not connected is explicit, no zero fare');
check(rail.includes('noopener noreferrer') && !rail.includes('<img>'), 'safe new tab and escaping');
check(context.adjacentScheduleMarkup([])==='', 'no invented itinerary');
check(context.adjacentScheduleMarkup([{date:'2099-01-01',venue:'<script>'}]).includes('&lt;script&gt;'), 'schedule escaped');
check(app.includes("type: 'time'") && app.includes('training_start_time') && app.includes('training_end_time'), 'exact interval controls');
check(app.includes("k: 'teacher_level'") && app.includes("{ v: '', l: '待补充' }, '讲师', '高级讲师', '特级讲师', '特聘讲师'"), 'explicit ungraded option and four levels');
check(app.includes("score === null ? '模型未评分'") && app.includes('模型匹配分'), 'missing model score is not displayed as zero');
check(!app.includes('城市点距离不等于') && app.includes('同城及所有铁路小于4小时的合格老师统一比较'), 'full rail pool replaces geometric distance and early cutoff');
const snapshot=context.railVerificationMarkup({route_reference:{status:'rail_time_reference',outbound:{from_station:'南京南',to_station:'合肥南',train_no:'G3591',rail_minutes:48,departure_time:'06:53',arrival_time:'07:41',source_service_date:null,observed_on:'2026-09-07',source_url:'javascript:alert(1)'},message:'<script>'}});
check(snapshot.includes('高铁参考时长 48 分钟')&&!snapshot.includes('网页未标查询日期')&&!snapshot.includes('门到门'), 'station-time reference is explicit without research-date clutter or door-to-door claim');
check(!snapshot.includes('javascript:')&&!snapshot.includes('<script>'), 'snapshot sources and prose cannot inject markup');
const local=context.railVerificationMarkup({route_reference:{status:'same_city',message:'市内通勤待确认'}});
check(local.includes('通勤待确认')&&!local.includes('跨城'), 'same-city candidates do not request high-speed railway');
check(app.includes('模型待评分')&&app.includes('未混入模型排名'), 'partial model results separated from unscored fallback');
check(app.includes('outside_nearby_routes')&&app.includes('路线待补查'), 'long and missing routes stay visible');
const air=context.railVerificationMarkup({route_reference:{status:'air_time_reference',outbound:{from_airport_code:'NKG',to_airport_code:'PEK',flight_no:'MU1234',flight_minutes:179,source_url:'javascript:alert(1)'},message:'<script>'}});
check(air.includes('179 分钟')&&!air.includes('javascript:')&&!air.includes('<script>'),'air source output is escaped and never a script link');
check(app.includes('enumerated_count')&&app.includes('transport_scope_complete')&&app.includes('清单已列全不等于交通已查全'),'city enumeration cannot masquerade as full travel coverage');
check(app.includes('机构选择不会覆盖已填写地点') && app.includes("organizationSelect.value === '' ? null"), 'empty organization selection is not row zero and actual city protected');
console.log(`Semantic evidence and rail UI: ${checks} checks passed`);
