'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const app=fs.readFileSync(path.join(__dirname,'../web/app.js'),'utf8');
const ctx={icon:()=>'<i></i>',esc:value=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')};
vm.createContext(ctx);
vm.runInContext(app.slice(app.indexOf('  function guidedRequirementText('),app.indexOf('  function demandGuidedFields(')),ctx);
vm.runInContext(app.slice(app.indexOf('  function requirementInputMarkup('),app.indexOf('  function renderRecommendationResults(')),ctx);
let checks=0;const check=(ok,label)=>{assert.ok(ok,label);checks++;};
const draft={topic:'  ＡＢＣ编号  ',audience:' 新任人员 ',goals:'不应自动认定为本人已有经历',extra:'<script>alert(1)</script>'};
const contract=ctx.guidedRequirementContract(draft),text=ctx.guidedRequirementText(draft);
check(contract.schema_version==='guided_requirement_v1','explicit schema');
check(Object.keys(contract.fields).join(',')==='unit,topic,audience,goals,date,hours,preference,extra','exact eight fields');
check(contract.fields.topic===draft.topic&&contract.fields.audience===draft.audience,'untrimmed field originals retained');
check(text.includes('培训主题：ＡＢＣ编号')&&text.includes('参训对象：新任人员'),'existing renderer unchanged');
check(!('industry' in contract.fields),'no invented unused field');
check(ctx.requirementInputMarkup(null)===''&&ctx.requirementInputMarkup({schema_version:'unknown'})==='','unknown version not displayed as parsed');
const html=ctx.requirementInputMarkup({schema_version:contract.schema_version,field_ledger:[{status:'requires_review',label:'<b>其他要求</b>',raw_value:draft.extra}]});
check(html.includes('补充要求待核对')&&html.includes('核对前不会视为全部满足'),'unresolved requirements visible');
check(!html.includes('<script>')&&!html.includes('<b>其他要求</b>')&&html.includes('&lt;script&gt;'),'untrusted field text escaped');
check(html.includes('培训目标不会被当作讲师已有授课经历'),'goals not credentials');
check(app.includes("if (inputMode === 'guided') {\n          body.requirement_contract = guidedRequirementContract(readGuided());"),'raw path not silently converted');
check(app.includes('if (demandSelect.value) body.demand_id = Number(demandSelect.value);'),'guided linked demand source preserved');
console.log(`Guided requirement UI: ${checks} checks passed`);
