// Pure rendering. Optional actual regression arguments never activate application settings.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
function renderer(path){const s=fs.readFileSync(path,'utf8'),a=s.indexOf('  function railVerificationMarkup('),b=s.indexOf('  function adjacentScheduleMarkup(',a);assert(a>=0&&b>a);return vm.runInNewContext(`(${s.slice(a,b).trim()})`,{esc,icon:()=>''});}
const render=renderer('web/app.js'),copy=x=>JSON.parse(JSON.stringify(x));let checks=0;const check=(b,label)=>{checks++;assert(b,label);};
function fixture(){const a={id:'C001',city:'合成甲'},b={id:'C002',city:'合成乙'},leg=(f,t,id)=>({from:f,to:t,from_endpoint:f.city,to_endpoint:t.city,endpoint_scope:{from:'city_summary',to:'city_summary'},scope:'city_summary',precision:'reported_minutes',source_document:id,source_url:'https://example.invalid/'+id,source_published_on:id==='out'?'2026-08-16':'2025-12-22',reviewed_on:'2026-09-08',review_due_on:'2026-12-07'}),shown=(f,t,id,value,qualifier)=>({from_registry_id:f.id,to_registry_id:t.id,source_document:id,annotation_id:'SYNTHETIC',source_qualifier:qualifier,precision:'reported_minutes',duration:{kind:'reported_minutes',value,unit:'minute'}});
 const p={status:'planning_reference',purpose:'prebid_city_planning_only',planning_band_id:'planning_0_1h',transport_verified:false,time_score_applicable:false,air_fallback_trigger:false,rail_exclusion_complete:false,outbound:leg(a,b,'out'),inbound:leg(b,a,'back'),selection_reference:{basis:'unbuffered_city_reference_v1',buffer_applied:false,confirmed_itinerary:false,outbound:{reference_minutes:24,unit:'minute',precision:'reported_minutes',upper_exclusive:false},inbound:{reference_minutes:20,unit:'minute',precision:'reported_minutes',upper_exclusive:false}},presentation:{version:'city-planning-presentation-v2',purpose:'presentation_only',affects_selection:false,status:'ready',revision:2,outbound:shown(a,b,'out',24,'reported_fastest'),inbound:shown(b,a,'back',20,'general_reported')}};
 p.presentation.inbound.source_context='institution_location';return {planning_included:true,planning_reference:p,route_reference:{status:'rail_reference_pending',eligibility:'unknown'}};}
const f=fixture(),html=render(f);check(html.includes('去程：报道最快24分钟'),'fastest forward');check(html.includes('返程：机构区位参考20分钟'),'institution context visible');check(!html.includes('最快20分钟'),'institution not fastest');check(html.includes('未指定站点'),'unknown station visible');check(html.includes('实际出行待核')&&html.includes('不是所有班次或到场保证'),'not real-time/guaranteed');for(const date of ['2026-08-16','2025-12-22','2026-09-08','2026-12-07'])check(html.includes(date),'source/review date '+date);
function rejected(edit,why){const v=copy(f);edit(v.planning_reference);const h=render(v);check(h.includes('时长说明待核'),why);check(!h.includes('机构区位参考20分钟')&&!h.includes('报道最快24分钟'),why+' no bare fallback');}
for(const value of ['__proto__','unknown','<img src=x>',null])rejected(p=>p.presentation.inbound.source_context=value,'unknown context');
rejected(p=>p.presentation.version='city-planning-presentation-v1','v1 rejects new context field');rejected(p=>p.presentation.inbound.source_qualifier='reported_fastest','institution cannot be fastest');rejected(p=>p.presentation.inbound.source_document='out','wrong source direction');rejected(p=>p.presentation.inbound.duration.value=24,'cannot mirror outgoing number');rejected(p=>p.presentation.inbound.extra='x','extra field rejected');
const malicious=copy(f);malicious.planning_reference.inbound.from_endpoint='<script>x</script>';malicious.planning_reference.inbound.source_url='javascript:alert(1)';const safe=render(malicious);check(!safe.includes('<script>')&&!safe.includes('javascript:'),'source and endpoints escaped');check(safe.includes('&lt;script&gt;'),'escaped original endpoint retained');
if(process.argv.length>2){assert.equal(process.argv.length,5,'Usage: node test_city_presentation_v2_ui.cjs actual-collection-result.json old-v1-actual.json app.before.js');const actual=JSON.parse(fs.readFileSync(process.argv[2],'utf8')),old=JSON.parse(fs.readFileSync(process.argv[3],'utf8')),before=renderer(process.argv[4]),key=x=>`${x.from.id}:${x.to.id}`,oldRows=new Map(old.planning_outputs.map(x=>[key(x),x]));let newDirections=0,oldDirections=0,shared=0;
 const fit=r=>({planning_included:true,planning_reference:r,route_reference:{status:'rail_reference_pending',eligibility:'unknown'}});
 for(const row of actual.planning_outputs){const v=fit(row.reference),h=render(v),oldRow=oldRows.get(key(row));if(row.shared){Object.assign(v,{planning_policy:'explicit_roundtrip_shared_planning_v1',planning_reference_kind:'explicit_roundtrip_shared_v1',shared_planning_band_id:'planning_1_2h'});check(render(v)===before(v),'shared exact old markup');shared++;continue;}
  check(!h.includes('时长说明待核'),'actual ready display');check(h.includes(row.reference.outbound.source_published_on)&&h.includes(row.reference.inbound.source_published_on),'actual dates both directions');
  if(oldRow){check(h===before(fit(oldRow.reference)),'old36 rendered HTML exactly unchanged');const noView=copy(v);delete noView.planning_reference.presentation;check(render(noView)===before(noView),'old default HTML identical');oldDirections++;}
  else{check(h.includes('报道最快24分钟')&&h.includes('机构区位参考20分钟'),'both new labels visible, not just stored note');check(h.includes('成都东站')&&h.includes('德阳站')&&h.includes('未指定站点'),'mixed original endpoints');check(h.includes('2026-08-16')&&h.includes('2025-12-22'),'two original publication dates');newDirections++;}}
 check(oldDirections===36&&newDirections===2&&shared===1,'all38 display directions plus shared');check(actual.total_disjoint_pairs_across_layers===39,'actual39 aggregate');
 for(const row of actual.new_synthetic_selections.filter(x=>x.expired)){const expired=render(fit(row.expired));check(!expired.includes('报道最快24分钟')&&!expired.includes('机构区位参考20分钟'),'expired pair no affirmative duration');}
 check(actual.unknown_pair.air_fallback_trigger===false&&actual.unknown_pair.rail_exclusion_complete===false,'unknown is not air proof');
}
console.log(`City presentation v2 UI: ${checks} assertions passed; pure rendering only`);
