'use strict';
// Private R25 candidate only: actual Main HTTP, fresh temporary H2, example.invalid memory sender.
const fs=require('node:fs'),path=require('node:path'),net=require('node:net'),crypto=require('node:crypto'),assert=require('node:assert/strict');
const http=require('node:http');
const {spawn,execFile}=require('node:child_process'),run=require('node:util').promisify(execFile),args={};
for(let i=2;i<process.argv.length;i+=2){assert.ok(['--java','--classes','--overlay','--baseline','--app'].includes(process.argv[i])&&process.argv[i+1],'Use --java PATH --classes PRIVATE_PRODUCT_OUT --overlay FIXTURE_OUT --app APP');args[process.argv[i]]=process.argv[i+1];}
const java=args['--java']||'java',app=fs.realpathSync(args['--app']||path.resolve(__dirname, '..'));
const classes=fs.realpathSync(args['--classes']||''),overlay=fs.realpathSync(args['--overlay']||''),baselineClasses=args['--baseline']?fs.realpathSync(args['--baseline']):classes;
for(const dir of [classes,overlay,baselineClasses])assert.ok(dir!==app&&!dir.startsWith(app+path.sep),'Classes must be independent of shared app');
assert.ok(fs.existsSync(path.join(overlay,'com/training/TrustedDevices.class'))||fs.existsSync(path.join(classes,'com/training/TrustedDevices.class')),'An actual ready private R25 product build is required');
assert.ok(fs.existsSync(path.join(overlay,'com/training/TrustedDeviceHttpFixture.class')),'Compile the scripts-only fixture separately');
const own=fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'yanxu-trusted-device-http-')),data=path.join(own,'data');fs.mkdirSync(data,{mode:0o700});
const password=crypto.randomBytes(24).toString('hex'),env={...process.env},failures=[],processes=[],readEvidence=[];
for(const key of Object.keys(env))if(/^YANXU_LOGIN_(SMTP_|MAIL_)/.test(key))delete env[key];
Object.assign(env,{YANXU_LOGIN_MAIL_TRANSPORT:'disabled',JAVA_TOOL_OPTIONS:'',JDK_JAVA_OPTIONS:'',_JAVA_OPTIONS:'',YANXU_SEMANTIC_PORT:'',YANXU_SEMANTIC_TOKEN:'',YANXU_CITY_PLANNING_COLLECTION_FILE:''});
let child,port,ids,checks=0,phase='setup',fatal=null,baseline;
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms)),uuid=()=>crypto.randomUUID(),origin=()=>`http://127.0.0.1:${port}`,endpoint='/login/device/restore';
function check(ok,label){checks++;if(!ok)failures.push(phase+': '+label);}
function same(a,b,label){let ok=true;try{assert.deepEqual(a,b);}catch{ok=false;}check(ok,label);}
function options(resume=false){return ['-Dbind.address=127.0.0.1','-Dbootstrap.demo=false','-Dbootstrap.admin.password='+password,'-Dintegration.trusted.device.root='+own,'-Dintegration.trusted.device.resume='+resume,'-Ddata.dir='+data,'-Dlogin.email.mode=required','-Dlogin.device.maxAgeSeconds=3600','-Dlogin.device.origin='+origin(),'-Dsemantic.port=','-Dsemantic.token=','-Daccount.import.manifest=','-Daccount.import.manifest.sha256=','-cp',overlay+path.delimiter+classes+path.delimiter+baselineClasses+path.delimiter+path.join(app,'lib','*')];}
async function boot(resume=false){
 if(!port){const probe=net.createServer();await new Promise((resolve,reject)=>{probe.once('error',reject);probe.listen(0,'127.0.0.1',resolve);});port=probe.address().port;await new Promise(resolve=>probe.close(resolve));}
 const log=fs.openSync(path.join(own,'fixture.log'),'a',0o600);child=spawn(java,[...options(resume),'com.training.TrustedDeviceHttpFixture',String(port)],{cwd:app,env,stdio:['ignore',log,log]});fs.closeSync(log);if(child.pid)processes.push(child.pid);let error;child.once('error',e=>error=e);
 for(let i=0;i<180;i++){if(error)throw error;assert.equal(child.exitCode,null,'Private fixture exited; see fixture.log');try{const r=await fetch(origin()+'/api/me',{signal:AbortSignal.timeout(1000)});await r.text();if(r.status===401){ids=JSON.parse(fs.readFileSync(path.join(own,'fixture.json'),'utf8'));return;}}catch{}await pause(100);}throw new Error('Private candidate Main startup timeout');
}
async function stop(){const current=child;child=null;if(!current||current.exitCode!==null||current.signalCode!==null)return;await new Promise(resolve=>{const timer=setTimeout(()=>{if(current.exitCode===null&&current.signalCode===null)current.kill('SIGKILL');},2000);current.once('exit',()=>{clearTimeout(timer);resolve();});current.kill('SIGTERM');});}
async function control(operation,extra={}){const nonce=uuid(),tmp=path.join(own,'control-request.next');fs.writeFileSync(tmp,JSON.stringify({nonce,operation,...extra}),{mode:0o600});fs.renameSync(tmp,path.join(own,'control-request.json'));for(let i=0;i<250;i++){let ack;try{ack=JSON.parse(fs.readFileSync(path.join(own,'control-result.json'),'utf8'));}catch{}if(ack?.nonce===nonce){assert.equal(ack.ok,true,'Synthetic control failed: '+operation);return ack.data;}await pause(20);}throw new Error('Synthetic control timeout: '+operation);}
async function request(route,body,opt={}){
 const headers={...(opt.headers||{})};if(opt.origin!==null)headers.Origin=opt.origin||origin();if(opt.cookie)headers.Cookie=opt.cookie;if(opt.token)headers['X-Token']=opt.token;
 if(body!==undefined&&opt.contentType!==null)headers['Content-Type']=opt.contentType||'application/json';
 const method=opt.method||(body===undefined?'GET':'POST'),wireBody=body===undefined?undefined:opt.raw?body:JSON.stringify(body);
 const response=opt.headers?.Host?await new Promise((resolve,reject)=>{const req=http.request(origin()+'/api'+route,{method,headers},res=>{const chunks=[];res.on('data',chunk=>chunks.push(chunk));res.on('end',()=>{const responseHeaders=new Headers();for(const [key,value]of Object.entries(res.headers))if(value!==undefined)for(const item of Array.isArray(value)?value:[value])responseHeaders.append(key,item);resolve({status:res.statusCode,headers:responseHeaders,rawSetCookies:res.headers['set-cookie']||[],text:async()=>Buffer.concat(chunks).toString('utf8')});});});req.on('error',reject);req.setTimeout(25000,()=>req.destroy(new Error('Synthetic HTTP timeout')));if(wireBody!==undefined)req.write(wireBody);req.end();}):await fetch(origin()+'/api'+route,{method,headers,body:wireBody,signal:AbortSignal.timeout(25000)});
 const text=await response.text();let envelope=null;if(text){try{envelope=JSON.parse(text);}catch{throw new Error(route+' returned non-JSON HTTP '+response.status);}}
 check(!text.includes(password)&&!text.includes('pbkdf2$')&&!text.includes(own),'Response exposes no password, stored hash or private path');
 if(route.startsWith('/login')||route==='/logout')check(response.headers.get('cache-control')==='no-store','Authentication/device response is not cached');
 if(route.startsWith('/login'))check(!text.includes('@example.invalid'),'Login reveals no candidate address');
 const setCookies=response.rawSetCookies|| (response.headers.getSetCookie?response.headers.getSetCookie():[response.headers.get('set-cookie')||'']);
 return {status:response.status,envelope,text,headers:response.headers,setCookies};
}
async function api(route,body,opt={}){const r=await request(route,body,opt);assert.equal(r.status,200,phase+': '+route+' HTTP '+r.status+': '+r.envelope?.msg);assert.equal(r.envelope?.code,0,route);return {data:r.envelope.data,response:r};}
function rawCookie(r,name){return r.setCookies.filter(value=>value.startsWith(name+'=')).at(-1)||null;}
function clearsCookie(r,name){return r.setCookies.some(value=>value.startsWith(name+'=')&&/(?:^|;)\s*Max-Age=0(?:;|$)/i.test(value));}
function clearsBrowser(r,label){check(clearsCookie(r,'yx_device_local')&&clearsCookie(r,'__Host-yx_device')&&clearsCookie(r,'yx_session'),label+' clears both device names and short cookie');}
function usableCookie(r,name){const value=rawCookie(r,name);return value&&!/(?:^|;)\s*Max-Age=0(?:;|$)/i.test(value)?value.split(';')[0]:null;}
function joinCookies(...values){return values.filter(Boolean).join('; ');}
function valueOfCookie(cookie){return cookie?.substring(cookie.indexOf('=')+1);}
function maxAge(raw){return Number(/(?:^|;)\s*Max-Age=(\d+)/i.exec(raw||'')?.[1]);}
function session(r){return {token:r.envelope?.data?.token,cookie:usableCookie(r,'yx_session'),device:usableCookie(r,'yx_device_local')||usableCookie(r,'__Host-yx_device'),user:r.envelope?.data?.user};}
async function denied(route,body,status,label,opt={}){const r=await request(route,body,opt),expected=Array.isArray(status)?status:[status];check(expected.includes(r.status)&&(opt.method==='HEAD'?r.text==='':r.envelope?.code===r.status),label+' (HTTP '+r.status+')');check(!r.envelope?.data&&!usableCookie(r,'yx_session')&&!usableCookie(r,'yx_device_local')&&!usableCookie(r,'__Host-yx_device'),label+' issues no usable credential');return r;}
const stats=()=>control('stats'),fresh=()=>control('advance',{millis:3600001}),storage=()=>control('device-storage');
const mailbox=()=>JSON.parse(fs.readFileSync(path.join(own,'mailbox.json'),'utf8'));
function mail(email){const found=mailbox().filter(row=>row.email===email).at(-1);assert.ok(found,'Missing in-memory synthetic mail');assert.match(found.code,/^[0-9]{6}$/);return found;}
async function begin(name,pass=password){await fresh();const before=await stats(),{data:c,response}=await api('/login',{username:ids.usernames[name],password:pass});same(Object.keys(c).sort(),['challenge_id','expires_at','masked_email','resend_after','status'],'Password proof returns only opaque email challenge');check(c.status==='EMAIL_REQUIRED'&&c.masked_email==='***@***'&&!usableCookie(response,'yx_session')&&!usableCookie(response,'yx_device_local'),'Password alone cannot sign short or device cookie');same((await stats()).sessions,before.sessions,'Password alone creates no Auth session');return c;}
async function verify(name,email=ids.initial_emails[name],opt={}){const challenge=await begin(name,opt.password||password),sent=mail(email),r=await request('/login/email/verify',{challenge_id:challenge.challenge_id,code:sent.code},opt);assert.equal(r.status,200,phase+': actual email verify HTTP '+r.status+': '+r.envelope?.msg);same(Object.keys(r.envelope.data).sort(),['token','user'],'Verification JSON contains only original short-session DTO');const s=session(r);check(s.token&&s.cookie&&s.user.uid===ids.accounts[name],'Actual email verification creates correct short identity');check(!sent.held_lock,'Memory sender runs outside business lock');if(opt.expectDevice!==false){check(Boolean(s.device),'Correct email code creates persistent device cookie');if(opt.secure){const secure=rawCookie(r,'__Host-yx_device');check(secure?.includes('HttpOnly')&&secure?.includes('SameSite=Strict')&&secure?.includes('Path=/')&&/;\s*Secure(?:;|$)/i.test(secure||'')&&!secure?.includes('Domain=')&&!usableCookie(r,'yx_device_local'),'HTTPS production cookie has __Host prefix, Secure, HttpOnly, SameSite=Strict and no Domain');}else check(rawCookie(r,'yx_device_local')?.includes('HttpOnly')&&rawCookie(r,'yx_device_local')?.includes('SameSite=Strict')&&rawCookie(r,'yx_device_local')?.includes('Path=/')&&!/;\s*Secure(?:;|$)/i.test(rawCookie(r,'yx_device_local')||'')&&!rawCookie(r,'yx_device_local')?.includes('Domain='),'Loopback cookie has strict site/path/HttpOnly attributes without Secure');check(maxAge(rawCookie(r,opt.secure?'__Host-yx_device':'yx_device_local'))===3600,'Explicit synthetic retention is used');check(!r.text.includes(valueOfCookie(s.device)||'never-present')&&!JSON.stringify(r.envelope).includes('deviceToken'),'Persistent secret never enters JSON');}else check(!s.device,'Disabled trust keeps email-proven short login without device cookie');return {...s,response:r};}
async function restore(device,sessionCookie=null,opt={}){const {response:r}=await api(endpoint,{}, {cookie:joinCookies(sessionCookie,device),...opt});const result=session(r);check(result.token&&result.cookie&&result.user,'Restore returns original short-session DTO');same(Object.keys(r.envelope.data).sort(),['token','user'],'Restore never expands JSON with persistent secret');if(result.device)check(!r.text.includes(valueOfCookie(result.device)),'Rotated secret remains HttpOnly-cookie-only');return {...result,response:r};}
async function readOnly(label,fn){phase=label;const before=await control('snapshot');await fn();const after=await control('snapshot');same(after,before,'Every PUBLIC table stays unchanged');readEvidence.push({phase:label,tables:Object.keys(before).length,unchanged:JSON.stringify(before)===JSON.stringify(after)});}
function epoch(rows,name){return Number(rows.epochs.find(row=>row.user_id===ids.accounts[name])?.epoch||0);}
function record(rows,device){return rows.devices.find(row=>row.selector===valueOfCookie(device).split('.')[0]);}
const maintenance=(name,revision,email)=>({user_id:ids.accounts[name],expected_revision:revision,request_id:uuid(),email,confirmed_username:ids.usernames[name],purpose:'LOGIN_VERIFICATION'});
const userBody=(name,changes={})=>({id:ids.accounts[name],username:ids.usernames[name],name:'SYNTHETIC DEVICE '+name,role:name==='admin'||name==='admin2'?'admin':'viewer',status:1,password:'',...changes});
function configuration(version,allow=true){const relation={required:false,allowedTargetRoles:['ROLE-STAFF'],targetMustCoverOrganization:false,allowSelf:false};return {version,codeRules:{organizationPattern:'ORG-[0-9]{3}',personPattern:'PERSON-[0-9]{3}',rolePattern:'ROLE-[A-Z]+'},roleCodes:['ROLE-STAFF'],organizations:[{organizationCode:'ORG-001',parentOrganizationCode:null,enabled:true}],people:[{personCode:'PERSON-001',organizationCode:'ORG-001',responsibleOrganizationCodes:[],leaderPersonCode:null,bpPersonCode:null,roleCodes:['ROLE-STAFF'],enabled:true}],relations:[{roleCode:'ROLE-STAFF',leader:relation,bp:relation}],accountBindings:[{accountId:ids.accounts.native,personCode:'PERSON-001',enabled:true}],grants:allow?[{ruleId:'synthetic-view',roleCode:'ROLE-STAFF',resource:'training.record',action:'VIEW',effect:'ALLOW',scope:'OWN_ORG',organizationCodes:[]}]:[]};}
async function rolledBack(label,operation){phase=label;const before=await control('snapshot'),statsBefore=await stats();await control('epochs-fail');try{const r=await operation();check([500,503].includes(r.status)&&r.envelope?.code===r.status,'Injected revocation storage error fails business HTTP');check(!r.envelope?.data,'Failed transaction returns no success data');}finally{await control('epochs-normal');}same(await control('snapshot'),before,'Business and device tables roll back together');check((await stats()).epoch_failures>statsBefore.epoch_failures,'Failure passed through actual same-transaction epoch write');}
async function cookieBoundaryChecks(){
 for(const secure of [false,true]){
  await control(secure?'device-production-origin':'device-restore-config');
  const opt=secure?{origin:'https://device.example.invalid',headers:{Host:'device.example.invalid'},secure:true}:{},expectedName=secure?'__Host-yx_device':'yx_device_local',otherName=secure?'yx_device_local':'__Host-yx_device',label=secure?'HTTPS':'loopback';
  phase=label+' cookie name isolation';let target=await verify('imported','imported@example.invalid',opt),other=await verify('native','native@example.invalid',opt);
  await readOnly(label+' wrong cookie name supplies no identity',async()=>{
   const r=await denied(endpoint,{},401,'Correct secret under inapplicable cookie name cannot authenticate',{...opt,cookie:otherName+'='+valueOfCookie(target.device)});clearsBrowser(r,'Rejected wrong-name restore');
   const result=await api('/logout',{}, {...opt,cookie:otherName+'='+valueOfCookie(other.device)});clearsBrowser(result.response,'Wrong-name-only logout');
   const wrongOrigin=await denied('/logout',{},403,'Origin check precedes malformed-cookie logout',{...opt,origin:'https://wrong.example.invalid',cookie:expectedName+'=bad; '+expectedName+'=bad'});check(wrongOrigin.setCookies.length===0,'Wrong-origin logout does not clear browser cookies');
  });
  phase=label+' applicable credential wins without consuming foreign name';
  const otherBefore=record(await storage(),other.device);target=await restore(target.device,null,{...opt,cookie:joinCookies(target.device,otherName+'='+valueOfCookie(other.device))});
  same(target.user.uid,6,'Only applicable cookie determines restored identity');same(record(await storage(),other.device),otherBefore,'Inapplicable cookie cannot rotate or revoke other device');
  for(const duplicate of [false,true]){
   const broken=duplicate?joinCookies(target.device,target.device):expectedName+'=malformed',kind=duplicate?'duplicate':'malformed';
   await readOnly(label+' strict '+kind+' restore and logout repair',async()=>{
    const deniedRestore=await denied(endpoint,{},400,'Applicable '+kind+' cookie remains invalid for restore',{...opt,cookie:broken});clearsBrowser(deniedRestore,'Invalid restore');
    const wrongRestore=await denied(endpoint,{},403,'Origin is checked before '+kind+' restore',{...opt,origin:'https://wrong.example.invalid',cookie:broken});check(wrongRestore.setCookies.length===0,'Wrong-origin restore does not clear any cookie');
    const logout=await api('/logout',{}, {...opt,cookie:broken});clearsBrowser(logout.response,'No-session '+kind+' logout');
   });
   phase=label+' fresh email proof repairs '+kind+' browser state';
   const oldTarget=record(await storage(),target.device),repaired=await verify('imported','imported@example.invalid',{...opt,cookie:broken});
   check(clearsCookie(repaired.response,'yx_device_local')&&clearsCookie(repaired.response,'__Host-yx_device'),'Fresh proof clears malformed old device-cookie state');
   check(Boolean(repaired.device)&&repaired.device!==target.device,'Fresh password and OTP create a new device after cookie repair');same(record(await storage(),target.device),oldTarget,'Bad old value never supplies an identity for revocation');
   await api('/logout',{}, {...opt,cookie:joinCookies(repaired.cookie,repaired.device)});
   phase=label+' session-bound logout repairs '+kind+' device state';
   const bound=await verify('imported','imported@example.invalid',opt),foreignBefore=record(await storage(),other.device);
   const cookieState=duplicate?joinCookies(expectedName+'='+valueOfCookie(other.device),expectedName+'='+valueOfCookie(other.device)):expectedName+'=bad';
   const logout=await api('/logout',{}, {...opt,cookie:joinCookies(bound.cookie,cookieState)});clearsBrowser(logout.response,'Authenticated '+kind+' logout');
   check(record(await storage(),bound.device).revoked===true,'Actual short-session-linked device is revoked');same(record(await storage(),other.device),foreignBefore,'Malformed or duplicate supplied value cannot revoke another device');
   await denied('/me',undefined,401,'Logged-out bound short session is invalid',{...opt,cookie:bound.cookie});
  }
  phase=label+' verification ignores the other device-cookie name';
  const foreignBefore=record(await storage(),other.device),freshDevice=await verify('imported','imported@example.invalid',{...opt,cookie:otherName+'='+valueOfCookie(other.device)});
  same(record(await storage(),other.device),foreignBefore,'Fresh OTP does not consume an inapplicable named device');
  await api('/logout',{}, {...opt,cookie:joinCookies(freshDevice.cookie,freshDevice.device)});
  target=await restore(target.device,null,opt);same(target.user.uid,6,'Legitimate applicable cookie remains usable after rejected malformed state');
  await api('/logout',{}, {...opt,cookie:joinCookies(target.cookie,target.device)});await api('/logout',{}, {...opt,cookie:joinCookies(other.cookie,other.device)});
 }
 await control('device-restore-config');
}
async function runChecks(){
 await boot();baseline=await control('snapshot');
 await readOnly('fresh browser requires email verification',async()=>{await denied(endpoint,{},401,'Missing device cannot restore');await denied('/me',undefined,401,'No short session exists');check((await stats()).mail_count===0,'Restore never invokes sender');});
 await cookieBoundaryChecks();
 phase='email proof establishes bounded persistent browser trust';let native=await verify('native'),nativeOriginal=native.device,admin=await verify('admin2');let persisted=await storage();
 const nativeRow=record(persisted,native.device);check(nativeRow&&nativeRow.expires_at-nativeRow.created_at===3600000,'Stored absolute expiry matches explicit policy');check(nativeRow.secret_hash?.match(/^[a-f0-9]{64}$/)&&nativeRow.secret_hash!==valueOfCookie(native.device).split('.')[1],'Database stores hash rather than raw secret');check(!JSON.stringify(persisted).includes(valueOfCookie(native.device))&&!JSON.stringify(persisted).includes(valueOfCookie(native.device).split('.')[1]),'No raw device credential is stored in any trusted-device column');
 await readOnly('strict device restore request boundary',async()=>{
  const c=native.device;
  for(const badOrigin of [null,'https://wrong.example.invalid',origin()+'/',origin()+', https://wrong.example.invalid','null'])await denied(endpoint,{},403,'Missing or nonexact Origin rejected',{cookie:c,origin:badOrigin});
  for(const suffix of ['?','?x=1','?user_id=5&%75ser_id=5'])await denied(endpoint+suffix,{},400,'Restore accepts no query',{cookie:c});
  for(const body of [{uid:5},{token:valueOfCookie(c)},{email:'native@example.invalid'},[],null,'secret'])await denied(endpoint,body,400,'Restore accepts empty JSON object only',{cookie:c});
  for(const raw of ['{"x":1,"x":2}','{"x":1,"\\u0078":2}','\u000b{}','{}{}',''])await denied(endpoint,raw,400,'Strict raw restore parser rejects malformed/duplicate JSON',{cookie:c,raw:true});
  await denied(endpoint,{},403,'Cross-site Fetch Metadata cannot restore',{cookie:c,headers:{'Sec-Fetch-Site':'cross-site'}});
  await denied('/logout',{},403,'Cross-origin logout cannot revoke device',{cookie:c,origin:'https://wrong.example.invalid'});
  await denied(endpoint,'{}',415,'Restore requires JSON media',{cookie:c,raw:true,contentType:'text/plain'});
  for(const method of ['GET','HEAD','PUT','DELETE'])await denied(endpoint,undefined,405,'Restore requires POST',{cookie:c,method});
  for(const duplicate of [c+'; '+c,'yx_device_local=malformed; '+c]){const r=await denied(endpoint,{},400,'Duplicate applicable cookie names cannot select a credential',{cookie:duplicate});clearsBrowser(r,'Duplicate applicable cookie');}
  const malformed=await denied(endpoint,{},400,'Malformed credential cannot restore',{cookie:'yx_device_local=not-a-secret'});clearsBrowser(malformed,'Malformed applicable cookie');
 });
 phase='verification without exact browser origin grants no persistent trust';await verify('imported','imported@example.invalid',{origin:null,expectDevice:false});await verify('imported','imported@example.invalid',{origin:'https://wrong.example.invalid',expectDevice:false});
 phase='production HTTPS cookie attributes over synthetic loopback exchange';await control('device-production-origin');await verify('imported','imported@example.invalid',{origin:'https://device.example.invalid',headers:{Host:'device.example.invalid'},secure:true});await control('device-restore-config');
 phase='live short session is reused';const reused=await restore(native.device,native.cookie);same(reused.token,native.token,'Already-live short session token is reused');check(!reused.device,'Live short session does not rotate device credential');
 phase='idle short session expires then device rotates once';await control('expire-short-sessions');await denied('/me',undefined,401,'Original short idle expiry is respected',{cookie:native.cookie});await control('device-advance',{millis:10000});native=await restore(native.device);check(native.device!==nativeOriginal,'Successful restore strictly rotates cookie secret');same((await storage()).devices.find(row=>row.selector===nativeRow.selector).expires_at,nativeRow.expires_at,'Restore never extends absolute expiry');check(maxAge(rawCookie(native.response,'yx_device_local'))<=3590,'Rotated cookie retention does not exceed original remaining expiry');
 phase='device survives process restart without short session';const beforeRestart=await control('snapshot');await stop();const offline=JSON.parse((await run(java,[...options(true),'com.training.TrustedDeviceHttpFixture','inspect'],{cwd:app,env,timeout:20000,maxBuffer:262144})).stdout.trim());same(offline,beforeRestart,'Stopped database agrees with live device state');await boot(true);await denied('/me',undefined,401,'Cold Main restores no short session',{cookie:native.cookie});const beforeColdMail=(await stats()).mail_count,cold=await restore(native.device);same((await stats()).mail_count,beforeColdMail,'Remembered device cold restore needs no new mail');check(cold.device!==native.device&&cold.user.uid===5,'Cold restore rotates and recovers exact current account');
 phase='single-use previous credential replay revokes whole device';await denied(endpoint,{},401,'Used previous secret cannot mint another session',{cookie:native.device});await denied('/me',undefined,401,'Previous-secret replay invalidates device-derived session',{cookie:cold.cookie});await denied(endpoint,{},401,'Replay also invalidates latest cookie',{cookie:cold.device});
 phase='new browser still requires mail';const mailCount=(await stats()).mail_count;await denied(endpoint,{},401,'New browser without cookie is not remembered');const pending=await begin('native');check((await stats()).mail_count===mailCount+1,'New browser must obtain fresh password and email challenge');await api('/login/email/cancel',{challenge_id:pending.challenge_id});
 phase='short-session-free logout revokes only current device';let loggedOut=await verify('native'),otherDevice=await verify('native');await control('expire-short-sessions');const logout=await api('/logout',{}, {cookie:loggedOut.device});check(/Max-Age=0/.test(rawCookie(logout.response,'yx_device_local')||'')&&/Max-Age=0/.test(rawCookie(logout.response,'yx_session')||''),'Logout clears persistent and short cookies without restoring');await denied(endpoint,{},401,'Logged-out browser cannot restore',{cookie:loggedOut.device});otherDevice=await restore(otherDevice.device);check(otherDevice.user.uid===5,'Unrelated device for same account survives current-device logout');
 phase='natural expiry does not shorten an existing short session';let expiring=await verify('imported');await control('device-advance',{millis:3600001});same((await api('/me',undefined,{cookie:expiring.cookie})).data.uid,6,'Device expiry alone preserves existing original short session');await control('expire-short-sessions');await denied(endpoint,{},401,'Expired device cannot issue new short session',{cookie:expiring.device});
 phase='clock rollback fails closed';let backward=await verify('imported');await control('device-advance',{millis:-1000});await control('expire-short-sessions');await denied(endpoint,{},401,'Clock older than recorded use rejects restore',{cookie:backward.device});await control('device-advance',{millis:1000});
 phase='explicit policy defaults preserve email login';
 for(const operation of ['device-disable','device-missing-origin']){await control(operation);await readOnly(operation+' no remembered fallback',async()=>{await denied(endpoint,{},401,'Missing explicit policy disables restore',{cookie:otherDevice.device});});await verify('native','native@example.invalid',{expectDevice:false});await control('device-restore-config');}
 await control('device-invalid');await denied(endpoint,{},503,'Invalid configured retention fails closed',{cookie:otherDevice.device});await control('device-restore-config');
 await control('mode-legacy');const legacy=await api('/login',{username:ids.usernames.native,password});check(legacy.data.token&&!usableCookie(legacy.response,'yx_device_local')&&!usableCookie(legacy.response,'__Host-yx_device'),'Legacy password login remains compatible and never enrolls a device');await denied(endpoint,{},[401,503],'Legacy mode never allows persistent restore',{cookie:otherDevice.device});await control('mode-required');
 phase='real email mutation A-B-A advances persistent epoch';admin=await verify('admin2');native=await verify('native');let before=await storage(),rev=(await api('/account-email-maintenance?user_id=5',undefined,{cookie:admin.cookie})).data.revision;
 await api('/account-email-maintenance',maintenance('native',rev,'native-b@example.invalid'),{cookie:admin.cookie});await api('/account-email-maintenance',maintenance('native',rev+1,'native@example.invalid'),{cookie:admin.cookie});check(epoch(await storage(),'native')===epoch(before,'native')+2,'Both actual email changes persist revocation epochs');await denied(endpoint,{},401,'Returning to original email never revives old browser',{cookie:native.device});
 phase='real role A-B-A remains revoked';native=await verify('native');before=await storage();await api('/users',userBody('native',{role:'manager'}),{cookie:admin.cookie});await api('/users',userBody('native'),{cookie:admin.cookie});check(epoch(await storage(),'native')===epoch(before,'native')+2,'Both role changes persist epoch');await denied(endpoint,{},401,'Restored role cannot revive old cookie',{cookie:native.device});
 phase='stored display name same-value preserves device';native=await verify('native');before=await storage();await readOnly('same stored name has no revocation side effects',async()=>{await api('/users',userBody('native'),{cookie:admin.cookie});});same(epoch(await storage(),'native'),epoch(before,'native'),'Same stored name does not advance device epoch');
 phase='actual stored display-name A-B-A persists epoch';await api('/users',userBody('native',{name:'SYNTHETIC DEVICE native changed'}),{cookie:admin.cookie});await api('/users',userBody('native'),{cookie:admin.cookie});check(epoch(await storage(),'native')===epoch(before,'native')+2,'Each actual stored name change persists revocation');await denied(endpoint,{},401,'Restored display name never revives old device',{cookie:native.device});
 phase='real disable-enable remains revoked';native=await verify('native');before=await storage();await api('/users',userBody('native',{status:0}),{cookie:admin.cookie});await api('/users',userBody('native'),{cookie:admin.cookie});check(epoch(await storage(),'native')===epoch(before,'native')+2,'Both enabled-state changes persist epoch');await denied(endpoint,{},401,'Reenabled user cannot revive old browser',{cookie:native.device});
 phase='self-password and admin reset use persistent revocation';native=await verify('native');before=await storage();const changedPassword=password+'-synthetic-change';await api('/password',{old:password,new:changedPassword},{cookie:native.cookie});await api('/users/resetpwd',{id:5,password},{cookie:admin.cookie});check(epoch(await storage(),'native')===epoch(before,'native')+2,'Self change and admin reset each persist epoch');await denied(endpoint,{},401,'Resetting original password text never revives old device',{cookie:native.device});
 phase='actual organization publication A-B-A persists revocation';await api('/organization/config',{expectedVersion:null,configuration:configuration('synthetic-device-A')},{cookie:admin.cookie});native=await verify('native');before=await storage();await api('/organization/config',{expectedVersion:'synthetic-device-A',configuration:configuration('synthetic-device-B',false)},{cookie:admin.cookie});await api('/organization/config',{expectedVersion:'synthetic-device-B',configuration:configuration('synthetic-device-C')},{cookie:admin.cookie});check(epoch(await storage(),'native')===epoch(before,'native')+2,'Conservative organization policy change set advances epoch');await denied(endpoint,{},401,'Restored grants cannot revive old device',{cookie:native.device});
 phase='business revocation storage failures roll back same transaction';native=await verify('native');
 await rolledBack('self-password rollback',()=>request('/password',{old:password,new:changedPassword},{cookie:native.cookie}));
 await rolledBack('admin-reset rollback',()=>request('/users/resetpwd',{id:5,password:changedPassword},{cookie:admin.cookie}));
 await rolledBack('users-name rollback',()=>request('/users',userBody('native',{name:'SYNTHETIC DEVICE must rollback'}),{cookie:admin.cookie}));
 await rolledBack('users-role rollback',()=>request('/users',userBody('native',{role:'manager'}),{cookie:admin.cookie}));
 rev=(await api('/account-email-maintenance?user_id=5',undefined,{cookie:admin.cookie})).data.revision;
 await rolledBack('email-maintenance rollback',()=>request('/account-email-maintenance',maintenance('native',rev,'must-rollback@example.invalid'),{cookie:admin.cookie}));
 await rolledBack('organization-publication rollback',()=>request('/organization/config',{expectedVersion:'synthetic-device-C',configuration:configuration('synthetic-device-rollback',false)},{cookie:admin.cookie}));
 same((await api('/me',undefined,{cookie:native.cookie})).data.uid,5,'Business rollback preserves previously verified session');await control('expire-short-sessions');native=await restore(native.device);check(native.user.uid===5,'Business rollback leaves original device valid');
 phase='persisted revocation survives final cold restart';let finalDevice=await verify('native');admin=await verify('admin2');await api('/users',userBody('native',{role:'manager'}),{cookie:admin.cookie});await api('/users',userBody('native'),{cookie:admin.cookie});const final=await control('snapshot');await stop();await boot(true);await denied(endpoint,{},401,'Cold restart does not reset persisted revocation epoch',{cookie:finalDevice.device});same(await control('snapshot'),final,'Rejecting revoked device after startup causes no unrelated writes');
 for(const name of Object.keys(baseline))if(!['USERS','ORGANIZATION_ACCESS_CONFIG','S01_TRUSTED_DEVICE_EPOCHS','S01_TRUSTED_DEVICES','S01_ACCOUNT_EMAIL_MAINTENANCE_HEADS','S01_ACCOUNT_EMAIL_MAINTENANCE_REVISIONS','S01_ACCOUNT_EMAIL_MAINTENANCE_REQUESTS'].includes(name))same(final[name],baseline[name],'Unrelated persistent table remains unchanged: '+name);
 check((await stats()).sender_lock_violations===0,'All synthetic deliveries ran outside shared lock');fs.writeFileSync(path.join(own,'database-invariants.json'),JSON.stringify({baseline,final,read_phases:readEvidence},null,2),{mode:0o600});
 return {public_tables:Object.keys(final).length,read_only_phases:readEvidence.length,real_mail_transport:'disabled',sender_network_calls:0,retention_seconds:3600,product_classes:classes,baseline_classes:baselineClasses,fixture_classes:overlay};
}
let evidence;runChecks().then(value=>evidence=value).catch(error=>{fatal=(phase+': '+String(error.message||error)).replaceAll(password,'[redacted]');process.exitCode=1;}).finally(async()=>{await stop();const stopped=processes.every(pid=>{try{process.kill(pid,0);return false;}catch(error){return error.code==='ESRCH';}});check(stopped,'Every owned synthetic Main process is stopped');const summary={suite:'trusted-device-http-r25',checks,failures,...(fatal?{error:fatal}:{}),...(evidence||{}),server_processes_stopped:stopped,production_touched:false,notifications_sent:false,artifacts:own};fs.writeFileSync(path.join(own,'result.json'),JSON.stringify(summary,null,2),{mode:0o600});console.log(JSON.stringify(summary));if(failures.length||fatal)process.exitCode=1;});
