package com.training;

import java.io.*;
import java.lang.reflect.*;
import java.nio.file.*;
import java.sql.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicLong;
import java.util.function.LongSupplier;

/** Isolated synthetic H2 + candidate real Auth. No live server, SMTP, real identities or app data. */
public final class TrustedDevicesTest {
    private static final String PASSWORD="synthetic-trusted-device-only";
    private static final long START=1_850_000_000_000L,AGE_SECONDS=1800;
    private static final List<String> DEVICE_TABLES=List.of("s01_trusted_device_epochs","s01_trusted_devices");
    private static final List<String> PROTECTED_TABLES=List.of("users","organization_account_import_state","organization_account_import_batches","organization_account_import_people","s01_account_email_heads","s01_account_email_revisions","s01_account_email_requests","s01_account_email_maintenance_heads","s01_account_email_maintenance_revisions","s01_account_email_maintenance_requests","synthetic_permissions","synthetic_outbox");
    private static final List<String> syntheticSecrets=new ArrayList<>();
    private static int checks;
    private static String hash;
    @FunctionalInterface interface Work{void run()throws Exception;}
    static void check(boolean value,String label){checks++;if(!value)throw new AssertionError(label);}
    static Api.ApiException reject(int code,Work work,String label)throws Exception{
        try{work.run();throw new AssertionError("Expected rejection: "+label);}catch(Api.ApiException e){check(e.code==code,label+" expected="+code+" actual="+e.code);privateError(e,label);return e;}
    }
    static void denied(Work work,String label)throws Exception{
        try{work.run();throw new AssertionError("Expected denial: "+label);}catch(Api.ApiException e){check(Set.of(400,401,403,409,503).contains(e.code),label+" is a stable API denial");privateError(e,label);}
    }
    static void privateError(Throwable failure,String label){String message=Objects.toString(failure.getMessage(),"");for(String secret:syntheticSecrets)check(!message.contains(secret),label+" does not expose synthetic credential");check(!message.contains(PASSWORD)&&!message.contains("@example.test"),label+" contains no password or email");}
    static final class FakeClock implements LongSupplier{final AtomicLong now=new AtomicLong(START);public long getAsLong(){return now.get();}void advance(long ms){now.addAndGet(ms);}void set(long ms){now.set(ms);}}
    static String username(long uid){return "synthetic-device-"+uid;}
    static String email(long uid){return "synthetic-device-"+uid+"@example.test";}
    static Auth.Credential credential(long uid)throws Exception{Auth.Credential value=Auth.checkedCredential(username(uid),PASSWORD);check(value!=null,"real password proof exists for synthetic user");return value;}
    static NotificationChannelsAccountEmailPreparation.Snapshot snapshot(long uid)throws Exception{return NotificationChannelsAccountEmailPreparation.loginSnapshot(uid);}
    static TrustedDevices.Login enroll(TrustedDevices service,long uid)throws Exception{return remember(service.enroll(credential(uid),snapshot(uid),null));}
    static TrustedDevices.Login remember(TrustedDevices.Login value){syntheticSecrets.add(value.deviceToken());syntheticSecrets.add(value.sessionToken());return value;}
    static Map<String,String> rows(List<String> tables)throws Exception{Map<String,String> result=new TreeMap<>();for(String table:tables){List<String> values=new ArrayList<>();for(Map<String,Object> row:Db.query("SELECT * FROM "+table))values.add(Json.write(row));Collections.sort(values);result.put(table,values.toString());}return result;}
    static long count(String table)throws Exception{return Db.count(table);}
    static void active(TrustedDevices.Login login,long uid){Auth.Session session=Auth.get(login.sessionToken());check(session!=null&&session.uid==uid,"trusted device grants a real currently authenticated short session");check(!login.deviceToken().equals(login.sessionToken()),"persistent device secret differs from short-session token");check(!login.toString().contains(login.deviceToken())&&!login.toString().contains(login.sessionToken()),"Login toString redacts credentials");}
    static void configurePolicy(){System.setProperty("login.email.mode","required");System.setProperty("login.device.maxAgeSeconds",String.valueOf(AGE_SECONDS));System.setProperty("login.device.origin","https://trusted.example.test");}
    static void withinTransaction(Work work)throws Exception{synchronized(Api.MUTATION_LOCK){Db.transaction(()->{work.run();return null;});}}

    static void initializationAndPolicy()throws Exception{
        Map<String,String> before=rows(PROTECTED_TABLES),devices=rows(DEVICE_TABLES);TrustedDevices.init();TrustedDevices.init();check(count("s01_trusted_devices")==0&&devices.equals(rows(DEVICE_TABLES)),"idempotent initialization creates no implicit device trust");check(before.equals(rows(PROTECTED_TABLES)),"device initialization changes no account, email, import or permission rows");
        FakeClock clock=new FakeClock();TrustedDevices service=new TrustedDevices(clock);Auth.Credential proof=credential(100);var candidate=snapshot(100);
        for(String key:List.of("login.device.maxAgeSeconds","login.device.origin")){String old=System.getProperty(key);System.clearProperty(key);try{TrustedDevices.Login shortOnly=service.enroll(proof,candidate,null);check(shortOnly.deviceToken()==null&&shortOnly.deviceId()==null&&shortOnly.expiresAt()==0,"missing explicit policy creates no persistent device trust");check(Auth.get(shortOnly.sessionToken())!=null,"missing device configuration preserves successful original email login");Auth.logout(shortOnly.sessionToken());denied(()->service.restore("untrusted-synthetic-token"),"missing device policy never restores trust");}finally{System.setProperty(key,old);}}
        for(String age:List.of("0","-1","31536001","not-a-number","1.5")){System.setProperty("login.device.maxAgeSeconds",age);denied(()->service.enroll(proof,candidate,null),"invalid retention cannot enroll");}System.setProperty("login.device.maxAgeSeconds",String.valueOf(AGE_SECONDS));
        for(String origin:List.of("http://public.example.test","https://trusted.example.test/path","https://trusted.example.test?x=1","https://trusted.example.test#fragment","https://user@trusted.example.test","null","*")){System.setProperty("login.device.origin",origin);denied(()->service.enroll(proof,candidate,null),"untrusted or non-origin policy cannot enroll");}System.setProperty("login.device.origin","https://trusted.example.test");
        System.setProperty("login.email.mode","legacy");try{denied(()->service.enroll(proof,candidate,null),"legacy password mode cannot enroll device");denied(()->service.restore("untrusted-synthetic-token"),"legacy password mode cannot restore device");}finally{System.setProperty("login.email.mode","required");}
        check(count("s01_trusted_devices")==0,"all invalid-policy attempts leave no device record");
    }
    static void rotationReplayAndSecrets()throws Exception{
        FakeClock clock=new FakeClock();TrustedDevices service=new TrustedDevices(clock);TrustedDevices.Login first=enroll(service,100);active(first,100);check(first.expiresAt()==START+AGE_SECONDS*1000,"device absolute expiry derives from explicit configured duration");check(first.deviceToken().length()>=64,"random persistent credential has sufficient representation length");
        String persisted=rows(DEVICE_TABLES).toString();check(!persisted.contains(first.deviceToken())&&!persisted.contains(first.deviceToken().substring(33))&&!persisted.contains(first.sessionToken()),"persistent tables contain no plaintext bearer token or secret suffix");check(!persisted.contains(PASSWORD)&&!persisted.contains(email(100))&&!persisted.contains(hash),"persistent tables retain digests instead of identity secrets");
        clock.advance(1000);TrustedDevices.Login second=remember(service.restore(first.deviceToken()));active(second,100);check(!first.deviceToken().equals(second.deviceToken()),"successful restore rotates persistent secret");check(first.deviceId().equals(second.deviceId()),"rotation keeps one logical device");check(first.expiresAt()==second.expiresAt(),"restore never extends absolute expiry");
        reject(401,()->service.restore(first.deviceToken()),"used previous secret is strictly single-use");check(Auth.get(second.sessionToken())==null&&Auth.get(first.sessionToken())==null,"previous-secret replay revokes all short sessions derived from that device");reject(401,()->service.restore(second.deviceToken()),"replay revocation also blocks current rotated secret");
        FakeClock anotherClock=new FakeClock();TrustedDevices another=new TrustedDevices(anotherClock);Map<String,String> before=rows(DEVICE_TABLES);for(String malformed:Arrays.asList(null,""," ","uid:100","a".repeat(4096)))denied(()->another.restore(malformed),"malformed token fails closed");check(before.equals(rows(DEVICE_TABLES)),"unrecognized malformed credentials are read-only");
    }
    static void expiryAndRollbackClock()throws Exception{
        FakeClock clock=new FakeClock();TrustedDevices service=new TrustedDevices(clock);TrustedDevices.Login login=enroll(service,101);active(login,101);clock.set(login.expiresAt());reject(401,()->service.restore(login.deviceToken()),"absolute device expiry rejects restore at exact boundary");check(Auth.get(login.sessionToken())!=null,"natural device expiry does not shorten existing original 12-hour short session");check(TrustedDevices.sessionCurrent(login.deviceId(),101),"sessionCurrent checks revocation but does not impose device expiry");clock.set(START+1000);reject(401,()->service.restore(login.deviceToken()),"observed natural expiry cannot be undone by clock rollback");check(Auth.get(login.sessionToken())!=null,"expired device remains unable to restore without revoking its already-issued short session");
        FakeClock backwards=new FakeClock();TrustedDevices rewind=new TrustedDevices(backwards);TrustedDevices.Login initial=enroll(rewind,102);backwards.advance(5000);TrustedDevices.Login next=remember(rewind.restore(initial.deviceToken()));backwards.set(START+4000);reject(401,()->rewind.restore(next.deviceToken()),"backward clock cannot extend or reuse device lifetime");
    }
    static void currentDeviceLogout()throws Exception{
        FakeClock clock=new FakeClock();TrustedDevices service=new TrustedDevices(clock);TrustedDevices.Login one=enroll(service,103),two=enroll(service,103);active(one,103);active(two,103);check(!one.deviceId().equals(two.deviceId()),"same account can have independent devices");
        service.logout(one.deviceToken(),one.sessionToken());check(Auth.get(one.sessionToken())==null,"logout immediately revokes current device session");check(Auth.get(two.sessionToken())!=null,"current device logout leaves another device session valid");reject(401,()->service.restore(one.deviceToken()),"logout credential cannot restore");TrustedDevices.Login continued=remember(service.restore(two.deviceToken()));active(continued,103);
        Auth.Session session=Auth.get(continued.sessionToken());session.time=System.currentTimeMillis()-13L*3600*1000;check(Auth.get(continued.sessionToken())==null,"fixture expires original short session using existing Auth idle contract");service.logout(continued.deviceToken(),continued.sessionToken());reject(401,()->service.restore(continued.deviceToken()),"logout still revokes device after short session expires");
        TrustedDevices.Login replacement=enroll(service,104);TrustedDevices.Login newer=remember(service.enroll(credential(104),snapshot(104),replacement.deviceToken()));active(newer,104);reject(401,()->service.restore(replacement.deviceToken()),"fresh verified enrollment replaces prior current browser device");check(Auth.get(newer.sessionToken())!=null,"replaced old device token cannot revoke separately verified new device");
    }
    static void durableRevocationAndLegacySemantics()throws Exception{
        FakeClock clock=new FakeClock();TrustedDevices service=new TrustedDevices(clock);TrustedDevices.Login old=enroll(service,105);Map<String,String> before=rows(DEVICE_TABLES);Auth.revokeUserSessions(105);check(before.equals(rows(DEVICE_TABLES)),"existing Auth.revokeUserSessions remains memory-only");check(Auth.get(old.sessionToken())==null,"old Auth revoke still revokes short session");TrustedDevices.Login restored=remember(service.restore(old.deviceToken()));active(restored,105);
        withinTransaction(()->TrustedDevices.revokeUserInTransaction(105));check(Auth.get(restored.sessionToken())==null,"persistent device revocation immediately invalidates linked session");reject(401,()->service.restore(restored.deviceToken()),"persistent epoch change blocks device restoration");
        TrustedDevices.Login aba=enroll(service,106);withinTransaction(()->{Db.exec("UPDATE users SET role='manager' WHERE id=106");TrustedDevices.revokeUserInTransaction(106);});Auth.revokeUserSessions(106);withinTransaction(()->{Db.exec("UPDATE users SET role='viewer' WHERE id=106");TrustedDevices.revokeUserInTransaction(106);});Auth.revokeUserSessions(106);reject(401,()->service.restore(aba.deviceToken()),"role A to B to A cannot revive device trust");
        boolean transactionRequired=false;try{synchronized(Api.MUTATION_LOCK){TrustedDevices.revokeUserInTransaction(107);}}catch(Exception e){transactionRequired=true;}check(transactionRequired,"persistent revoke cannot execute outside existing transaction");
        boolean lockRequired=false;try{Db.transaction(()->{TrustedDevices.revokeUserInTransaction(107);return null;});}catch(Exception e){lockRequired=true;}check(lockRequired,"persistent revoke cannot bypass business mutation lock");
    }
    static void liveIdentityAndAtomicRollback()throws Exception{
        FakeClock clock=new FakeClock();TrustedDevices service=new TrustedDevices(clock);TrustedDevices.Login login=enroll(service,108);Map<String,String> beforeDevice=rows(DEVICE_TABLES);Map<String,Object> beforeUser=Db.one("SELECT * FROM users WHERE id=108");
        try{withinTransaction(()->{Db.exec("UPDATE users SET role='manager' WHERE id=108");TrustedDevices.revokeUserInTransaction(108);throw new SQLException("synthetic transaction abort");});throw new AssertionError("Expected synthetic rollback");}catch(SQLException expected){check(true,"fixture aborts original business transaction");}
        check(beforeDevice.equals(rows(DEVICE_TABLES))&&beforeUser.equals(Db.one("SELECT * FROM users WHERE id=108")),"business and device revocation roll back together");check(Auth.get(login.sessionToken())!=null,"rolled-back revocation retains linked valid short session");TrustedDevices.Login valid=remember(service.restore(login.deviceToken()));active(valid,108);
        TrustedDevices.Login changed=enroll(service,109);Db.exec("UPDATE users SET role='manager' WHERE id=109");try{reject(401,()->service.restore(changed.deviceToken()),"restore compares current role with verified device identity");}finally{Db.exec("UPDATE users SET role='viewer' WHERE id=109");}
        TrustedDevices.Login disabled=enroll(service,110);Db.exec("UPDATE users SET status=0 WHERE id=110");try{reject(401,()->service.restore(disabled.deviceToken()),"disabled account cannot restore");}finally{Db.exec("UPDATE users SET status=1 WHERE id=110");}
        TrustedDevices.Login emailHistory=enroll(service,111);Map<String,Object> row=Db.one("SELECT recorded_at FROM s01_account_email_maintenance_revisions WHERE user_id=111 AND revision=1");Db.exec("UPDATE s01_account_email_maintenance_revisions SET recorded_at='broken-synthetic-history' WHERE user_id=111 AND revision=1");try{reject(401,()->service.restore(emailHistory.deviceToken()),"restore checks complete real maintained-email history");}finally{Db.exec("UPDATE s01_account_email_maintenance_revisions SET recorded_at=? WHERE user_id=111 AND revision=1",row.get("recorded_at"));}
    }
    static void concurrentSingleUse()throws Exception{
        FakeClock clock=new FakeClock();TrustedDevices service=new TrustedDevices(clock);TrustedDevices.Login initial=enroll(service,112);ExecutorService pool=Executors.newFixedThreadPool(2);CountDownLatch start=new CountDownLatch(1);List<Future<Object>> futures=new ArrayList<>();
        try{for(int i=0;i<2;i++)futures.add(pool.submit(()->{start.await();try{return service.restore(initial.deviceToken());}catch(Api.ApiException e){return e.code;}}));start.countDown();int successes=0,denials=0;TrustedDevices.Login winner=null;for(Future<Object> future:futures){Object result=future.get(10,TimeUnit.SECONDS);if(result instanceof TrustedDevices.Login got){winner=remember(got);successes++;}else if(Integer.valueOf(401).equals(result))denials++;}check(successes==1&&denials==1,"strict concurrent restore has exactly one issuance and one replay rejection");check(winner!=null&&Auth.get(winner.sessionToken())==null,"concurrent previous-secret replay revokes the winning device session");}
        finally{pool.shutdownNow();check(pool.awaitTermination(5,TimeUnit.SECONDS),"all synthetic concurrency workers stop");}
    }
    static void injectedRevocationStorageFailure()throws Exception{
        FakeClock clock=new FakeClock();TrustedDevices service=new TrustedDevices(clock);TrustedDevices.Login login=enroll(service,113);Map<String,String> beforeDevice=rows(DEVICE_TABLES),beforeProtected=rows(PROTECTED_TABLES);Connection actual=Db.get();Field field=Db.class.getDeclaredField("conn");field.setAccessible(true);boolean[] injected={false};
        Connection proxy=(Connection)Proxy.newProxyInstance(TrustedDevicesTest.class.getClassLoader(),new Class<?>[]{Connection.class},(p,m,a)->{try{if(m.getName().equals("prepareStatement")&&a!=null&&a.length>0&&a[0] instanceof String sql&&sql.matches("(?is)^\\s*(?:INSERT|UPDATE|DELETE|MERGE).*s01_trusted_device.*")){injected[0]=true;throw new SQLException("synthetic persistent revocation storage failure");}return m.invoke(actual,a);}catch(InvocationTargetException e){throw e.getCause();}});
        field.set(null,proxy);boolean failed=false;try{withinTransaction(()->{Db.exec("UPDATE users SET role='manager' WHERE id=113");TrustedDevices.revokeUserInTransaction(113);});}catch(Exception expected){failed=true;}finally{field.set(null,actual);if(!actual.getAutoCommit())actual.setAutoCommit(true);}
        check(injected[0]&&failed,"real device-revocation SQL failure aborts original business transaction");check(beforeDevice.equals(rows(DEVICE_TABLES))&&beforeProtected.equals(rows(PROTECTED_TABLES)),"persistent device SQL failure cannot leave changed role or device epoch");check(Auth.get(login.sessionToken())!=null,"rolled-back storage failure does not revoke otherwise-current session");active(remember(service.restore(login.deviceToken())),113);
    }
    static void prepareColdRestart(Path data)throws Exception{
        FakeClock clock=new FakeClock();TrustedDevices service=new TrustedDevices(clock);TrustedDevices.Login durable=enroll(service,135),revoked=enroll(service,136),renamed=enroll(service,137),expired=enroll(service,138),logout=enroll(service,139);withinTransaction(()->TrustedDevices.revokeUserInTransaction(136));Auth.revokeUserSessions(136);
        Map<String,String> initialDevice=rows(DEVICE_TABLES);TrustedDevices.mutation(137,false,()->{Db.exec("UPDATE users SET name=name WHERE id=137");return null;});check(initialDevice.equals(rows(DEVICE_TABLES))&&Auth.get(renamed.sessionToken())!=null,"same-value name write with unchanged revoke decision preserves device");
        Map<String,Object> initialName=Db.one("SELECT name FROM users WHERE id=137");try{TrustedDevices.mutation(137,true,()->{Db.exec("UPDATE users SET name='Synthetic transient renamed' WHERE id=137");throw new SQLException("synthetic name transaction failure");});throw new AssertionError("Expected name rollback");}catch(SQLException expected){check(initialName.equals(Db.one("SELECT name FROM users WHERE id=137"))&&initialDevice.equals(rows(DEVICE_TABLES)),"failed display-name write rolls back account and device state");}
        TrustedDevices.mutation(137,true,()->{Db.exec("UPDATE users SET name='Synthetic renamed device user' WHERE id=137");return null;});TrustedDevices.mutation(137,true,()->{Db.exec("UPDATE users SET name=? WHERE id=137",initialName.get("name"));return null;});check(Auth.get(renamed.sessionToken())==null,"name A to B to A persistent revoke invalidates linked short session without widening old Auth revoke call");reject(401,()->service.restore(renamed.deviceToken()),"display-name A to B to A cannot revive current-process device");
        clock.set(expired.expiresAt());reject(401,()->service.restore(expired.deviceToken()),"record natural expiry before cold clock rollback");clock.set(START);
        Properties properties=new Properties();properties.setProperty("device",durable.deviceToken());properties.setProperty("short",durable.sessionToken());properties.setProperty("expires",String.valueOf(durable.expiresAt()));properties.setProperty("revoked",revoked.deviceToken());properties.setProperty("renamed",renamed.deviceToken());properties.setProperty("expired",expired.deviceToken());properties.setProperty("logout",logout.deviceToken());properties.setProperty("now",String.valueOf(clock.getAsLong()));
        // Only generated synthetic test credentials cross the process boundary, inside this owned temp root.
        try(OutputStream out=Files.newOutputStream(data.getParent().resolve("synthetic-restart.properties"))){properties.store(out,"Synthetic test-only continuation; removed with this invocation");}
    }
    static void coldRestart(Path data)throws Exception{
        configurePolicy();Properties properties=new Properties();try(InputStream in=Files.newInputStream(data.getParent().resolve("synthetic-restart.properties"))){properties.load(in);}String old=properties.getProperty("device"),revoked=properties.getProperty("revoked");syntheticSecrets.add(old);syntheticSecrets.add(revoked);check(Auth.get(properties.getProperty("short"))==null,"cold JVM has no surviving short session");FakeClock clock=new FakeClock();clock.set(Long.parseLong(properties.getProperty("now"))+5000);TrustedDevices service=new TrustedDevices(clock);Map<String,String> before=rows(PROTECTED_TABLES);
        TrustedDevices.Login restored=remember(service.restore(old));active(restored,135);check(restored.expiresAt()==Long.parseLong(properties.getProperty("expires")),"cold restart preserves original absolute device expiry");check(!old.equals(restored.deviceToken()),"cold restart rotates persistent secret");reject(401,()->service.restore(revoked),"persistent revocation survives JVM restart despite matching identity fields");reject(401,()->service.restore(properties.getProperty("renamed")),"name A to B to A stays revoked across cold JVM restart");reject(401,()->service.restore(properties.getProperty("expired")),"persistent natural expiry cannot revive after cold JVM clock rollback");service.logout(properties.getProperty("logout"),null);reject(401,()->service.restore(properties.getProperty("logout")),"cold logout revokes device without restoring or requiring a short session");reject(401,()->service.restore(old),"cold JVM recognizes previously used token digest");check(Auth.get(restored.sessionToken())==null,"cold previous-value replay revokes restored session");check(before.equals(rows(PROTECTED_TABLES)),"device restore and replay never alter users, permissions, email or import data");System.out.println("R25 trusted devices cold JVM: "+checks+" checks passed.");
    }
    static void setup()throws Exception{
        System.setProperty("login.email.mode","legacy");Db.exec("CREATE TABLE users(id BIGINT PRIMARY KEY,username VARCHAR(64) UNIQUE,password VARCHAR(128),name VARCHAR(64),role VARCHAR(16),status INT)");hash=Auth.hash(PASSWORD);Db.exec("INSERT INTO users VALUES(1,?,?,?,'admin',1)",username(1),hash,"Synthetic device admin");for(long uid=100;uid<=140;uid++)Db.exec("INSERT INTO users VALUES(?,?,?,?,'viewer',1)",uid,username(uid),hash,"Synthetic device user "+uid);OrganizationAccountImport.init();NotificationChannelsAccountEmailPreparation.init();TrustedDevices.init();FirstBindStore.init();
        check(count("s01_trusted_devices")==0&&count("s01_trusted_device_epochs")==0,"fresh initialization does not enroll or migrate preexisting accounts");String token=Auth.login(username(1),PASSWORD);Auth.Session admin=Auth.get(token);check(admin!=null,"setup authenticates using real Auth");for(long uid=100;uid<=140;uid++)NotificationChannelsAccountEmailMaintenance.save(admin,Map.of("user_id",uid,"expected_revision",0L,"request_id",UUID.randomUUID().toString(),"email",email(uid),"confirmed_username",username(uid),"purpose","LOGIN_VERIFICATION"));Auth.logout(token);
        for(String table:List.of("synthetic_permissions","synthetic_outbox")){Db.exec("CREATE TABLE "+table+"(id INT PRIMARY KEY,payload VARCHAR(64))");Db.exec("INSERT INTO "+table+" VALUES(1,'unchanged synthetic sentinel')");}configurePolicy();
    }
    static Path configureData(String[] args,boolean reopen)throws Exception{
        if(args.length!=(reopen?2:1))throw new IllegalArgumentException("One owned synthetic data directory is required");Path supplied=Path.of(args[reopen?1:0]);if(!supplied.isAbsolute()||Files.isSymbolicLink(supplied))throw new IllegalArgumentException("Absolute non-symbolic synthetic directory required");Path data=supplied.toRealPath(),parent=data.getParent();
        if(parent==null||!data.getFileName().toString().equals("data")||!parent.getFileName().toString().startsWith("yanxu-trusted-device-r25.")||!Files.isRegularFile(parent.resolve(".trusted-devices-test-root")))throw new IllegalArgumentException("Data directory does not belong to this test invocation");String configured=System.getProperty("data.dir");if(configured==null||!Path.of(configured).toRealPath().equals(data))throw new IllegalArgumentException("JVM data.dir must already point at the owned synthetic directory");
        if(reopen){if(!Files.isRegularFile(data.resolve("training.mv.db")))throw new IllegalArgumentException("Cold reopen requires prior synthetic database");}else try(var files=Files.list(data)){if(files.findAny().isPresent())throw new IllegalArgumentException("Fresh synthetic directory must be empty");}System.setProperty("data.dir",data.toString());return data;
    }
    public static void main(String[] args)throws Exception{
        boolean reopen=args.length>0&&args[0].equals("--reopen");Path data=configureData(args,reopen);boolean opened=false;
        try{String url=Db.get().getMetaData().getURL();opened=true;check(url.startsWith("jdbc:h2:"+data.resolve("training")),"all SQL is confined to validated synthetic directory");if(reopen){coldRestart(data);return;}setup();Map<String,String> protectedBefore=rows(PROTECTED_TABLES);initializationAndPolicy();rotationReplayAndSecrets();expiryAndRollbackClock();currentDeviceLogout();durableRevocationAndLegacySemantics();liveIdentityAndAtomicRollback();injectedRevocationStorageFailure();concurrentSingleUse();check(protectedBefore.equals(rows(PROTECTED_TABLES)),"all core device flows preserve complete account, import, permission and email data");prepareColdRestart(data);System.out.println("R25 trusted devices: "+checks+" checks passed (synthetic H2, real Auth, fake time, no network/mail/private data).");}finally{if(opened)Db.exec("SHUTDOWN");}
    }
}
